const aBoundaryOfMineIs = {
  "funny": [
    "no texting before coffee because I'm literally not a person yet 😂",
    "don't talk to me before 10am or I can't be responsible",
    "no sharing food unless you asked first because that's just basic manners",
    "don't touch my phone ever because that's a sacred personal space",
    "no surprise plans because I need time to mentally prepare for everything",
    "don't expect me to function without at least eight hours of sleep",
    "no morning conversations because my brain doesn't work that early honestly",
    "don't mess with my playlist because I curated it perfectly thank you",
    "no judging my comfort shows because they bring me joy and peace",
    "don't wake me up unless the house is literally on fire maybe",
    "no stealing my hoodies because I will notice and hunt you down",
    "don't expect me to remember things you told me before coffee time",
    "no plans on sundays because that's my sacred rest and recharge day",
    "don't criticize my snack choices because they're perfect for me thanks",
    "no touching my skincare products because that stuff is expensive and mine",
    "don't expect quick responses when I'm in my cozy introvert mode honestly",
    "no making fun of my comfort foods because they're comforting for",
    "don't rush me in the morning because I need my slow",
    "no borrowing my stuff without asking first because boundaries matter people",
    "don't expect me to be social when I'm in my recharge"
  ],
  "romantic": [
    "honesty always because trust is the foundation of everything we build ❤️",
    "open communication even when it's hard because that's how we grow together",
    "respecting my need for alone time because I love you but",
    "no playing games with feelings because emotions are too important for that",
    "being genuine and authentic because I need real connection not fake vibes",
    "respecting my emotional needs and not dismissing how I feel ever honestly",
    "no ghosting or disappearing because communication matters even when it's uncomfortable",
    "making time for us because relationships need effort and intentional quality time",
    "respecting my past and not using it against me in arguments",
    "being emotionally available because I need someone who shows up fully always",
    "no comparing me to exes because I'm my own person thanks",
    "supporting my dreams even when they seem scary or unrealistic to you",
    "respecting my boundaries without making me feel guilty about having them",
    "being consistent because I need stability and reliability in my relationships always",
    "no love bombing then disappearing because that's manipulative and hurtful honestly",
    "meeting my emotional needs halfway because relationships are about mutual effort",
    "respecting my love language and showing affection in ways I understand",
    "being vulnerable with me because intimacy requires openness from both of us",
    "no dismissing my feelings because they're valid even if you disagree",
    "choosing me every day because love is a choice we make"
  ],
  "adventurous": [
    "always saying yes to new experiences because that's how we grow 🌟",
    "being spontaneous sometimes because the best memories are often unplanned adventures honestly",
    "trying new things together because shared adventures create the strongest bonds",
    "no staying in the same routine forever because variety makes life",
    "being open to travel even if it's just weekend road trips",
    "stepping outside comfort zones because that's where all the magic happens",
    "no saying no to adventures without at least considering them first",
    "being willing to explore new places and try new foods together",
    "taking risks together because playing it safe gets boring after a while",
    "no being stuck in the same old patterns because growth requires",
    "being open to spontaneous plans even when we had other ideas",
    "trying activities that scare us a little because that's how we",
    "no refusing to leave the house because there's a world to",
    "being adventurous with food and trying cuisines we've never had before honestly",
    "taking trips even if they're not perfectly planned out in advance",
    "no playing it safe all the time because calculated risks are",
    "being willing to get lost and find new places together sometimes",
    "trying new hobbies together even if we might not be good",
    "no staying comfortable when adventure is calling us to explore more honestly",
    "being open to last minute plans because spontaneity keeps life exciting"
  ],
  "quirky": [
    "letting me be weird without judgment because that's just who I 🎨",
    "accepting my random interests even if you don't understand them at all",
    "no making fun of my quirks because they're what make me",
    "letting me express myself however I want without trying to change",
    "accepting that I do things differently and that's perfectly okay honestly",
    "no judging my weird collections because they bring me joy and happiness",
    "letting me have my odd routines because they help me function",
    "accepting my unconventional style choices because I dress for myself not others",
    "no trying to make me more normal because normal is boring",
    "letting me be authentically myself even when it's a bit much",
    "accepting my niche interests even if nobody else gets them at",
    "no laughing at my weird habits unless you're laughing with me",
    "letting me decorate my space however I want even if unconventional",
    "accepting that I think differently and that's actually a good thing",
    "no trying to tone down my personality because this is who",
    "letting me enjoy my weird hobbies without questioning why I like",
    "accepting my eccentric taste in literally everything from music to decor honestly",
    "no making me feel bad for being different from everyone else",
    "letting me be my authentic weird self without trying to fix",
    "accepting that my brain works differently and that's what makes me"
  ],
  "serious": [
    "respect always because I won't tolerate being treated as less than",
    "honesty even when it's uncomfortable because lies break trust completely and permanently",
    "no disrespecting my time because it's valuable and I choose how",
    "taking accountability for actions because I need mature communication not excuses honestly",
    "respecting my career and ambitions because they're important to my future",
    "no crossing boundaries I've clearly communicated because they exist for good reasons",
    "treating me as an equal partner because I won't accept anything",
    "respecting my need for independence because I'm my own person first",
    "no dismissing my concerns because my feelings and thoughts matter equally always",
    "being reliable and consistent because I need to know I can",
    "respecting my values even if they're different from yours sometimes honestly",
    "no making me compromise my self worth because I know what",
    "taking my goals seriously and supporting them even when they're challenging",
    "respecting my boundaries without guilt tripping me about having them ever honestly",
    "no expecting me to sacrifice my growth for anyone else's comfort",
    "being honest about intentions because I don't have time for games",
    "respecting my decisions even when you don't fully understand or agree",
    "no violating my trust because once it's broken it's hard to",
    "treating me with dignity because that's the bare minimum I deserve",
    "respecting my standards because I set them for my own wellbeing"
  ],
  "intellectual": [
    "respecting my intelligence and not talking down to me ever 🧠",
    "having real conversations that go beyond surface level small talk always honestly",
    "no dismissing my ideas just because they're different from yours or unconventional",
    "being open to learning from me because knowledge sharing goes both",
    "respecting my opinions even when you disagree with them completely and totally",
    "no mansplaining things I already know because it's condescending and annoying",
    "engaging in thoughtful debate without getting defensive or personal about it",
    "respecting my expertise in areas I've studied and worked hard in",
    "no assuming you know more just because of gender or age",
    "being intellectually curious and open to new perspectives and ideas always honestly",
    "respecting my need for mental stimulation because I get bored easily",
    "no dumbing things down for me because I can handle complex",
    "engaging with my ideas seriously instead of dismissing them as overthinking",
    "respecting my education and the work I've put into learning things",
    "no interrupting me when I'm explaining something I'm passionate about honestly",
    "being open to having your views challenged because that's how we",
    "respecting my critical thinking even when it questions common beliefs or norms",
    "no acting like your opinion is fact when it's just perspective",
    "engaging in meaningful discussions that make us both think more deeply",
    "respecting my intellectual boundaries and not pushing when I need space"
  ],
  "default": [
    "respect because that's the foundation of any healthy relationship or friendship ✨",
    "honesty even when it's hard because trust matters more than comfort",
    "no crossing lines I've clearly set because boundaries exist for reasons",
    "treating me with kindness because that's basic human decency we all deserve",
    "respecting my time because it's valuable and I choose how to",
    "no making me feel bad for having needs because they're valid",
    "being considerate of my feelings because emotions matter in every interaction always",
    "respecting my space when I need it because alone time is",
    "no expecting me to compromise my values because they're important to",
    "treating me as an equal because that's what I am period",
    "respecting my choices even if you'd choose differently in my situation honestly",
    "no judging me for things that don't affect you at all",
    "being reliable when you say you'll do something because words should",
    "respecting my boundaries without making me explain them repeatedly to you",
    "no making me feel guilty for prioritizing myself sometimes because self",
    "treating me with basic decency because that's the bare minimum honestly",
    "respecting my decisions about my own life because they're mine to",
    "no dismissing my feelings just because you don't understand them fully",
    "being honest about your intentions because I deserve to know where",
    "respecting me as a whole person with needs and boundaries that"
  ]
};

module.exports = aBoundaryOfMineIs;
