const aLifeGoalOfMine = {
  "funny": [
    "becoming the kind of person who actually uses their gym membership 😂",
    "learning to cook without setting off the smoke alarm every single time",
    "finally finishing all the shows in my watch list before adding more",
    "becoming a morning person but honestly that's probably never happening realistically",
    "mastering the art of adulting without googling everything I need to do",
    "learning to keep plants alive for longer than two weeks maximum",
    "becoming someone who meal preps instead of ordering takeout constantly every night",
    "actually using all the apps I downloaded to be more productive",
    "learning to fold fitted sheets properly because that's apparently impossible for me",
    "becoming the person who responds to texts immediately instead of three",
    "mastering the skill of packing light instead of bringing my entire closet",
    "learning to wake up without hitting snooze seventeen times every morning",
    "becoming someone who actually finishes books instead of starting ten at once",
    "figuring out how to be on time instead of fashionably late",
    "learning to take good selfies on the first try instead of",
    "becoming the person who has their life together at least a",
    "mastering the art of small talk without it being super awkward honestly",
    "learning to save money instead of spending it all on random stuff",
    "becoming someone who actually uses their planner instead of buying pretty ones",
    "figuring out how to adult without calling my mom for every"
  ],
  "romantic": [
    "building a life with someone who truly gets me and loves deeply ❤️",
    "creating a relationship that's built on trust and genuine connection and partnership",
    "finding someone to grow old with and still be in love with",
    "building a home filled with love and laughter and beautiful memories together",
    "creating a partnership where we both feel supported and loved every single",
    "finding my person and building a beautiful life together full of love",
    "having a love story that inspires others and stands the test of",
    "building a relationship where we choose each other every single day intentionally",
    "creating a family filled with love and warmth and genuine connection always",
    "finding someone who makes me want to be better every single day",
    "building a life where love is the foundation of everything we do",
    "having a partner who's also my best friend and biggest supporter",
    "creating a relationship that grows stronger through every challenge we face together",
    "finding someone to share all of life's adventures and quiet moments with",
    "building a love that's patient and kind and unconditional through everything",
    "having a relationship where we communicate openly and love each other deeply",
    "creating a partnership where we both feel safe to be vulnerable always",
    "finding someone who loves me for exactly who I am right now",
    "building a life where we support each other's dreams and grow",
    "having a love that feels like home no matter where we"
  ],
  "adventurous": [
    "traveling to every continent and experiencing different cultures around the world 🌟",
    "living in different countries and immersing myself in new ways of life",
    "hiking all the major trails and seeing nature's most beautiful places",
    "learning to surf and dive and do all the water sports",
    "road tripping across the country and discovering hidden gems along the way",
    "trying every adventure sport at least once even if it scares me",
    "visiting every national park and camping under the stars in each one",
    "learning new languages so I can connect with people everywhere I travel",
    "sailing around the world and living on a boat for a while",
    "climbing mountains and pushing my physical limits to see what I'm capable",
    "exploring every major city and finding the best local spots in each",
    "living nomadically for a year and working remotely from different countries everywhere",
    "trying cuisine from every culture and becoming a total foodie world traveler",
    "going on safari and seeing wildlife in their natural habitats up close",
    "learning to fly a plane and getting my pilot's license eventually",
    "backpacking through europe and staying in hostels meeting people from everywhere",
    "diving the great barrier reef and exploring underwater worlds and ecosystems",
    "taking a cross country motorcycle trip and feeling totally free on road",
    "visiting all seven wonders of the world and checking them off",
    "living abroad for at least a year to really experience different"
  ],
  "quirky": [
    "collecting something weird and becoming known as the person who has 🎨",
    "mastering a random skill that nobody expects like juggling or ventriloquism honestly",
    "creating art that makes people think what the heck but I love",
    "starting a quirky business that's totally unique and reflects my weird personality",
    "writing a book about my weird thoughts and perspectives on random things",
    "becoming internet famous for something completely random and unexpected and niche honestly",
    "learning an obscure instrument that most people have never heard of before",
    "creating a weird tradition that my future family will think is normal",
    "mastering the art of thrifting and finding the most unique vintage pieces",
    "becoming known for my eclectic style that nobody can quite figure out",
    "starting a collection of something oddly specific that brings me pure joy",
    "learning to make weird art that people either love or hate",
    "becoming the person with the most random fun facts at every party",
    "creating a quirky podcast about niche topics nobody else talks about honestly",
    "mastering a weird hobby that makes me happy even if others",
    "becoming known for my unique perspective on literally everything in life honestly",
    "starting a weird club or community for people with my niche interests",
    "learning to embrace my weirdness so fully that it becomes my brand",
    "creating something totally unique that's never been done before in history",
    "becoming the eccentric person everyone knows and loves for being different"
  ],
  "serious": [
    "building financial independence so I never have to rely on anyone else",
    "creating a career that's meaningful and aligns with my values and passions",
    "making a real impact in my field and leaving a lasting legacy",
    "achieving financial freedom so I can live life on my own terms",
    "building generational wealth for my family and future generations to benefit from",
    "becoming a leader in my industry and inspiring others to follow",
    "creating multiple streams of income so I have security and freedom",
    "investing in real estate and building a portfolio that generates passive income",
    "achieving work life balance while still reaching my professional goals and ambitions",
    "building a business that solves real problems and helps people genuinely",
    "becoming financially literate and teaching others how to manage money wisely too",
    "creating a life where I'm not living paycheck to paycheck anymore",
    "achieving my career goals while maintaining my mental health and wellbeing always",
    "building a retirement fund so I can enjoy my later years",
    "becoming an expert in my field through continuous learning and dedication always",
    "creating stability and security for myself and my future family members",
    "achieving professional success without sacrificing my personal values and integrity ever",
    "building a network of meaningful professional connections that help me grow",
    "becoming someone who's known for their expertise and reliability in their field",
    "creating a life where I have options and freedom to choose"
  ],
  "intellectual": [
    "earning an advanced degree in something I'm truly passionate about learning 🧠",
    "writing a book that contributes something meaningful to my field of interest",
    "becoming fluent in multiple languages and understanding different cultures through them",
    "reading a thousand books and constantly expanding my knowledge and perspective on",
    "contributing to research that advances human understanding of something important and meaningful",
    "teaching others and sharing knowledge that helps them grow and learn too",
    "mastering a complex subject and becoming an expert people turn to",
    "attending lectures and seminars from the greatest minds in various fields",
    "publishing research or articles that contribute to academic discourse and knowledge base",
    "learning from experts in different fields and integrating diverse knowledge together",
    "becoming a lifelong learner who never stops being curious about the world",
    "understanding complex philosophical questions and forming my own well reasoned perspectives on",
    "contributing to important conversations in my field through writing and speaking publicly",
    "building a personal library filled with books that have shaped my thinking",
    "engaging in meaningful intellectual discourse that challenges and expands my worldview constantly",
    "learning about as many subjects as possible to be well rounded",
    "becoming someone who asks better questions rather than just knowing all answers",
    "understanding the world more deeply through study and reflection and critical thinking",
    "contributing something valuable to human knowledge even if it's small and specific",
    "never stopping learning and growing intellectually throughout my entire life journey"
  ],
  "default": [
    "living a life that feels authentic and true to who I am ✨",
    "building meaningful relationships with people who genuinely care about me and vice",
    "finding balance between work and personal life and actually maintaining it successfully",
    "creating a life I'm proud of and don't need vacation from",
    "being happy and content with where I am while still growing",
    "making a positive impact on the people around me every single day",
    "living without regrets and making choices that align with my values always",
    "building a life that brings me joy and fulfillment in every area",
    "becoming the best version of myself while staying true to who I",
    "creating memories and experiences that I'll cherish for my entire life",
    "finding purpose and meaning in the work I do every single day",
    "building a life where I feel fulfilled and genuinely happy most days",
    "being someone my younger self would be proud of and look",
    "creating a life that reflects my values and what matters most to",
    "living intentionally and making conscious choices about how I spend my time",
    "building strong connections with people who lift me up and support me",
    "finding joy in the simple everyday moments and not just big achievements",
    "becoming someone who makes a difference even in small ways every day",
    "living a life full of love and laughter and meaningful experiences",
    "being present and grateful for what I have while working toward"
  ]
};

module.exports = aLifeGoalOfMine;
