const allIAskIsThatYou = {
  "funny": [
    "laugh at my jokes even when they're really not that funny 😂",
    "don't judge me for eating cereal at midnight like a child",
    "let me nap whenever I want without making me feel guilty",
    "appreciate my memes even if you don't fully understand them all honestly",
    "don't make fun of my comfort shows that I've watched",
    "let me be dramatic sometimes because that's just how I process",
    "laugh with me not at me when I do something embarrassing",
    "don't question my snack choices because they make perfect sense to",
    "let me sleep in on weekends without any judgment at all",
    "appreciate my sense of humor even when it's kinda weird honestly",
    "don't take life too seriously because I certainly don't most days",
    "let me be chaotic sometimes because that's when I'm most myself",
    "laugh at yourself too because we're all a mess honestly here",
    "don't judge my spotify wrapped because my music taste is eclectic",
    "let me have my silly moments without making it a thing",
    "appreciate my random bursts of energy even at weird times honestly",
    "don't make me feel bad for binge watching shows all weekend",
    "let me be goofy and weird without trying to tone me",
    "laugh at the absurdity of life with me instead of stressing",
    "don't take my sarcasm personally because that's just how I communicate"
  ],
  "romantic": [
    "choose me every day even when it's not always easy ❤️",
    "love me for who I am not who you want me",
    "communicate openly and honestly even when conversations are hard and uncomfortable honestly",
    "show up for me consistently not just when it's convenient for",
    "be patient with me as I grow and figure things out",
    "make me feel safe enough to be vulnerable and completely myself",
    "put in effort to understand my love language and speak it",
    "be my partner through the good times and the challenging ones",
    "love me on my bad days not just when I'm easy",
    "be honest about your feelings instead of making me guess everything",
    "make time for us even when life gets busy and overwhelming",
    "be affectionate in ways that make me feel loved and valued",
    "support my dreams even when they seem scary or unrealistic to others",
    "be emotionally available and present when I need you most honestly",
    "choose to work through problems instead of running away from them",
    "make me feel like a priority not an option in your",
    "be consistent with your words and actions so I can trust",
    "love me intentionally and show it through your daily actions always",
    "be willing to grow together instead of growing apart over time",
    "make me feel cherished and appreciated for exactly who I am"
  ],
  "adventurous": [
    "say yes to spontaneous adventures even when they're a bit crazy 🌟",
    "be willing to try new things with me even if scary",
    "explore the world with me and make memories we'll never forget",
    "be open to last minute plans and going with the flow",
    "step outside your comfort zone sometimes because that's where fun happens",
    "be down for road trips with no real destination in mind",
    "try new foods and experiences without complaining about it being different",
    "be spontaneous sometimes and surprise me with random fun adventures together",
    "explore new places with me even if they're just in our",
    "be willing to get lost and find our way back together",
    "say yes to adventures that scare us both a little bit",
    "be open to trying activities we've never done before at all",
    "travel with me and experience different cultures and ways of living",
    "be down for weekend getaways even if we plan them last",
    "step out of routine sometimes because variety makes life so much",
    "be willing to take risks with me and see what happens",
    "explore nature and go on hikes to places we've never been",
    "be spontaneous with date ideas instead of doing the same things",
    "say yes to new experiences even when they push our boundaries",
    "be my adventure partner in life and try everything with me"
  ],
  "quirky": [
    "let me be my weird authentic self without trying to change 🎨",
    "appreciate my quirks instead of trying to make me more normal honestly",
    "embrace the weird with me because normal is honestly so boring",
    "let me have my odd interests without questioning why I like",
    "be weird with me and not worry about what others think",
    "appreciate my unique perspective even when it's different from everyone else's",
    "let me express myself however I want without judgment or criticism",
    "embrace my eccentricities because they're what make me who I am",
    "be open to my unconventional ideas and ways of doing things",
    "let me be different without trying to fit me into a",
    "appreciate my niche interests even if you don't understand them fully",
    "be weird alongside me instead of making me feel alone in",
    "let me have my quirky routines because they help me function",
    "embrace the unconventional with me and not worry about fitting in",
    "appreciate my unique style choices even when they're a bit out",
    "let me be authentically myself in all my weird glory honestly",
    "be open to my random ideas that might seem strange at",
    "appreciate the things that make me different from everyone else around",
    "let me be eccentric without making me feel like it's bad",
    "embrace all my weirdness because that's the real me you're getting"
  ],
  "serious": [
    "respect my boundaries without making me feel guilty for having them",
    "be honest with me even when the truth is uncomfortable or",
    "take accountability for your actions instead of making excuses all the",
    "respect my time because it's valuable and I choose how to",
    "be reliable and do what you say you're going to do",
    "treat me as an equal partner in everything we do together",
    "respect my goals and ambitions even if they're different from yours",
    "be mature enough to communicate instead of playing games with me",
    "respect my need for independence because I'm my own person first",
    "be honest about your intentions from the start so I know",
    "take my feelings seriously instead of dismissing them as being dramatic",
    "respect my values even when they differ from your own personal",
    "be consistent with your words and actions so I can trust",
    "take responsibility for your part in conflicts instead of blaming me",
    "respect my decisions about my own life because they're mine to",
    "be emotionally mature enough to handle difficult conversations without shutting down",
    "take my career and personal goals as seriously as your own",
    "respect my standards because I set them for my own wellbeing",
    "be honest about where you're at instead of leading me on",
    "take our relationship seriously and put in the effort it deserves"
  ],
  "intellectual": [
    "engage in real conversations that go beyond just surface level topics 🧠",
    "be open to learning from me just as I learn from",
    "challenge my thinking in respectful ways that help me grow intellectually",
    "be curious about the world and want to learn new things",
    "engage with my ideas seriously instead of dismissing them as overthinking",
    "be open to having thoughtful debates without getting defensive or personal",
    "respect my intelligence and not talk down to me ever at",
    "be willing to discuss complex topics and ideas that matter to",
    "challenge yourself intellectually and not just stay in your comfort zone",
    "be open to different perspectives and willing to change your mind",
    "engage in meaningful discussions that make us both think more deeply",
    "be curious and ask questions instead of assuming you know everything",
    "respect my opinions even when they differ from yours or challenge",
    "be intellectually honest and admit when you don't know something instead",
    "engage with ideas that challenge your worldview instead of dismissing them",
    "be open to learning together and growing our understanding of things",
    "respect my need for intellectual stimulation because I get bored easily",
    "be willing to have deep conversations about life and meaning regularly",
    "challenge me to think differently and expand my perspective on things",
    "be genuinely curious about understanding different viewpoints and ideas from mine"
  ],
  "default": [
    "be kind and treat me with basic respect and human decency ✨",
    "be honest with me because trust is the foundation of everything",
    "communicate openly instead of making me guess what you're thinking or",
    "be yourself authentically because I want to know the real you",
    "respect my boundaries and understand they exist for good reasons always",
    "be consistent and reliable so I know what to expect from",
    "treat me the way you'd want to be treated in return",
    "be patient with me as I figure things out and grow",
    "listen when I talk instead of just waiting for your turn",
    "be understanding when I'm having a bad day or struggling with",
    "respect my feelings even if you don't fully understand them all",
    "be genuine and real with me instead of putting on an",
    "make an effort because relationships take work from both people involved",
    "be supportive of my goals and dreams even when they're different",
    "respect my time and don't take it for granted ever honestly",
    "be honest about your intentions so I know where we stand",
    "treat me with kindness even when we disagree about something important",
    "be present when we're together instead of being distracted by everything",
    "respect me as a whole person with my own thoughts and",
    "be willing to work through issues instead of giving up when"
  ]
};

module.exports = allIAskIsThatYou;
