const changeMyMindAbout = {
  "funny": [
    "pineapple on pizza because honestly it's kinda good and I'm not sorry 😂",
    "morning people being real because I think they're all just faking",
    "cats being better than dogs when clearly both are perfect in different",
    "coffee being necessary when I literally can't function without it every morning",
    "adulting being fun because it's mostly just paying bills and being tired",
    "my music taste being weird when it's actually iconic and ahead of",
    "reality tv being trash when it's actually the best entertainment ever made",
    "my sleep schedule being bad when night time is clearly the best",
    "texting back fast being clingy when I'm just excited to talk honestly",
    "being indecisive when I just like keeping my options open always lol",
    "overthinking everything when I'm just being thorough about life decisions and stuff",
    "my hobbies being random when they're actually perfectly curated chaos and fun",
    "staying in being boring when it's actually the best time ever",
    "my jokes being bad when they're actually hilarious and everyone's just mean",
    "being dramatic when I'm just expressing myself with passion and energy honestly",
    "my fashion choices when I think I look cute and that's all",
    "needing snacks constantly when it's literally just self care and survival mode",
    "talking too much when I'm just enthusiastic about literally everything in life",
    "being too online when the internet is where all the fun happens",
    "my comfort shows being basic when they're classics for a good reason"
  ],
  "romantic": [
    "love at first sight because I think real connection takes time ❤️",
    "soulmates existing when I believe we create deep bonds through effort and care",
    "grand gestures being necessary when small consistent acts mean so much more",
    "relationships being easy when the best ones take work and communication honestly",
    "love being enough when compatibility and effort matter just as much too",
    "romance being dead when I see beautiful love stories happening every day",
    "long distance not working when strong love can survive anything with effort",
    "opposites attracting when I think shared values matter more than differences do",
    "love languages being real when I think they're actually super important honestly",
    "timing being everything when the right person makes any time feel perfect",
    "butterflies fading meaning love is gone when comfort is actually beautiful too",
    "relationships needing space when I think closeness and intimacy matter more honestly",
    "love being complicated when honest communication makes it so much simpler always",
    "romance needing to be spontaneous when planned dates show thoughtfulness and care",
    "vulnerability being weakness when it's actually the strongest thing you can do",
    "love changing over time being bad when growth together is beautiful honestly",
    "needing someone being codependent when wanting partnership is actually healthy and normal",
    "expressing feelings being too much when honesty creates the deepest connections always",
    "relationships needing to be perfect when real love embraces all the flaws",
    "falling fast being reckless when sometimes you just know it feels right"
  ],
  "adventurous": [
    "staying in my comfort zone when the best memories happen outside it 🌟",
    "planning everything when spontaneous adventures are way more fun and exciting honestly",
    "playing it safe when taking risks leads to the best stories",
    "routine being good when variety and new experiences make life so exciting",
    "traveling alone being scary when it's actually the most freeing thing ever",
    "adventure needing to be expensive when the best ones are free honestly",
    "staying local when there's a whole world out there to explore right",
    "needing a plan when winging it leads to the best unexpected moments",
    "comfort being better than adventure when growth happens outside your comfort zone",
    "familiar being best when new experiences teach you so much about yourself",
    "safety being everything when calculated risks make life worth living and exciting",
    "adventure being for young people when it's actually for anyone with curiosity",
    "needing company for adventures when solo trips are incredibly empowering and freeing",
    "bucket lists being cliche when they actually motivate you to live fully",
    "spontaneity being irresponsible when it brings the most joy and best memories",
    "staying grounded when I think reaching for more makes life so exciting",
    "playing it safe with food when trying new cuisines is half the",
    "needing comfort when pushing boundaries leads to the most growth and fun",
    "adventure requiring extreme sports when exploring new places counts just as much",
    "routine being necessary when breaking it creates the most memorable experiences ever"
  ],
  "quirky": [
    "normal being better when weird is so much more interesting and fun 🎨",
    "fitting in mattering when standing out is way more authentic and cool",
    "being too much when I'm literally just the right amount of me",
    "my weird interests being embarrassing when they're actually what makes me unique",
    "mainstream being better when niche things are so much more interesting honestly",
    "toning it down when being fully myself is the whole point of",
    "weird being bad when it's actually the most interesting thing about people",
    "normal hobbies being better when mine are way more fun and creative",
    "my quirks being too much when they're what make me memorable honestly",
    "fitting a mold when breaking it is so much more fun and",
    "being relatable when being unique is way more interesting to people honestly",
    "my style being weird when I think it's actually ahead of trends",
    "conventional being better when unconventional is where all the creativity happens and thrives",
    "my humor being too niche when the right people totally get it",
    "being eccentric being negative when it's actually a compliment to me honestly",
    "normal conversations when deep weird ones are so much more fun and",
    "my collections being random when they're actually carefully curated and meaningful to",
    "being too different when different is literally what makes life interesting and",
    "mainstream taste being better when mine is more authentic to who I",
    "toning down my personality when being fully me attracts the right people"
  ],
  "serious": [
    "settling for less when I know exactly what I deserve in life",
    "lowering my standards when they exist for good reasons and protect me",
    "compromising my values when they're what make me who I truly am",
    "giving up on my goals when I've worked too hard to quit",
    "accepting mediocrity when I'm capable of so much more than that honestly",
    "my boundaries being too strict when they're necessary for my wellbeing always",
    "being too picky when knowing what I want is actually self awareness",
    "my expectations being too high when I just know my worth clearly",
    "needing to change when growth is different from losing who I am",
    "success being luck when it's actually hard work and dedication paying off",
    "my priorities being wrong when they align with my values and goals",
    "being too serious when I'm just focused on building my best life",
    "my standards being unrealistic when they're based on what I deserve honestly",
    "needing to settle when waiting for right is worth it every time",
    "my goals being too ambitious when I'm willing to work for them",
    "being inflexible when I'm just clear about my non negotiables in life",
    "my path being wrong when it's mine and that's what matters",
    "needing to compromise more when my boundaries are already healthy and reasonable",
    "being too focused when dedication is what leads to real success always",
    "my vision being unrealistic when I have a plan to achieve it"
  ],
  "intellectual": [
    "knowing everything when staying curious and learning is way more important 🧠",
    "being right always when being open to new perspectives matters more",
    "intelligence being fixed when growth mindset is everything for learning and development",
    "formal education being the only way when self learning is powerful too",
    "one right answer existing when most things have nuance and complexity honestly",
    "my opinion being fact when I'm always open to changing my mind",
    "intelligence being innate when effort and curiosity matter just as much always",
    "knowing more making you better when humility and openness matter more honestly",
    "books being better than experience when both teach valuable lessons in life",
    "my perspective being complete when there's always more to learn and understand",
    "being smart meaning you know everything when it's about asking good questions",
    "logic being everything when emotion and intuition have value too in decisions",
    "my understanding being final when I'm constantly evolving and learning new things",
    "intelligence being one dimensional when it comes in so many different forms",
    "being well read meaning you're wise when experience teaches just as much",
    "my knowledge being enough when there's infinite things to learn and explore",
    "certainty being good when doubt drives curiosity and deeper understanding of things",
    "expertise meaning you stop learning when the best experts stay curious always",
    "my views being set when I actively seek out perspectives that challenge",
    "intelligence being about facts when critical thinking and wisdom matter more honestly"
  ],
  "default": [
    "my way being the only way when I'm open to different perspectives ✨",
    "being set in my ways when I'm actually pretty flexible about things",
    "my opinion being final when I love hearing other viewpoints and learning honestly",
    "knowing best when I'm always down to learn something new from anyone",
    "my preferences being universal when everyone's different and that's totally cool with",
    "being right when having good conversations matters more than winning arguments honestly",
    "my taste being superior when it's just what works for me personally",
    "my approach being best when different methods work for different people always",
    "being closed minded when I actually love exploring new ideas and perspectives",
    "my way or the highway when compromise and understanding matter so much",
    "knowing everything when admitting I don't know is actually pretty freeing honestly",
    "being stubborn when I'm just passionate about things I care about",
    "my views being fixed when I'm constantly growing and changing my mind",
    "being inflexible when I adapt pretty easily to new situations and ideas",
    "my perspective being complete when there's always more to consider and learn",
    "being set when I'm actually open to changing based on new information",
    "my judgment being final when I love reconsidering things with new context honestly",
    "knowing better when everyone has something valuable to teach if you listen",
    "being rigid when I'm pretty open to different ways of doing things",
    "my opinion mattering most when collaboration and openness create better outcomes always"
  ]
};

module.exports = changeMyMindAbout;
