const datingMeIsLike = {
  "funny": [
    "a rom com but with way more snacks and naps involved 😂",
    "an adventure where we get lost but make it fun anyway",
    "a comedy show where I'm both the star and the audience",
    "a reality tv show that's chaotic but somehow entertaining to watch",
    "a sitcom where every episode is me being accidentally funny and weird",
    "a rollercoaster that's mostly fun with occasional moments of what just",
    "a meme come to life with random bursts of energy and",
    "a comedy special where half the jokes are about my own",
    "an improv show where I'm making it up as I go",
    "a blooper reel because I mess up but laugh about it",
    "a variety show with random talents and even more random thoughts",
    "a comedy podcast where I overshare and laugh at my own",
    "a game show where the rules change every five minutes honestly",
    "a stand up routine where I'm the only one laughing sometimes",
    "a prank show but the pranks are mostly on myself accidentally",
    "a cooking show where everything almost burns but tastes good eventually",
    "a talk show where I ask weird questions and give weirder",
    "a comedy sketch that's equal parts funny and confusing for everyone",
    "a sitcom rerun that you've seen before but still makes you",
    "a comedy roast where I roast myself before anyone else can"
  ],
  "romantic": [
    "finding your best friend and falling in love at same time ❤️",
    "a slow burn romance where every moment feels meaningful and intentional",
    "coming home after a long day because I'm your safe space",
    "a love story where we choose each other every single day",
    "finding someone who sees you and loves all of you completely",
    "a partnership where we grow together instead of growing apart over",
    "falling in love with your favorite person over and over again",
    "a romance novel but real and messy and beautiful all at",
    "finding someone who makes ordinary moments feel special and magical somehow",
    "a love that feels easy and natural like it was meant",
    "building a life together filled with laughter and love and support",
    "finding your person who gets you on a level nobody else",
    "a relationship where vulnerability is safe and love is unconditional always",
    "coming home to someone who makes everything feel better just by",
    "a love story that's built on friendship and genuine connection first",
    "finding someone who loves you on your worst days not just",
    "a partnership where we support each other's dreams and celebrate wins",
    "falling for someone who makes you want to be better every",
    "a romance where small gestures mean more than grand expensive displays",
    "finding love that feels like home no matter where we are"
  ],
  "adventurous": [
    "a spontaneous road trip where we figure it out as we 🌟",
    "an adventure where every day brings something new and exciting to",
    "exploring the world together and making memories we'll never forget ever",
    "a journey where we say yes to things that scare us",
    "an expedition where we get lost but find amazing things along",
    "a travel documentary where we're discovering new places and experiences constantly",
    "an adventure story where we're both the main characters living fully",
    "exploring life together and trying everything at least once or twice",
    "a quest where we push boundaries and see what we're capable",
    "an odyssey filled with spontaneous plans and unexpected beautiful moments together",
    "a safari where every day is different and exciting in new",
    "exploring uncharted territory together and creating our own path through life",
    "an adventure race where we're partners working together toward the finish",
    "a journey of discovery where we learn about ourselves and each",
    "an exploration where comfort zones are left behind for growth and",
    "a treasure hunt where the real treasure is the memories we",
    "an expedition where we support each other through challenges and celebrate",
    "a voyage where we navigate life's ups and downs together as",
    "an adventure where spontaneity and planning balance out perfectly for us",
    "a journey where we collect experiences instead of things and love"
  ],
  "quirky": [
    "dating your weird best friend who just gets your odd humor 🎨",
    "an indie film that's quirky and different from anything mainstream honestly",
    "a weird art project that makes sense only to us two",
    "an alternative universe where normal rules don't apply to us at",
    "a quirky sitcom where the jokes are niche but hilarious to",
    "dating someone who embraces your weirdness and adds their own to",
    "an experimental film that's unconventional but somehow works perfectly for us",
    "a weird book that you can't put down even though confusing",
    "an offbeat comedy where the humor is specific and wonderfully strange",
    "dating your favorite weirdo who makes life more interesting every single",
    "a cult classic that not everyone gets but the right",
    "an eclectic playlist where every song is different but somehow flows",
    "a quirky rom com where the meet cute is actually weird",
    "dating someone who celebrates your oddities instead of trying to change",
    "an indie game that's weird and wonderful and totally unique honestly",
    "a strange dream that makes no sense but feels right somehow",
    "an art house film that's beautifully weird and unapologetically different from",
    "dating your partner in weirdness who matches your energy perfectly always",
    "a quirky adventure where we make our own rules and have",
    "an unconventional love story that doesn't follow any traditional rom com"
  ],
  "serious": [
    "a partnership built on mutual respect and genuine effort from both",
    "a commitment where we both show up and do the work",
    "a mature relationship where communication is honest even when it's hard",
    "building something real that requires effort and intention from both of",
    "a partnership where we hold each other accountable and grow together",
    "a relationship where boundaries are respected and feelings are taken seriously",
    "building a foundation of trust that takes time and consistent effort",
    "a commitment to growth both individually and together as a team",
    "a mature partnership where we work through issues instead of running",
    "building something meaningful that aligns with both our values and goals",
    "a relationship where emotional intelligence and communication are priorities for both",
    "a partnership where we're equals working toward shared goals and dreams",
    "building trust through consistency and following through on what we say",
    "a commitment where we prioritize the relationship and make time for",
    "a mature connection where we support each other's individual growth and",
    "building something stable that can weather challenges because we're committed to",
    "a partnership where honesty is valued even when truth is uncomfortable",
    "a relationship where we take each other's needs and boundaries seriously",
    "building a life together with intention and purpose and shared values",
    "a commitment to being better partners and people through continuous effort"
  ],
  "intellectual": [
    "endless conversations that challenge how you think about everything in life 🧠",
    "a meeting of minds where we learn from each other constantly",
    "deep discussions that go way beyond surface level small talk always",
    "a partnership where we challenge each other to think more deeply",
    "intellectual stimulation mixed with emotional connection and genuine understanding of each",
    "conversations that make you question your assumptions and expand your perspective",
    "a relationship where we're both students and teachers learning from each",
    "debates that are respectful but push us to think more critically",
    "a partnership where curiosity and learning are valued and encouraged always",
    "discussions about philosophy and life and meaning late into the night",
    "a meeting of minds that creates something greater than the sum",
    "intellectual compatibility where we understand each other's thought processes and perspectives",
    "conversations that leave you thinking long after they've ended for days",
    "a partnership where we explore ideas together and challenge each other",
    "deep dives into topics that fascinate us both and spark curiosity",
    "a relationship where intelligence is appreciated and nurtured in both of",
    "discussions that range from silly to serious to deeply philosophical seamlessly",
    "a partnership where we're intellectually matched and constantly learning new things",
    "conversations that feel like discovering new worlds and perspectives together always",
    "a meeting of minds where we make each other smarter and"
  ],
  "default": [
    "finding someone who makes everyday life feel a little more special ✨",
    "a partnership where we're both comfortable being our authentic selves always",
    "building something real with someone who genuinely cares about you and",
    "a relationship that feels natural and easy most of the time",
    "finding someone who gets you and accepts you for who you",
    "a partnership where we balance each other out in good ways",
    "building a connection that's based on genuine friendship and mutual respect",
    "a relationship where we can be silly and serious in equal",
    "finding someone who makes you laugh and supports you through everything life",
    "a partnership where we grow together and bring out each other's",
    "building something meaningful with someone who shows up consistently for you",
    "a relationship that feels comfortable but never boring or stagnant ever",
    "finding someone who appreciates you for exactly who you are right",
    "a partnership where communication is open and feelings are expressed honestly",
    "building a life together that reflects both of our values and",
    "a relationship where we support each other's goals and celebrate each",
    "finding someone who makes you feel seen and understood and valued",
    "a partnership where we're teammates working together through life's challenges and",
    "building something that feels right and authentic to both of us",
    "a relationship where love is shown through actions not just words"
  ]
};

module.exports = datingMeIsLike;
