const datingMeIsLike = {
  funny: [
    "a rom com with more snacks and naps",
    "an adventure where we get lost but make it fun",
    "a comedy show where Im both star and audience",
    "a reality TV show thats chaotic but entertaining",
    "a sitcom where Im accidentally funny and weird",
    "a rollercoaster thats mostly fun with occasional what just happened",
    "a meme come to life with random energy",
    "a comedy special where I overshare and laugh at myself",
    "an improv show making it up as I go",
    "a blooper reel because I mess up but laugh",
    "a variety show with random talents and thoughts",
    "a podcast where I overshare and laugh at myself",
    "a game show where rules change every five minutes",
    "a stand up routine where Im the only one laughing",
    "a prank show where pranks are on myself",
    "a cooking show where everything almost burns",
    "a talk show with weird questions and answers",
    "a comedy sketch thats equal parts funny and confusing",
    "a sitcom rerun youve seen before but still enjoy",
    "a comedy roast where I roast myself first",
  ],
  romantic: [
    "finding your best friend and falling in love",
    "a slow burn romance where every moment feels meaningful",
    "coming home to me as your safe space",
    "a love story where we choose each other daily",
    "finding someone who sees you and loves all of you",
    "a partnership where we grow together not apart",
    "falling in love with your favorite person repeatedly",
    "a romance novel thats real and messy and beautiful",
    "finding someone who makes ordinary moments feel special",
    "a love that feels easy and natural",
    "building a life together with laughter and love",
    "finding your person who gets you on another level",
    "a relationship where vulnerability is safe",
    "coming home to someone who makes everything better",
    "a love story built on friendship first",
    "finding someone who loves you on your worst days",
    "a partnership that supports each others dreams",
    "falling for someone who makes you want better",
    "a romance where small gestures mean more",
    "finding love that feels like home",
  ],
  adventurous: [
    "a spontaneous road trip where we figure it out",
    "an adventure where every day brings something new",
    "exploring the world together and making memories",
    "a journey where we say yes to scary things",
    "an expedition where we get lost but find amazing things",
    "a travel documentary discovering new places and experiences",
    "an adventure story where were both main characters",
    "exploring life together and trying everything at least once",
    "a quest where we push boundaries",
    "an odyssey with spontaneous plans and unexpected moments",
    "a safari where every day is different",
    "exploring uncharted territory together and creating our own path",
    "an adventure race where were partners",
    "a journey of discovery about ourselves and each other",
    "an exploration where comfort zones are left behind",
    "a treasure hunt where memories are the real treasure",
    "an expedition where we support each other through challenges",
    "a voyage navigating lifes ups and downs together",
    "an adventure where spontaneity and planning balance perfectly",
    "a journey where we collect experiences not things",
  ],
  quirky: [
    "dating your weird best friend who gets your humor",
    "an indie film thats quirky and different",
    "a weird art project that makes sense only to us",
    "an alternative universe where normal rules dont apply",
    "a quirky sitcom with niche but hilarious jokes",
    "dating someone who embraces your weirdness",
    "an experimental film that somehow works for us",
    "a weird book you cant put down",
    "an offbeat comedy with specific and wonderful humor",
    "dating your favorite weirdo who makes life interesting",
    "a cult classic not everyone gets",
    "an eclectic playlist where every song flows",
    "a quirky rom com where the meet cute is weird",
    "dating someone who celebrates your oddities",
    "an indie game thats weird and wonderful",
    "a strange dream that makes no sense but feels right",
    "an art house film thats beautifully weird",
    "dating your partner in weirdness who matches your energy",
    "a quirky adventure where we make our own rules",
    "an unconventional love story that doesnt follow tradition",
  ],
  serious: [
    "a partnership built on mutual respect and genuine effort",
    "a commitment where we both show up and do work",
    "a mature relationship with honest communication even when hard",
    "building something real that requires effort and intention",
    "a partnership where we hold each other accountable",
    "a relationship where boundaries are respected and feelings matter",
    "building a foundation of trust over time",
    "a commitment to growth both individually and together",
    "a mature partnership where we work through issues",
    "building something meaningful that aligns with our values",
    "a relationship where emotional intelligence is a priority",
    "a partnership where were equals working toward shared goals",
    "building trust through consistency and following through",
    "a commitment where we prioritize the relationship",
    "a mature connection supporting each others individual growth",
    "building something stable that can weather challenges",
    "a partnership where honesty is valued even when uncomfortable",
    "a relationship where needs and boundaries are taken seriously",
    "building a life together with intention and purpose",
    "a commitment to being better partners through continuous effort",
  ],
  intellectual: [
    "endless conversations that challenge how you think",
    "a meeting of minds where we learn from each other",
    "deep discussions that go beyond surface level",
    "a partnership where we challenge each other to think deeper",
    "intellectual stimulation mixed with emotional connection",
    "conversations that make you question your assumptions",
    "a relationship where were both students and teachers",
    "respectful debates that push us to think critically",
    "a partnership where curiosity and learning are valued",
    "discussions about philosophy and meaning late into the night",
    "a meeting of minds creating something greater than the sum",
    "intellectual compatibility where we understand each other",
    "conversations that leave you thinking long after",
    "a partnership where we explore ideas together",
    "deep dives into topics that fascinate us both",
    "a relationship where intelligence is appreciated and nurtured",
    "discussions ranging from silly to serious seamlessly",
    "a partnership where were intellectually matched and learning",
    "conversations that feel like discovering new worlds together",
    "a meeting of minds where we make each other smarter",
  ],
  default: [
    "finding someone who makes everyday life feel special",
    "a partnership where were both comfortable being authentic",
    "building something real with someone who genuinely cares",
    "a relationship that feels natural and easy",
    "finding someone who gets you and accepts you",
    "a partnership where we balance each other out",
    "building a connection based on genuine friendship and respect",
    "a relationship where we can be silly and serious",
    "finding someone who makes you laugh and supports you",
    "a partnership where we grow together and bring out the best",
    "building something meaningful with someone who shows up",
    "a relationship thats comfortable but never boring",
    "finding someone who appreciates you for exactly who you are",
    "a partnership with open communication and honest feelings",
    "building a life together that reflects our values",
    "a relationship where we support each others goals",
    "finding someone who makes you feel seen and understood",
    "a partnership where were teammates through lifes challenges",
    "building something that feels right and authentic",
    "a relationship where love is shown through actions",
  ],
};

module.exports = datingMeIsLike;
