const doYouAgreeOrDisagreeThat = {
  funny: [
    "you read recipe blogs like they're romantic novels about disagree.",
    "strong opinions about the optimal cereal-to-milk ratio",
    "sending 2 AM memes that instantly improve my mood about disagree.",
    "turning minor disasters into comedy sketches",
    "making very specific mood playlists",
    "quoting obscure movies at inconvenient times",
    "celebrating tiny wins like a big holiday",
    "pretending to be a food critic at food trucks",
    "dramatic reactions to small things are my specialty",
    "messy buns and too much coffee fuel my chaos",
    "you read recipe blogs like they're romantic novels about disagree so much.",
    "strong opinions about the optimal cereal-to-milk ratio lowkey.",
    "sending 2 AM memes that instantly improve my mood about disagree and smiling.",
    "turning minor disasters into comedy sketches for real.",
    "making very specific mood playlists and happy.",
    "quoting obscure movies at inconvenient times and grinning.",
    "celebrating tiny wins like a big holiday no cap.",
    "pretending to be a food critic at food trucks seriously.",
    "dramatic reactions to small things are my specialty always.",
    "messy buns and too much coffee fuel my chaos and proud of it.",
  ],
  romantic: [
    "I melt over thoughtful touches about disagree.",
    "Warm check-ins make my day.",
    "Late-night cuddles and warm honesty are my vibe about disagree.",
    "I respond to steady attention, not games.",
    "Small surprises mean the most to me.",
    "I save my best for people who show up.",
    "Cozy nights and cute check-ins win me.",
    "I like slow flirts and real feelings.",
    "Sweet notes and small details make me smile.",
    "I keep it real and flirty.",
    "I melt over thoughtful touches about disagree so much.",
    "Warm check-ins make my day lowkey.",
    "Late-night cuddles and warm honesty are my vibe about disagree and smiling.",
    "I respond to steady attention, not games for real.",
    "Small surprises mean the most to me and happy.",
    "I save my best for people who show up and grinning.",
    "Cozy nights and cute check-ins win me no cap.",
    "I like slow flirts and real feelings seriously.",
    "Sweet notes and small details make me smile always.",
    "I keep it real and flirty and proud of it.",
  ],
  adventurous: [
    "Spontaneous trips make my heart race about disagree.",
    "I pack snacks and a brave playlist.",
    "Little risks with kind people are my thing about disagree.",
    "Weekend road trips are my happy place.",
    "I’m down to try new things if it’s respectful.",
    "Adventures with good vibes beat strict plans.",
    "I set boundaries but bring the energy.",
    "I trade time for wild memories.",
    "I love sharing maps and silly playlists.",
    "Brave stories and warm check-ins hook me.",
    "Spontaneous trips make my heart race about disagree so much.",
    "I pack snacks and a brave playlist lowkey.",
    "Little risks with kind people are my thing about disagree and smiling.",
    "Weekend road trips are my happy place for real.",
    "I’m down to try new things if it’s respectful and happy.",
    "Adventures with good vibes beat strict plans and grinning.",
    "I set boundaries but bring the energy no cap.",
    "I trade time for wild memories seriously.",
    "I love sharing maps and silly playlists always.",
    "Brave stories and warm check-ins hook me and proud of it.",
  ],
  quirky: [
    "I collect odd stories and giggle about disagree.",
    "Please ask before touching my plants.",
    "Secret playlists and weird snacks are my love language about disagree.",
    "I keep my quirks and give big smiles.",
    "I trade jokes for cozy invites.",
    "I love tiny rituals and honest weirdness.",
    "My laugh is loud and a little dramatic.",
    "I guard my space and reward charm.",
    "I adore playful weirdness and kind folks.",
    "Small oddities make me curious.",
    "I collect odd stories and giggle about disagree so much.",
    "Please ask before touching my plants lowkey.",
    "Secret playlists and weird snacks are my love language about disagree and smiling.",
    "I keep my quirks and give big smiles for real.",
    "I trade jokes for cozy invites and happy.",
    "I love tiny rituals and honest weirdness and grinning.",
    "My laugh is loud and a little dramatic no cap.",
    "I guard my space and reward charm seriously.",
    "I adore playful weirdness and kind folks always.",
    "Small oddities make me curious and proud of it.",
  ],
  serious: [
    "I value honesty and steady follow-through about disagree.",
    "I show up, no games, just real care.",
    "I set boundaries and respect yours about disagree.",
    "I give time to people who prove themselves.",
    "Kind consistency wins my attention.",
    "I prefer deep talks to small talk.",
    "I protect my time and share it wisely.",
    "I like partners who keep their promises.",
    "Real effort outshines fancy words.",
    "I treasure trust and thoughtful actions.",
    "I value honesty and steady follow-through about disagree so much.",
    "I show up, no games, just real care lowkey.",
    "I set boundaries and respect yours about disagree and smiling.",
    "I give time to people who prove themselves for real.",
    "Kind consistency wins my attention and happy.",
    "I prefer deep talks to small talk and grinning.",
    "I protect my time and share it wisely no cap.",
    "I like partners who keep their promises seriously.",
    "Real effort outshines fancy words always.",
    "I treasure trust and thoughtful actions and proud of it.",
  ],
  intellectual: [
    "I love late chats and coffee about disagree.",
    "Clever ideas and playful debate light me up.",
    "Smart books and honest thoughts feel sexy about disagree.",
    "I trade curiosities and thoughtful notes.",
    "I like people who read and say interesting things.",
    "Curiosity keeps me interested.",
    "Brainy banter and soft laughs work for me.",
    "I guard my focus but share it for good talks.",
    "Witty messages and honest curiosity win me.",
    "Thoughtful conversations feel like sparks.",
    "I love late chats and coffee about disagree so much.",
    "Clever ideas and playful debate light me up lowkey.",
    "Smart books and honest thoughts feel sexy about disagree and smiling.",
    "I trade curiosities and thoughtful notes for real.",
    "I like people who read and say interesting things and happy.",
    "Curiosity keeps me interested and grinning.",
    "Brainy banter and soft laughs work for me no cap.",
    "I guard my focus but share it for good talks seriously.",
    "Witty messages and honest curiosity win me always.",
    "Thoughtful conversations feel like sparks and proud of it.",
  ],
  default: [
    "I want honesty, sparks, and small kindnesses about disagree.",
    "Boundaries help me stay open and present.",
    "I prefer real connection over empty noise about disagree.",
    "Small gestures and steady check-ins are my thing.",
    "I share my space with people who show up.",
    "Warm messages and playful banter make my day.",
    "I protect my time but trade it for fun.",
    "Simple plans and sweet follow-through make me smile.",
    "Respect my limits and I’ll cheer you on.",
    "I like people who know how to show up.",
    "I want honesty, sparks, and small kindnesses about disagree so much.",
    "Boundaries help me stay open and present lowkey.",
    "I prefer real connection over empty noise about disagree and smiling.",
    "Small gestures and steady check-ins are my thing for real.",
    "I share my space with people who show up and happy.",
    "Warm messages and playful banter make my day and grinning.",
    "I protect my time but trade it for fun no cap.",
    "Simple plans and sweet follow-through make me smile seriously.",
    "Respect my limits and I’ll cheer you on always.",
    "I like people who know how to show up and proud of it.",
  ],
};

module.exports = doYouAgreeOrDisagreeThat;
