const doYouAgreeOrDisagreeThat = {
  "funny": [
    "breakfast food is acceptable at any time of day or night 😂",
    "naps should be socially acceptable for adults in the workplace too",
    "pizza is a vegetable if it has any toppings on it",
    "staying in is way better than going out most of time",
    "coffee is a personality trait and I'm okay with that honestly",
    "being an adult is just googling how to do everything constantly",
    "sweatpants are appropriate attire for literally any occasion in life honestly",
    "cereal is a soup and I will die on this hill",
    "the best conversations happen at 2am for some weird reason always",
    "dogs are better than most people I've met in my life",
    "sleeping is the best hobby and nobody can change my mind",
    "texting is better than calling because phone calls are honestly terrifying",
    "being tired is just a permanent state of existence now honestly",
    "snacks are a food group and should be treated as such",
    "weekends should be three days long because two isn't enough time",
    "morning people are suspicious and probably not fully human at all",
    "online shopping counts as cardio because scrolling burns calories probably right",
    "having plants makes you responsible even if they're all dying slowly",
    "binge watching shows is a valid way to spend an entire",
    "being indecisive is actually just keeping your options open which is"
  ],
  "romantic": [
    "love languages are real and important to understand in relationships ❤️",
    "small consistent gestures mean more than big grand romantic displays always",
    "communication is the most important part of any healthy relationship ever honestly",
    "you should be friends with your partner before anything else really",
    "love is a choice you make every day not just feeling",
    "relationships take work and effort from both people to truly succeed",
    "vulnerability is strength not weakness in a relationship with someone you",
    "you can love someone and still need space for yourself sometimes",
    "actions speak louder than words when it comes to showing love",
    "healthy relationships should make you feel more yourself not less of",
    "compromise is necessary but you shouldn't compromise your core values ever honestly",
    "trust is the foundation and without it nothing else really matters",
    "you should never have to beg for basic respect or effort",
    "love should feel safe and comfortable not anxious and uncertain always",
    "your partner should be your biggest supporter not your biggest critic",
    "emotional intimacy is just as important as physical intimacy in relationships always",
    "you can't love someone into changing if they don't want to",
    "healthy relationships bring out the best in both people not worst",
    "you should be able to be fully yourself with your",
    "love isn't enough if there's no compatibility or shared values"
  ],
  "adventurous": [
    "life is too short to not take risks and try 🌟",
    "the best memories come from spontaneous unplanned adventures and experiences always",
    "comfort zones are meant to be pushed and expanded regularly honestly",
    "traveling changes you and opens your mind in incredible ways always",
    "saying yes to new experiences is always better than saying no",
    "adventure doesn't have to be expensive to be meaningful and fun",
    "getting lost sometimes leads to the best discoveries and memories ever",
    "life's too short to stay in one place for too long",
    "trying new things is how you figure out who you are",
    "the best stories come from times when things didn't go",
    "spontaneity makes life more exciting and worth living every single day",
    "you should travel while you're young and have the energy for",
    "experiences are more valuable than material possessions you can buy with",
    "stepping outside your comfort zone is where real growth happens always",
    "adventure is a mindset not just about traveling to exotic places",
    "life begins at the end of your comfort zone every time",
    "you'll regret the chances you didn't take more than ones you",
    "exploring new places teaches you more than any classroom ever could",
    "the best adventures are the ones you take with people you",
    "living in the moment is better than constantly planning for future"
  ],
  "quirky": [
    "being weird is way more interesting than being normal ever could 🎨",
    "everyone's a little bit strange and that's what makes life fun",
    "normal is overrated and boring compared to being authentically yourself always",
    "your quirks are what make you memorable to other people honestly",
    "weird people are more creative and interesting than conventional people are",
    "embracing your oddities is more attractive than trying to fit in",
    "the best people are the ones who are unapologetically themselves always",
    "being different is a strength not something to be ashamed of",
    "quirky is just another word for interesting and unique in life",
    "normal people are just people you don't know well enough yet",
    "your weirdness is what attracts the right people into your life",
    "being eccentric is way more fun than following all the rules",
    "the most interesting conversations happen with the weirdest people you meet",
    "embracing your uniqueness is the key to being truly happy in",
    "weird is a compliment not an insult to me personally honestly",
    "the best friendships are built on shared weirdness and odd humor",
    "being authentically odd is better than being fake and normal always",
    "quirky people make the world more colorful and interesting for everyone",
    "your strange interests are what make you you so embrace them",
    "normal is just a setting on the washing machine nothing more"
  ],
  "serious": [
    "mental health is just as important as physical health and deserves",
    "therapy should be normalized and accessible for everyone who needs it honestly",
    "setting boundaries is necessary for maintaining your wellbeing and mental health",
    "you can't pour from an empty cup so self care matters",
    "success means different things to different people and that's perfectly okay",
    "financial literacy should be taught in schools because it's essential for",
    "you're responsible for your own happiness not anyone else's job honestly",
    "hard work matters but privilege and luck play huge roles too",
    "you should prioritize your mental health over your job or career",
    "personal growth requires discomfort and facing things you'd rather avoid honestly",
    "you can't change people who don't want to change themselves period",
    "investing in yourself is the best investment you can ever make",
    "your worth isn't determined by your productivity or accomplishments at all",
    "it's okay to outgrow people and relationships that no longer serve",
    "you should never sacrifice your values for success or other people",
    "taking accountability is a sign of maturity and strength not weakness",
    "your career doesn't define you as a person or your worth",
    "it's important to have goals but also be flexible with them",
    "you deserve respect regardless of your job or social status in",
    "personal development is a lifelong journey not a destination you reach"
  ],
  "intellectual": [
    "critical thinking is more important than memorizing facts and information alone 🧠",
    "being wrong and changing your mind is a sign of intelligence",
    "asking questions is more valuable than pretending to know all the",
    "education should focus on teaching how to think not what to",
    "intelligence comes in many different forms not just academic achievement alone",
    "being well read doesn't automatically make you wise or emotionally intelligent",
    "curiosity is more important than knowledge when it comes to learning",
    "you should actively seek out perspectives that challenge your own beliefs",
    "emotional intelligence is just as important as intellectual intelligence in life",
    "understanding nuance is more important than having strong opinions on everything",
    "admitting you don't know something is smarter than pretending you do",
    "wisdom comes from experience and reflection not just reading books alone",
    "being open minded doesn't mean accepting everything without critical thought honestly",
    "intelligence without empathy and kindness is pretty much useless in life",
    "learning should be a lifelong pursuit not something that ends",
    "being intellectually humble is a sign of true intelligence and wisdom",
    "questioning everything is healthier than accepting things at face value always",
    "knowledge without application is just trivia that serves no real purpose",
    "being well informed requires consuming diverse sources not just echo chambers",
    "intelligence is about asking better questions not having all the answers"
  ],
  "default": [
    "everyone deserves basic kindness and respect regardless of anything else ✨",
    "communication is key in literally every type of relationship you have",
    "it's okay to change your mind when you learn new information",
    "people are doing the best they can with what they have",
    "you should treat others the way you want to be treated",
    "honesty is always better than lying even when truth is hard",
    "everyone's fighting battles you know nothing about so be kind always",
    "it's important to listen more than you speak in most conversations",
    "you can disagree with someone and still respect them as a",
    "actions speak louder than words in almost every situation in life",
    "it's okay to ask for help when you need it honestly",
    "you should apologize when you're wrong and mean it sincerely always",
    "everyone has something valuable to teach you if you're willing to",
    "being kind costs nothing but means everything to someone who needs",
    "you should stand up for what you believe in even when",
    "it's important to have empathy and try to understand different perspectives",
    "you can't control others but you can control how you react",
    "being genuine is more important than being liked by everyone you",
    "it's okay to have boundaries and say no to things sometimes",
    "life's too short to hold grudges or stay angry at"
  ]
};

module.exports = doYouAgreeOrDisagreeThat;
