const firstRoundIsOnMeIf = {
  "funny": [
    "you can make me laugh within the first five minutes honestly 😂",
    "you don't judge my questionable food choices or weird eating habits",
    "you're down to split an appetizer sampler with me right now",
    "you can handle my sarcasm and dish it right back at",
    "you laugh at my jokes even if they're really not funny",
    "you're okay with me being a little chaotic and weird honestly",
    "you can keep up with my random topic changes in conversation",
    "you don't take yourself too seriously because life's too short for",
    "you're willing to debate whether a hot dog is a",
    "you can appreciate a good meme and understand my humor references",
    "you're down for spontaneous karaoke even if we're both terrible",
    "you don't mind that I'm probably gonna order way too much",
    "you can laugh at yourself and don't get offended too easily",
    "you're okay with me stealing fries off your plate occasionally honestly",
    "you can handle my energy level which varies wildly throughout the",
    "you're down to people watch and make up stories about",
    "you don't judge me for ordering dessert before the meal even",
    "you can appreciate my random fun facts that nobody asked for",
    "you're willing to try the weirdest thing on the menu with",
    "you can match my vibe and keep the conversation flowing naturally"
  ],
  "romantic": [
    "you make me feel butterflies just by the way you smile ❤️",
    "you're genuinely interested in getting to know the real me honestly",
    "you make me feel comfortable enough to be myself completely around",
    "you look at me like I'm the only person in the",
    "you're emotionally available and ready for something real and meaningful together",
    "you make conversation feel easy and natural like we've known each",
    "you're looking for connection not just someone to pass the time",
    "you make me laugh and feel special at the same time",
    "you're genuinely kind to the server and people around us always",
    "you make me feel seen and heard in a way that",
    "you're open about your feelings and intentions from the very start",
    "you make me feel like this could actually turn into something",
    "you're present and engaged not distracted by your phone the whole",
    "you make me feel safe enough to be vulnerable with you",
    "you're looking for something real not just playing games with people",
    "you make me feel like you're genuinely interested in my stories",
    "you're affectionate in small ways that make me feel cared for",
    "you make me feel like I want to see you again",
    "you're honest about what you're looking for in a relationship honestly",
    "you make me feel like this date is going somewhere good"
  ],
  "adventurous": [
    "you're down to try the weirdest thing on the menu 🌟",
    "you suggest we go somewhere unexpected instead of the usual spots",
    "you're open to spontaneous plans after this if it goes well",
    "you have stories about adventures and travels that sound absolutely amazing",
    "you're willing to explore a new part of town we've",
    "you suggest doing something active instead of just sitting and talking",
    "you're down for an adventure date like hiking or exploring something",
    "you have a bucket list and are actively working on checking",
    "you're open to trying new cuisines and foods you've never had",
    "you suggest we go somewhere neither of us has been before",
    "you're spontaneous and don't need everything planned out perfectly in advance",
    "you have travel stories that make me want to hear more",
    "you're down to turn this into a mini adventure around",
    "you suggest we try that new place everyone's been talking about",
    "you're open to doing something unconventional for a first date honestly",
    "you have plans to travel or try new things in near",
    "you're willing to step outside your comfort zone and try something",
    "you suggest we explore the city and find something fun to",
    "you're down for an impromptu road trip if the vibe is",
    "you have that adventurous energy that makes me want to explore"
  ],
  "quirky": [
    "you appreciate my weird sense of humor and odd references 🎨",
    "you're just as weird as me and own it completely honestly",
    "you have niche interests that most people don't understand or know",
    "you're okay with deep conversations about random philosophical topics at dinner",
    "you appreciate my quirky style and don't try to change it",
    "you have weird hobbies or collections that you're passionate about sharing",
    "you're down to debate silly hypothetical questions for hours on end",
    "you appreciate the unconventional and don't judge my odd interests at",
    "you're authentically yourself even if that means being a little strange",
    "you have unique perspectives on things that make me think differently",
    "you're okay with me being eccentric and embrace your own weirdness",
    "you appreciate my random tangents and add your own to the",
    "you're down to do something unconventional instead of a typical dinner",
    "you have obscure references that only certain people would understand and",
    "you're okay with comfortable silences and don't need constant small talk",
    "you appreciate art or music that's a bit off the beaten",
    "you're down to have weird deep conversations that go absolutely nowhere",
    "you have that quirky energy that makes you interesting and different",
    "you're okay with being different and celebrate what makes you unique",
    "you appreciate my oddities and share some of your own with"
  ],
  "serious": [
    "you're genuinely looking for something real and not just wasting time",
    "you're emotionally mature and can communicate like an actual adult honestly",
    "you respect boundaries and understand consent in all aspects of dating",
    "you're honest about your intentions and what you're looking for clearly",
    "you treat the server with respect because that says a lot",
    "you're financially responsible and have your life somewhat together at least",
    "you respect my time and showed up when you said you",
    "you're looking for a partner not just someone to fill time",
    "you have goals and ambitions and are working toward them actively",
    "you're emotionally available and not still hung up on your ex",
    "you respect my career and take my ambitions seriously from start",
    "you're honest about your past and what you've learned from",
    "you have your priorities straight and know what you want in",
    "you're mature enough to handle difficult conversations without shutting down completely",
    "you respect women and treat me as an equal from beginning",
    "you're looking for something meaningful not just something casual or temporary",
    "you have emotional intelligence and can read social cues appropriately always",
    "you're reliable and do what you say you're going to do",
    "you respect my boundaries without making me feel guilty for having",
    "you're serious about dating and not just here for attention or"
  ],
  "intellectual": [
    "you can hold a conversation that goes beyond surface level topics 🧠",
    "you're genuinely curious and ask thoughtful questions about my life and",
    "you have interesting perspectives that challenge how I think about things",
    "you're well read and can discuss books or ideas that interest",
    "you're open to having your views challenged in respectful thoughtful ways",
    "you can debate topics without getting defensive or taking things too",
    "you're intellectually curious and always learning new things about the world",
    "you have passions and interests that you can talk about intelligently",
    "you're open minded and willing to consider perspectives different from your",
    "you can discuss complex topics without dumbing things down unnecessarily for",
    "you're knowledgeable about current events and can discuss them thoughtfully and",
    "you ask questions that make me think more deeply about things",
    "you're interested in learning from me just as I learn from",
    "you can appreciate nuance and don't see everything in black and",
    "you're intellectually engaged and present in our conversation throughout the date",
    "you have thoughts and opinions that are well reasoned and thought",
    "you're curious about the world and want to understand things more",
    "you can discuss ideas without making it feel like a lecture",
    "you're open to admitting when you don't know something instead of",
    "you make me think and challenge my assumptions in good ways"
  ],
  "default": [
    "you're genuine and seem like a good person overall honestly ✨",
    "you make me feel comfortable and like I can be myself",
    "you're easy to talk to and conversation flows naturally between us",
    "you seem genuinely interested in getting to know me as a",
    "you're kind to everyone around us not just me on date",
    "you make me laugh and smile throughout our time together so",
    "you're respectful and treat me well from the very beginning honestly",
    "you seem like someone I'd actually want to see again soon",
    "you're present and engaged instead of distracted by your phone constantly",
    "you make this feel easy and natural not forced or awkward",
    "you're honest and upfront about who you are and what",
    "you seem like you have good intentions and aren't playing games",
    "you make me feel good about myself and this whole experience",
    "you're interesting and have things to talk about beyond just",
    "you seem emotionally available and ready for whatever this could become",
    "you make me feel like this was worth my time tonight",
    "you're respectful of my boundaries and don't push for anything more",
    "you seem like someone who's looking for something real and meaningful",
    "you make me feel safe and comfortable in your presence tonight",
    "you're just a good vibe and I want to keep"
  ]
};

module.exports = firstRoundIsOnMeIf;
