const giveMeTravelTipsFor = {
  "funny": [
    "pack snacks because airport food is expensive and honestly kinda gross 😂",
    "bring portable chargers because your phone will die at worst time",
    "download offline maps because you will definitely get lost without them",
    "pack extra underwear because you never know what could go wrong",
    "bring hand sanitizer because airports are basically germ factories on steroids",
    "wear comfy shoes because you'll be walking way more than expected",
    "pack a hoodie because planes are always freezing cold for reason",
    "bring headphones because crying babies are inevitable on every single flight",
    "download shows before because airplane wifi is expensive and super slow",
    "pack medications because getting sick abroad is the actual worst nightmare",
    "bring a reusable water bottle to save money and stay hydrated",
    "pack layers because weather is unpredictable and you'll regret not preparing",
    "bring copies of documents because losing your passport is a nightmare",
    "pack a small first aid kit because accidents happen when traveling",
    "download translation apps because google translate saves lives when you're lost",
    "bring a travel adapter because outlets are different everywhere you go",
    "pack light because lugging heavy bags around ruins the whole vibe",
    "bring wet wipes because you never know when you'll need them",
    "download your boarding pass because printers are never around when needed",
    "pack patience because travel delays are basically guaranteed to happen always"
  ],
  "romantic": [
    "visit local markets and try street food together holding hands ❤️",
    "watch the sunset from the best viewpoint and just be present",
    "take a cooking class together and learn to make local dishes",
    "get lost in old neighborhoods and discover hidden gems just us",
    "have a picnic in a beautiful park with local treats we",
    "take a boat ride at sunset and enjoy the peaceful moments",
    "visit local cafes and spend hours just talking and people watching",
    "explore museums together and share what moves us about the art",
    "take long walks through historic districts holding hands and talking about",
    "find a rooftop bar with views and watch the city lights",
    "visit local bookstores and pick out books for each other to",
    "take a day trip to nearby towns and explore together slowly",
    "find the best gelato spot and try every flavor they have",
    "watch street performers and leave tips while enjoying the local culture",
    "visit gardens and take photos of each other among the flowers",
    "find a jazz club or live music venue for a romantic",
    "explore local neighborhoods on foot and stop wherever looks interesting to",
    "take a sunset cruise if available and enjoy the romantic atmosphere",
    "visit local wineries or breweries and do tastings together all afternoon",
    "find the most romantic restaurant and dress up for a special"
  ],
  "adventurous": [
    "try the local adventure sports even if they scare you a 🌟",
    "rent bikes or scooters and explore areas tourists don't usually visit",
    "hike to viewpoints early morning to catch sunrise over the city",
    "try all the street food even the weird stuff you can't",
    "take local transportation instead of taxis to experience real local life",
    "say yes to invitations from locals and see where it leads",
    "explore neighborhoods that aren't in the guidebook for authentic experiences truly",
    "try activities you've never done before like surfing or rock climbing",
    "wake up early to beat crowds at popular tourist spots always",
    "take a day trip to somewhere off the beaten path nearby",
    "try the spiciest local dish and see if you can handle",
    "go on a food tour and eat everything they recommend trying",
    "rent a car and drive to remote areas for the best",
    "try water sports or activities available at beaches or lakes there",
    "climb to the highest point in the city for the views",
    "take a night tour to see the city from different perspective",
    "try local transportation methods like tuk tuks or rickshaws for fun",
    "explore markets early morning when locals shop for freshest ingredients daily",
    "say yes to random adventures even if they weren't in plan",
    "push your boundaries and try things that make you nervous excited"
  ],
  "quirky": [
    "find the weirdest museum or attraction and spend hours there exploring 🎨",
    "collect something random from each place like cool rocks or postcards",
    "try to learn a weird local phrase and use it everywhere",
    "find the most unique local shops that sell odd handmade things",
    "visit places that are off the beaten path and totally random",
    "try the weirdest local food you can find even if scary",
    "take photos with the strangest statues or street art you find",
    "find quirky cafes with unusual themes or weird decor to explore",
    "collect stamps or stickers from every place you visit for memories",
    "visit local flea markets and find the most random unique treasures",
    "try to befriend a local cat or dog in every city",
    "find the most unusual accommodation like treehouses or weird hostels honestly",
    "visit places that have weird histories or ghost stories to tell",
    "try local superstitions or traditions even if they seem totally strange",
    "find street art and take artsy photos in front of everything",
    "visit the most random roadside attractions you can possibly find there",
    "collect menus from restaurants even if you don't eat there always",
    "find the quirkiest bookstore or record shop and spend hours browsing",
    "try to find hidden speakeasies or secret bars that locals know",
    "visit places that tourists skip because they're too weird or niche"
  ],
  "serious": [
    "research safety concerns and avoid sketchy areas especially at night always",
    "keep copies of important documents in multiple places for security backup",
    "have travel insurance because medical emergencies abroad are incredibly expensive honestly",
    "respect local customs and dress codes to avoid offending anyone there",
    "learn basic phrases in the local language to show respect always",
    "be aware of common scams targeting tourists in that specific area",
    "keep valuables secure and don't flash expensive items around carelessly ever",
    "have emergency contacts saved and know where your embassy is",
    "budget carefully and track spending to avoid running out of money",
    "book accommodations in safe neighborhoods even if costs a bit more",
    "be mindful of local laws because ignorance isn't an excuse abroad",
    "stay connected with someone back home and check in regularly always",
    "research transportation options and book reliable services in advance when possible",
    "be cautious with alcohol especially in unfamiliar places at night time",
    "trust your instincts and leave situations that feel unsafe immediately always",
    "keep medications in original containers with prescriptions for customs and safety",
    "research local emergency numbers and save them in your phone immediately",
    "be respectful of cultural sites and follow all posted rules carefully",
    "plan your itinerary but stay flexible for unexpected changes or delays",
    "register with your embassy if traveling to potentially risky areas"
  ],
  "intellectual": [
    "visit museums and historical sites to understand the culture deeply 🧠",
    "read about the history before you go to appreciate context better",
    "take walking tours with knowledgeable guides who can explain local history",
    "visit universities or libraries to see how education differs there culturally",
    "attend lectures or cultural events if available during your visit there",
    "learn about local politics and social issues to understand the place",
    "visit archaeological sites and learn about ancient civilizations that lived there",
    "read local literature or poetry to understand the cultural perspective better",
    "attend theater or cultural performances to experience local art forms authentically",
    "visit local bookstores and find books by authors from that region",
    "learn about the architecture and different styles throughout the city's history",
    "visit galleries and learn about local artists and their cultural significance",
    "take a historical walking tour to understand how the city evolved",
    "learn about local cuisine's history and cultural significance beyond just eating",
    "visit religious sites respectfully and learn about local spiritual practices there",
    "attend workshops or classes to learn traditional crafts or skills deeply",
    "research the local language's origins and how it evolved over time",
    "visit neighborhoods with different cultural influences to see diversity and history",
    "learn about environmental issues affecting the region and local conservation efforts",
    "engage with locals in meaningful conversations about their culture and lives"
  ],
  "default": [
    "pack smart and bring only what you actually need for trip ✨",
    "stay hydrated and get enough sleep to enjoy your time there",
    "be open to new experiences and don't over plan everything out",
    "try local food and step outside your comfort zone a bit",
    "take lots of photos but also remember to be present and",
    "be respectful of local culture and customs wherever you go always",
    "budget for unexpected expenses because things always cost more than expected",
    "make friends with locals who can show you the best spots",
    "don't try to see everything just enjoy what you do see",
    "bring a good attitude because things will go wrong sometimes inevitably",
    "stay flexible with plans because the best moments are often unplanned",
    "take time to rest and don't burn yourself out sightseeing",
    "try to learn a few basic phrases in the local language",
    "be safe but don't let fear stop you from having fun",
    "bring comfortable walking shoes because you'll walk way more than expected",
    "stay connected but also take breaks from your phone and social",
    "be patient with yourself and others because travel is stressful sometimes",
    "enjoy the journey not just the destination and embrace the chaos",
    "make memories and collect experiences rather than just checking off sights",
    "have fun and remember why you wanted to travel there originally"
  ]
};

module.exports = giveMeTravelTipsFor;
