const greenFlagsILookOutFor = {
  "funny": [
    "they laugh at my terrible jokes even when they're really bad 😂",
    "they're not afraid to be silly and goofy with me always",
    "they can handle my chaotic energy and match it back perfectly",
    "they appreciate my weird sense of humor and add to it",
    "they're down for spontaneous food runs at 2am without question honestly",
    "they don't take themselves too seriously ever and can laugh at",
    "they can laugh at themselves too and don't get offended easily",
    "they match my meme energy perfectly and send me good ones",
    "they're okay with my random tangents and actually find them entertaining",
    "they find my awkwardness endearing somehow instead of judging me for",
    "they can keep up with banter and dish it right back",
    "they appreciate my sarcasm and dish back their own witty comebacks too",
    "they're down for late night adventures that make no sense honestly",
    "they laugh when things go wrong instead of getting stressed out",
    "they don't judge my comfort shows that I've watched a million",
    "they're okay with me being dramatic because they know it's",
    "they can handle my mood swings and don't take it personally",
    "they appreciate my random fun facts that nobody asked for at",
    "they're down to try weird food combinations with me for fun",
    "they make everything more fun naturally just by being themselves honestly"
  ],
  "romantic": [
    "they remember small details I mention in passing weeks ago ❤️",
    "they make me feel safe and valued every single day consistently",
    "they're emotionally available and communicate openly always even when it's hard",
    "they show affection in little ways daily that make me smile",
    "they're consistent with their words and actions so I can trust",
    "they make time for me no matter how busy life gets",
    "they're genuinely interested in my life deeply and ask thoughtful questions",
    "they support my dreams and goals always without making me feel",
    "they're affectionate without me having to ask or hint at it",
    "they make me feel like a priority not an option ever",
    "they're vulnerable and open with their feelings which makes me feel",
    "they show love through actions not just words that mean nothing",
    "they're patient with me when I'm struggling and don't make me",
    "they make me feel beautiful every day not just when dressed",
    "they're thoughtful and remember what matters to me without being reminded",
    "they communicate instead of playing games with me or my feelings",
    "they make me feel heard and understood on a deep level",
    "they're intentional about building something real together for the long term",
    "they show up consistently not just sometimes when it's convenient for",
    "they make me feel cherished and appreciated for exactly who I am"
  ],
  "adventurous": [
    "they're down for spontaneous road trips with no real plan at 🌟",
    "they say yes to new experiences even when they're a bit",
    "they're not afraid to try new things that push our boundaries",
    "they're open to exploring new places together and getting a little",
    "they have that adventurous energy I love and it's so contagious",
    "they're willing to step outside comfort zones and try scary things",
    "they're spontaneous and go with the flow instead of over planning",
    "they love trying new foods and cuisines from different cultures always",
    "they're up for outdoor adventures and activities like hiking or camping",
    "they're not afraid of getting a little dirty or messy honestly",
    "they're open to travel and exploring world whenever we get the",
    "they have interesting stories from their adventures that make me want",
    "they're willing to take risks with me and see what happens",
    "they're excited about trying new activities together that we've never done",
    "they're not stuck in boring routines always and crave new experiences",
    "they're open to last minute plans and spontaneous adventures with me",
    "they have that wanderlust energy I vibe with so much honestly",
    "they're willing to get lost and explore without stressing about it",
    "they're down for adrenaline rush activities sometimes that scare us both",
    "they're excited about making new memories together through adventures and experiences"
  ],
  "quirky": [
    "they embrace their own weirdness fully and don't try to hide 🎨",
    "they appreciate my odd interests and quirks instead of judging them",
    "they're unapologetically themselves always and completely without caring what others think",
    "they have niche interests that fascinate them and they're passionate about",
    "they're okay with being different from everyone else and actually prefer",
    "they celebrate the unconventional and unique things that make life more interesting",
    "they have their own weird hobbies too that most people don't",
    "they're not trying to fit into molds or be like everyone",
    "they appreciate art and creativity in life and see beauty in",
    "they have unique perspectives on random things that make me think differently",
    "they're comfortable with their eccentricities completely and don't apologize for them",
    "they don't judge my weird collections or odd habits at all",
    "they have obscure references I actually get and we bond over",
    "they're authentically odd in the best way possible and own it",
    "they appreciate the beauty in strange things that others might overlook completely",
    "they're not afraid to stand out always and be different from",
    "they have quirky habits that make them unique and interesting to me",
    "they're okay with deep weird conversations late at night about random",
    "they celebrate what makes them different proudly instead of hiding their quirks",
    "they're perfectly imperfect and own it without trying to change themselves"
  ],
  "serious": [
    "they respect boundaries without being told twice or making me feel",
    "they're emotionally mature and can communicate well even during difficult conversations",
    "they take accountability for their actions always instead of making excuses constantly",
    "they're honest even when it's uncomfortable honestly because integrity matters to them",
    "they have their life somewhat together at least and have clear",
    "they're reliable and do what they say they're going to do",
    "they respect my time and don't waste it playing games with",
    "they're looking for something real and meaningful not just casual or",
    "they have goals and are working toward them actively every single day",
    "they're financially responsible and have plans for their future and stability",
    "they treat everyone with respect not just me when it's convenient",
    "they're consistent and don't play mind games or hot and cold",
    "they have emotional intelligence and self awareness clearly and work on themselves",
    "they're serious about their intentions with me from the very beginning",
    "they respect my career and take it seriously as their own",
    "they're mature enough to handle difficult conversations without shutting down completely",
    "they have their priorities straight and know what they want in",
    "they're honest about their past and learned from their mistakes and",
    "they respect women and treat me as an equal partner always",
    "they're ready for commitment not just casual dating or wasting time"
  ],
  "intellectual": [
    "they can hold deep meaningful conversations always that go beyond surface 🧠",
    "they're curious and always learning new things about the world around",
    "they ask thoughtful questions that make me think differently about things honestly",
    "they're open to different perspectives and ideas even when they challenge",
    "they can debate respectfully without getting defensive ever or taking things personally",
    "they're well read and have interesting thoughts on various topics always",
    "they're intellectually curious about the world around them and ask great",
    "they can discuss complex topics without dumbing down or being condescending to",
    "they're open minded and willing to learn from anyone including me",
    "they challenge my thinking in good ways that help me grow",
    "they're knowledgeable about topics they're passionate about and can explain them",
    "they ask questions instead of assuming they know everything about a",
    "they're interested in understanding not just being right in every argument",
    "they can appreciate nuance in complex issues instead of seeing black",
    "they're thoughtful and consider different angles on things before forming strong",
    "they're engaged and present in conversations always and actually listen to",
    "they have opinions that are well thought out and based on",
    "they're curious about my thoughts and perspectives too not just their",
    "they can discuss ideas without making it feel like a lecture",
    "they're intellectually stimulating and make me think more deeply about everything"
  ],
  "default": [
    "they're kind to everyone not just me when it's convenient ✨",
    "they're genuine and authentic in how they present themselves to me",
    "they communicate openly and honestly with me always even when it's difficult",
    "they're respectful of my boundaries and feelings consistently without making me",
    "they make me feel comfortable being myself completely without any judgment at",
    "they're consistent with their words and actions so I can trust",
    "they show up when they say they will and don't flake",
    "they're interested in getting to know me deeply beyond just surface",
    "they treat me with respect from the very beginning of knowing",
    "they're emotionally available and present with me when we're together always",
    "they make effort and don't make me do all the work",
    "they're honest about their intentions from start so I know where",
    "they're supportive of my goals and dreams and cheer me on",
    "they listen when I talk and remember things I've told them",
    "they're patient and understanding with me always even when I'm difficult",
    "they make me feel valued and appreciated for exactly who I",
    "they're reliable and I can count on them to follow through",
    "they're respectful and treat me well consistently not just when convenient",
    "they make me feel safe and comfortable being vulnerable with them",
    "they're looking for something real and meaningful not just passing time"
  ]
};

module.exports = greenFlagsILookOutFor;
