const iBeatMyBluesBy = {
  funny: [
    "watching funny animal videos until i cant breathe properly",
    "eating ice cream straight from the container unapologetically always",
    "calling my best friend to roast our past selves",
    "watching comedy specials and laughing at my own problems",
    "making tiktoks i'll never post but they make me",
    "online shopping for things i definitely dont need right",
    "watching my comfort show for the millionth time honestly",
    "dancing badly in my room to early 2000s music",
    "scrolling through memes until i forget why i was",
    "doing a full skincare routine like im a beauty",
    "making elaborate snacks at midnight that are totally unnecessary",
    "watching fails videos and feeling better about my life",
    "texting my group chat the most unhinged thoughts ever",
    "reorganizing something random at 2am for no reason whatsoever",
    "watching reality tv drama and forgetting my own problems",
    "doing retail therapy in my cart then never checking",
    "making playlists with the most chaotic song combinations possible",
    "talking to my pet like theyre my therapist honestly",
    "watching cooking videos while eating takeout on my couch",
    "doing face masks and pretending im at expensive spa",
  ],
  romantic: [
    "calling someone who always knows how to make smile",
    "reading old messages that remind me im loved deeply",
    "listening to love songs and believing in happy endings",
    "looking at photos that remind me of good times",
    "writing in my journal about things im grateful for",
    "watching romantic movies that make me cry happy tears",
    "texting someone just to tell them i appreciate them",
    "thinking about future plans with someone i care about",
    "doing something kind for someone else to spread love",
    "cuddling with my pet and feeling their unconditional love",
    "listening to our song and replaying my favorite memories",
    "writing letters to people i love even if unsent",
    "watching sunset and feeling hopeful about tomorrow coming soon",
    "calling my mom or someone who always lifts me",
    "looking through old photos and remembering happy moments together",
    "doing small acts of self love and treating myself",
    "thinking about people who make my life better daily",
    "watching videos that restore my faith in humanity again",
    "spending time with people who genuinely care about me",
    "reminding myself that bad days dont last forever here",
  ],
  adventurous: [
    "going for a long drive with music blasting loudly",
    "trying a new restaurant or cafe ive never been",
    "going for a run or hike to clear my",
    "booking a spontaneous trip to look forward to soon",
    "exploring a new part of the city ive never",
    "trying a new workout class that challenges me physically",
    "going on a solo adventure to reset my mindset",
    "planning my next big trip and getting excited again",
    "trying something ive never done before just because why",
    "going to a random event i found online today",
    "taking a different route and discovering something new around",
    "doing something that scares me a little bit honestly",
    "going somewhere in nature to breathe and reset myself",
    "trying a new hobby or activity ive been curious",
    "going for a bike ride to nowhere in particular",
    "exploring farmers markets and trying all the new samples",
    "doing something spontaneous that breaks my usual routine completely",
    "going to the beach or lake to watch waves",
    "trying extreme sports or activities that get adrenaline going",
    "planning adventures to give myself something to look forward",
  ],
  quirky: [
    "reorganizing my entire room at midnight for no reason",
    "making oddly specific playlists for every possible mood ever",
    "doing a full main character montage in my mirror",
    "researching random topics until i feel like an expert",
    "making lists of literally everything to feel in control",
    "watching video essays about things i never knew mattered",
    "doing craft projects i saw online probably wont finish",
    "color coding everything in my life including my calendar",
    "watching people clean and organize things on social media",
    "doing personality tests to confirm what i already know",
    "making mood boards for aesthetics ill never actually achieve",
    "learning random skills from youtube at odd hours nightly",
    "doing jigsaw puzzles while listening to murder mystery podcasts",
    "researching conspiracy theories for entertainment purposes only obviously here",
    "organizing my bookshelf then immediately changing it back again",
    "watching restoration videos of things being fixed so satisfying",
    "doing those oddly satisfying repetitive tasks that calm me",
    "making elaborate plans i probably wont follow through with",
    "learning about random historical events through wikipedia rabbit holes",
    "doing weird self care rituals that only make sense",
  ],
  serious: [
    "journaling until i process whatever im feeling right now",
    "going for a walk alone to clear my head",
    "calling my therapist or someone i trust completely always",
    "meditating and practicing mindfulness to ground myself again here",
    "doing yoga or stretching to reconnect with my body",
    "reading self help books that give me new perspective",
    "talking to someone who understands and validates my feelings",
    "practicing gratitude even when its hard to find things",
    "setting boundaries and saying no to things draining me",
    "doing therapy exercises or homework to work through it",
    "disconnecting from social media and being present with myself",
    "allowing myself to feel emotions without judging them harshly",
    "doing something productive that makes me feel in control",
    "reaching out for support instead of isolating myself completely",
    "reminding myself that this feeling is temporary not permanent",
    "doing self care that actually nourishes me not just",
    "reflecting on my progress and how far ive come",
    "being honest with myself about what i actually need",
    "giving myself permission to rest without feeling guilty about",
    "focusing on things i can control and letting go",
  ],
  intellectual: [
    "reading books that shift my perspective on things completely",
    "listening to podcasts about psychology or philosophy topics deeply",
    "watching documentaries that teach me something new and interesting",
    "writing to process my thoughts and understand them better",
    "learning something new to remind myself im capable always",
    "reading poetry that puts feelings into words i cant",
    "listening to music and analyzing the lyrics and meaning",
    "researching topics that fascinate me until im distracted completely",
    "watching ted talks that inspire me to think differently",
    "having deep conversations with people who get me truly",
    "reading articles about mental health and understanding myself better",
    "learning about different cultures and perspectives outside my own",
    "doing brain games or puzzles to focus my mind",
    "exploring philosophical questions that put things in perspective here",
    "reading about people who overcame challenges similar to mine",
    "listening to lectures about topics that interest me deeply",
    "writing essays or thoughts to organize my mind clearly",
    "learning a new skill to prove to myself im",
    "reading scientific studies about emotions and the human brain",
    "exploring art or literature that resonates with how i",
  ],
};

module.exports = iBeatMyBluesBy;
