const iBeatMyBluesBy = {
  funny: [
    "watching funny animal videos until I cannot breathe",
    "eating ice cream straight from the container",
    "calling my best friend to roast our past selves",
    "watching comedy specials and laughing at my own problems",
    "making TikToks I will never post",
    "online shopping for things I definitely do not need",
    "watching my comfort show for the millionth time",
    "dancing badly in my room to 2000s music",
    "scrolling through memes until I forget why I was sad",
    "doing a full skincare routine like I am a beauty influencer",
    "making elaborate snacks at midnight",
    "watching fails videos and feeling better about my life",
    "texting my group chat the most unhinged thoughts",
    "reorganizing something random at 2am",
    "watching reality TV drama and forgetting my own problems",
    "doing retail therapy in my cart then never checking out",
    "making playlists with chaotic song combinations",
    "talking to my pet like they are my therapist",
    "watching cooking videos while eating takeout",
    "doing face masks and pretending I am at a spa",
  ],
  romantic: [
    "calling someone who always knows how to make me smile",
    "reading old messages that remind me I am loved",
    "listening to love songs and believing in happy endings",
    "looking at photos that remind me of good times",
    "writing in my journal about things I am grateful for",
    "watching romantic movies that make me cry happy tears",
    "texting someone just to tell them I appreciate them",
    "thinking about future plans with someone I care about",
    "doing something kind for someone else to spread love",
    "cuddling with my pet and feeling their unconditional love",
    "listening to our song and replaying my favorite memories",
    "writing letters to people I love even if unsent",
    "watching sunset and feeling hopeful about tomorrow",
    "calling my mom or someone who always lifts me",
    "looking through old photos and remembering happy moments",
    "doing small acts of self love",
    "thinking about people who make my life better",
    "watching videos that restore my faith in humanity",
    "spending time with people who genuinely care about me",
    "reminding myself that bad days do not last forever",
  ],
  adventurous: [
    "going for a long drive with music blasting",
    "trying a new restaurant or cafe I have never been",
    "going for a run or hike to clear my head",
    "booking a spontaneous trip to look forward to",
    "exploring a new part of the city",
    "trying a new workout class that challenges me",
    "going on a solo adventure to reset",
    "planning my next big trip and getting excited",
    "trying something I have never done before",
    "going to a random event I found online",
    "taking a different route and discovering something new",
    "doing something that scares me a little",
    "going somewhere in nature to breathe and reset",
    "trying a new hobby or activity",
    "going for a bike ride to nowhere",
    "exploring farmers markets and trying new samples",
    "doing something spontaneous that breaks my routine",
    "going to the beach or lake to watch waves",
    "trying extreme sports or activities",
    "planning adventures to give myself something to look forward to",
  ],
  quirky: [
    "reorganizing my entire room at midnight",
    "making oddly specific playlists for every possible mood",
    "doing a full main character montage in my mirror",
    "researching random topics until I feel like an expert",
    "making lists of literally everything to feel in control",
    "watching video essays about things I never knew mattered",
    "doing craft projects I saw online",
    "color coding everything in my life",
    "watching people clean and organize on social media",
    "doing personality tests to confirm what I already know",
    "making mood boards for aesthetics I will never achieve",
    "learning random skills from YouTube at odd hours",
    "doing jigsaw puzzles while listening to podcasts",
    "researching conspiracy theories for entertainment purposes only",
    "organizing my bookshelf then immediately changing it back",
    "watching restoration videos of things being fixed",
    "doing those oddly satisfying repetitive tasks",
    "making elaborate plans I probably will not follow through with",
    "learning about random historical events through Wikipedia rabbit holes",
    "doing weird self care rituals",
  ],
  serious: [
    "journaling until I process whatever I am feeling",
    "going for a walk alone to clear my head",
    "calling my therapist or someone I trust",
    "meditating and practicing mindfulness to ground myself",
    "doing yoga or stretching to reconnect with my body",
    "reading self help books that give me new perspective",
    "talking to someone who understands and validates my feelings",
    "practicing gratitude even when it is hard",
    "setting boundaries and saying no to things draining me",
    "doing therapy exercises or homework",
    "disconnecting from social media and being present",
    "allowing myself to feel emotions without judging them",
    "doing something productive that makes me feel in control",
    "reaching out for support instead of isolating",
    "reminding myself that this feeling is temporary",
    "doing self care that actually nourishes me",
    "reflecting on my progress and how far I have come",
    "being honest with myself about what I actually need",
    "giving myself permission to rest without feeling guilty",
    "focusing on things I can control",
  ],
  intellectual: [
    "reading books that shift my perspective",
    "listening to podcasts about psychology or philosophy",
    "watching documentaries that teach me something new",
    "writing to process my thoughts",
    "learning something new to remind myself I am capable",
    "reading poetry that puts feelings into words",
    "listening to music and analyzing the lyrics",
    "researching topics that fascinate me",
    "watching TED talks that inspire me",
    "having deep conversations with people who get me",
    "reading articles about mental health and understanding myself",
    "learning about different cultures and perspectives",
    "doing brain games or puzzles to focus my mind",
    "exploring philosophical questions",
    "reading about people who overcame challenges",
    "listening to lectures about topics that interest me",
    "writing essays or thoughts to organize my mind",
    "learning a new skill",
    "reading scientific studies about emotions",
    "exploring art or literature that resonates",
  ],
};

module.exports = iBeatMyBluesBy;
