const iBetYouCant = {
  funny: [
    "beat me at mario kart without falling off rainbow road",
    "make me laugh harder than my own jokes do honestly",
    "out-pizza the hut or out-dance me at weddings ever",
    "handle my spotify playlist without judging my guilty pleasures hard",
    "keep up when i start talking about my random theories",
    "resist adopting every dog we see on our walks together",
    "watch just one episode without saying just one more please",
    "beat my high score or my confidence in trivia nights",
    "make better pancakes than me on lazy sunday mornings always",
    "stay serious when i start doing my celebrity impressions badly",
    "out-sing me in the car during our road trip adventures",
    "handle my energy after three cups of coffee in morning",
    "resist laughing at my dad jokes even the really bad",
    "beat me at any board game without me getting competitive",
    "keep a straight face during my terrible pun attempts daily",
    "match my enthusiasm for trying every new food spot around",
    "out-meme me in our daily text conversations and banter sessions",
    "handle my random 2am thoughts without thinking im weird",
    "resist stealing fries after saying you dont want any food",
    "keep up with my movie references from the early 2000s",
  ],
  romantic: [
    "make me smile wider than you already do every day",
    "love rainy days more than cozy mornings with you babe",
    "resist holding my hand when we walk together anywhere ever",
    "stop thinking about you even when were apart for hours",
    "find someone who gets me the way you do perfectly",
    "imagine my future without you being right there beside me",
    "resist kissing you when you look at me that way",
    "stop falling for you more with each passing day together",
    "find a better cuddle buddy than you on cold nights",
    "resist planning our future together in my head constantly now",
    "stop smiling when i see your name pop up notifications",
    "find someone whose laugh i love more than yours honestly",
    "imagine a better way to spend my time than you",
    "resist telling you how much you mean to me daily",
    "stop wanting to make you happy every single day always",
    "find someone who makes me feel safer than you do",
    "resist falling asleep thinking about you every single night dear",
    "stop choosing you over and over again without hesitation ever",
    "imagine loving someone more than i already love you now",
    "find a better reason to believe in love than us",
  ],
  adventurous: [
    "keep up on a spontaneous road trip with no plans",
    "try every adventure sport before i do them all first",
    "resist saying yes when i suggest something wild and crazy",
    "beat me to the top of the hiking trail tomorrow",
    "handle my need to explore every new place we visit",
    "say no to a last minute weekend getaway adventure together",
    "out-adventure me when it comes to trying new experiences always",
    "resist booking flights when we see a good deal online",
    "keep up with my travel bucket list additions every week",
    "stay still when theres a whole world to explore out",
    "beat me at finding hidden gems in every city we",
    "resist the urge to chase sunsets with me every evening",
    "say no to midnight drives with no destination in mind",
    "handle my spontaneous ideas without thinking im too impulsive here",
    "resist trying that sketchy looking local food with me bravely",
    "keep up when i want to do everything all once",
    "beat my record for most countries visited in one year",
    "say no to camping under the stars this weekend together",
    "resist exploring that random trail we just discovered hiking today",
    "handle my constant need for the next big adventure always",
  ],
  quirky: [
    "guess my weirdly specific coffee order on the first try",
    "handle my collection of random facts about everything obscure always",
    "resist judging my comfort show that ive watched ten times",
    "beat me at coming up with the most random hypotheticals",
    "understand my organizational system that makes sense only to me",
    "resist laughing at my weird habits that i dont notice",
    "guess which historical figure id want to have dinner with",
    "handle my need to rearrange furniture at random times monthly",
    "beat my score in the most obscure trivia categories ever",
    "resist asking questions when i start my weird bedtime routine",
    "understand why i name all my plants and talk to",
    "beat me at making up stories about strangers we see",
    "handle my obsession with collecting things nobody else cares about",
    "resist joining in when i start dancing randomly in public",
    "guess my exact order at every restaurant before i say",
    "understand my very specific way of eating certain foods always",
    "beat me at finding faces in clouds or random objects",
    "handle my need to learn one random skill every month",
    "resist questioning my logic that makes perfect sense to me",
    "guess which conspiracy theory i find weirdly fascinating and believable",
  ],
  serious: [
    "challenge my perspective without me respecting your viewpoint completely here",
    "find someone more committed to personal growth than me daily",
    "match my dedication to the things i care about deeply",
    "handle deep conversations at two in the morning without hesitation",
    "find someone who values honesty more than i do always",
    "beat my work ethic when it comes to my goals",
    "resist respecting my boundaries and communication style in relationships here",
    "find someone more loyal than me to people i love",
    "match my level of commitment once i decide youre worth",
    "handle my intensity when i care about something or someone",
    "find someone who takes relationships more seriously than i do",
    "beat my standards for how i want to be treated",
    "resist appreciating my direct communication style in tough conversations always",
    "find someone more dedicated to building something real and lasting",
    "match my emotional intelligence and self awareness levels in life",
    "handle my need for depth over surface level connections always",
    "find someone who values growth more than comfort zones daily",
    "beat my consistency in showing up for people i love",
    "resist respecting how much i value trust and transparency here",
    "find someone more intentional about their choices and relationships overall",
  ],
  intellectual: [
    "out-debate me without me finding it incredibly attractive honestly",
    "recommend a book i havent already read or heard about",
    "beat me in a random trivia category i actually know",
    "challenge my perspective with a better argument than mine logically",
    "resist getting into deep philosophical discussions with me at midnight",
    "find a topic i dont have an opinion on yet",
    "beat me at connecting random concepts into coherent theories always",
    "handle my need to analyze everything we watch or read",
    "resist asking why when i make a random intellectual observation",
    "match my curiosity about literally everything in the world around",
    "beat my reading speed without sacrificing comprehension or retention levels",
    "handle my tendency to turn everything into a learning moment",
    "resist engaging when i start theorizing about random topics passionately",
    "find a documentary i havent already watched or added to",
    "beat me at making connections between completely unrelated subjects here",
    "handle my constant need to understand how things work deeply",
    "resist joining my deep dive into whatever im researching now",
    "match my enthusiasm for learning something new every single day",
    "beat my ability to remember random facts from years ago",
    "handle conversations that go from light to existential in seconds",
  ],
};

module.exports = iBetYouCant;
