const iBetYouCant = {
  funny: [
    "beat me at Mario Kart without falling off Rainbow Road",
    "make me laugh harder than my own jokes",
    "out pizza the hut or out dance me at weddings",
    "handle my Spotify playlist without judging my guilty pleasures",
    "keep up when I start talking about my random theories",
    "resist adopting every dog we see on walks",
    "watch just one episode without saying just one more",
    "beat my high score in trivia nights",
    "make better pancakes than me on lazy Sunday mornings",
    "stay serious when I start doing celebrity impressions badly",
    "out sing me in the car during road trips",
    "handle my energy after three cups of coffee",
    "resist laughing at my dad jokes even the really bad ones",
    "beat me at any board game without me getting competitive",
    "keep a straight face during my terrible pun attempts",
    "match my enthusiasm for trying every new food spot",
    "out meme me in our daily text conversations",
    "handle my random 2am thoughts without thinking I am weird",
    "resist stealing fries after saying you do not want any",
    "keep up with my movie references from the early 2000s",
  ],
  romantic: [
    "make me smile wider than you already do",
    "love rainy days more than cozy mornings with me",
    "resist holding my hand when we walk together",
    "stop thinking about you even when we are apart",
    "find someone who gets me the way you do",
    "imagine my future without you being right there",
    "resist kissing me when I look at you that way",
    "stop falling for you more with each passing day",
    "find a better cuddle buddy than me",
    "resist planning our future together in my head constantly",
    "stop smiling when I see your name pop up",
    "find someone whose laugh I love more than yours",
    "imagine a better way to spend my time than with you",
    "resist telling you how much you mean to me",
    "stop wanting to make you happy every single day",
    "find someone who makes me feel safer than you do",
    "resist falling asleep thinking about you every night",
    "stop choosing you over and over again without hesitation",
    "imagine loving someone more than I already love you",
    "find a better reason to believe in love than us",
  ],
  adventurous: [
    "keep up on a spontaneous road trip with no plans",
    "try every adventure sport before I do them all",
    "resist saying yes when I suggest something wild",
    "beat me to the top of the hiking trail",
    "handle my need to explore every new place",
    "say no to a last minute weekend getaway",
    "out adventure me when it comes to trying new experiences",
    "resist booking flights when we see a good deal",
    "keep up with my travel bucket list additions",
    "stay still when there is a whole world to explore",
    "beat me at finding hidden gems in every city",
    "resist the urge to chase sunsets with me",
    "say no to midnight drives with no destination",
    "handle my spontaneous ideas without thinking I am too impulsive",
    "resist trying that sketchy looking local food",
    "keep up when I want to do everything at once",
    "beat my record for most countries visited in one year",
    "say no to camping under the stars",
    "resist exploring that random trail we just discovered",
    "handle my constant need for the next big adventure",
  ],
  quirky: [
    "guess my weirdly specific coffee order on the first try",
    "handle my collection of random facts about everything obscure",
    "resist judging my comfort show that I have watched ten times",
    "beat me at coming up with the most random hypotheticals",
    "understand my organizational system that makes sense only to me",
    "resist laughing at my weird habits that I do not notice",
    "guess which historical figure I would want to have dinner with",
    "handle my need to rearrange furniture at random times",
    "beat my score in the most obscure trivia categories",
    "resist asking questions when I start my weird bedtime routine",
    "understand why I name all my plants and talk to them",
    "beat me at making up stories about strangers we see",
    "handle my obsession with collecting things nobody else cares about",
    "resist joining in when I start dancing randomly in public",
    "guess my exact order at every restaurant before I say it",
    "understand my very specific way of eating certain foods",
    "beat me at finding faces in clouds",
    "handle my need to learn one random skill every month",
    "resist questioning my logic that makes perfect sense to me",
    "guess which conspiracy theory I find weirdly fascinating",
  ],
  serious: [
    "challenge my perspective without me respecting your viewpoint",
    "find someone more committed to personal growth than me",
    "match my dedication to the things I care about",
    "handle deep conversations at two in the morning",
    "find someone who values honesty more than I do",
    "beat my work ethic when it comes to my goals",
    "resist respecting my boundaries and communication style",
    "find someone more loyal than me to people I love",
    "match my level of commitment once I decide you are worth it",
    "handle my intensity when I care about something",
    "find someone who takes relationships more seriously than I do",
    "beat my standards for how I want to be treated",
    "resist appreciating my direct communication style",
    "find someone more dedicated to building something real",
    "match my emotional intelligence and self awareness",
    "handle my need for depth over surface level connections",
    "find someone who values growth more than comfort",
    "beat my consistency in showing up for people I love",
    "resist respecting how much I value trust and transparency",
    "find someone more intentional about their choices",
  ],
  intellectual: [
    "out debate me without me finding it attractive",
    "recommend a book I have not already read",
    "beat me in a random trivia category I actually know",
    "challenge my perspective with a better argument",
    "resist getting into deep philosophical discussions with me",
    "find a topic I do not have an opinion on yet",
    "beat me at connecting random concepts into coherent theories",
    "handle my need to analyze everything we watch or read",
    "resist asking why when I make a random observation",
    "match my curiosity about literally everything",
    "beat my reading speed without sacrificing comprehension",
    "handle my tendency to turn everything into a learning moment",
    "resist engaging when I start theorizing about random topics",
    "find a documentary I have not already watched",
    "beat me at making connections between completely unrelated subjects",
    "handle my constant need to understand how things work deeply",
    "resist joining my deep dive into whatever I am researching",
    "match my enthusiasm for learning something new every day",
    "beat my ability to remember random facts from years ago",
    "handle conversations that go from light to existential in seconds",
  ],
};

module.exports = iBetYouCant;
