const iFeelMostSupportedWhen = {
  funny: [
    "someone laughs at my jokes even the really bad",
    "my friends hype me up for no reason at",
    "someone pretends my problems are the most important thing",
    "people validate my online shopping addiction as self care",
    "someone agrees that i deserve that extra slice of",
    "my friends support my delusions and bad ideas equally",
    "someone tells me im right even when im clearly",
    "people laugh with me not at me hopefully always",
    "someone brings me food without me having to ask",
    "my friends gas me up in the group chat",
    "someone defends my questionable life choices without hesitation ever here",
    "people act like my drama is their drama too",
    "someone validates my need to buy another plant i",
    "my friends match my energy no matter how unhinged",
    "someone agrees that i need a mental health day",
    "people support my impulse purchases as investments in happiness",
    "someone tells me im the funniest person they know",
    "my friends enable my bad habits with zero judgment",
    "someone laughs at my texts even with just emojis",
    "people treat my comfort show rewatches as valid activity",
  ],
  romantic: [
    "someone holds my hand without me having to ask",
    "they listen without trying to fix everything immediately always",
    "someone checks in just to make sure im okay",
    "they remember small details i mentioned weeks ago casually",
    "someone makes me feel safe enough to be vulnerable",
    "they show up consistently not just when its easy",
    "someone validates my feelings even when they dont understand",
    "they choose me over and over again without hesitation",
    "someone makes me feel like im their priority always",
    "they give me space but let me know theyre",
    "someone looks at me like im their favorite person",
    "they support my dreams even when theyre scared too",
    "someone loves me on my worst days not just",
    "they make me feel heard and seen and valued",
    "someone reminds me of my worth when i forget",
    "they celebrate my wins like theyre their own too",
    "someone stays when things get hard instead of leaving",
    "they make me feel chosen not just an option",
    "someone shows love through actions not just empty words",
    "they make me believe im worthy of good things",
  ],
  adventurous: [
    "someone says yes to my spontaneous ideas without hesitation",
    "they match my energy for trying new things together",
    "someone encourages me to take risks and chase dreams",
    "they join my adventures instead of holding me back",
    "someone believes in my crazy plans and wild ideas",
    "they push me out of my comfort zone gently",
    "someone celebrates my courage to try new things always",
    "they dont make me feel weird for wanting more",
    "someone joins me in exploring instead of staying comfortable",
    "they support my need for change and growth constantly",
    "someone gets excited about my travel plans with me",
    "they encourage me to go after what i want",
    "someone doesnt try to make me play it safe",
    "they trust me to know my own limits and",
    "someone cheers me on when i do scary things",
    "they remind me im capable of more than i",
    "someone supports my need to keep moving and exploring",
    "they dont make me choose between them and adventure",
    "someone believes i can handle whatever comes my way",
    "they encourage my independence while still being there always",
  ],
  quirky: [
    "someone appreciates my weird habits instead of judging them",
    "they laugh at my random thoughts and observations daily",
    "someone gets my references that nobody else understands ever",
    "they dont question my oddly specific routines and systems",
    "someone matches my energy for random deep dives into",
    "they appreciate my collections that make no sense to",
    "someone validates my need to do things my own",
    "they find my quirks endearing instead of annoying always",
    "someone doesnt make me feel weird for being myself",
    "they engage with my random hypotheticals at 2am seriously",
    "someone appreciates my niche interests and obscure knowledge about",
    "they dont try to change the things that make",
    "someone celebrates my weirdness instead of trying to fix",
    "they understand my logic even when it makes no",
    "someone joins my weird traditions without asking too many",
    "they appreciate my specific way of doing literally everything",
    "someone doesnt judge my comfort items or routines ever",
    "they find my randomness charming instead of confusing always",
    "someone gets why certain things matter so much to",
    "they make me feel normal for being completely myself",
  ],
  serious: [
    "someone respects my boundaries without making me feel guilty",
    "they validate my feelings without trying to fix me",
    "someone shows up consistently through actions not just words",
    "they give me space to process without taking it",
    "someone listens to understand not just to respond back",
    "they respect my need for honesty and direct communication",
    "someone takes my concerns seriously instead of dismissing them",
    "they support my growth even when it means changing",
    "someone holds space for my emotions without judgment ever",
    "they show up when i need them most consistently",
    "someone respects my healing process and my timeline always",
    "they communicate openly and dont make me guess anything",
    "someone takes accountability instead of making excuses for actions",
    "they match my effort and energy in the relationship",
    "someone values my time and doesnt take it for",
    "they respect my independence while still being emotionally present",
    "someone follows through on what they say theyll do",
    "they make me feel safe to be completely honest",
    "someone prioritizes our relationship through consistent intentional effort daily",
    "they show love in ways that actually matter to",
  ],
  intellectual: [
    "someone engages with my ideas instead of dismissing them",
    "they challenge my perspective in respectful thoughtful ways always",
    "someone asks questions that make me think deeper about",
    "they value my opinions and actually consider them seriously",
    "someone appreciates my need to understand things deeply thoroughly",
    "they have conversations that go beyond surface level small",
    "someone respects my intelligence and doesnt talk down to",
    "they encourage my curiosity instead of finding it annoying",
    "someone debates with me without getting defensive or emotional",
    "they appreciate my analytical approach to problems and situations",
    "someone values learning and growth as much as i",
    "they listen when i explain things im passionate about",
    "someone doesnt make me feel bad for overthinking everything",
    "they appreciate my need to research before making decisions",
    "someone engages with my theories and random observations seriously",
    "they value depth and substance in our conversations always",
    "someone respects my need to process things logically first",
    "they appreciate my perspective even when its different from",
    "someone makes me feel smart instead of too much",
    "they engage intellectually without making it a competition ever",
  ],
};

module.exports = iFeelMostSupportedWhen;
