const iGeekOutOn = {
  "funny": [
    "reality tv drama because it's honestly better than any scripted show 😂",
    "memes that are so specific only like three people would understand them",
    "conspiracy theories that are absolutely wild but kinda fun to think about",
    "celebrity gossip even though I pretend I don't care about it honestly",
    "true crime podcasts where I try to solve cases from my couch",
    "random wikipedia rabbit holes at 3am about the weirdest topics ever",
    "tiktok trends even when I'm way too old to understand them lol",
    "my horoscope even though I know it's probably not that accurate",
    "reality dating shows that are absolutely chaotic and make no sense",
    "internet drama between people I don't even know or follow honestly",
    "random facts that I'll never use but find absolutely fascinating for some",
    "bad movies that are so terrible they're actually entertaining to watch",
    "celebrity couple drama like I personally know them and their whole relationship",
    "conspiracy theory videos on youtube at 2am when I should be sleeping",
    "trashy reality tv that I watch ironically but actually love unironically",
    "random trivia that makes me seem smart at parties but is useless",
    "internet culture and memes from like 2012 that nobody remembers anymore",
    "dramatic reddit stories that are probably fake but entertaining as hell",
    "celebrity feuds and drama like it's my own personal soap opera",
    "random youtube videos about topics I never knew I needed to know"
  ],
  "romantic": [
    "love stories that make me believe in soulmates and happy endings ❤️",
    "romantic movies that make me cry every single time I watch them",
    "poetry about love and connection that hits different late at night honestly",
    "couples who've been together forever and still look at each other lovingly",
    "love songs that perfectly capture exactly how I feel about someone special",
    "romantic gestures that show someone really pays attention and cares deeply",
    "wedding videos that make me emotional even though I don't know them",
    "love letters and handwritten notes that feel so personal and intimate always",
    "old couples holding hands and still being in love after all years",
    "romantic books where the love story feels real and deeply emotional honestly",
    "proposals that are thoughtful and personal rather than just big and flashy",
    "anniversary stories about couples who still choose each other every single day",
    "romantic quotes that make me feel all the feelings about love honestly",
    "date ideas that are creative and show real thought and effort",
    "love languages and learning how people show and receive love differently always",
    "relationship advice that helps people build stronger and healthier connections with partners",
    "romantic comedies that make me laugh and believe in love at same",
    "couples therapy success stories that show love is worth fighting for always",
    "small romantic gestures that mean more than any grand expensive display ever",
    "love stories that prove timing and effort can make anything work"
  ],
  "adventurous": [
    "travel vlogs that make me want to book flights immediately 🌟",
    "extreme sports videos even though I'd probably never try them myself",
    "hiking trails and planning my next outdoor adventure in nature somewhere",
    "travel blogs with hidden gems and off the beaten path destinations",
    "adventure documentaries about people doing insane things I'd never attempt honestly",
    "road trip planning and mapping out the perfect route with all stops",
    "camping gear and outdoor equipment even though I rarely go camping",
    "travel photography that captures the beauty of places I want to visit",
    "adventure stories from people who quit their jobs to travel the world",
    "national parks and planning trips to visit every single one eventually",
    "backpacking tips and tricks for traveling light and living minimally on road",
    "adrenaline rush activities that scare me but also sound incredibly fun honestly",
    "travel deals and finding cheap flights to places I've always wanted",
    "outdoor survival skills even though I'll probably never need them realistically",
    "bucket list destinations and adding new places constantly to my growing list",
    "adventure travel accounts that inspire me to get out and explore more",
    "road trip playlists and curating the perfect songs for long drives ahead",
    "travel hacks that make trips easier and more affordable for everyone honestly",
    "adventure challenges like hiking all the tallest peaks or visiting every continent",
    "spontaneous trip ideas that I could do on a random weekend getaway"
  ],
  "quirky": [
    "random niche hobbies that most people have never even heard of 🎨",
    "weird historical facts that sound fake but are actually completely true",
    "obscure indie music that nobody else seems to know or listen to",
    "vintage fashion from specific eras that most people find kinda weird honestly",
    "strange collections like cool rocks or vintage postcards from random places everywhere",
    "unusual art styles that most people don't understand but I find beautiful",
    "niche internet communities dedicated to the most random specific things ever",
    "weird food combinations that sound gross but actually taste amazing trust me",
    "obscure movies that nobody's heard of but are actually cinematic masterpieces honestly",
    "random crafts and DIY projects that seem pointless but are fun",
    "strange subcultures and learning about communities I never knew existed before",
    "vintage technology and how things used to work before everything went digital",
    "unusual plants and learning how to care for weird species nobody",
    "niche podcasts about incredibly specific topics that only I seem interested in",
    "weird animals that most people don't know exist but are fascinating",
    "obscure books from authors nobody's heard of but should definitely read",
    "strange traditions from different cultures that seem wild but are meaningful",
    "random skills like juggling or origami that serve no real purpose",
    "unusual architecture and buildings that look like they're from another planet honestly",
    "niche fashion subcultures that express creativity in the most unique ways"
  ],
  "serious": [
    "personal development and constantly working on becoming the best version of myself",
    "productivity systems and finding the most efficient ways to achieve my goals",
    "financial literacy and learning how to build wealth and security for future",
    "career growth strategies and networking to advance in my professional life always",
    "mental health resources and learning how to maintain emotional wellbeing every day",
    "goal setting frameworks that actually help me achieve what I want",
    "time management techniques that maximize productivity and minimize wasted time throughout day",
    "leadership development and learning how to inspire and guide others effectively always",
    "self improvement books that challenge me to grow and think differently honestly",
    "habit formation science and building routines that support my long term goals",
    "professional development courses that give me skills for career advancement and growth",
    "investment strategies and learning how to make my money work for me",
    "communication skills and learning how to express myself clearly and effectively always",
    "boundary setting and learning to protect my energy and time wisely",
    "success stories from people who've achieved what I'm working towards honestly",
    "strategic planning and mapping out my five and ten year life plans",
    "emotional intelligence and learning to understand and manage my feelings better daily",
    "networking events and building connections that can help me grow professionally",
    "personal finance podcasts that teach me how to manage money smarter",
    "life coaching content that helps me stay focused on my priorities"
  ],
  "intellectual": [
    "philosophy and questioning the fundamental nature of reality and existence 🧠",
    "scientific discoveries that change how we understand the world around us",
    "psychology research about why people think and behave the way they do",
    "history documentaries that provide context for understanding today's world and society",
    "linguistics and how language shapes the way we think and perceive reality",
    "space exploration and the mysteries of the universe we haven't solved",
    "neuroscience and understanding how our brains work and create consciousness somehow",
    "political theory and different systems of governance throughout history and today",
    "economics and how markets and human behavior intersect in fascinating ways",
    "anthropology and learning about different cultures and human societies throughout time",
    "quantum physics even though it makes my brain hurt trying to understand",
    "literature analysis and finding deeper meanings in books and written works always",
    "ethical philosophy and debating moral questions that have no easy answers",
    "evolutionary biology and how life developed and adapted over millions of years",
    "cognitive science and how we process information and make decisions every day",
    "mathematical concepts that reveal patterns in nature and the universe around",
    "sociology and understanding how societies function and change over time constantly",
    "artificial intelligence and the implications for humanity's future and society overall",
    "environmental science and understanding our impact on the planet we live on",
    "ancient civilizations and how they solved problems without modern technology available"
  ],
  "default": [
    "things that make me happy and bring joy to my everyday life ✨",
    "hobbies that let me express myself and relax after a long day",
    "topics I find interesting even if they're random or niche honestly",
    "learning new things that expand my perspective and understanding of world",
    "creative projects that let me make something with my own hands",
    "conversations that go deep and make me think about life differently",
    "content that inspires me to be better and try new things always",
    "communities of people who share my interests and passions in life",
    "discovering new music and artists that resonate with how I'm feeling",
    "books that transport me to different worlds and make me feel things",
    "podcasts about topics I'm curious about and want to learn more",
    "art that makes me feel something or see the world differently somehow",
    "stories that teach me something new about people or the world",
    "skills that challenge me and help me grow as a person overall",
    "ideas that make me question my assumptions and think more deeply",
    "experiences that push me outside my comfort zone in good ways",
    "people who are passionate about their interests and share that energy openly",
    "moments that remind me why life is beautiful and worth living fully",
    "things that make me laugh and bring lightness to my day always",
    "whatever captures my attention and makes me want to learn more honestly"
  ]
};

module.exports = iGeekOutOn;
