const iGoCrazyFor = {
  "funny": [
    "good food especially when it's free or someone else paid 😂",
    "my bed after a long day because sleep is life",
    "coffee in the morning because I'm not human without it",
    "finding money in pockets I forgot about which is rare",
    "when plans get cancelled and I can stay home instead",
    "free samples at stores because who doesn't love free food",
    "perfectly timed naps that make me feel like a new person",
    "when my favorite song comes on at the perfect moment randomly",
    "getting into bed with fresh clean sheets that smell amazing",
    "finding a new show to binge watch all weekend long",
    "when someone else cooks dinner so I don't have to honestly",
    "good deals and sales because saving money feels so good",
    "lazy sundays where I have absolutely nothing to do at",
    "when my food arrives faster than expected from delivery apps honestly",
    "finding the perfect meme that describes my exact mood right",
    "when someone brings me food without me even asking for",
    "cozy rainy days where I can just stay inside all",
    "when my package arrives early and I wasn't even expecting it",
    "perfectly brewed coffee that hits different on a monday morning honestly",
    "when everything just works out without any stress or drama"
  ],
  "romantic": [
    "deep conversations that last until 3am with someone special ❤️",
    "genuine connection with someone who really gets me on every level",
    "when someone remembers small details I mentioned weeks ago to them",
    "feeling completely comfortable and myself around someone I care about deeply",
    "meaningful eye contact that says more than words ever could honestly",
    "when someone makes me feel safe enough to be vulnerable",
    "thoughtful gestures that show someone was thinking of me throughout day",
    "quality time with someone where we're fully present with each",
    "when someone supports my dreams and believes in me unconditionally always",
    "genuine affection and feeling loved for exactly who I am right",
    "deep emotional connection that goes beyond surface level attraction or anything",
    "when someone makes me laugh and smile without even trying hard",
    "feeling cherished and appreciated by someone who truly values me always",
    "romantic moments that feel natural and not forced or awkward",
    "when someone shows love through actions not just empty words",
    "building something real with someone who's equally invested in us",
    "feeling butterflies when I see someone I really care about",
    "when someone makes me feel like I'm the only person",
    "genuine chemistry and connection that's undeniable between two people honestly",
    "love that feels easy and natural like it was meant"
  ],
  "adventurous": [
    "trying new experiences that push me outside my comfort zone 🌟",
    "spontaneous trips with no real plan just going with flow",
    "exploring new places I've never been to before in life",
    "adrenaline rush from activities that scare me a little bit",
    "discovering hidden gems in cities I'm visiting for first time",
    "trying foods from cuisines I've never experienced before at all",
    "outdoor adventures like hiking camping or anything in nature honestly",
    "saying yes to opportunities that come up even when scary",
    "traveling to new countries and experiencing different cultures there always",
    "road trips with good music and no real destination in",
    "adventure sports that make my heart race and feel alive",
    "exploring off the beaten path places tourists don't usually visit",
    "spontaneous plans that turn into the best memories I have",
    "trying activities I've never done before just to see what",
    "getting lost in new cities and finding my way back",
    "weekend getaways to places I've been wanting to explore forever",
    "new experiences that become stories I'll tell for years honestly",
    "pushing my limits and discovering what I'm capable of doing",
    "adventures with people who match my energy and spontaneity always",
    "living in the moment and embracing whatever comes my way"
  ],
  "quirky": [
    "weird niche interests that most people don't understand or appreciate 🎨",
    "random obscure facts that I can't help but share with",
    "my oddly specific collections that bring me so much joy",
    "unconventional hobbies that make me unique and interesting to some",
    "strange coincidences and patterns I notice that nobody else sees",
    "quirky traditions I've made up that don't make sense to",
    "obscure references from shows or books nobody else has heard",
    "weird art and music that's too niche for mainstream taste",
    "my eccentricities and the things that make me different from",
    "random tangents and deep dives into topics nobody asked about",
    "unconventional ways of doing things that work for me personally",
    "niche communities online where I can geek out with similar",
    "strange combinations that shouldn't work but somehow do for me",
    "my unique perspective on things that others find odd or",
    "quirky aesthetics and styles that express my personality fully and",
    "obscure hobbies that I'm passionate about even if nobody",
    "weird humor that only certain people understand and appreciate fully",
    "unconventional ideas and ways of thinking about everything in life",
    "my oddities and quirks that make me memorable to people",
    "strange interests that fascinate me even though they're super niche"
  ],
  "serious": [
    "achieving my goals and seeing my hard work pay off",
    "personal growth and becoming better than I was yesterday always",
    "building a stable secure future for myself and my family",
    "meaningful work that aligns with my values and makes impact",
    "financial independence and having security in my life going forward",
    "reaching milestones I've been working towards for a long time",
    "self improvement and constantly working on becoming my best self daily",
    "building strong foundations in all areas of my life consistently",
    "achieving success through dedication and consistent effort over time always",
    "making progress towards my long term goals even when slow",
    "developing skills that will help me advance in my career",
    "creating stability and security in my personal and professional life",
    "accomplishing things I set my mind to no matter how difficult",
    "building wealth and financial freedom for my future and family",
    "personal development and investing in myself and my growth constantly",
    "achieving work life balance while still reaching my goals successfully",
    "making smart decisions that benefit my future self and wellbeing",
    "building a life I'm proud of through hard work",
    "reaching my full potential in all areas of my life",
    "creating lasting success through discipline and consistent effort daily"
  ],
  "intellectual": [
    "learning new things and expanding my knowledge about everything 🧠",
    "deep intellectual conversations that challenge my thinking and perspectives on things",
    "discovering new ideas and concepts that change how I see",
    "reading books that make me think differently about life and",
    "engaging debates where I learn from different viewpoints and perspectives",
    "understanding complex topics and how things work in the world",
    "philosophical discussions about life meaning and purpose of everything around",
    "learning from people who are smarter than me in areas",
    "exploring new subjects and diving deep into topics that fascinate",
    "intellectual stimulation from conversations that go beyond surface level talk",
    "discovering connections between different ideas and concepts I'm learning about",
    "expanding my understanding of the world through reading and learning",
    "thoughtful analysis and critical thinking about important issues in society",
    "learning about different cultures perspectives and ways of thinking about",
    "intellectual growth and constantly challenging my assumptions about everything I",
    "deep dives into subjects I'm passionate about and want to",
    "meaningful discussions that make me question and reconsider my views",
    "learning from experts and people with deep knowledge in fields",
    "exploring ideas that push my thinking in new directions I",
    "intellectual curiosity and never stopping learning about the world around"
  ],
  "default": [
    "things that bring me genuine joy and happiness in life ✨",
    "spending time with people I care about and love deeply",
    "doing things I'm passionate about that make me feel alive",
    "moments that make me feel grateful for my life and",
    "experiences that create lasting memories I'll cherish forever and always",
    "things that make me laugh and bring lightness to my",
    "activities that help me relax and recharge my energy levels",
    "pursuing my interests and hobbies that I genuinely enjoy doing",
    "connecting with people on a real authentic level without pretense",
    "things that make me feel like myself and bring out",
    "moments of peace and contentment in my everyday life honestly",
    "doing things that align with my values and what matters",
    "experiences that help me grow and learn as a person",
    "spending quality time doing things I love with people I",
    "things that make my life feel meaningful and purposeful every",
    "moments that remind me why life is beautiful and worth",
    "activities that bring out the best version of myself always",
    "connecting with things that resonate with who I am deeply",
    "experiences that make me feel alive and present in moment",
    "things that bring balance and fulfillment to my life overall"
  ]
};

module.exports = iGoCrazyFor;
