const iKnowTheBestSpotInTownFor = {
  funny: [
    "getting food poisoning but in a fun way honestly",
    "people watching and judging strangers life choices silently together",
    "finding the worst parking spot in the entire city",
    "overpriced coffee that tastes exactly like regular coffee does",
    "getting lost even with gps telling you exactly where",
    "pretending youre fancy when youre really just broke and",
    "taking instagram photos you'll never actually post anywhere online",
    "spending way too much money on things you dont",
    "having an existential crisis over brunch menu options always",
    "running into everyone you've ever met all at once",
    "getting judged by hipsters who got there way before",
    "waiting in line for something thats just okay honestly",
    "overpriced drinks that are mostly ice and vibes only",
    "feeling poor after looking at the menu prices first",
    "taking aesthetic photos that hide how expensive everything was",
    "people watching and making up elaborate backstories for strangers",
    "getting food coma and regretting all your life choices",
    "spending your entire paycheck on one meal basically here",
    "pretending you understand the menu when you absolutely dont",
    "having the most chaotic brunch experience of your life",
  ],
  romantic: [
    "sunset views that make you believe in love again",
    "cozy coffee dates that turn into hours of talking",
    "romantic walks that feel like a movie scene honestly",
    "stargazing away from the city lights and noise pollution",
    "intimate dinners with the perfect ambiance and mood lighting",
    "watching sunrise together and feeling grateful for this moment",
    "quiet spots where we can just be together peacefully",
    "late night drives with the best views of city",
    "picnic spots that feel like our own little world",
    "cozy bookstores where we can get lost for hours",
    "rooftop views perfect for deep conversations under the stars",
    "hidden gardens that feel magical and romantic always here",
    "coffee shops with the coziest corners for long talks",
    "beach spots perfect for watching waves and holding hands",
    "scenic overlooks where we can watch the world together",
    "candlelit dinners that make every moment feel special always",
    "walking trails perfect for hand holding and deep conversations",
    "cozy wine bars with intimate seating and soft lighting",
    "hidden spots where it feels like just us two",
    "romantic restaurants perfect for celebrating special moments together always",
  ],
  adventurous: [
    "spontaneous adventures that start with no real plan ever",
    "hiking trails with the most incredible views at top",
    "hidden gems tourists dont know about yet thankfully here",
    "trying the weirdest food you've never heard of",
    "adrenaline rushes that make you feel alive again instantly",
    "exploring parts of the city most people never see",
    "outdoor activities that push you out of comfort zone",
    "sunrise hikes that are totally worth waking up for",
    "water sports and activities that get your heart racing",
    "rock climbing spots for beginners and experienced climbers both",
    "bike trails that take you through the best scenery",
    "kayaking or paddleboarding with amazing views around you always",
    "zip lining through forests and feeling completely free finally",
    "camping spots away from civilization and city noise pollution",
    "road trip starting points with endless possibilities ahead of",
    "farmers markets with the best local food to try",
    "spontaneous day trips to nearby towns worth exploring together",
    "adventure parks with activities for every thrill level honestly",
    "scenic drives that make you want to keep going",
    "outdoor concerts and festivals with the best energy always",
  ],
  quirky: [
    "finding the most random vintage items you dont need",
    "weird museums that most people dont know exist here",
    "thrift stores with the most chaotic energy and finds",
    "oddly specific bookstores that cater to niche interests only",
    "quirky cafes with the strangest themes and decor choices",
    "record stores where you can get lost for hours",
    "art galleries featuring local artists nobody knows yet somehow",
    "comic book shops with the most passionate staff ever",
    "vintage arcades that take you back to childhood instantly",
    "indie movie theaters showing films youve never heard of",
    "craft stores with supplies for hobbies you'll never start",
    "used bookstores that smell like nostalgia and old paper",
    "antique shops full of things with mysterious backstories probably",
    "quirky gift shops with items you never knew existed",
    "local markets with the most random unique finds always",
    "board game cafes perfect for competitive game nights together",
    "weird themed restaurants that commit fully to the bit",
    "independent coffee shops with oddly specific drink menu options",
    "vintage clothing stores with one of a kind pieces",
    "curiosity shops filled with random treasures and odd items",
  ],
  serious: [
    "quiet reflection and actually processing your thoughts and feelings",
    "meaningful conversations without distractions or interruptions from phones constantly",
    "quality time with people who actually matter to you",
    "peaceful walks when you need to clear your head",
    "coffee shops perfect for working or deep thinking alone",
    "libraries where you can focus and be productive finally",
    "meditation or yoga classes that actually help you center",
    "therapy friendly cafes for processing life over good coffee",
    "quiet parks perfect for journaling and self reflection time",
    "bookstores where you can lose yourself in good literature",
    "coworking spaces with the right atmosphere for deep work",
    "nature trails perfect for clearing your mind and resetting",
    "quiet restaurants for serious conversations that matter deeply here",
    "wellness centers focused on actual mental and physical health",
    "study spots with minimal distractions and good energy always",
    "peaceful gardens perfect for meditation and quiet contemplation time",
    "support group meeting spaces that feel safe and welcoming",
    "quiet cafes perfect for one on one meaningful conversations",
    "retreats focused on personal growth and self development work",
    "spaces designed for intentional connection and deep conversation always",
  ],
  intellectual: [
    "thought provoking conversations that last until way too late",
    "independent bookstores with the best curated selection of literature",
    "lectures and talks about topics that actually matter deeply",
    "museums with exhibits that make you think differently about",
    "coffee shops where intellectuals gather and debate ideas passionately",
    "libraries with rare books and quiet study spaces perfect",
    "poetry readings and open mics with talented local artists",
    "documentary screenings followed by discussions and thoughtful analysis always",
    "philosophy meetups where people actually engage with ideas seriously",
    "art galleries featuring thought provoking contemporary works and installations",
    "book clubs that have deep discussions about literature themes",
    "science museums with interactive exhibits that teach you things",
    "cultural centers celebrating diverse perspectives and artistic expressions beautifully",
    "academic talks open to the public about fascinating topics",
    "jazz clubs with live music that makes you feel",
    "historic sites that connect you to the past meaningfully",
    "indie theaters showing foreign films and documentaries worth watching",
    "debate clubs where people discuss current events and ideas",
    "writing workshops with other people passionate about the craft",
    "symposiums and panels discussing important social and cultural issues",
  ],
};

module.exports = iKnowTheBestSpotInTownFor;
