const illBragAboutYouToMyFriendsIf = {
  funny: [
    "you can make me laugh until i snort embarrassingly",
    "you have a weirdly impressive useless talent to show",
    "you can beat me at mario kart fair and square",
    "you have the best memes in your camera roll",
    "you can do a really good celebrity impression badly",
    "you make the best late night snack runs ever",
    "you have an embarrassing hidden talent youre proud of",
    "you can make me laugh at the worst times",
    "you have the most unhinged group chat energy ever",
    "you can handle my chaotic energy without getting overwhelmed",
    "you laugh at all my jokes even the bad",
    "you have strong opinions about random things like me",
    "you can match my energy for spontaneous bad ideas",
    "you make the best playlists for every random mood",
    "you have the funniest stories from your past honestly",
    "you can roast me but make it feel like",
    "you have the best comebacks in any situation ever",
    "you can make anything fun even boring errands together",
    "you have a signature move that cracks me up",
    "you can keep up with my random 2am thoughts",
  ],
  romantic: [
    "you make me feel like the luckiest person alive",
    "you remember every little detail i tell you about",
    "you look at me like im your whole world",
    "you make me believe in love like the movies",
    "you do the sweetest things without me asking ever",
    "you make me feel safe and loved every day",
    "you give the best hugs that fix everything instantly",
    "you write me notes or texts that make me",
    "you plan the most thoughtful dates and surprises always",
    "you make me feel beautiful even on my worst",
    "you support my dreams like theyre your own too",
    "you know exactly how to make me smile always",
    "you make ordinary moments feel special and magical together",
    "you love me on my bad days not just",
    "you make me want to be a better person",
    "you show up for me in ways nobody else",
    "you make me feel chosen every single day consistently",
    "you give me butterflies even after all this time",
    "you treat me like im the most important person",
    "you make me believe im worthy of good love",
  ],
  adventurous: [
    "you say yes to my spontaneous adventure ideas always",
    "you can keep up with my energy for exploring",
    "you push me out of my comfort zone gently",
    "you have the best travel stories and bucket list",
    "you make every day feel like an adventure together",
    "you arent afraid to try new things with me",
    "you have been to the coolest places ive never",
    "you can navigate anywhere without getting us too lost",
    "you match my enthusiasm for trying everything once at",
    "you make boring days exciting just by being there",
    "you have the best ideas for weekend adventures always",
    "you arent scared of a little risk or challenge",
    "you can handle my need for constant new experiences",
    "you turn every outing into a memorable fun experience",
    "you have the most impressive adventure photos and stories",
    "you make me want to see the whole world",
    "you can pack light and adapt to anything thrown",
    "you find beauty and excitement in unexpected places always",
    "you have the best spontaneous date ideas ever honestly",
    "you make me feel alive and excited about life",
  ],
  quirky: [
    "you have the most random niche knowledge about things",
    "you appreciate my weird habits and quirks completely always",
    "you have a collection of something oddly specific too",
    "you get all my obscure references nobody else understands",
    "you have the most interesting hobbies ive ever heard",
    "you can match my energy for random deep dives",
    "you have strong opinions about the weirdest things ever",
    "you do things in your own unique way unapologetically",
    "you have the best random facts stored in your",
    "you appreciate my oddly specific routines and systems completely",
    "you have a comfort show youve watched too many",
    "you can keep up with my random hypothetical questions",
    "you have the most unique perspective on everything around",
    "you make being weird feel completely normal and fun",
    "you have a signature quirk that makes you you",
    "you appreciate the little details nobody else notices ever",
    "you have the most interesting way of doing simple",
    "you can talk about your niche interests for hours",
    "you make me feel normal for being completely myself",
    "you have the best random stories that nobody believes",
  ],
  serious: [
    "you have integrity and actually live by your values",
    "you communicate honestly even when its hard to do",
    "you take accountability and work on yourself actively always",
    "you show up consistently through actions not just words",
    "you have emotional intelligence and arent afraid to use",
    "you respect boundaries and communicate your own clearly too",
    "you handle conflict maturely without shutting down or running",
    "you have clear goals and work toward them daily",
    "you treat people with respect and genuine kindness always",
    "you follow through on what you say you'll do",
    "you have self awareness and continue growing as person",
    "you value honesty and depth over surface level connections",
    "you make me feel safe to be vulnerable with",
    "you prioritize our relationship through consistent intentional effort daily",
    "you have strong character and stand by your principles",
    "you handle difficult situations with grace and maturity always",
    "you invest in our relationship not just expect it",
    "you respect my independence while being emotionally present too",
    "you make me want to be better without changing",
    "you show love in ways that actually matter to",
  ],
  intellectual: [
    "you can debate without getting defensive or emotional ever",
    "you have the most interesting perspective on everything around",
    "you read books and actually remember what you read",
    "you can explain complex topics in simple clear terms",
    "you ask thoughtful questions that make me think deeper",
    "you have knowledge about the most fascinating random topics",
    "you challenge my perspective in respectful meaningful ways always",
    "you can hold conversations about literally anything interesting deeply",
    "you value learning and growth as much as i",
    "you make intellectual conversations feel fun not pretentious ever",
    "you have opinions backed by actual thought and research",
    "you can connect random concepts in brilliant ways always",
    "you appreciate nuance and think beyond black and white",
    "you listen to understand not just to respond back",
    "you have curiosity about how everything works around us",
    "you can admit when you dont know something honestly",
    "you make me think differently about things i thought",
    "you have the best recommendations for books podcasts documentaries",
    "you value substance and depth in all our conversations",
    "you make me feel smart instead of too much",
  ],
};

module.exports = illBragAboutYouToMyFriendsIf;
