const illBragAboutYouToMyFriendsIf = {
  funny: [
    "you can make me laugh until I snort",
    "you have a weirdly impressive useless talent",
    "you can beat me at Mario Kart fair",
    "you have the best memes in your camera roll",
    "you can do a really good celebrity impression badly",
    "you make the best late night snack runs",
    "you have an embarrassing hidden talent youre proud of",
    "you can make me laugh at the worst times",
    "you have the most unhinged group chat energy",
    "you can handle my chaotic energy without getting overwhelmed",
    "you laugh at all my jokes even the bad ones",
    "you have strong opinions about random things like me",
    "you can match my energy for spontaneous ideas",
    "you make the best playlists for every mood",
    "you have the funniest stories from your past",
    "you can roast me but make it feel like love",
    "you have the best comebacks in any situation",
    "you can make anything fun even boring errands",
    "you have a signature move that cracks me up",
    "you can keep up with my random 2am thoughts",
  ],
  romantic: [
    "you make me feel like the luckiest person",
    "you remember every little detail I tell you",
    "you look at me like Im your whole world",
    "you make me believe in love like the movies",
    "you do the sweetest things without me asking",
    "you make me feel safe and loved every day",
    "you give the best hugs that fix everything",
    "you write me notes or texts that make me smile",
    "you plan the most thoughtful dates and surprises",
    "you make me feel beautiful even on my worst days",
    "you support my dreams like they are your own",
    "you know exactly how to make me smile",
    "you make ordinary moments feel special and magical",
    "you love me on my bad days not just good",
    "you make me want to be a better person",
    "you show up for me in ways nobody else does",
    "you make me feel chosen every single day",
    "you give me butterflies even after all this time",
    "you treat me like Im the most important person",
    "you make me believe Im worthy of good love",
  ],
  adventurous: [
    "you say yes to my spontaneous adventure ideas",
    "you can keep up with my energy for exploring",
    "you push me out of my comfort zone gently",
    "you have the best travel stories and bucket list",
    "you make every day feel like an adventure",
    "you are not afraid to try new things with me",
    "you have been to the coolest places",
    "you can navigate anywhere without getting us too lost",
    "you match my enthusiasm for trying everything once",
    "you make boring days exciting just by being there",
    "you have the best ideas for weekend adventures",
    "you are not scared of a little risk",
    "you can handle my need for constant new experiences",
    "you turn every outing into a memorable experience",
    "you have the most impressive adventure photos and stories",
    "you make me want to see the whole world",
    "you can pack light and adapt to anything",
    "you find beauty and excitement in unexpected places",
    "you have the best spontaneous date ideas",
    "you make me feel alive and excited about life",
  ],
  quirky: [
    "you have the most random niche knowledge",
    "you appreciate my weird habits and quirks completely",
    "you have a collection of something oddly specific too",
    "you get all my obscure references nobody else understands",
    "you have the most interesting hobbies",
    "you can match my energy for random deep dives",
    "you have strong opinions about the weirdest things",
    "you do things in your own unique way unapologetically",
    "you have the best random facts stored",
    "you appreciate my oddly specific routines and systems",
    "you have a comfort show you have watched too many times",
    "you can keep up with my random hypothetical questions",
    "you have the most unique perspective on everything",
    "you make being weird feel completely normal and fun",
    "you have a signature quirk that makes you you",
    "you appreciate the little details nobody else notices",
    "you have the most interesting way of doing simple things",
    "you can talk about your niche interests for hours",
    "you make me feel normal for being myself",
    "you have the best random stories",
  ],
  serious: [
    "you have integrity and actually live by your values",
    "you communicate honestly even when its hard",
    "you take accountability and work on yourself actively",
    "you show up consistently through actions not just words",
    "you have emotional intelligence",
    "you respect boundaries and communicate your own clearly",
    "you handle conflict maturely without shutting down",
    "you have clear goals and work toward them daily",
    "you treat people with respect and genuine kindness",
    "you follow through on what you say you will do",
    "you have self awareness and continue growing",
    "you value honesty and depth over surface level",
    "you make me feel safe to be vulnerable",
    "you prioritize our relationship through consistent effort",
    "you have strong character and stand by your principles",
    "you handle difficult situations with grace and maturity",
    "you invest in our relationship",
    "you respect my independence while being emotionally present",
    "you make me want to be better",
    "you show love in ways that actually matter",
  ],
  intellectual: [
    "you can debate without getting defensive",
    "you have the most interesting perspective on everything",
    "you read books and actually remember what you read",
    "you can explain complex topics in simple terms",
    "you ask thoughtful questions that make me think deeper",
    "you have knowledge about fascinating random topics",
    "you challenge my perspective in respectful meaningful ways",
    "you can hold conversations about literally anything deeply",
    "you value learning and growth",
    "you make intellectual conversations feel fun",
    "you have opinions backed by actual thought",
    "you can connect random concepts in brilliant ways",
    "you appreciate nuance and think beyond black and white",
    "you listen to understand not just to respond",
    "you have curiosity about how everything works",
    "you can admit when you do not know something",
    "you make me think differently about things",
    "you have the best recommendations for books and podcasts",
    "you value substance and depth",
    "you make me feel smart",
  ],
};

module.exports = illBragAboutYouToMyFriendsIf;
