const illPickTheTopicIfYouStartTheConversation = {
  funny: [
    "why pineapple on pizza is actually a valid choice",
    "our most embarrassing childhood memories we still cringe about",
    "which fictional character we'd fight in real life",
    "the worst pickup lines we've ever heard or used",
    "conspiracy theories we dont believe but find hilarious anyway",
    "our unpopular opinions that would get us cancelled probably",
    "the dumbest thing we've ever done for a crush",
    "which celebrity we think we could totally beat up",
    "our most irrational fears that make no sense logically",
    "the weirdest compliment we've ever received from someone random",
    "what we'd do if we won the lottery",
    "our signature dance move that should never be seen",
    "the worst date story we have that still haunts",
    "which superpower would actually be the most inconvenient daily",
    "our go to karaoke song we absolutely butcher every",
    "the most embarrassing thing in our search history recently",
    "what our last meal would be before we die",
    "the worst lie we told as a kid obviously",
    "which animal we'd be and why its accurate honestly",
    "our hottest take that people always disagree with strongly",
  ],
  romantic: [
    "what our ideal date night looks like in detail",
    "the moment we knew we wanted something real serious",
    "our love language and how we like to receive",
    "what makes us feel most loved and appreciated always",
    "our idea of a perfect relationship and future together",
    "the little things that make us fall for someone",
    "what we look for in a real genuine connection",
    "our favorite love song and why it hits different",
    "the most romantic gesture someone could do for us",
    "what we think makes a relationship actually last long",
    "our dream vacation destination to visit with someone special",
    "the qualities we value most in a partner always",
    "what we want our future to look like together",
    "the moment we feel most connected to someone special",
    "our idea of the perfect cozy night in together",
    "what we think love should feel like in reality",
    "the sweetest thing someone has ever done for us",
    "our relationship goals and what we want to build",
    "what makes us believe in love and happy endings",
    "the little moments that mean the most to us",
  ],
  adventurous: [
    "the craziest thing on our bucket list we want",
    "where we'd go if we could travel anywhere tomorrow",
    "the most spontaneous thing we've ever done in life",
    "our dream adventure and who we'd want there with",
    "the scariest thing we've done that was totally worth",
    "where we see ourselves in five years from now",
    "the next place we want to explore and why",
    "our ideal weekend getaway with zero plans made beforehand",
    "the most adventurous thing we want to try next",
    "what living life to the fullest means to us",
    "the best trip we've ever taken and why memorable",
    "our comfort zone and how we push past it",
    "the wildest story from our travels or adventures so",
    "what we'd do with one year and unlimited money",
    "the adrenaline rush we're chasing next in life soon",
    "our dream road trip route and all the stops",
    "the experience that changed our perspective on life completely",
    "what adventure means to us beyond just traveling places",
    "the risk we took that paid off big time",
    "our next big goal or dream we're working toward",
  ],
  quirky: [
    "our weirdly specific icks that make no sense logically",
    "the most random hill we'd die on without hesitation",
    "our comfort show and why we've watched it repeatedly",
    "the oddly specific thing we find attractive in people",
    "our unpopular opinion that nobody ever agrees with us",
    "the weird habit we have that we dont notice",
    "our go to fun fact about ourselves thats actually",
    "the most random thing we're currently obsessed with lately",
    "our signature order at restaurants that never changes ever",
    "the niche interest nobody else seems to care about",
    "our oddly specific pet peeve that drives us crazy",
    "the random skill we have that impresses nobody really",
    "our comfort food that other people find weird honestly",
    "the thing we collect that makes no sense to",
    "our morning routine thats weirdly specific and never changes",
    "the random fact we know that we'll never use",
    "our guilty pleasure that wed defend to the death",
    "the weird thing we do when nobodys watching us",
    "our most niche reference that nobody ever gets unfortunately",
    "the random thing that brings us unreasonable amount of",
  ],
  serious: [
    "what we value most in relationships and why it",
    "our biggest goal right now and how were working",
    "what personal growth means to us in our lives",
    "our non negotiables in relationships and life in general",
    "what we've learned about ourselves recently through reflection or",
    "our communication style and what we need from partners",
    "what we're working on improving about ourselves right now",
    "our boundaries and why theyre important to us always",
    "what makes us feel truly seen and understood deeply",
    "our idea of a healthy relationship and partnership dynamic",
    "what we need to feel secure in a relationship",
    "our past experiences and how theyve shaped us today",
    "what emotional intimacy means to us in relationships here",
    "our love language and how we show we care",
    "what we think makes a strong foundation for relationships",
    "our deal breakers and why theyre non negotiable for",
    "what we want from life in the next chapter",
    "our values and how we try to live them",
    "what vulnerability means to us and why its hard",
    "our vision for the future and what matters most",
  ],
  intellectual: [
    "the book that changed our perspective on life completely",
    "our current existential crisis or philosophical question we're pondering",
    "the topic we could talk about for hours without",
    "our unpopular opinion on a social or cultural issue",
    "the documentary that made us think differently about everything",
    "our theory about something that nobody else agrees with",
    "the concept or idea we find most fascinating right",
    "our take on a controversial topic people avoid discussing",
    "the question we wish more people would ask themselves",
    "our favorite thought experiment or philosophical paradox to explore",
    "the thing we're currently learning about and finding fascinating",
    "our perspective on human nature and what drives people",
    "the idea that challenges conventional thinking we find interesting",
    "our thoughts on the meaning of life and purpose",
    "the pattern we've noticed that nobody else talks about",
    "our favorite debate topic that gets us fired up",
    "the connection we made between two unrelated concepts recently",
    "our take on what makes life meaningful and worthwhile",
    "the question that keeps us up at night thinking",
    "our current rabbit hole of research and why interesting",
  ],
};

module.exports = illPickTheTopicIfYouStartTheConversation;
