const imLookingFor = {
  "funny": [
    "someone who laughs at my jokes even when they're terrible 😂",
    "a partner in crime for spontaneous food adventures at 2am",
    "someone who's okay with me being chaotic and adds to",
    "a person who appreciates my sarcasm and dishes it back",
    "someone who doesn't judge my comfort shows I've watched repeatedly",
    "a partner who lets me nap whenever without any judgment",
    "someone who understands I'm not a morning person ever honestly",
    "a person who makes everything fun even boring everyday tasks",
    "someone who doesn't take life too seriously and laughs always",
    "a partner who's down for movie marathons and binge watching",
    "someone who can handle my mood swings without taking personally",
    "a person who appreciates my weird humor and contributes their",
    "someone who's okay with me talking to myself constantly throughout",
    "a partner who brings me snacks without me asking for",
    "someone who makes me laugh when I'm having worst days",
    "a person who's down to try weird food combinations",
    "someone who shares their food with me which is love",
    "a partner who matches my meme energy and sends good",
    "someone who's okay with me being dramatic because that's",
    "a person who makes ordinary moments fun by being themselves"
  ],
  "romantic": [
    "someone who's ready for something real and meaningful not casual ❤️",
    "a partner who values communication and emotional availability in relationships always",
    "someone who shows love through actions not just empty words",
    "a person who's ready to build something lasting with me",
    "someone who values quality time and being present with each",
    "a partner who's emotionally available and ready for real connection",
    "someone who believes in showing love consistently not just beginning",
    "a person who values honesty and open communication always honestly",
    "someone who's looking for a partner not just passing time",
    "a partner who makes effort and doesn't play games with",
    "someone who's affectionate and isn't afraid to show their feelings",
    "a person who's ready for commitment and building something lasting",
    "someone who believes in supporting each other's dreams and goals",
    "a partner who values emotional intimacy and being vulnerable together",
    "someone who's my best friend and partner at same time",
    "a person who believes relationships take work and puts in",
    "someone who's consistent and someone I can count on always",
    "a partner who chooses me every day not just sometimes",
    "someone who's ready to build something real through effort intention",
    "a person who values genuine connection over superficial attraction alone"
  ],
  "adventurous": [
    "someone who's down for spontaneous adventures and last minute plans 🌟",
    "a partner who loves trying new things even when scary",
    "someone who's open to exploring new places and experiences with",
    "a person who has adventurous energy and loves to travel",
    "someone who's willing to step outside comfort zone with me",
    "a partner who loves trying new foods from different cultures",
    "someone who's spontaneous and doesn't need everything planned out always",
    "a person who's down for outdoor activities and nature adventures",
    "someone who loves road trips and exploring new places together",
    "a partner who's open to saying yes to random opportunities",
    "someone who has wanderlust and wants to see the world",
    "a person who's willing to take risks and see where",
    "someone who loves making memories through experiences not just things",
    "a partner who's excited about trying new activities together always",
    "someone who's spontaneous with weekend plans and goes with flow",
    "a person who loves exploring and discovering hidden gems everywhere",
    "someone who's down for adventure dates instead of just dinner",
    "a partner who's open to travel and experiencing different cultures",
    "someone who loves being active and trying new outdoor activities",
    "a person who's excited about making every day an adventure"
  ],
  "quirky": [
    "someone who's unapologetically themselves even when it's weird or different 🎨",
    "a partner who appreciates my quirks and adds their own",
    "someone who's okay with being different and standing out always",
    "a person who has niche interests they're passionate about sharing",
    "someone who's comfortable with their weirdness and doesn't hide it",
    "a partner who appreciates unconventional and finds beauty in strange",
    "someone who's authentically odd and owns every bit of uniqueness",
    "a person who has unique perspective on things that fascinates",
    "someone who's okay with deep weird conversations at 3am honestly",
    "a partner who celebrates what makes them different not hides",
    "someone who's perfectly imperfect and embraces all their quirks oddities",
    "a person who has obscure references only certain people understand",
    "someone who's comfortable being themselves even when doesn't make sense",
    "a partner who appreciates my oddities and doesn't try changing",
    "someone who's weird in the best way possible and owns",
    "a person who has quirky habits that make them memorable",
    "someone who's okay with being eccentric and not fitting molds",
    "a partner who celebrates our differences and things that make",
    "someone who's authentically themselves without worrying what others think about",
    "a person who appreciates weird humor and has their own"
  ],
  "serious": [
    "someone who's emotionally mature and communicates like an actual adult",
    "a partner who has their life together and works toward",
    "someone who's honest about intentions and what they're looking for",
    "a person who respects boundaries and understands they exist for",
    "someone who's reliable and does what they say they'll do",
    "a partner who takes accountability instead of making excuses always",
    "someone who's looking for something real and meaningful not casual",
    "a person who respects my time and doesn't waste it",
    "someone who's financially responsible and has plan for their future",
    "a partner who's consistent with words and actions I trust",
    "someone who takes relationships seriously and puts in the effort",
    "a person who's emotionally available and ready for real connection",
    "someone who respects my career and ambitions as their own",
    "a partner who's mature enough to handle difficult conversations without",
    "someone who takes my feelings seriously and doesn't dismiss them",
    "a person I can count on through good times and",
    "someone who respects my standards because I set them for",
    "a partner who's honest about past and learned from it",
    "someone who's ready for commitment not just casual dating temporary",
    "a person who respects me as equal partner in everything"
  ],
  "intellectual": [
    "someone who enjoys deep conversations beyond surface level topics always 🧠",
    "a partner who's intellectually curious and wants to learn things",
    "someone who's open to different perspectives and willing to change",
    "a person who enjoys thoughtful discussions that challenge our thinking",
    "someone who's well read and has interesting thoughts on topics",
    "a partner who asks questions and wants to understand deeply",
    "someone who's open minded and willing to learn from anyone",
    "a person who enjoys debates without getting defensive or personal",
    "someone who's curious about world and wants to understand it",
    "a partner who has well thought out opinions based on",
    "someone who's intellectually stimulating and makes me think in ways",
    "a person who's interested in learning together and exploring ideas",
    "someone who enjoys meaningful discussions about topics that matter to",
    "a partner who's thoughtful and considers different angles before opinions",
    "someone who's curious about my thoughts and perspectives on things",
    "a person who engages with ideas seriously not dismissing them",
    "someone who's intellectually honest and admits when doesn't know something",
    "a partner who enjoys interesting engaging conversations not just small",
    "someone who's open to having views challenged in good ways",
    "a person who values intellectual connection as much as emotional"
  ],
  "default": [
    "someone who's kind and treats everyone with respect always ✨",
    "a partner who's genuine and authentic in how they present",
    "someone who makes me feel comfortable being myself completely around",
    "a person who's a good listener and hears what I",
    "someone who's consistent and I can count on through everything",
    "a partner who's honest and communicates openly even when difficult",
    "someone who makes me laugh and brings joy into life",
    "a person who's supportive of my goals and dreams always",
    "someone who respects my boundaries and understands they exist for",
    "a partner who's patient and understanding with me through everything",
    "someone who makes me feel valued and appreciated for who",
    "a person who's emotionally available and present when together not",
    "someone who shows love through actions not just empty words",
    "a partner who's reliable and follows through on what says",
    "someone who makes me feel safe and comfortable being vulnerable",
    "a person who's thoughtful and does little things showing care",
    "someone who respects me and treats me well consistently always",
    "a partner who makes me want to be better every",
    "someone who makes me feel like I matter and feelings",
    "a person who's genuine about intentions and what wants from"
  ]
};

module.exports = imLookingFor;
