const weirdlyAttractedTo = {
  funny: [
    "people who laugh at their own jokes before finishing them",
    "guys who get way too competitive at mini golf",
    "someone who does terrible celebrity impressions but commits fully",
    "people who talk to animals like they will actually respond",
    "guys who get genuinely excited about their favorite snacks",
    "someone who dances badly but with full confidence in public",
    "people who make sound effects for everything they do",
    "guys who have strong opinions about the best pizza toppings",
    "someone who laughs at the wrong times during movies",
    "people who create elaborate backstories for random strangers",
    "guys who get overly invested in reality TV drama",
    "someone who does a little victory dance after small wins",
    "people who have a signature dad joke they tell everyone",
    "guys who narrate their actions like a sports commentator",
    "someone who makes up songs about whatever they are doing",
    "people who have weirdly strong feelings about breakfast foods",
    "guys who do funny voices when reading texts out loud",
    "someone who gets way too serious about board game strategy",
    "people who have a specific way they eat certain foods",
    "guys who laugh so hard they snort and get embarrassed",
  ],
  romantic: [
    "the way someone looks at me when they think I am not looking",
    "guys who remember tiny details from conversations weeks ago",
    "someone who leaves little notes in unexpected places for me",
    "people who get shy when giving compliments but do it anyway",
    "guys who have a soft spot for old love songs",
    "someone whose eyes light up when they talk about me",
    "people who hold doors and do small gestures without thinking",
    "guys who are not afraid to be vulnerable and emotionally open",
    "someone who makes me feel safe just by being near",
    "people who give the best hugs that last just right",
    "guys who text good morning without me asking them to",
    "someone who looks at me like I am their favorite person",
    "people who remember how I like my coffee or tea",
    "guys who play with my hair absentmindedly while we talk",
    "someone who makes me laugh when I am trying to be serious",
    "people who check in just to make sure I am okay",
    "guys who are not too cool to hold my hand in public",
    "someone who makes ordinary moments feel special and meaningful",
    "people who listen like what I am saying actually matters",
    "guys who make me feel chosen every single day",
  ],
  adventurous: [
    "people who suggest spontaneous road trips on random weeknights",
    "guys who are not afraid to try the weird food options",
    "someone who gets excited about exploring new places with me",
    "people who say yes before asking where we are going",
    "guys who have a whole bucket list ready to go",
    "someone who does not need a plan to have fun adventures",
    "people who get genuinely excited about trying new experiences",
    "guys who are not scared of a little adventure and risk",
    "someone who matches my energy for spontaneous weekend getaways",
    "people who find beauty in unexpected places we discover",
    "guys who suggest hiking at sunrise without complaining",
    "someone who treats every day like a potential new adventure",
    "people who are not afraid to get lost and find their way",
    "guys who have passport stamps and stories to share",
    "someone who sees obstacles as part of the fun challenge",
    "people who pack light and adapt to whatever comes next",
    "guys who suggest the scenic route instead of fastest way",
    "someone who collects experiences instead of just taking pictures",
    "people who are not afraid to look silly trying new things",
    "guys who make even grocery shopping feel like an adventure",
  ],
  quirky: [
    "people who have very specific and weird pet peeves",
    "guys who collect something totally random that nobody understands",
    "someone who has a comfort show they have watched way too many times",
    "people who do things in a weirdly specific order always",
    "guys who have strong opinions about fonts and design choices",
    "someone who names inanimate objects and gets attached to them",
    "people who have an oddly extensive knowledge about random topics",
    "guys who get excited about office supplies and organization systems",
    "someone who has a very particular morning routine they follow",
    "people who make up their own words for things",
    "guys who have a signature outfit formula they always wear",
    "someone who talks to themselves while doing tasks out loud",
    "people who have weirdly specific comfort foods nobody else gets",
    "guys who organize things in ways that only make sense to them",
    "someone who has a playlist for every possible mood",
    "people who notice tiny details that everyone else completely misses",
    "guys who have a lucky item they bring everywhere",
    "someone who does things the hard way just because they want to",
    "people who have inside jokes with themselves that crack them up",
    "guys who get unreasonably excited about their niche interests",
  ],
  serious: [
    "people who have clear boundaries and communicate them directly",
    "guys who take accountability without making excuses for their actions",
    "someone who values growth over being right in every argument",
    "people who show up consistently not just when it is convenient",
    "guys who have emotional intelligence and are not afraid to use it",
    "someone who means what they say and follows through always",
    "people who can handle difficult conversations without shutting down",
    "guys who respect my time and energy as much as their own",
    "someone who has clear goals and works toward them daily",
    "people who value honesty even when the truth is uncomfortable",
    "guys who take relationships seriously and invest in them intentionally",
    "someone who understands that actions speak louder than words",
    "people who have integrity and stick to their values consistently",
    "guys who can admit when they are wrong and actually change",
    "someone who values depth over surface level connections",
    "people who show love through consistent effort not just words",
    "guys who have self awareness and work on themselves actively",
    "someone who respects my independence while wanting to be close",
    "people who understand that trust is earned not just given",
    "guys who match my energy and commitment level in relationships",
  ],
  intellectual: [
    "people who can explain complex topics in simple terms",
    "guys who get excited about learning new things every day",
    "someone who asks thoughtful questions instead of just talking",
    "people who can debate without getting defensive or emotional",
    "guys who read books and actually remember what they read",
    "someone who makes unexpected connections between random concepts",
    "people who have curiosity about how everything works",
    "guys who can admit when they do not know something",
    "someone who challenges my perspective in respectful thoughtful ways",
    "people who listen to understand not just to respond",
    "guys who have opinions backed by actual research and thought",
    "someone who finds learning attractive and makes it fun",
    "people who can hold deep conversations about literally anything",
    "guys who appreciate nuance and do not think in black and white",
    "someone who values knowledge but does not act superior about it",
    "people who ask why until they really understand something",
    "guys who can make intellectual topics feel accessible and engaging",
    "someone who has interesting theories about random everyday observations",
    "people who remember details from conversations we had months ago",
    "guys who get excited about ideas not just things",
  ],
};

module.exports = weirdlyAttractedTo;
