const weirdlyAttractedTo = {
  funny: [
    "people who laugh at their own jokes before finishing them",
    "guys who get way too competitive at mini golf honestly",
    "someone who does terrible celebrity impressions but commits fully to",
    "people who talk to animals like theyll actually respond back",
    "guys who get genuinely excited about their favorite snacks and",
    "someone who dances badly but with full confidence in public",
    "people who make sound effects for everything they do daily",
    "guys who have strong opinions about the best pizza toppings",
    "someone who laughs at the wrong times during movies always",
    "people who create elaborate backstories for random strangers we see",
    "guys who get overly invested in reality tv show drama",
    "someone who does a little victory dance after small wins",
    "people who have a signature dad joke they tell everyone",
    "guys who narrate their actions like a sports commentator sometimes",
    "someone who makes up songs about whatever theyre doing currently",
    "people who have weirdly strong feelings about breakfast foods honestly",
    "guys who do funny voices when reading texts out loud",
    "someone who gets way too serious about board game strategy",
    "people who have a specific way they eat certain foods",
    "guys who laugh so hard they snort and get embarrassed",
  ],
  romantic: [
    "the way someone looks at me when they think im",
    "guys who remember tiny details from conversations weeks ago sweetly",
    "someone who leaves little notes in unexpected places for me",
    "people who get shy when giving compliments but do it",
    "guys who have a soft spot for old love songs",
    "someone whose eyes light up when they talk about me",
    "people who hold doors and do small gestures without thinking",
    "guys who arent afraid to be vulnerable and emotionally open",
    "someone who makes me feel safe just by being near",
    "people who give the best hugs that last just right",
    "guys who text good morning without me asking them to",
    "someone who looks at me like im their favorite person",
    "people who remember how i like my coffee or tea",
    "guys who play with my hair absentmindedly while we talk",
    "someone who makes me laugh when im trying to serious",
    "people who check in just to make sure im okay",
    "guys who arent too cool to hold my hand in public",
    "someone who makes ordinary moments feel special and meaningful together",
    "people who listen like what im saying actually matters deeply",
    "guys who make me feel chosen every single day consistently",
  ],
  adventurous: [
    "people who suggest spontaneous road trips on random weeknights boldly",
    "guys who arent afraid to try the weirdest food options",
    "someone who gets excited about exploring new places with me",
    "people who say yes before asking where were going exactly",
    "guys who have a whole bucket list ready to go",
    "someone who doesnt need a plan to have fun adventures",
    "people who get genuinely excited about trying new experiences always",
    "guys who arent scared of a little adventure and risk",
    "someone who matches my energy for spontaneous weekend getaways together",
    "people who find beauty in unexpected places we randomly discover",
    "guys who suggest hiking at sunrise without complaining about waking",
    "someone who treats every day like a potential new adventure",
    "people who arent afraid to get lost and find way",
    "guys who have passport stamps and stories to share excitedly",
    "someone who sees obstacles as part of the fun challenge",
    "people who pack light and adapt to whatever comes next",
    "guys who suggest the scenic route instead of fastest way",
    "someone who collects experiences instead of just taking pictures only",
    "people who arent afraid to look silly trying new things",
    "guys who make even grocery shopping feel like an adventure",
  ],
  quirky: [
    "people who have very specific and weird pet peeves honestly",
    "guys who collect something totally random that nobody understands why",
    "someone who has a comfort show theyve watched way too",
    "people who do things in a weirdly specific order always",
    "guys who have strong opinions about fonts and design choices",
    "someone who names inanimate objects and gets attached to them",
    "people who have an oddly extensive knowledge about random topics",
    "guys who get excited about office supplies and organization systems",
    "someone who has a very particular morning routine they follow",
    "people who make up their own words for things regularly",
    "guys who have a signature outfit formula they always wear",
    "someone who talks to themselves while doing tasks out loud",
    "people who have weirdly specific comfort foods nobody else gets",
    "guys who organize things in ways that only make sense",
    "someone who has a playlist for every possible mood and",
    "people who notice tiny details that everyone else completely misses",
    "guys who have a lucky item they bring everywhere with",
    "someone who does things the hard way just because they",
    "people who have inside jokes with themselves that crack up",
    "guys who get unreasonably excited about their niche interests passionately",
  ],
  serious: [
    "people who have clear boundaries and communicate them directly always",
    "guys who take accountability without making excuses for their actions",
    "someone who values growth over being right in every argument",
    "people who show up consistently not just when its convenient",
    "guys who have emotional intelligence and arent afraid to use",
    "someone who means what they say and follows through always",
    "people who can handle difficult conversations without shutting down completely",
    "guys who respect my time and energy as much as",
    "someone who has clear goals and works toward them daily",
    "people who value honesty even when the truth is uncomfortable",
    "guys who take relationships seriously and invest in them intentionally",
    "someone who understands that actions speak louder than words always",
    "people who have integrity and stick to their values consistently",
    "guys who can admit when theyre wrong and actually change",
    "someone who values depth over surface level connections every time",
    "people who show love through consistent effort not just words",
    "guys who have self awareness and work on themselves actively",
    "someone who respects my independence while wanting to be close",
    "people who understand that trust is earned not just given",
    "guys who match my energy and commitment level in relationships",
  ],
  intellectual: [
    "people who can explain complex topics in simple terms clearly",
    "guys who get excited about learning new things every day",
    "someone who asks thoughtful questions instead of just talking always",
    "people who can debate without getting defensive or emotional quickly",
    "guys who read books and actually remember what they read",
    "someone who makes unexpected connections between random concepts brilliantly here",
    "people who have curiosity about how everything works around them",
    "guys who can admit when they dont know something honestly",
    "someone who challenges my perspective in respectful thoughtful ways always",
    "people who listen to understand not just to respond back",
    "guys who have opinions backed by actual research and thought",
    "someone who finds learning attractive and makes it fun together",
    "people who can hold deep conversations about literally anything interesting",
    "guys who appreciate nuance and dont think in black white",
    "someone who values knowledge but doesnt act superior about it",
    "people who ask why until they really understand something deeply",
    "guys who can make intellectual topics feel accessible and engaging",
    "someone who has interesting theories about random everyday observations here",
    "people who remember details from conversations we had months ago",
    "guys who get excited about ideas not just things or",
  ],
};

module.exports = weirdlyAttractedTo;
