const iRecentlyDiscoveredThat = {
  "funny": [
    "I can't adult as well as I thought I could 😂",
    "naps are even better as an adult than as a",
    "I'm not a morning person and never will be honestly",
    "my metabolism is not what it used to be at",
    "I need way more sleep than I'm currently getting daily",
    "coffee is a personality trait and I'm okay with that",
    "I'm allergic to mornings and there's no cure for it",
    "my body makes weird noises now that it didn't before",
    "I can't eat like I did in college anymore",
    "staying in is way more fun than going out honestly",
    "I'm becoming my parents and there's nothing I can do",
    "hangovers last way longer than they used to back then",
    "I need reading glasses and I'm not ready for that",
    "my back hurts for no reason and that's just life",
    "I get excited about kitchen appliances and that's concerning to",
    "I can't stay up late anymore without regretting it",
    "my idea of a wild night is being in bed",
    "I make the same sounds as my dad when sitting",
    "I'm too old for this but doing it anyway honestly",
    "adulting is just googling how to do everything constantly always"
  ],
  "romantic": [
    "I'm ready for something real and not just casual anymore ❤️",
    "love languages are actually really important in relationships and connection always",
    "I deserve someone who chooses me every single day consistently",
    "communication is literally the most important thing in any relationship ever",
    "I'm capable of loving deeper than I ever thought possible",
    "vulnerability is strength not weakness in relationships with people I trust",
    "I need someone who matches my energy and effort equally",
    "actions speak louder than words when it comes to love",
    "I'm not afraid to be alone until I find right",
    "healthy relationships shouldn't feel like constant work or struggle always",
    "I know what I want and won't settle for less",
    "emotional availability is non negotiable for me in relationships now",
    "I'm worthy of the love I give to other people",
    "compatibility matters more than chemistry in the long run honestly",
    "I need someone who supports my growth not holds me",
    "love should feel safe and secure not anxious and uncertain",
    "I'm ready to build something real with the right person",
    "my standards aren't too high they're just protecting my peace",
    "I deserve someone who's excited about me not lukewarm or",
    "real love is consistent not just intense in the beginning"
  ],
  "adventurous": [
    "I'm braver than I give myself credit for honestly 🌟",
    "saying yes to new experiences changes everything in the best",
    "I'm capable of way more than I thought I was",
    "comfort zones are meant to be pushed and expanded regularly",
    "spontaneity makes life so much more interesting and fun always",
    "I thrive when I'm trying new things and taking risks",
    "travel changes you in ways you can't even imagine before",
    "I'm happiest when I'm exploring and experiencing new things daily",
    "fear is just excitement in disguise most of the time",
    "I need adventure and new experiences to feel truly alive",
    "the best memories come from unplanned spontaneous moments and adventures",
    "I'm more adventurous than I ever thought I could be",
    "trying new things is how I figure out who I",
    "I need variety and change to feel fulfilled in life",
    "stepping outside my comfort zone is where growth happens always",
    "I'm capable of adapting to any situation thrown at me",
    "adventure is a mindset not just about traveling to places",
    "I feel most alive when I'm doing something new",
    "taking risks is worth it even when things don't work",
    "I need experiences not things to feel happy and fulfilled"
  ],
  "quirky": [
    "I'm way weirder than people initially think I am 🎨",
    "my niche interests are actually what make me interesting to",
    "being different is way better than being like everyone else",
    "my quirks are my best features not things to hide",
    "normal is overrated and I'm perfectly fine being odd honestly",
    "the right people appreciate my weirdness and that's all that",
    "I'm most myself when I'm being authentically weird and",
    "my strange interests connect me with the coolest people ever",
    "being eccentric is more fun than trying to fit in",
    "my oddities are what make me memorable to other people",
    "weird is just another word for interesting and unique honestly",
    "I'm happiest when I'm embracing my unconventional side fully",
    "my quirky habits are actually coping mechanisms that work for",
    "being authentically myself attracts the right kind of people always",
    "my weirdness is a filter for finding my kind of",
    "I don't want to be normal and that's perfectly okay",
    "my niche hobbies bring me more joy than mainstream ones",
    "being different is my superpower not something to be ashamed",
    "the people who get my weirdness are my favorite people",
    "I'm perfectly imperfect and that's what makes me interesting honestly"
  ],
  "serious": [
    "I'm stronger than I ever gave myself credit for being",
    "my mental health is just as important as my physical",
    "setting boundaries is necessary not selfish like I thought before",
    "I can't pour from an empty cup and self care",
    "therapy is one of the best investments I've made in",
    "I'm responsible for my own happiness not anyone else's job",
    "not everyone deserves access to me and that's perfectly okay",
    "I need to prioritize myself more than I have been",
    "growth is uncomfortable but necessary for becoming who I want",
    "I can't control everything and that's actually freeing to accept",
    "my worth isn't determined by my productivity or accomplishments at",
    "I deserve rest without feeling guilty about taking it honestly",
    "saying no is a complete sentence and needs no explanation",
    "I'm allowed to outgrow people and relationships that no longer",
    "my peace is more important than pleasing everyone around me",
    "I can't change people who don't want to change themselves",
    "investing in myself is the best thing I can do",
    "I'm doing better than I think I am most days",
    "healing isn't linear and that's okay to accept and understand",
    "I'm worthy of the same love and care I give"
  ],
  "intellectual": [
    "I don't know as much as I thought I did 🧠",
    "being wrong is actually an opportunity to learn and grow",
    "my perspective is limited by my experiences and that's okay",
    "asking questions is smarter than pretending to know everything about",
    "I have so much more to learn about literally everything",
    "intellectual humility is more valuable than being right all the",
    "my biases affect my thinking more than I realized before",
    "listening is more important than always having something to say",
    "I'm capable of changing my mind when presented with evidence",
    "curiosity is more valuable than knowledge in the long run honestly",
    "I don't have to have an opinion on everything always",
    "being open minded means actually considering perspectives different from mine",
    "I learn more from being wrong than from being right",
    "my education is never finished and that's exciting not scary",
    "questioning my assumptions leads to better understanding of things around",
    "I'm smarter when I admit what I don't know",
    "reading diverse perspectives has changed how I see the world",
    "I'm more ignorant than I thought and that's humbling honestly",
    "learning is a lifelong process not something that ends with",
    "my worldview is constantly evolving and that's a good thing"
  ],
  "default": [
    "I'm doing better than I give myself credit for ✨",
    "small steps forward are still progress even when they feel",
    "I'm stronger and more resilient than I ever realized before",
    "it's okay to not have everything figured out right now",
    "I'm exactly where I need to be in my journey",
    "growth happens slowly and that's perfectly okay to accept honestly",
    "I'm capable of more than I ever thought possible before",
    "taking care of myself isn't selfish it's absolutely necessary always",
    "I deserve good things and don't need to earn them",
    "my journey is unique and I shouldn't compare it to",
    "I'm learning and growing every single day even when unnoticed",
    "it's okay to ask for help when I need it",
    "I'm worthy of love respect and kindness from everyone around",
    "my feelings are valid even when others don't understand them",
    "I'm doing the best I can with what I have",
    "progress isn't always visible but it's still happening every day",
    "I'm allowed to change my mind and grow as a",
    "my worth isn't determined by other people's opinions of me",
    "I'm more resilient than I ever gave myself credit for",
    "it's okay to prioritize my own happiness and wellbeing always"
  ]
};

module.exports = iRecentlyDiscoveredThat;
