const iUnwindBy = {
  funny: [
    "watching reality TV and judging peoples life choices",
    "scrolling through memes until I forget what time it is",
    "talking to my plants like they are my therapist",
    "making snacks I do not need but absolutely deserve",
    "watching cooking shows while eating takeout on my couch",
    "doing online shopping and abandoning my cart every time",
    "reorganizing my room at midnight for no good reason",
    "watching animal videos until my face hurts from smiling",
    "having full conversations with my pet about my day",
    "making playlists I will listen to once then forget",
    "watching the same comfort show for the hundredth time",
    "doing face masks and pretending I am at a spa",
    "scrolling through old photos and cringing at past fashion",
    "making elaborate plans I probably will not follow through with",
    "watching fails compilations and feeling better about my life",
    "organizing things that do not need organizing",
    "reading reviews of products I will never actually buy",
    "watching true crime and double checking all my door locks",
    "making midnight snacks that are way too elaborate",
    "doing absolutely nothing and feeling zero guilt about it",
  ],
  romantic: [
    "reading romance novels that make me believe in love",
    "taking long walks while daydreaming about my future",
    "listening to love songs and thinking about someone special",
    "writing in my journal about all the good things",
    "watching sunset and feeling grateful for the little moments",
    "calling someone who makes me smile just to hear their voice",
    "looking through old photos and messages that make my heart full",
    "lighting candles and creating a cozy peaceful atmosphere",
    "listening to our playlist and replaying my favorite memories",
    "stargazing and thinking about all the possibilities ahead",
    "taking bubble baths with soft music playing in background",
    "cuddling up with a good book and warm blanket",
    "watching romantic movies that make me cry happy tears",
    "writing letters I might never send but need to write",
    "spending quality time with people I love most",
    "making comfort food that reminds me of happy times",
    "watching old home videos and feeling nostalgic",
    "having deep conversations that last until way too late",
    "doing small acts of kindness that make me feel good",
    "planning future adventures with someone I care about deeply",
  ],
  adventurous: [
    "planning my next trip and getting lost in travel dreams",
    "going for late night drives with no destination",
    "trying a new hiking trail I found online",
    "exploring random parts of the city I have never been",
    "booking spontaneous weekend getaways to places I have never visited",
    "researching adventure activities I want to try next month",
    "going for runs in new neighborhoods to explore",
    "planning road trips with way too many stops",
    "trying new restaurants and cuisines I have never experienced",
    "watching travel documentaries and adding places to my bucket list",
    "going to random events I find online last minute",
    "taking different routes home just to see what is there",
    "planning outdoor activities for the upcoming weekend",
    "exploring nature trails and finding hidden spots",
    "trying new workout classes that push me out of comfort",
    "going to farmers markets and trying all the samples",
    "researching adrenaline activities I can do near me",
    "taking spontaneous day trips to nearby towns",
    "going for bike rides and discovering new paths",
    "planning my next big adventure while recovering from last",
  ],
  quirky: [
    "organizing my bookshelf by color then immediately regretting it",
    "making Spotify playlists with oddly specific themes and vibes",
    "rearranging my furniture until it feels just right",
    "watching video essays about topics I never knew interested me",
    "doing jigsaw puzzles while listening to murder mystery podcasts",
    "making lists of things that do not need to be listed",
    "learning random skills from YouTube at two in the morning",
    "color coding my entire life including my Google calendar",
    "watching documentaries about the most random niche topics",
    "doing craft projects I saw online and probably will not finish",
    "researching conspiracy theories I do not actually believe in",
    "making mood boards for aesthetics I will never actually achieve",
    "organizing my closet by season and then by vibe",
    "watching restoration videos of old things being fixed perfectly",
    "doing personality quizzes to confirm what I already know",
    "learning about topics through Wikipedia rabbit holes for hours",
    "making elaborate to do lists that are color coded",
    "watching people clean and organize on social media satisfyingly",
    "researching random historical events that fascinate me for hours",
    "doing those oddly satisfying repetitive tasks that calm me",
  ],
  serious: [
    "journaling and processing my thoughts and feelings",
    "meditating and practicing mindfulness to center myself",
    "reading self development books that challenge my perspective",
    "going for quiet walks alone to clear my head",
    "doing yoga and focusing on my breath and body",
    "setting boundaries with my time and energy",
    "reflecting on my goals and progress I have made",
    "having honest conversations with myself about what I need",
    "practicing gratitude and acknowledging the good in my life",
    "doing therapy homework and working on personal growth",
    "disconnecting from social media and being present with myself",
    "reading and learning about topics that matter to me",
    "organizing my space to create a peaceful calm environment",
    "working on hobbies that bring me genuine joy",
    "spending intentional quality time with people who matter most",
    "processing emotions through writing or creative expression",
    "setting intentions for the next day and week ahead",
    "doing self care routines that actually nourish me",
    "reflecting on my values and whether I am living aligned",
    "creating space for rest without guilt or productivity pressure",
  ],
  intellectual: [
    "reading books that challenge my current way of thinking",
    "listening to podcasts about philosophy psychology or science",
    "watching documentaries that teach me something completely new",
    "writing and exploring ideas I have been thinking about",
    "researching topics that sparked my curiosity during the day",
    "doing puzzles or brain games that actually challenge me",
    "reading articles about current events and forming my opinions",
    "listening to lectures or talks from experts",
    "learning a new skill through online courses or tutorials",
    "having deep conversations about ideas that matter",
    "reading poetry or literature that makes me think differently",
    "exploring new perspectives through books from different cultures",
    "watching TED talks about topics outside my usual interests",
    "writing essays or thoughts about concepts I am trying to understand",
    "learning about history and connecting it to present day",
    "reading scientific studies about things I find fascinating",
    "listening to music and analyzing the lyrics and composition",
    "exploring philosophical questions that do not have easy answers",
    "reading biographies of people who changed the world",
    "learning languages or studying linguistics just for fun",
  ],
};

module.exports = iUnwindBy;
