const iUnwindBy = {
  funny: [
    "watching reality tv and judging peoples life choices loudly",
    "scrolling through memes until i forget what time it is",
    "talking to my plants like theyre my therapist honestly",
    "making snacks i dont need but absolutely deserve right now",
    "watching cooking shows while eating takeout on my couch",
    "doing online shopping and abandoning my cart every single time",
    "reorganizing my room at midnight for no good reason",
    "watching animal videos until my face hurts from smiling hard",
    "having full conversations with my pet about my day today",
    "making playlists i'll listen to once then forget about completely",
    "watching the same comfort show for the hundredth time",
    "doing face masks and pretending im at a fancy spa",
    "scrolling through old photos and cringing at past fashion",
    "making elaborate plans i probably wont follow through with",
    "watching fails compilations and feeling better about my life",
    "organizing things that dont need organizing at all honestly",
    "reading reviews of products ill never actually buy online",
    "watching true crime and double checking all my door locks",
    "making midnight snacks that are way too elaborate for",
    "doing absolutely nothing and feeling zero guilt about it",
  ],
  romantic: [
    "reading romance novels that make me believe in love again",
    "taking long walks while daydreaming about my future together",
    "listening to love songs and thinking about someone special always",
    "writing in my journal about all the good things lately",
    "watching sunset and feeling grateful for the little moments here",
    "calling someone who makes me smile just to hear voice",
    "looking through old photos and messages that make heart",
    "lighting candles and creating a cozy peaceful atmosphere at home",
    "listening to our playlist and replaying my favorite memories together",
    "stargazing and thinking about all the possibilities ahead of us",
    "taking bubble baths with soft music playing in background quietly",
    "cuddling up with a good book and warm blanket",
    "watching romantic movies that make me cry happy tears always",
    "writing letters i might never send but need to write",
    "spending quality time with people i love most in",
    "making comfort food that reminds me of happy times",
    "watching old home videos and feeling nostalgic about everything",
    "having deep conversations that last until way too late",
    "doing small acts of kindness that make me feel",
    "planning future adventures with someone i care about deeply",
  ],
  adventurous: [
    "planning my next trip and getting lost in travel",
    "going for late night drives with no destination in",
    "trying a new hiking trail i found on the",
    "exploring random parts of the city ive never been",
    "booking spontaneous weekend getaways to places ive never visited before",
    "researching adventure activities i want to try next month",
    "going for runs in new neighborhoods to explore around",
    "planning road trips with way too many stops along",
    "trying new restaurants and cuisines ive never experienced before today",
    "watching travel documentaries and adding places to my bucket",
    "going to random events i find online last minute",
    "taking different routes home just to see whats there",
    "planning outdoor activities for the upcoming weekend adventures together",
    "exploring nature trails and finding hidden spots nobody knows",
    "trying new workout classes that push me out of",
    "going to farmers markets and trying all the samples",
    "researching adrenaline activities i can do near me soon",
    "taking spontaneous day trips to nearby towns ive never",
    "going for bike rides and discovering new paths around",
    "planning my next big adventure while recovering from last",
  ],
  quirky: [
    "organizing my bookshelf by color then immediately regretting it",
    "making spotify playlists with oddly specific themes and vibes",
    "rearranging my furniture until it feels just right finally",
    "watching video essays about topics i never knew interested",
    "doing jigsaw puzzles while listening to murder mystery podcasts",
    "making lists of things that dont need to be",
    "learning random skills from youtube at two in morning",
    "color coding my entire life including my google calendar",
    "watching documentaries about the most random niche topics ever",
    "doing craft projects i saw online and probably wont",
    "researching conspiracy theories i dont actually believe in honestly",
    "making mood boards for aesthetics ill never actually achieve",
    "organizing my closet by season and then by vibe",
    "watching restoration videos of old things being fixed perfectly",
    "doing personality quizzes to confirm what i already know",
    "learning about topics through wikipedia rabbit holes for hours",
    "making elaborate to do lists that are color coded",
    "watching people clean and organize on social media satisfyingly",
    "researching random historical events that fascinate me for hours",
    "doing those oddly satisfying repetitive tasks that calm me",
  ],
  serious: [
    "journaling and processing my thoughts and feelings from today",
    "meditating and practicing mindfulness to center myself again here",
    "reading self development books that challenge my perspective daily",
    "going for quiet walks alone to clear my head",
    "doing yoga and focusing on my breath and body",
    "setting boundaries with my time and energy for tomorrow",
    "reflecting on my goals and progress ive made recently",
    "having honest conversations with myself about what i need",
    "practicing gratitude and acknowledging the good in my life",
    "doing therapy homework and working on personal growth actively",
    "disconnecting from social media and being present with myself",
    "reading and learning about topics that matter to me",
    "organizing my space to create a peaceful calm environment",
    "working on hobbies that bring me genuine joy and",
    "spending intentional quality time with people who matter most",
    "processing emotions through writing or creative expression honestly here",
    "setting intentions for the next day and week ahead",
    "doing self care routines that actually nourish me deeply",
    "reflecting on my values and whether im living aligned",
    "creating space for rest without guilt or productivity pressure",
  ],
  intellectual: [
    "reading books that challenge my current way of thinking",
    "listening to podcasts about philosophy psychology or science topics",
    "watching documentaries that teach me something completely new today",
    "writing and exploring ideas ive been thinking about lately",
    "researching topics that sparked my curiosity during the day",
    "doing puzzles or brain games that actually challenge me",
    "reading articles about current events and forming my opinions",
    "listening to lectures or talks from experts in various",
    "learning a new skill through online courses or tutorials",
    "having deep conversations about ideas that matter to me",
    "reading poetry or literature that makes me think differently",
    "exploring new perspectives through books from different cultures always",
    "watching ted talks about topics outside my usual interests",
    "writing essays or thoughts about concepts im trying to",
    "learning about history and connecting it to present day",
    "reading scientific studies about things i find fascinating currently here",
    "listening to music and analyzing the lyrics and composition",
    "exploring philosophical questions that dont have easy answers at",
    "reading biographies of people who changed the world somehow",
    "learning languages or studying linguistics just for fun honestly",
  ],
};

module.exports = iUnwindBy;
