const iWantSomeoneWho = {
  "funny": [
    "laughs at my terrible jokes even when they're really bad 😂",
    "doesn't judge me for eating cereal at midnight like a",
    "lets me nap whenever I want without any questions asked",
    "appreciates my chaotic energy and adds to it not tones",
    "understands that I'm not a morning person and never will",
    "shares their food with me which is basically true love",
    "makes everything fun even boring tasks like doing laundry together",
    "doesn't take life too seriously and laughs at everything with",
    "lets me be dramatic without calling me out for it",
    "brings me snacks without me even having to ask for",
    "matches my meme energy and sends me good ones back",
    "appreciates my sarcasm and dishes it right back at me",
    "makes me laugh when I'm having the absolute worst day",
    "understands my need for twelve hours of sleep to function",
    "doesn't judge my comfort shows that I've watched a million",
    "lets me sleep in on weekends without making me feel",
    "is goofy and silly with me without worrying about looking",
    "appreciates my weird sense of humor and contributes their own",
    "makes ordinary moments fun just by being their authentic self",
    "gets my random references and makes their own that I"
  ],
  "romantic": [
    "chooses me every single day not just in the beginning ❤️",
    "makes me feel safe enough to be completely vulnerable with",
    "remembers small details I mention and brings them up later",
    "is emotionally available and communicates openly about their feelings always",
    "shows love through actions not just empty words they say",
    "makes me feel like a priority in their life not",
    "is affectionate without me having to ask for it constantly",
    "supports my dreams and believes in me even when I",
    "makes me laugh and smile even on my worst days",
    "is patient with me when I'm going through difficult times",
    "is vulnerable and open about their feelings with me too",
    "makes me feel beautiful even when I'm in sweats",
    "listens when I talk and actually remembers what I said",
    "is thoughtful and does little things that show they care",
    "makes me feel heard and understood on a deep level",
    "is consistent so I know I can trust them completely",
    "shows up for me when I need them most without",
    "makes me feel cherished and appreciated for exactly who I",
    "is my best friend and partner at the same time",
    "loves me for who I am not who they want"
  ],
  "adventurous": [
    "is spontaneous and says yes to random adventures with me 🌟",
    "tries new things together even when they're scary or unknown",
    "is down for last minute road trips with no plan",
    "matches my energy and enthusiasm for exploring new places always",
    "is willing to step outside their comfort zone with me",
    "says yes to adventures and makes memories we'll never forget",
    "is open to trying new foods and experiences without complaining",
    "has that wanderlust energy that matches mine perfectly and completely",
    "is spontaneous and doesn't need everything planned out in advance",
    "is excited about exploring and discovering new things together always",
    "is willing to get lost and find our way back",
    "has a sense of adventure and isn't afraid to try",
    "is down for outdoor activities and nature adventures with me",
    "is open to travel and experiencing different cultures together always",
    "is willing to take risks and see where they lead",
    "has that adventurous spirit that makes life so much more",
    "is excited about trying activities we've never done before together",
    "is spontaneous with plans and goes with the flow always",
    "is willing to explore off the beaten path with me",
    "has that energy that makes every day feel like an"
  ],
  "quirky": [
    "appreciates my weirdness and adds their own to the mix 🎨",
    "is authentically themselves even when it's odd or different from",
    "gets my obscure references and makes their own that I",
    "is weird with me and doesn't care what anyone thinks",
    "embraces their quirks and celebrates what makes them different and",
    "has niche interests that they're passionate about and share with",
    "is comfortable with being different and standing out from everyone",
    "appreciates the unconventional and finds beauty in strange things with",
    "is their authentic weird self without trying to be normal",
    "has their own unique perspective on things that fascinates me",
    "is okay with deep weird conversations at 3am about random",
    "celebrates our differences and the quirky things that make us",
    "is perfectly imperfect and owns every bit of their weirdness",
    "has obscure hobbies or interests that most people don't understand",
    "is unapologetically themselves even when it doesn't make sense to",
    "appreciates my odd habits and shares their own with me",
    "is comfortable in their own skin even when they're different",
    "has that quirky energy that makes them interesting and memorable",
    "is weird in the best way possible and owns it",
    "celebrates what makes us unique instead of trying to fit"
  ],
  "serious": [
    "is honest and genuine about their intentions from the start",
    "shows emotional maturity and communicates like an actual adult always",
    "respects my boundaries without making me feel guilty for having",
    "is reliable and does what they say they're going to",
    "takes accountability for their actions instead of making excuses constantly",
    "is emotionally available and present when we're together not distracted",
    "respects my time and doesn't waste it playing games with",
    "is consistent with their words and actions so I can",
    "has their life somewhat together and works toward their goals",
    "is honest even when the truth is uncomfortable or difficult",
    "respects me as an equal partner in everything we do",
    "is mature enough to handle difficult conversations without shutting down",
    "takes my feelings seriously and doesn't dismiss them as dramatic",
    "is someone I can count on through good times and",
    "respects my career and ambitions as much as their own",
    "is financially responsible and has a plan for their future",
    "takes our relationship seriously and puts in the effort it",
    "is honest about their past and what they've learned from",
    "respects my standards because I set them for good reasons",
    "is ready for commitment not just casual dating or games"
  ],
  "intellectual": [
    "has deep meaningful conversations that go beyond surface level topics 🧠",
    "is intellectually curious and always wants to learn new things",
    "challenges my thinking in respectful ways that help me grow",
    "is open to different perspectives and willing to change their",
    "has thoughtful discussions that make me see things differently than",
    "is well read and has interesting thoughts on various topics",
    "asks questions that make me think more deeply about things",
    "is open minded and willing to learn from anyone including",
    "engages in debates without getting defensive or taking things too",
    "is curious about the world and wants to understand it",
    "has opinions that are well thought out and based on",
    "is intellectually stimulating and makes me think in new ways",
    "is interested in learning together and exploring ideas as a",
    "has meaningful discussions about topics that matter to both of",
    "is thoughtful and considers different angles before forming strong opinions",
    "is curious about my thoughts and perspectives on things that",
    "engages with ideas seriously instead of dismissing them as overthinking",
    "is intellectually honest and admits when they don't know something",
    "has that curiosity that makes conversations interesting and engaging always",
    "is open to having their views challenged in good ways"
  ],
  "default": [
    "is kind and treats everyone with respect not just me ✨",
    "is genuine and authentic in how they present themselves to",
    "makes me feel comfortable being myself completely around them always",
    "is a good listener and actually hears what I say",
    "shows up consistently and is someone I can count on",
    "is honest and communicates openly even when it's difficult or",
    "makes me laugh and brings joy into my life daily",
    "is supportive of my goals and dreams no matter what",
    "respects my boundaries and understands they exist for good reasons",
    "is patient and understanding with me through everything in life",
    "makes me feel valued and appreciated for who I am",
    "is emotionally available and present when we're together not distant",
    "shows love through actions not just words that mean nothing",
    "is reliable and follows through on what they say they'll",
    "makes me feel safe and comfortable being vulnerable with them",
    "is thoughtful and does little things that show they care",
    "respects me and treats me well consistently not just sometimes",
    "is someone who makes me want to be better every",
    "makes me feel like I matter and my feelings are",
    "is genuine about their intentions and what they want from"
  ]
};

module.exports = iWantSomeoneWho;
