const iWantSomeoneWho = {
  funny: [
    "laughs at my terrible jokes even when they are really bad",
    "does not judge me for eating cereal at midnight",
    "lets me nap whenever I want without any questions",
    "appreciates my chaotic energy and adds to it",
    "understands that I am not a morning person",
    "shares their food with me which is true love",
    "makes everything fun even boring tasks like laundry",
    "does not take life too seriously",
    "lets me be dramatic without calling me out",
    "brings me snacks without me even having to ask",
    "matches my meme energy and sends good ones back",
    "appreciates my sarcasm and dishes it right back",
    "makes me laugh when I am having the worst day",
    "understands my need for twelve hours of sleep",
    "does not judge my comfort shows",
    "lets me sleep in on weekends without guilt",
    "is goofy and silly with me",
    "appreciates my weird sense of humor",
    "makes ordinary moments fun just by being authentic",
    "gets my random references and makes their own",
  ],
  romantic: [
    "chooses me every single day not just in the beginning",
    "makes me feel safe enough to be completely vulnerable",
    "remembers small details I mention and brings them up later",
    "is emotionally available and communicates openly about feelings",
    "shows love through actions not just empty words",
    "makes me feel like a priority not an option",
    "is affectionate without me having to ask constantly",
    "supports my dreams and believes in me",
    "makes me laugh and smile even on my worst days",
    "is patient with me when I am going through hard times",
    "is vulnerable and open about their feelings",
    "makes me feel beautiful even when I am in sweats",
    "listens when I talk and actually remembers",
    "is thoughtful and does little things that show they care",
    "makes me feel heard and understood on a deep level",
    "is consistent so I know I can trust them",
    "shows up for me when I need them most",
    "makes me feel cherished and appreciated for who I am",
    "is my best friend and partner at the same time",
    "loves me for who I am not who they want",
  ],
  adventurous: [
    "is spontaneous and says yes to random adventures",
    "tries new things together even when they are scary",
    "is down for last minute road trips with no plan",
    "matches my energy and enthusiasm for exploring",
    "is willing to step outside their comfort zone",
    "says yes to adventures and makes memories",
    "is open to trying new foods and experiences",
    "has that wanderlust energy that matches mine",
    "is spontaneous and does not need everything planned",
    "is excited about exploring and discovering new things",
    "is willing to get lost and find our way back",
    "has a sense of adventure and is not afraid to try",
    "is down for outdoor activities and nature adventures",
    "is open to travel and experiencing different cultures",
    "is willing to take risks and see where they lead",
    "has that adventurous spirit that makes life more fun",
    "is excited about trying activities we have never done",
    "is spontaneous with plans and goes with the flow",
    "is willing to explore off the beaten path",
    "has that energy that makes every day feel like adventure",
  ],
  quirky: [
    "appreciates my weirdness and adds their own",
    "is authentically themselves even when it is odd",
    "gets my obscure references and makes their own",
    "is weird with me and does not care what anyone thinks",
    "embraces their quirks and celebrates what makes them different",
    "has niche interests that they are passionate about",
    "is comfortable with being different and standing out",
    "appreciates the unconventional and finds beauty in strange things",
    "is their authentic weird self without trying to be normal",
    "has their own unique perspective that fascinates me",
    "is okay with deep weird conversations at 3am",
    "celebrates our differences and the quirky things that make us us",
    "is perfectly imperfect and owns their weirdness",
    "has obscure hobbies or interests most people do not understand",
    "is unapologetically themselves",
    "appreciates my odd habits and shares their own",
    "is comfortable in their own skin",
    "has that quirky energy that makes them interesting",
    "is weird in the best way possible",
    "celebrates what makes us unique",
  ],
  serious: [
    "is honest and genuine about their intentions",
    "shows emotional maturity and communicates like an adult",
    "respects my boundaries without making me feel guilty",
    "is reliable and does what they say they are going to",
    "takes accountability for their actions",
    "is emotionally available and present when we are together",
    "respects my time and does not waste it playing games",
    "is consistent with their words and actions",
    "has their life somewhat together and works toward goals",
    "is honest even when the truth is uncomfortable",
    "respects me as an equal partner",
    "is mature enough to handle difficult conversations",
    "takes my feelings seriously",
    "is someone I can count on through good times and bad",
    "respects my career and ambitions",
    "is financially responsible and has a plan",
    "takes our relationship seriously",
    "is honest about their past",
    "respects my standards",
    "is ready for commitment not just casual dating",
  ],
  intellectual: [
    "has deep meaningful conversations that go beyond surface level",
    "is intellectually curious and always wants to learn new things",
    "challenges my thinking in respectful ways",
    "is open to different perspectives",
    "has thoughtful discussions that make me see things differently",
    "is well read and has interesting thoughts on various topics",
    "asks questions that make me think more deeply",
    "is open minded and willing to learn from anyone",
    "engages in debates without getting defensive",
    "is curious about the world",
    "has opinions that are well thought out",
    "is intellectually stimulating",
    "is interested in learning together",
    "has meaningful discussions about things that matter",
    "is thoughtful and considers different angles",
    "is curious about my thoughts and perspectives",
    "engages with ideas seriously",
    "is intellectually honest",
    "has that curiosity that makes conversations interesting",
    "is open to having their views challenged",
  ],
  default: [
    "is kind and treats everyone with respect",
    "is genuine and authentic in how they present themselves",
    "makes me feel comfortable being myself completely",
    "is a good listener and actually hears what I say",
    "shows up consistently and is someone I can count on",
    "is honest and communicates openly",
    "makes me laugh and brings joy into my life",
    "is supportive of my goals and dreams",
    "respects my boundaries",
    "is patient and understanding with me",
    "makes me feel valued and appreciated",
    "is emotionally available and present",
    "shows love through actions not just words",
    "is reliable",
    "makes me feel safe and comfortable being vulnerable",
    "is thoughtful",
    "respects me and treats me well consistently",
    "is someone who makes me want to be better",
    "makes me feel like I matter",
    "is genuine about their intentions",
  ],
};

module.exports = iWantSomeoneWho;
