const iWontShutUpAbout = {
  "funny": [
    "how much I love naps and sleeping in general honestly 😂",
    "my favorite tv shows and why everyone should watch them",
    "food and where to find the best food in town",
    "how coffee is literally the only reason I function daily",
    "my pets and showing everyone photos of them constantly always",
    "random memes I saw that made me laugh way too",
    "how much I hate mornings and being a morning person",
    "the weirdest dreams I had last night that made no",
    "how I'm basically a professional napper at this point honestly",
    "my comfort shows that I've watched a million times already",
    "how staying in is better than going out most times",
    "random conspiracy theories I don't actually believe but find funny",
    "how I'm not built for adulting and nobody prepared me",
    "the best snacks and where to find them in stores",
    "how my metabolism betrayed me after turning twenty five years",
    "random facts I learned that nobody asked about but interesting",
    "how I need like twelve hours of sleep to function",
    "my favorite restaurants and why you need to try them",
    "how I'm basically a hobbit who loves food and",
    "the funniest tiktoks I saw that I need to share"
  ],
  "romantic": [
    "love languages and why they're so important in relationships ❤️",
    "my favorite romantic movies that make me cry every time",
    "what I'm looking for in a partner and relationship honestly",
    "how important communication is in any healthy relationship between two people",
    "my ideal date ideas and why they'd be so perfect",
    "how actions speak louder than words when it comes to",
    "what makes a relationship healthy and worth fighting for always",
    "my favorite love songs and why they hit so different",
    "how important it is to find someone who gets you",
    "what I think makes a relationship last through everything in",
    "my thoughts on soulmates and whether they actually exist or",
    "how vulnerability is the key to real intimacy with someone",
    "what I value most in a partner and why it",
    "my favorite romantic gestures that mean more than expensive gifts",
    "how important it is to be friends with your partner",
    "what I think true love actually looks like in real",
    "my thoughts on dating and finding the right person for",
    "how important emotional availability is in a relationship with someone",
    "what I'm not willing to compromise on in relationships ever",
    "my favorite couples and what makes their relationships work so"
  ],
  "adventurous": [
    "places I want to travel to and why they're amazing 🌟",
    "my bucket list and all the adventures I want to",
    "the best hikes and trails I've discovered in my area",
    "travel tips and hacks I've learned from my adventures so",
    "my favorite travel destinations and why you need to visit",
    "adventure activities I want to try even though they scare",
    "the best food I've tried while traveling to different places",
    "my travel plans and where I'm going next in life",
    "hidden gems I've discovered that tourists don't know about yet",
    "the most amazing experiences I've had while traveling around the",
    "outdoor activities and why everyone should try them at least",
    "my favorite road trips and the memories I made along",
    "adventure sports I've tried and why they were so worth",
    "the best spontaneous trips I've taken with no real plan",
    "places off the beaten path that are worth the effort",
    "my travel bucket list that keeps getting longer every day",
    "the most beautiful places I've seen and why they're special",
    "adventure stories from my trips that I love telling people",
    "the best local spots I've found in cities I've",
    "why everyone should step outside their comfort zone and travel"
  ],
  "quirky": [
    "my niche interests that most people have never heard of 🎨",
    "random theories I have about things that don't really matter",
    "my weird collections and why I started collecting them originally",
    "obscure movies and shows that nobody else seems to know",
    "my oddly specific pet peeves that drive me crazy daily",
    "random facts about topics nobody asked about but I know",
    "my unconventional hobbies that people find weird but I love",
    "strange coincidences I've noticed that nobody else seems to see",
    "my unique perspective on things that others find odd or",
    "niche music genres that I'm obsessed with right now honestly",
    "my weird habits and routines that don't make sense to",
    "obscure references from shows or books nobody else has seen",
    "my quirky opinions on things that most people don't",
    "random patterns I notice in everyday life that fascinate me",
    "my strange food combinations that sound gross but taste amazing",
    "niche communities I'm part of online that are super specific",
    "my unconventional ways of doing things that work for me",
    "weird traditions I've created that don't make sense to",
    "my oddly specific preferences about random everyday things in life",
    "niche topics I could talk about for hours without stopping"
  ],
  "serious": [
    "my goals and what I'm working towards in my life",
    "personal development and how I'm constantly trying to improve myself",
    "my career aspirations and the steps I'm taking to achieve",
    "financial literacy and why everyone should learn about money management early",
    "mental health and why therapy should be normalized for everyone",
    "my values and what's most important to me in life",
    "the importance of setting boundaries and protecting your peace always",
    "self improvement strategies that have actually worked for me in",
    "my long term plans and the future I'm building for",
    "the importance of investing in yourself and your growth constantly",
    "work life balance and why it's so crucial for wellbeing",
    "my professional goals and how I'm working to achieve them",
    "the importance of financial planning and preparing for the future",
    "personal growth and the journey of becoming who I want",
    "my priorities in life and why they matter so much",
    "the importance of taking accountability and owning your choices always",
    "building healthy habits that support long term success and happiness",
    "my vision for my future and the life I'm creating",
    "the importance of continuous learning and skill development throughout life",
    "setting goals and actually following through on them consistently every"
  ],
  "intellectual": [
    "books I'm reading and the ideas they've sparked in me 🧠",
    "philosophical questions that keep me up at night thinking deeply",
    "podcasts I'm listening to and the concepts they explore thoroughly",
    "theories and ideas that challenge conventional thinking about everything around",
    "the importance of critical thinking and questioning assumptions we hold",
    "topics I'm researching and learning about in my free time",
    "intellectual debates and different perspectives on complex issues in society",
    "the books that changed how I see the world completely",
    "ideas that fascinate me and make me think differently about",
    "the importance of staying curious and never stopping learning new",
    "concepts I'm trying to understand more deeply through reading and",
    "the value of intellectual discourse and respectful debate with others",
    "topics I find endlessly fascinating and could discuss for hours",
    "the importance of reading diverse perspectives and challenging your views",
    "ideas from different fields and how they connect in interesting",
    "the books on my reading list and why I'm excited",
    "philosophical concepts that have influenced how I think about life",
    "the importance of intellectual humility and admitting what you don't",
    "topics I'm passionate about learning and want to understand better",
    "the value of education and continuous intellectual growth throughout life"
  ],
  "default": [
    "things I'm passionate about and genuinely care about in life ✨",
    "my favorite hobbies and why they bring me so much",
    "topics I find interesting and could talk about for hours",
    "things that make me happy and bring joy to my",
    "my interests and the things I'm currently obsessed with right",
    "what I'm learning about and why it fascinates me so",
    "my favorite things to do in my free time honestly",
    "topics I'm knowledgeable about and love sharing with other people",
    "things I'm excited about and looking forward to in life",
    "my passions and what drives me to keep going every",
    "what I'm currently into and why I love it so",
    "things that inspire me and make me want to be",
    "my favorite activities and why they're so meaningful to me",
    "topics I could discuss endlessly without ever getting bored of",
    "things I'm enthusiastic about and want to share with everyone",
    "what I'm working on and why it matters to me",
    "my interests that I get really excited talking about with",
    "things that bring me fulfillment and purpose in my daily",
    "topics I'm passionate about and love learning more about constantly",
    "what makes me excited and eager to share with others"
  ]
};

module.exports = iWontShutUpAbout;
