const letsMakeSureWereOnTheSamePageAbout = {
  funny: [
    "pineapple on pizza being completely valid and delicious actually",
    "dogs being better than cats obviously no debate needed",
    "breakfast for dinner being the superior meal choice always",
    "the office being the best comfort show ever made",
    "naps being a legitimate form of self care daily",
    "ranch dressing going on literally everything we eat together",
    "memes being a valid form of communication these days",
    "staying in being better than going out most nights",
    "pizza being its own food group in our diet",
    "sweatpants being acceptable date night attire at home always",
    "sharing food being mandatory not optional in this relationship",
    "laughing at our own jokes before finishing them completely",
    "singing loudly in the car being required on trips",
    "ordering appetizers being more important than the actual meal",
    "watching the same show again being totally acceptable behavior",
    "snacks being a food group we take very seriously",
    "dad jokes being the highest form of comedy honestly",
    "double texting being completely fine and not weird ever",
    "dessert before dinner being allowed on bad days sometimes",
    "our pets being our children no questions asked here",
  ],
  romantic: [
    "communication being the most important thing in our relationship",
    "always saying goodnight even when were mad at each",
    "making time for each other no matter how busy",
    "being each others safe space and biggest support system",
    "choosing each other every day not just when easy",
    "honesty even when the truth is hard to hear",
    "never going to bed angry at each other ever",
    "making our relationship a priority not an afterthought always",
    "growing together not apart as we both change over",
    "being a team through everything life throws at us",
    "showing love through actions not just saying the words",
    "always having each others back no matter what happens",
    "making effort every day not just in the beginning",
    "being vulnerable and open even when its scary to",
    "celebrating the small moments not just the big ones",
    "keeping the romance alive even after the honeymoon phase",
    "being best friends and lovers at the same time",
    "supporting each others dreams like theyre our own too",
    "choosing love even when its hard work some days",
    "building a future together one day at a time",
  ],
  adventurous: [
    "saying yes to spontaneous adventures and random road trips",
    "trying new things together even if they scare us",
    "traveling being a priority not just a someday dream",
    "making memories being more important than making money always",
    "living life to the fullest not just existing daily",
    "taking risks together and supporting each others wild ideas",
    "exploring new places being a regular part of life",
    "adventure being a mindset not just a vacation thing",
    "pushing each other out of comfort zones in good",
    "collecting experiences not things as we go through life",
    "being open to change and new possibilities always together",
    "making every day an adventure even the ordinary",
    "supporting each others bucket list dreams and goals actively",
    "not letting fear hold us back from living fully",
    "finding beauty in the journey not just the destination",
    "being spontaneous and flexible with our plans and life",
    "trying the local food no matter how weird it",
    "getting lost together being part of the fun adventure",
    "living with no regrets and taking chances when possible",
    "making our life together one big adventure story always",
  ],
  quirky: [
    "our weirdness being completely accepted and celebrated always here",
    "having our own inside jokes nobody else understands ever",
    "our comfort shows being watched on repeat without judgment",
    "weird habits being endearing not annoying to each other",
    "our niche interests being supported even if not shared",
    "making up our own words and phrases together regularly",
    "our specific routines being respected and never questioned really",
    "being weird together in public without caring what people",
    "our random collections making perfect sense to us both",
    "talking in references and memes being our love language",
    "our oddly specific preferences being remembered and honored always",
    "embracing our quirks instead of trying to change them",
    "our weird food combinations being accepted without judgment ever",
    "having matching energy for random deep dives into topics",
    "our comfort items and rituals being taken seriously always",
    "being unapologetically ourselves around each other every single day",
    "our random hypotheticals being engaged with at 2am seriously",
    "weird being a compliment not an insult between us",
    "our specific ways of doing things being understood completely",
    "finding someone who matches our exact brand of weird",
  ],
  serious: [
    "honesty and communication being non negotiable in our relationship always",
    "respecting each others boundaries without question or guilt tripping",
    "taking accountability for our actions and words every time",
    "working on ourselves individually while growing together as couple",
    "handling conflict maturely without stonewalling or running away ever",
    "being emotionally available and present for each other consistently",
    "trust being the foundation of everything we build together",
    "showing up consistently through actions not just pretty words",
    "respecting each others independence while building something together here",
    "having difficult conversations instead of avoiding them always courageously",
    "our mental health being a priority we both support",
    "being partners who add to each others lives positively",
    "commitment meaning showing up every day not just staying",
    "growth being more important than being right in arguments",
    "supporting each other through hard times not just good",
    "being intentional about our relationship and its future together",
    "loyalty and respect being the bare minimum we expect",
    "making our relationship a safe space for vulnerability always",
    "putting in equal effort to make this work long",
    "building something real and lasting not just something easy",
  ],
  intellectual: [
    "having deep conversations being a regular part of our",
    "challenging each others perspectives respectfully and thoughtfully always here",
    "valuing growth and learning together as we go through",
    "being curious about the world and each other constantly",
    "having intellectual compatibility being just as important as physical",
    "asking questions and seeking to understand not just respond",
    "appreciating nuance and complexity in discussions and life generally",
    "reading and learning being things we do together often",
    "debating ideas without it becoming personal or defensive ever",
    "valuing substance and depth over surface level interactions always",
    "being open minded and willing to change our views",
    "having conversations that make us think differently about things",
    "appreciating each others intelligence and unique perspectives on life",
    "learning from each other and growing our knowledge together",
    "being able to discuss anything from light to existential",
    "valuing education and self improvement as lifelong pursuits here",
    "having meaningful discussions about ideas that matter to us",
    "respecting each others opinions even when we disagree strongly",
    "being intellectually stimulated by each other regularly in conversations",
    "making learning and discovery a part of our relationship",
  ],
};

module.exports = letsMakeSureWereOnTheSamePageAbout;
