const letsDebateThisTopic = {
  funny: [
    "whether cereal is soup and why im obviously right",
    "if a hotdog is a sandwich or its own",
    "whether pineapple belongs on pizza spoiler it does obviously",
    "if toilet paper should go over or under correctly",
    "whether water is wet or if thats even possible",
    "if its pop or soda and why youre wrong",
    "whether the dress was blue black or white gold",
    "if gif is pronounced with a hard or soft",
    "whether its called dinner or supper in your house",
    "if ketchup belongs in the fridge or the cupboard",
    "whether a straw has one hole or two holes",
    "if you should put milk before or after cereal",
    "whether its called a shopping cart or a buggy",
    "if pizza is a breakfast food or just dinner",
    "whether you fold or crumple toilet paper honestly here",
    "if boneless wings are actually wings or just nuggets",
    "whether the weekend starts friday night or saturday morning",
    "if its sneakers or tennis shoes or trainers regionally",
    "whether you bite or lick ice cream cones",
    "if its called subs hoagies or grinders where youre",
  ],
  romantic: [
    "whether love at first sight is real or just",
    "if soulmates exist or we create them over time",
    "whether actions or words matter more in showing love",
    "if opposites attract or similarities make better relationships work",
    "whether you can love someone and let them go",
    "if timing or effort matters more in relationships lasting",
    "whether love is a feeling or a choice daily",
    "if theres one person for everyone or many possibilities",
    "whether you should say i love you first or",
    "if grand gestures or small moments matter more overall",
    "whether distance makes the heart grow fonder or apart",
    "if you can be friends with an ex partner",
    "whether love is enough to make relationships work long",
    "if chemistry or compatibility is more important for lasting",
    "whether you should follow your heart or your head",
    "if true love means never having to say sorry",
    "whether relationships take work or should feel effortless naturally",
    "if you can love someone youre not in love",
    "whether the spark fades or evolves into something deeper",
    "if love conquers all or if thats just naive",
  ],
  adventurous: [
    "whether its better to plan trips or go spontaneous",
    "if you should quit your job to travel the",
    "whether the journey or the destination matters more overall",
    "if its better to visit many places or few",
    "whether you should travel solo or always with someone",
    "if adventure is about location or mindset you bring",
    "whether comfort zones are meant to be broken always",
    "if you need money to have great adventures or",
    "whether its better to be a tourist or local",
    "if taking risks is brave or just reckless behavior",
    "whether you should document adventures or just live them",
    "if the best adventures are planned or completely spontaneous",
    "whether you need to travel far for real adventure",
    "if saying yes to everything is living or exhausting",
    "whether adventure is running toward or away from something",
    "if you should finish your bucket list or keep",
    "whether the best stories come from good or bad",
    "if you can have adventure while staying in one",
    "whether playing it safe is smart or just boring",
    "if adventure is a phase or a lifestyle choice",
  ],
  quirky: [
    "whether aliens exist and are already among us secretly",
    "if we live in a simulation and how wed",
    "whether time travel would create paradoxes or alternate timelines",
    "if animals can understand us but choose not to",
    "whether parallel universes exist and our other selves are",
    "if birds are real or government surveillance drones obviously",
    "whether the mandela effect is real or mass confusion",
    "if we're alone in the universe or not really",
    "whether ghosts are real or just our brains playing",
    "if cryptids like bigfoot could actually exist somewhere hidden",
    "whether we have free will or everything is predetermined",
    "if the moon landing was real or faked completely",
    "whether were living in the matrix right now unknowingly",
    "if déjà vu means we died in another timeline",
    "whether dreams mean something or are just random brain",
    "if the illuminati is real and controls everything secretly",
    "whether we can trust our memories or theyre altered",
    "if glitches in reality prove were in a simulation",
    "whether the government is hiding aliens at area 51",
    "if our pets are secretly judging us all day",
  ],
  serious: [
    "whether you can separate art from the artist always",
    "if cancel culture helps accountability or just creates fear",
    "whether social media does more harm than good overall",
    "if we have a responsibility to stay informed or",
    "whether its better to be kind or be honest",
    "if people can really change or just hide better",
    "whether we should forgive people who dont ask for",
    "if success is about hard work or privilege mostly",
    "whether you owe your family loyalty no matter what",
    "if mental health days are valid or just excuses",
    "whether we're products of our environment or our choices",
    "if you should stay in relationships for the kids",
    "whether money can buy happiness or just temporary comfort",
    "if we have a moral obligation to help others",
    "whether the ends justify the means in difficult situations",
    "if you should always tell the truth or protect",
    "whether second chances should be given or earned always",
    "if we're responsible for our parents in old age",
    "whether you can love someone and still leave them",
    "if closure is necessary or just something we want",
  ],
  intellectual: [
    "whether free will exists or everything is predetermined fate",
    "if artificial intelligence will help or harm humanity overall",
    "whether objective truth exists or everything is just perspective",
    "if we have a moral obligation to future generations",
    "whether nature or nurture has more influence on us",
    "if the trolley problem has a right answer morally",
    "whether consciousness can exist without a physical body somehow",
    "if we can ever truly know anything with certainty",
    "whether the meaning of life is universal or personal",
    "if technology is making us smarter or just lazier",
    "whether we should colonize other planets or fix earth",
    "if art needs meaning or can exist for beauty",
    "whether morality is objective or culturally constructed always here",
    "if we have a duty to preserve human knowledge",
    "whether the ship of theseus is still the same",
    "if we can separate emotion from logic in decisions",
    "whether language shapes thought or just expresses it clearly",
    "if progress is linear or cyclical throughout human history",
    "whether we should pursue knowledge regardless of ethical concerns",
    "if the unexamined life is worth living at all",
  ],
};

module.exports = letsDebateThisTopic;
