const myCryinthecarSongIs = {
  funny: [
    "literally any song from high school musical unironically always",
    "the spongebob theme song when life gets too real",
    "all star by smash mouth but make it emotional",
    "any disney song because im basically a child still",
    "the friends theme song when i miss my people",
    "any early 2000s pop song that hits different now",
    "the hannah montana theme song no im not joking",
    "any song from shrek because its actually deep honestly",
    "the kim possible theme song when i need confidence",
    "literally anything by one direction without shame or regret",
    "the icarly theme song when nostalgia hits too hard",
    "any high school musical 2 song specifically bet on",
    "the suite life of zack and cody theme honestly",
    "any jonas brothers song from their disney channel era",
    "the victorious theme song when i need a moment",
    "literally any camp rock song they all hit different",
    "the drake and josh theme song for no reason",
    "any lizzie mcguire song because im that girl still",
    "the thats so raven theme when life gets weird",
    "literally any disney channel original movie soundtrack song ever",
  ],
  romantic: [
    "drivers license by olivia rodrigo on repeat for hours",
    "someone like you by adele when im in feelings",
    "all too well ten minute version by taylor swift",
    "when i was your man by bruno mars honestly",
    "the night we met by lord huron every time",
    "say something by a great big world and christina",
    "someone you loved by lewis capaldi without fail always",
    "falling by harry styles when im feeling everything deeply",
    "let her go by passenger when i need cry",
    "fix you by coldplay because it gets me every",
    "skinny love by bon iver the birdy version specifically",
    "gravity by sara bareilles when love feels heavy hard",
    "back to december by taylor swift always hits different",
    "the scientist by coldplay trying to figure it out",
    "stay by rihanna when i cant let go yet",
    "jar of hearts by christina perri feeling it all",
    "breathe me by sia when everything feels too much",
    "turning tables by adele when im done trying finally",
    "exile by taylor swift and bon iver hurts good",
    "dancing on my own by robyn the emotional version",
  ],
  adventurous: [
    "life is a highway by rascal flatts obviously always",
    "dont stop believin by journey on every road trip",
    "home by phillip phillips when im far away missing",
    "on top of the world by imagine dragons",
    "shut up and dance by walk the moon",
    "send me on my way by rusted root",
    "i lived by onerepublic when i need reminded why",
    "adventure of a lifetime by coldplay feeling it",
    "riptide by vance joy on coastal drives always here",
    "best day of my life by american authors",
    "unwritten by natasha bedingfield the ultimate road trip song",
    "somewhere only we know by keane hits different",
    "ho hey by the lumineers on long drives",
    "dog days are over by florence and machine",
    "shake it out by florence and the machine",
    "pompeii by bastille when everything feels big and",
    "little talks by of monsters and men always",
    "safe and sound by capital cities good vibes",
    "take me home country roads by john denver",
    "mr brightside by the killers for no reason",
  ],
  quirky: [
    "the entire shrek soundtrack because its unironically good honestly",
    "any weird al yankovic song when i need laugh",
    "bohemian rhapsody by queen the full six minutes always",
    "africa by toto for absolutely no reason at all",
    "never gonna give you up by rick astley unironically",
    "what does the fox say because why not",
    "the duck song on repeat until i feel better",
    "crazy frog axel f when life gets too serious",
    "numa numa by ozone the full emotional experience here",
    "shooting stars by bag raiders for the meme value",
    "caramelldansen the full dance included in my car",
    "nyan cat theme song for ten minutes straight honestly",
    "the gummy bear song in german for some",
    "chocolate rain by tay zonday unironically hits different now",
    "badger badger badger mushroom the full version always",
    "peanut butter jelly time when i need a",
    "hamster dance song because it makes me smile",
    "the llama song when nothing else makes sense anymore",
    "potter puppet pals theme song the mysterious ticking noise",
    "keyboard cat theme when i need to reset",
  ],
  serious: [
    "breathe me by sia when everything feels too heavy",
    "hurt by johnny cash the cover version specifically always",
    "mad world by gary jules tears for fears cover",
    "skinny love by bon iver when words arent enough",
    "the night we met by lord huron missing everything",
    "let it be by the beatles when i need",
    "hallelujah by jeff buckley the most emotional version ever",
    "fix you by coldplay when i need to believe",
    "everybody hurts by rem when i feel alone in",
    "tears in heaven by eric clapton gets me every",
    "nothing compares 2 u by sinead oconnor always",
    "black by pearl jam when loss feels too real",
    "the scientist by coldplay trying to understand it all",
    "hurt by nine inch nails the original version sometimes",
    "creep by radiohead when i feel like too much",
    "fake plastic trees by radiohead feeling everything at once",
    "landslide by fleetwood mac when change feels overwhelming here",
    "both sides now by joni mitchell understanding life finally",
    "wild horses by the rolling stones cant let go",
    "wish you were here by pink floyd missing someone",
  ],
  intellectual: [
    "comfortably numb by pink floyd existential crisis edition always here",
    "the sound of silence by simon and garfunkel",
    "imagine by john lennon when the world feels heavy",
    "blackbird by the beatles hope in dark times",
    "both sides now by joni mitchell understanding perspective finally",
    "a change is gonna come by sam cooke",
    "what a wonderful world by louis armstrong ironically",
    "blowin in the wind by bob dylan questions",
    "the times they are a changin by bob dylan",
    "where is my mind by the pixies existential",
    "mad world by gary jules questioning everything around me",
    "everybody wants to rule the world by tears for",
    "losing my religion by rem the metaphorical kind obviously",
    "hurt by johnny cash reflecting on life and choices",
    "wish you were here by pink floyd missing connection",
    "hotel california by the eagles the meaning hits different",
    "stairway to heaven by led zeppelin the full journey",
    "space oddity by david bowie feeling disconnected from everything",
    "across the universe by the beatles finding peace",
    "let it be by the beatles accepting what is",
  ],
};

module.exports = myCryinthecarSongIs;
