const myCryinthecarSongIs = {
  funny: [
    "literally any song from High School Musical unironically",
    "the SpongeBob theme song when life gets too real",
    "All Star by Smash Mouth but make it emotional",
    "any Disney song because I am basically a child",
    "the Friends theme song when I miss my people",
    "any early 2000s pop song that hits different now",
    "the Hannah Montana theme song no I am not joking",
    "any song from Shrek because it is actually deep",
    "the Kim Possible theme song when I need confidence",
    "literally anything by One Direction without shame",
    "the iCarly theme song when nostalgia hits too hard",
    "any High School Musical 2 song specifically Bet On It",
    "the Suite Life of Zack and Cody theme",
    "any Jonas brothers song from their Disney Channel era",
    "the Victorious theme song when I need a moment",
    "literally any Camp Rock song they all hit different",
    "the Drake and Josh theme song for no reason",
    "any Lizzie McGuire song because I am that girl",
    "the That is So Raven theme when life gets weird",
    "literally any Disney Channel Original Movie soundtrack song ever",
  ],
  romantic: [
    "Drivers License by Olivia Rodrigo on repeat for hours",
    "Someone Like You by Adele when I am in my feels",
    "All Too Well Ten Minute Version by Taylor Swift",
    "When I Was Your Man by Bruno Mars",
    "The Night We Met by Lord Huron every time",
    "Say Something by A Great Big World and Christina",
    "Someone You Loved by Lewis Capaldi",
    "Falling by Harry Styles when I am feeling everything",
    "Let Her Go by Passenger when I need to cry",
    "Fix You by Coldplay because it gets me every time",
    "Skinny Love by Bon Iver the Birdy version specifically",
    "Gravity by Sara Bareilles when love feels heavy",
    "Back to December by Taylor Swift always hits different",
    "The Scientist by Coldplay trying to figure it all out",
    "Stay by Rihanna when I cannot let go yet",
    "Jar of Hearts by Christina Perri feeling it all",
    "Breathe Me by Sia when everything feels too much",
    "Turning Tables by Adele when I am done trying",
    "Exile by Taylor Swift and Bon Iver hurts so good",
    "Dancing on My Own by Robyn the emotional version",
  ],
  adventurous: [
    "Life is a Highway by Rascal Flatts obviously",
    "Do not Stop Believin by Journey on every road trip",
    "Home by Phillip Phillips when I am far away",
    "On Top of the World by Imagine Dragons",
    "Shut Up and Dance by Walk the Moon",
    "Send Me On My Way by Rusted Root",
    "I Lived by OneRepublic when I need to be reminded",
    "Adventure of a Lifetime by Coldplay feeling it",
    "Riptide by Vance Joy on coastal drives",
    "Best Day of My Life by American Authors",
    "Unwritten by Natasha Bedingfield the ultimate road trip song",
    "Somewhere Only We Know by Keane hits different",
    "Ho Hey by The Lumineers on long drives",
    "Dog Days Are Over by Florence and the Machine",
    "Shake It Out by Florence and the Machine",
    "Pompeii by Bastille when everything feels big",
    "Little Talks by Of Monsters and Men",
    "Safe and Sound by Capital Cities good vibes",
    "Take Me Home Country Roads by John Denver",
    "Mr Brightside by The Killers for no reason",
  ],
  quirky: [
    "the entire Shrek soundtrack because it is unironically good",
    "any Weird Al Yankovic song when I need a laugh",
    "Bohemian Rhapsody by Queen the full six minutes",
    "Africa by Toto for absolutely no reason",
    "Never Gonna Give You Up by Rick Astley unironically",
    "What Does the Fox Say because why not",
    "the Duck Song on repeat until I feel better",
    "Crazy Frog Axel F when life gets too serious",
    "Numa Numa by O-Zone the full experience",
    "Shooting Stars by Bag Raiders for the meme value",
    "Caramelldansen the full dance included in my car",
    "Nyan Cat theme song for ten minutes straight",
    "the Gummy Bear Song in German",
    "Chocolate Rain by Tay Zonday unironically hits different",
    "Badger Badger Badger Mushroom the full version",
    "Peanut Butter Jelly Time when I need a reset",
    "the Hamster Dance Song because it makes me smile",
    "the Llama Song when nothing else makes sense",
    "Potter Puppet Pals theme the mysterious ticking noise",
    "Keyboard Cat theme when I need to reset",
  ],
  serious: [
    "Breathe Me by Sia when everything feels too heavy",
    "Hurt by Johnny Cash the cover version",
    "Mad World by Gary Jules tears for fears cover",
    "Skinny Love by Bon Iver when words are not enough",
    "The Night We Met by Lord Huron missing everything",
    "Let It Be by The Beatles when I need peace",
    "Hallelujah by Jeff Buckley the most emotional version ever",
    "Fix You by Coldplay when I need to believe",
    "Everybody Hurts by REM when I feel alone",
    "Tears in Heaven by Eric Clapton gets me every time",
    "Nothing Compares 2 U by Sinead O Connor",
    "Black by Pearl Jam when loss feels too real",
    "The Scientist by Coldplay trying to understand it all",
    "Hurt by Nine Inch Nails the original version",
    "Creep by Radiohead when I feel like too much",
    "Fake Plastic Trees by Radiohead feeling everything at once",
    "Landslide by Fleetwood Mac when change feels overwhelming",
    "Both Sides Now by Joni Mitchell understanding life",
    "Wild Horses by The Rolling Stones cannot let go",
    "Wish You Were Here by Pink Floyd missing someone",
  ],
  intellectual: [
    "Comfortably Numb by Pink Floyd existential crisis edition",
    "The Sound of Silence by Simon and Garfunkel",
    "Imagine by John Lennon when the world feels heavy",
    "Blackbird by The Beatles hope in dark times",
    "Both Sides Now by Joni Mitchell understanding perspective",
    "A Change is Gonna Come by Sam Cooke",
    "What a Wonderful World by Louis Armstrong ironically",
    "Blowin in the Wind by Bob Dylan questions",
    "The Times They Are a Changin by Bob Dylan",
    "Where is My Mind by The Pixies existential",
    "Mad World by Gary Jules questioning everything",
    "Everybody Wants to Rule the World by Tears for Fears",
    "Losing My Religion by REM the metaphorical kind",
    "Hurt by Johnny Cash reflecting on life",
    "Wish You Were Here by Pink Floyd missing connection",
    "Hotel California by The Eagles the meaning",
    "Stairway to Heaven by Led Zeppelin the full journey",
    "Space Oddity by David Bow ie feeling disconnected",
    "Across the Universe by The Beatles finding peace",
    "Let It Be by The Beatles accepting what is",
  ],
};

module.exports = myCryinthecarSongIs;
