const myFriendsAskMeForAdviceAbout = {
  funny: [
    "how to avoid adulting for as long as possible",
    "the best excuses to get out of plans last",
    "what to order at restaurants theyve never been to",
    "how to look busy at work while doing nothing",
    "the perfect response to texts they dont want answer",
    "how to survive on a budget of basically nothing",
    "what to watch when theyve already watched everything available",
    "how to make instant ramen taste like actual food",
    "the best ways to procrastinate productively on everything important",
    "what memes to send in every possible situation ever",
    "how to pretend they have their life together always",
    "the art of canceling plans without feeling guilty about",
    "how to survive family gatherings and awkward questions from",
    "what to say when they have no idea whats",
    "how to make bad decisions sound like good ideas",
    "the best snacks for every mood and situation possible",
    "how to avoid small talk and awkward conversations successfully",
    "what to binge watch next based on their mood",
    "how to look like they tried without actually trying",
    "the perfect comeback for every annoying situation they face",
  ],
  romantic: [
    "how to know if someone really likes them back",
    "what to text their crush without seeming too desperate",
    "how to get over someone they still have feelings",
    "whether they should give their ex another chance or",
    "how to know if its love or just attachment",
    "what red flags they should actually pay attention to",
    "how to communicate better in their current relationship issues",
    "whether they should confess their feelings or wait longer",
    "how to know when to walk away from someone",
    "what to do when they catch feelings too fast",
    "how to set boundaries without pushing people away completely",
    "whether someone is worth fighting for or letting go",
    "how to know if theyre settling or genuinely happy",
    "what love should actually feel like in real life",
    "how to stop overthinking everything in their relationship constantly",
    "whether they should text first or wait for them",
    "how to know if someone is emotionally available or",
    "what to do when they like someone unavailable emotionally",
    "how to move on and actually mean it this",
    "whether they deserve better or are being too picky",
  ],
  adventurous: [
    "the best travel destinations for their budget and vibe",
    "how to plan spontaneous trips without losing their mind",
    "what to pack for literally any type of adventure",
    "how to travel on a budget and still have",
    "the best hidden gems in cities theyve never heard",
    "how to convince their friends to take risks with",
    "what adventure activities are actually worth the hype and",
    "how to overcome fear and just do the thing",
    "the best road trip routes and stops along way",
    "how to travel solo without being scared or lonely",
    "what experiences are worth spending money on versus saving",
    "how to make the most of weekend getaways nearby",
    "the best ways to meet people while traveling alone",
    "how to balance adventure with responsibilities and real life",
    "what to do when wanderlust hits but budget",
    "how to find adventure in their everyday boring routine",
    "the best apps and resources for planning trips quickly",
    "how to stay safe while still having fun adventures",
    "what to do when they feel stuck and restless",
    "how to turn their life into an adventure story",
  ],
  quirky: [
    "the most random niche topics i know too much",
    "how to organize literally everything in their chaotic life",
    "what their weirdly specific problem means about them psychologically",
    "the best personality tests to take at 2am online",
    "how to embrace their weird quirks without feeling judged",
    "what their oddly specific preferences say about their personality",
    "the best ways to deep dive into random topics",
    "how to find their people who get their weird",
    "what comfort show they should rewatch based on mood",
    "the meaning behind their weird dreams and random thoughts",
    "how to make their niche interest seem cool to",
    "what their specific organizational system says about their brain",
    "the best rabbit holes to fall down when bored",
    "how to explain their weird habits to normal people",
    "what their comfort items and routines mean psychologically here",
    "the best ways to feed their oddly specific obsessions",
    "how to turn their quirks into their brand basically",
    "what their random collection hobby says about them deeply",
    "the psychology behind their weirdly specific pet peeves always",
    "how to find community around their niche interests online",
  ],
  serious: [
    "how to set boundaries with family and toxic people",
    "what to do when theyre struggling with mental health",
    "how to know when to walk away from relationships",
    "whether they should go to therapy or try something",
    "how to deal with difficult people at work professionally",
    "what to do when they feel lost and directionless",
    "how to have difficult conversations they've been avoiding for",
    "whether theyre being too hard on themselves or not",
    "how to prioritize their mental health over other peoples",
    "what to do when they feel stuck in life",
    "how to process difficult emotions in healthy ways always",
    "whether they should forgive someone who hurt them badly",
    "how to rebuild trust after it's been broken before",
    "what self care actually looks like beyond face masks",
    "how to know if theyre growing or just changing",
    "whether they need space or need to push through",
    "how to communicate their needs without feeling selfish about",
    "what to do when they feel overwhelmed by everything",
    "how to know their worth and stop settling for",
    "whether theyre healing or just distracting themselves from pain",
  ],
  intellectual: [
    "book recommendations based on their interests and reading level",
    "how to think critically about information they consume daily",
    "what podcast or documentary they should watch next based",
    "how to form better arguments and debate more effectively",
    "the best ways to learn new things efficiently and",
    "what their perspective is missing and how to broaden",
    "how to research topics thoroughly without getting overwhelmed by",
    "the best resources for learning about complex topics easily",
    "how to have productive discussions instead of just arguments",
    "what biases they might have and how to address",
    "how to read more effectively and retain information better",
    "the best ways to stay informed without information overload",
    "how to analyze situations from multiple perspectives and angles",
    "what questions they should be asking themselves about life",
    "how to develop critical thinking skills in everyday situations",
    "the best ways to challenge their own beliefs respectfully",
    "how to make connections between seemingly unrelated concepts brilliantly",
    "what philosophical questions they should explore more deeply now",
    "how to articulate their thoughts and ideas more clearly",
    "the best ways to engage with ideas that challenge",
  ],
};

module.exports = myFriendsAskMeForAdviceAbout;
