const myFriendsAskMeForAdviceAbout = {
  funny: [
    "how to avoid adulting for as long as possible",
    "the best excuses to get out of plans last minute",
    "what to order at restaurants they have never been to",
    "how to look busy at work while doing nothing",
    "the perfect response to texts they do not want to answer",
    "how to survive on a budget of basically nothing",
    "what to watch when they have already watched everything",
    "how to make instant ramen taste like actual food",
    "the best ways to procrastinate productively on everything important",
    "what memes to send in every possible situation",
    "how to pretend they have their life together",
    "the art of canceling plans without feeling guilty",
    "how to survive family gatherings and awkward questions",
    "what to say when they have no idea what is happening",
    "how to make bad decisions sound like good ideas",
    "the best snacks for every mood and situation",
    "how to avoid small talk and awkward conversations",
    "what to binge watch next based on their mood",
    "how to look like they tried without actually trying",
    "the perfect comeback for every annoying situation",
  ],
  romantic: [
    "how to know if someone really likes them back",
    "what to text their crush without seeming too desperate",
    "how to get over someone they still have feelings for",
    "whether they should give their ex another chance",
    "how to know if it is love or just attachment",
    "what red flags they should actually pay attention to",
    "how to communicate better in their current relationship",
    "whether they should confess their feelings or wait longer",
    "how to know when to walk away from someone",
    "what to do when they catch feelings too fast",
    "how to set boundaries without pushing people away",
    "whether someone is worth fighting for or letting go",
    "how to know if they are settling or genuinely happy",
    "what love should actually feel like",
    "how to stop overthinking everything in their relationship",
    "whether they should text first or wait for them",
    "how to know if someone is emotionally available",
    "what to do when they like someone unavailable",
    "how to move on and actually mean it",
    "whether they deserve better or are being too picky",
  ],
  adventurous: [
    "the best travel destinations for their budget and vibe",
    "how to plan spontaneous trips without losing their mind",
    "what to pack for literally any type of adventure",
    "how to travel on a budget and still have fun",
    "the best hidden gems in cities they have never heard of",
    "how to convince their friends to take risks with them",
    "what adventure activities are actually worth the hype",
    "how to overcome fear and just do the thing",
    "the best road trip routes and stops along the way",
    "how to travel solo without being scared or lonely",
    "what experiences are worth spending money on",
    "how to make the most of weekend getaways nearby",
    "the best ways to meet people while traveling alone",
    "how to balance adventure with responsibilities",
    "what to do when wanderlust hits but budget is low",
    "how to find adventure in their everyday boring routine",
    "the best apps and resources for planning trips quickly",
    "how to stay safe while still having fun adventures",
    "what to do when they feel stuck and restless",
    "how to turn their life into an adventure story",
  ],
  quirky: [
    "the most random niche topics I know too much about",
    "how to organize literally everything in their chaotic life",
    "what their weirdly specific problem means about them",
    "the best personality tests to take at 2am",
    "how to embrace their weird quirks without feeling judged",
    "what their oddly specific preferences say about their personality",
    "the best ways to deep dive into random topics",
    "how to find their people who get their weird",
    "what comfort show they should rewatch based on mood",
    "the meaning behind their weird dreams and random thoughts",
    "how to make their niche interest seem cool",
    "what their specific organizational system says about their brain",
    "the best rabbit holes to fall down when bored",
    "how to explain their weird habits to normal people",
    "what their comfort items and routines mean",
    "the best ways to feed their oddly specific obsessions",
    "how to turn their quirks into their brand",
    "what their random collection hobby says about them",
    "the psychology behind their weirdly specific pet peeves",
    "how to find community around their niche interests",
  ],
  serious: [
    "how to set boundaries with family and toxic people",
    "what to do when they are struggling with mental health",
    "how to know when to walk away from relationships",
    "whether they should go to therapy",
    "how to deal with difficult people at work",
    "what to do when they feel lost and directionless",
    "how to have difficult conversations they have been avoiding",
    "whether they are being too hard on themselves",
    "how to prioritize their mental health",
    "what to do when they feel stuck in life",
    "how to process difficult emotions in healthy ways",
    "whether they should forgive someone who hurt them",
    "how to rebuild trust after it has been broken",
    "what self care actually looks like",
    "how to know if they are growing or just changing",
    "whether they need space or need to push through",
    "how to communicate their needs without feeling selfish",
    "what to do when they feel overwhelmed",
    "how to know their worth and stop settling",
    "whether they are healing or just distracting from pain",
  ],
  intellectual: [
    "book recommendations based on their interests",
    "how to think critically about information they consume",
    "what podcast or documentary they should watch next",
    "how to form better arguments",
    "the best ways to learn new things efficiently",
    "what their perspective is missing",
    "how to research topics thoroughly",
    "the best resources for learning about complex topics",
    "how to have productive discussions",
    "what biases they might have",
    "how to read more effectively",
    "the best ways to stay informed",
    "how to analyze situations from multiple perspectives",
    "what questions they should be asking themselves",
    "how to develop critical thinking skills",
    "the best ways to challenge their own beliefs",
    "how to make connections between seemingly unrelated concepts",
    "what philosophical questions they should explore",
    "how to articulate their thoughts",
    "the best ways to engage with ideas that challenge them",
  ],
};

module.exports = myFriendsAskMeForAdviceAbout;
