const myGreatestStrength = {
  "funny": [
    "making people laugh even when I'm not trying to be funny 😂",
    "finding humor in literally any situation no matter how awkward honestly",
    "being able to laugh at myself before anyone else can honestly",
    "turning any conversation into a comedy show without even trying really",
    "making awkward situations less awkward with my terrible jokes and timing",
    "being the comic relief in literally every friend group I'm in",
    "finding the funny side of things when everything's going wrong honestly",
    "making people smile even on their worst days with my energy",
    "not taking myself too seriously ever which is honestly a blessing",
    "being able to roast myself better than anyone else could",
    "lightening the mood when things get too serious or heavy honestly",
    "making people laugh until they cry with my random observations daily",
    "being effortlessly entertaining without even meaning to be most times honestly",
    "finding joy in the little things and sharing that with everyone",
    "being able to laugh through literally anything life throws at me",
    "making even boring situations fun with my chaotic energy and humor",
    "not being afraid to look silly if it makes someone laugh",
    "turning my embarrassing moments into funny stories people love hearing honestly",
    "being the person who can always make you smile no matter",
    "finding humor in my own mistakes and sharing them with everyone"
  ],
  "romantic": [
    "loving deeply and giving my whole heart to the right person ❤️",
    "being loyal and committed once I decide you're my person honestly",
    "making people feel seen heard and valued in my presence always",
    "showing love through actions not just words that mean nothing really",
    "being emotionally available and vulnerable with someone I trust completely and",
    "making my partner feel like the most important person in world",
    "being affectionate and showing love in little ways every single day",
    "communicating openly and honestly even when conversations are hard and uncomfortable",
    "being supportive of my partner's dreams and goals no matter what",
    "making people feel safe enough to be their authentic selves around",
    "being patient and understanding when my partner is going through things",
    "showing up consistently not just when it's easy or convenient for",
    "being thoughtful and remembering the little details that matter to you",
    "loving unconditionally through the good times and the challenging ones too",
    "being someone you can count on no matter what happens ever",
    "making my partner feel cherished and appreciated every single day honestly",
    "being emotionally intelligent and understanding what my partner needs without asking",
    "creating a safe space where vulnerability and honesty are always welcomed",
    "being intentional about building something real and lasting with my person",
    "loving with my whole heart and never holding back my feelings"
  ],
  "adventurous": [
    "being spontaneous and saying yes to new experiences and opportunities 🌟",
    "adapting quickly to new situations and going with the flow always",
    "being fearless when it comes to trying new things that scare",
    "pushing myself outside my comfort zone to grow and experience life",
    "being open to adventure and making the most of every opportunity",
    "staying positive and excited even when plans change or go wrong",
    "being willing to take risks and see where they lead me",
    "embracing change and uncertainty instead of fearing it like most people",
    "being curious about the world and wanting to experience everything possible",
    "staying flexible and making the best of any situation I'm in",
    "being brave enough to try things even when they're scary",
    "turning ordinary moments into adventures with my energy and attitude honestly",
    "being open minded and willing to explore new places and cultures",
    "staying enthusiastic about life and all the possibilities it holds for",
    "being resilient and bouncing back quickly from setbacks or failures always",
    "making every day an adventure even in small ways that matter",
    "being willing to get lost and find my way back stronger",
    "staying curious and never losing my sense of wonder about world",
    "being bold enough to chase experiences that others might avoid completely",
    "embracing the unknown and seeing it as an opportunity not threat"
  ],
  "quirky": [
    "being unapologetically myself even when it's weird or different from 🎨",
    "embracing my quirks and oddities instead of trying to hide them",
    "thinking differently and seeing things from unique perspectives others miss completely",
    "being creative and coming up with ideas nobody else would think",
    "celebrating what makes me different instead of trying to fit in",
    "being authentically weird and not caring what anyone thinks about it",
    "having unique interests that make me interesting and different from everyone",
    "being comfortable with being different and standing out from the crowd",
    "thinking outside the box and approaching problems in unconventional ways always",
    "being eccentric and owning it completely without any shame or apology",
    "having my own style and perspective that's totally unique to me",
    "being weird in the best way possible and attracting similar people",
    "embracing the unconventional and finding beauty in strange things others overlook",
    "being authentically myself even when it doesn't make sense to",
    "having niche interests that make me fascinating to the right people",
    "being comfortable in my own skin even when I'm different",
    "thinking creatively and seeing possibilities others don't even consider at all",
    "being uniquely me and not trying to be like anyone else",
    "celebrating my oddities and the things that make me stand out",
    "being perfectly imperfect and owning every bit of my weirdness completely"
  ],
  "serious": [
    "being reliable and following through on what I say I'll do",
    "staying committed to my goals even when things get difficult or",
    "being resilient and bouncing back from setbacks stronger than before always",
    "working hard and putting in effort to achieve what I want",
    "being disciplined and maintaining focus on my long term goals daily",
    "staying determined even when facing obstacles or challenges in my path",
    "being responsible and taking accountability for my actions and choices always",
    "persevering through difficult times instead of giving up when it's hard",
    "being self motivated and driven to improve myself constantly every day",
    "staying focused on what matters and not getting distracted by nonsense",
    "being dependable and someone people can count on no matter what",
    "working towards my goals consistently even when progress feels slow sometimes",
    "being mature and handling difficult situations with grace and composure always",
    "staying committed to personal growth and becoming better every single day",
    "being strong mentally and emotionally even during challenging times in life",
    "taking responsibility for my life and not making excuses for failures",
    "being dedicated to my values and not compromising them for anyone",
    "staying level headed and rational even in stressful situations that arise",
    "being someone who gets things done instead of just talking about",
    "maintaining integrity and doing what's right even when it's hard"
  ],
  "intellectual": [
    "being curious and always wanting to learn more about everything 🧠",
    "thinking critically and analyzing situations from multiple angles before deciding anything",
    "being open minded and willing to change my views with evidence",
    "asking thoughtful questions that get to the heart of issues quickly",
    "being able to see patterns and connections others might miss completely",
    "thinking deeply about complex topics and understanding nuance in everything around",
    "being articulate and expressing my thoughts clearly and effectively to others",
    "staying curious about the world and never stopping learning new things",
    "being analytical and approaching problems logically and systematically every time always",
    "thinking independently and forming my own well reasoned opinions on things",
    "being intellectually honest and admitting when I don't know something clearly",
    "understanding complex concepts and explaining them in simple terms to",
    "being thoughtful and considering different perspectives before forming strong opinions about",
    "staying engaged mentally and always seeking to expand my understanding of",
    "being able to debate ideas respectfully without getting defensive or personal",
    "thinking creatively and coming up with innovative solutions to problems I",
    "being well read and knowledgeable about many different topics and subjects",
    "staying intellectually curious and questioning assumptions instead of accepting things blindly",
    "being able to synthesize information from different sources into coherent understanding",
    "thinking philosophically about life and meaning and purpose of everything around"
  ],
  "default": [
    "being a good friend and showing up for people I care ✨",
    "staying positive even when things get tough or challenging in life",
    "being empathetic and understanding what others are going through without judgment",
    "working hard and putting in effort to achieve my goals daily",
    "being honest and authentic in all my relationships with people around",
    "staying resilient and bouncing back from setbacks stronger than before always",
    "being kind and treating everyone with respect no matter who they",
    "listening well and making people feel heard and understood when talking",
    "being adaptable and handling change with grace and flexibility always honestly",
    "staying determined and not giving up when things get difficult or",
    "being supportive and encouraging to the people in my life always",
    "working on myself and constantly trying to grow and improve daily",
    "being reliable and doing what I say I'm going to do",
    "staying open minded and willing to learn from anyone and everyone",
    "being genuine and real with people instead of putting on an",
    "making people feel comfortable and safe in my presence always honestly",
    "staying focused on what matters most to me in my life",
    "being patient and understanding with myself and others through everything that",
    "working towards my goals consistently even when progress feels slow sometimes",
    "being someone people can count on through good times and bad"
  ]
};

module.exports = myGreatestStrength;
