const myLastJournalEntryWasAbout = {
  funny: [
    "why i deserve a nap as a reward for",
    "ranking all my past embarrassing moments from worst to",
    "the internal debate about ordering takeout again this week",
    "why my pet is judging me and theyre right",
    "all the things i said id do but didnt",
    "my elaborate plan to avoid responsibilities for another day",
    "ranking every snack ive eaten this week by satisfaction",
    "the conspiracy theory that everyone is adulting better than",
    "why i cant be trusted in target with money",
    "my detailed analysis of why im the main character",
    "all the shows ive rewatched instead of starting new",
    "the existential crisis i had in the grocery store",
    "why i need to stop online shopping at midnight",
    "ranking my life choices from questionable to absolutely terrible",
    "the imaginary argument i won in the shower today",
    "why my screen time report personally attacked me this",
    "all the plans i made then immediately canceled later",
    "the internal monologue that never stops talking ever honestly",
    "why i deserve an award for getting out of",
    "my expert analysis of why naps are self care",
  ],
  romantic: [
    "the moment i realized i was falling for someone",
    "all the little things that made me smile today",
    "what i want my future relationship to look like",
    "the person who made me believe in love again",
    "how it feels to be loved the way i",
    "the moment i knew they were different from everyone",
    "what love has taught me about myself and life",
    "the fear of losing someone i care about deeply",
    "how they make me feel safe and seen and",
    "the future im starting to imagine with someone special",
    "what i learned about love from past relationships honestly",
    "the way they look at me and how it",
    "how scary it is to let someone in completely",
    "the small gestures that mean more than grand ones",
    "what i need to work on to be better",
    "the moment i realized i deserve real genuine love",
    "how different this feels from anything ive felt before",
    "the walls im learning to let down for someone",
    "what i want to tell them but havent yet",
    "how grateful i am for the love in life",
  ],
  adventurous: [
    "the trip im planning and cant stop thinking about",
    "the moment i felt most alive and free recently",
    "all the places i want to visit before i",
    "the adventure that changed my perspective on everything completely",
    "what im learning about myself through new experiences lately",
    "the fear i overcame and how good it felt",
    "the spontaneous decision that led to the best memories",
    "where i see myself in five years from now",
    "the bucket list item i finally checked off recently",
    "what stepping out of my comfort zone taught me",
    "the next big adventure im working toward and planning",
    "the moment i realized i was capable of more",
    "what travel has taught me about life and myself",
    "the risk i took that was totally worth it",
    "the places that feel like home even though theyre",
    "what im running toward instead of running away from",
    "the adventure that scared me but i did anyway",
    "the person i want to become through my experiences",
    "what living fully actually means to me right now",
    "the next chapter im ready to start in life",
  ],
  quirky: [
    "my oddly specific theory about something nobody cares about",
    "the random rabbit hole i fell down at 3am",
    "why my weirdly specific routine actually makes perfect sense",
    "the niche interest im currently obsessed with and researching",
    "my analysis of a show nobody else watches anymore",
    "the random connection i made between two unrelated things",
    "why my organizational system is genius even if chaotic",
    "the weird dream i had and what it means",
    "my ranking of things that dont need to be",
    "the oddly satisfying thing i did today that calmed",
    "why my comfort show is actually deeper than people",
    "the random skill im learning for absolutely no reason",
    "my theory about why i do things this specific",
    "the weird thing that brought me joy today unexpectedly",
    "why my quirks actually make me interesting not weird",
    "the random fact i learned that i'll never use",
    "my detailed analysis of my own personality test results",
    "the niche community i found online that gets me",
    "why my specific preferences are valid and make sense",
    "the random thing im collecting and why it matters",
  ],
  serious: [
    "the pattern im noticing in my relationships and behaviors",
    "what therapy helped me realize about myself this week",
    "the boundary i finally set and how it felt",
    "what im learning about my attachment style and triggers",
    "the progress ive made even when it doesnt feel",
    "what i need to work on to be healthier",
    "the difficult conversation i finally had with someone important",
    "what im grateful for even on the hard days",
    "the cycle im trying to break in my life",
    "what i learned about myself through recent struggles and",
    "the person im becoming and whether i like them",
    "what i need to forgive myself for and why",
    "the growth that came from the pain i experienced",
    "what my emotions are trying to tell me lately",
    "the relationship dynamic im trying to understand and change",
    "what self love actually looks like for me personally",
    "the fear im working through in therapy right now",
    "what i need from others and how to ask",
    "the healing that still needs to happen within me",
    "what im learning about my worth and value finally",
  ],
  intellectual: [
    "the book that completely changed my perspective on life",
    "the philosophical question im currently pondering deeply about existence",
    "what i learned from the documentary i watched recently",
    "the connection i made between two different concepts today",
    "my thoughts on a complex issue im trying to",
    "the pattern im noticing in society and human behavior",
    "what the podcast i listened to made me think",
    "the theory im developing about something ive been observing",
    "my analysis of current events and what they mean",
    "the question that keeps me up at night thinking",
    "what im learning about human nature through observation and",
    "the idea that challenged my existing beliefs and assumptions",
    "my thoughts on the meaning of life and purpose",
    "what im discovering through my research on random topics",
    "the perspective shift that happened after reading something new",
    "my analysis of why people behave the way they",
    "the concept im trying to fully understand and articulate",
    "what im learning about myself through self reflection and",
    "the debate im having with myself about important issues",
    "my thoughts on how to live a meaningful life",
  ],
};

module.exports = myLastJournalEntryWasAbout;
