const myLastJournalEntryWasAbout = {
  funny: [
    "why I deserve a nap as a reward",
    "ranking all my past embarrassing moments from worst to best",
    "the internal debate about ordering takeout again",
    "why my pet is judging me and they are right",
    "all the things I said I would do but did not",
    "my elaborate plan to avoid responsibilities for another day",
    "ranking every snack I have eaten this week by satisfaction",
    "the conspiracy theory that everyone is adulting better than me",
    "why I cannot be trusted in Target with money",
    "my detailed analysis of why I am the main character",
    "all the shows I have rewatched instead of starting new ones",
    "the existential crisis I had in the grocery store",
    "why I need to stop online shopping at midnight",
    "ranking my life choices from questionable to absolutely terrible",
    "the imaginary argument I won in the shower today",
    "why my screen time report personally attacked me this week",
    "all the plans I made then immediately canceled later",
    "the internal monologue that never stops talking",
    "why I deserve an award for getting out of bed",
    "my expert analysis of why naps are self care",
  ],
  romantic: [
    "the moment I realized I was falling for someone",
    "all the little things that made me smile today",
    "what I want my future relationship to look like",
    "the person who made me believe in love again",
    "how it feels to be loved the way I deserve",
    "the moment I knew they were different from everyone",
    "what love has taught me about myself and life",
    "the fear of losing someone I care about deeply",
    "how they make me feel safe and seen",
    "the future I am starting to imagine with someone special",
    "what I learned about love from past relationships",
    "the way they look at me",
    "how scary it is to let someone in completely",
    "the small gestures that mean more than grand ones",
    "what I need to work on to be better",
    "the moment I realized I deserve real genuine love",
    "how different this feels from anything I have felt before",
    "the walls I am learning to let down",
    "what I want to tell them but have not yet",
    "how grateful I am for the love in my life",
  ],
  adventurous: [
    "the trip I am planning and cannot stop thinking about",
    "the moment I felt most alive and free recently",
    "all the places I want to visit before I die",
    "the adventure that changed my perspective on everything",
    "what I am learning about myself through new experiences",
    "the fear I overcame and how good it felt",
    "the spontaneous decision that led to the best memories",
    "where I see myself in five years",
    "the bucket list item I finally checked off recently",
    "what stepping out of my comfort zone taught me",
    "the next big adventure I am working toward",
    "the moment I realized I was capable of more",
    "what travel has taught me about life and myself",
    "the risk I took that was totally worth it",
    "the places that feel like home even though they are not",
    "what I am running toward instead of running away from",
    "the adventure that scared me but I did anyway",
    "the person I want to become through my experiences",
    "what living fully actually means to me right now",
    "the next chapter I am ready to start",
  ],
  quirky: [
    "my oddly specific theory about something nobody cares about",
    "the random rabbit hole I fell down at 3am",
    "why my weirdly specific routine actually makes perfect sense",
    "the niche interest I am currently obsessed with",
    "my analysis of a show nobody else watches anymore",
    "the random connection I made between two unrelated things",
    "why my organizational system is genius even if chaotic",
    "the weird dream I had and what it means",
    "my ranking of things that do not need to be ranked",
    "the oddly satisfying thing I did today",
    "why my comfort show is actually deeper than people think",
    "the random skill I am learning for absolutely no reason",
    "my theory about why I do things this specific way",
    "the weird thing that brought me joy today unexpectedly",
    "why my quirks actually make me interesting not weird",
    "the random fact I learned that I will never use",
    "my detailed analysis of my own personality test results",
    "the niche community I found online that gets me",
    "why my specific preferences are valid and make sense",
    "the random thing I am collecting and why it matters",
  ],
  serious: [
    "the pattern I am noticing in my relationships and behaviors",
    "what therapy helped me realize about myself this week",
    "the boundary I finally set and how it felt",
    "what I am learning about my attachment style and triggers",
    "the progress I have made even when it does not feel like it",
    "what I need to work on to be healthier",
    "the difficult conversation I finally had with someone important",
    "what I am grateful for even on the hard days",
    "the cycle I am trying to break in my life",
    "what I learned about myself through recent struggles",
    "the person I am becoming and whether I like them",
    "what I need to forgive myself for and why",
    "the growth that came from the pain I experienced",
    "what my emotions are trying to tell me lately",
    "the relationship dynamic I am trying to understand and change",
    "what self love actually looks like for me",
    "the fear I am working through in therapy",
    "what I need from others and how to ask",
    "the healing that still needs to happen within me",
    "what I am learning about my worth and value",
  ],
  intellectual: [
    "the book that completely changed my perspective on life",
    "the philosophical question I am currently pondering",
    "what I learned from the documentary I watched recently",
    "the connection I made between two different concepts today",
    "my thoughts on a complex issue I am trying to understand",
    "the pattern I am noticing in society and human behavior",
    "what the podcast I listened to made me think",
    "the theory I am developing about something I have been observing",
    "my analysis of current events",
    "the question that keeps me up at night",
    "what I am learning about human nature",
    "the idea that challenged my existing beliefs",
    "my thoughts on the meaning of life and purpose",
    "what I am discovering through my research on random topics",
    "the perspective shift that happened after reading something new",
    "my analysis of why people behave the way they do",
    "the concept I am trying to fully understand",
    "what I am learning about myself through self reflection",
    "the debate I am having with myself about important issues",
    "my thoughts on how to live a meaningful life",
  ],
};

module.exports = myLastJournalEntryWasAbout;
