const myLoveLanguageIs = {
  "funny": [
    "memes and sending you random stuff that made me laugh today 😂",
    "food because the way to my heart is literally through snacks",
    "quality time but like on the couch doing absolutely nothing together",
    "physical touch but mostly just stealing your hoodies and wearing them",
    "words of affirmation but make them funny compliments that are kinda",
    "acts of service like making you coffee even though I'm tired",
    "gift giving but it's mostly just random things that reminded me",
    "sending you memes at 2am because I thought you'd find funny",
    "making you laugh when you're having a bad day always honestly",
    "sharing my food with you which is basically true love honestly",
    "remembering your coffee order and surprising you with it randomly sometimes",
    "roasting you lovingly because that's how I show I care honestly",
    "buying you snacks when I go to the store without asking",
    "sending you tiktoks that only we would find funny together honestly",
    "making playlists for you with songs that remind me of us",
    "texting you random updates about my day even when boring honestly",
    "letting you have the last bite even though I want it",
    "laughing at your jokes even when they're really not that funny",
    "sharing my spotify password which is basically a marriage proposal honestly",
    "remembering inside jokes and bringing them up at random times always"
  ],
  "romantic": [
    "quality time where we're fully present with each other always ❤️",
    "physical touch like holding hands and random hugs throughout the day",
    "words of affirmation that remind you how much you mean to me",
    "acts of service doing little things to make your life easier",
    "gift giving thoughtful presents that show I was thinking of you",
    "deep conversations late at night where we share everything with each",
    "physical affection like cuddling and being close to you always honestly",
    "verbal affirmation telling you I love you and why every day",
    "thoughtful gestures that show I pay attention to what you need",
    "quality time creating memories together and being fully present in moments",
    "touch and affection showing love through hugs kisses and gentle touches",
    "meaningful gifts that have thought and personal significance behind them always",
    "acts of kindness doing things for you without being asked to",
    "expressing feelings openly and honestly about how much I care deeply",
    "spending intentional time together without distractions from phones or anything",
    "physical closeness feeling connected through touch and being near you always",
    "loving words that build you up and make you feel valued",
    "helpful actions that show I care by making your day better",
    "thoughtful surprises that show I remember what matters to you most",
    "emotional intimacy sharing our deepest thoughts and feelings with each other"
  ],
  "adventurous": [
    "trying new experiences together and making memories along the way 🌟",
    "spontaneous adventures even if they're just exploring our own city together",
    "quality time doing exciting activities that push us outside comfort zones",
    "shared experiences like traveling and discovering new places with you always",
    "adventure dates where we try something neither of us has done",
    "exploring together whether it's new restaurants or hiking trails we find",
    "making memories through experiences rather than just material things we buy",
    "spontaneous trips and saying yes to random adventures that come up",
    "trying new activities together even when they scare us a little",
    "shared adventures that become stories we'll tell for years to come",
    "exploring the world together one new experience at a time honestly",
    "quality time filled with excitement and new things to discover together",
    "adventure and spontaneity keeping life interesting and full of surprises always",
    "creating experiences together that we'll remember forever and talk about later",
    "trying everything once together and seeing where adventures take us next",
    "spontaneous dates where we don't plan and just see what happens",
    "shared exploration of new places foods and activities we've never tried",
    "making every day an adventure even in small ways together",
    "experiencing life fully together through travel and trying new things always",
    "building a life full of stories and memories from our adventures"
  ],
  "quirky": [
    "weird inside jokes that only we understand and make us laugh 🎨",
    "sharing niche interests and geeking out together about random obscure things",
    "quality time doing our own weird hobbies side by side together",
    "making each other playlists with oddly specific vibes and random songs",
    "sending each other weird memes and random thoughts throughout the day",
    "appreciating each other's quirks and celebrating what makes us different and",
    "parallel play where we do our own things but together",
    "sharing random facts and having deep conversations about weird topics late",
    "making up our own traditions that don't make sense to anyone",
    "being weird together and not caring what anyone else thinks honestly",
    "collecting random things together that have meaning only to us two",
    "having our own language of references nobody else would understand at",
    "quality time being authentically ourselves without trying to be normal ever",
    "appreciating the unconventional and finding beauty in strange things together always",
    "sharing our weird interests and learning about each other's niche hobbies",
    "making art or creating things together even if they're kinda weird",
    "having deep philosophical conversations about random things at 3am honestly together",
    "celebrating our differences and the quirky things that make us unique",
    "being comfortable in silence and doing our own thing side by",
    "embracing the weird and making our relationship uniquely ours in every"
  ],
  "serious": [
    "acts of service doing things that genuinely help and support you",
    "quality time with intentional presence and meaningful conversations about life and",
    "consistent effort showing up every day not just when it's easy",
    "emotional support being there when you need me most without question",
    "reliability and consistency so you know you can count on me",
    "words of affirmation that are genuine and specific to who you",
    "acts of service that show I prioritize your needs and wellbeing",
    "quality time where we build our relationship through deep connection and",
    "physical touch that provides comfort and shows I'm here for you",
    "thoughtful actions that demonstrate I understand and care about your needs",
    "emotional availability being present and supportive through everything you're going through",
    "consistent communication keeping you updated and making you feel secure always",
    "acts of care doing things that make your life easier better",
    "dedicated time together where you're my priority and focus completely always",
    "supportive words that encourage you and remind you of your worth",
    "practical help with things you're struggling with or need assistance on",
    "emotional intimacy sharing our lives fully and being vulnerable with each",
    "reliable presence showing up consistently and being someone you can trust",
    "meaningful gestures that show I pay attention to what matters to",
    "commitment and dedication to building something real and lasting together always"
  ],
  "intellectual": [
    "deep conversations where we explore ideas and challenge each other's thinking 🧠",
    "quality time discussing books philosophy and topics that fascinate us both deeply",
    "intellectual stimulation through debates and conversations that make me think differently",
    "sharing knowledge teaching each other things and learning together about everything",
    "meaningful discussions about life purpose and the things that matter most",
    "words that are thoughtful and show you understand me on deep",
    "quality time where we engage mentally and explore ideas together always",
    "intellectual connection through conversations that go beyond surface level small talk",
    "sharing perspectives and learning from each other's different viewpoints on things",
    "deep discussions that challenge assumptions and help us both grow mentally",
    "thoughtful communication where we really listen and understand each other fully",
    "exploring ideas together through reading discussing and questioning everything around us",
    "mental stimulation from conversations that make me see things in new",
    "quality time spent learning together and expanding our understanding of world",
    "intellectual partnership where we push each other to think more deeply",
    "meaningful dialogue about topics we're passionate about and want to explore",
    "sharing curiosity and discovering new things together through learning and discussion",
    "thoughtful exchanges where we really engage with each other's ideas and",
    "deep connection through understanding each other's minds and how we think",
    "intellectual intimacy sharing our thoughts perspectives and the way we see"
  ],
  "default": [
    "quality time just being together and enjoying each other's company fully ✨",
    "physical touch like hugs and holding hands that make me feel",
    "words of affirmation that remind me you care and appreciate me",
    "acts of service doing thoughtful things that make my life easier",
    "thoughtful gestures that show you're thinking of me throughout the day",
    "spending time together without distractions just focusing on us and connection",
    "affection and closeness feeling connected through touch and physical presence always",
    "kind words that build me up and make me feel valued",
    "helpful actions that show you care about my wellbeing and happiness",
    "quality moments where we're present and engaged with each other fully",
    "physical affection that makes me feel loved and secure with you",
    "verbal expressions of love and appreciation that you share with me",
    "thoughtful acts that show you pay attention to what I need",
    "time together creating memories and strengthening our bond as a couple",
    "touch and closeness that provides comfort and shows your love for",
    "affirming words that make me feel seen and appreciated for who",
    "caring actions that demonstrate your love through what you do for",
    "meaningful time spent together building our relationship and connection with each",
    "affectionate touch that reminds me we're connected and in this together",
    "loving words and actions that show me I matter to you"
  ]
};

module.exports = myLoveLanguageIs;
