const myMostIrrationalFear = {
  "funny": [
    "that everyone secretly finds me annoying but nobody tells me 😂",
    "accidentally liking someone's old instagram post from like three years ago",
    "forgetting how to walk normally when someone's watching me walk",
    "that I've been pronouncing a common word wrong my whole",
    "getting stuck in a conversation with no way to escape",
    "that my alarm won't go off and I'll sleep forever",
    "accidentally sending a text to the person I'm talking about",
    "that everyone can hear my stomach growling in quiet rooms",
    "forgetting someone's name right after they just told me it",
    "that I left the stove on even though I checked",
    "accidentally calling my boss mom or something equally embarrassing and awkward",
    "that my fly is down and everyone noticed but me",
    "getting trapped in a small talk loop that never ends",
    "that I'm the only one who doesn't understand the joke",
    "accidentally waving back at someone who wasn't waving at me",
    "that my headphones aren't plugged in and everyone heard everything",
    "forgetting what I was saying mid sentence in front of people",
    "that I have food stuck in my teeth all day",
    "accidentally replying all to an email I shouldn't have sent",
    "that everyone's just being nice and secretly thinks I'm weird"
  ],
  "romantic": [
    "falling for someone who doesn't feel the same way back ❤️",
    "being vulnerable and getting hurt by someone I really care about",
    "opening up completely and then being left or abandoned after",
    "not being enough for someone I love with my whole heart",
    "losing someone I care about because I wasn't good enough",
    "being replaced by someone better after I gave my whole heart",
    "trusting someone completely and having that trust broken by them",
    "loving someone more than they love me and feeling that",
    "being too much or not enough for the person I",
    "getting hurt again after finally opening my heart to someone",
    "falling in love and then watching it fall apart slowly",
    "not being loved the way I love other people deeply",
    "being vulnerable and having my feelings dismissed or minimized by",
    "losing myself in a relationship and forgetting who I am",
    "giving my heart to someone who doesn't treasure it properly",
    "being left after showing someone my true authentic self completely",
    "loving someone who can't or won't love me back fully",
    "opening up about my feelings and being rejected or laughed",
    "trusting again and getting hurt in the same way as",
    "not being chosen by someone I would choose every time"
  ],
  "adventurous": [
    "missing out on amazing experiences because I was too scared 🌟",
    "regretting not taking chances when I had the opportunity to",
    "staying in my comfort zone and never experiencing life fully",
    "looking back and wishing I had been braver when younger",
    "letting fear hold me back from adventures I'll never get",
    "playing it safe and missing out on the best stories",
    "not taking risks and living a boring predictable life instead",
    "being too cautious and never discovering what I'm capable of",
    "letting opportunities pass by because I was afraid to try",
    "staying comfortable and never pushing myself to grow and explore",
    "missing out on life because I was too worried about",
    "not saying yes to adventures and regretting it later in",
    "being too afraid to try new things and staying stagnant",
    "letting fear of failure stop me from attempting great things",
    "playing it safe my whole life and having no stories",
    "missing chances to explore because I was too scared to",
    "not taking the leap when opportunities present themselves to me",
    "staying in one place and never experiencing the world fully",
    "being too cautious and never living up to my full",
    "letting fear control my decisions and missing out on life"
  ],
  "quirky": [
    "that birds are secretly plotting something and we don't know 🎨",
    "accidentally stepping on a crack and actually breaking my mom's",
    "that my plants are judging me for forgetting to water",
    "that inanimate objects have feelings and I've hurt them somehow",
    "walking under ladders even though I know it's probably fine",
    "that my stuffed animals come alive when I leave the",
    "accidentally summoning something by saying a word three times in",
    "that mirrors are portals and something will come through one",
    "that my phone is listening to my thoughts not just",
    "accidentally creating a time paradox by doing something small and",
    "that pigeons are government drones and nobody believes me about",
    "that I'm living in a simulation and glitches will",
    "accidentally offending a ghost and being haunted for the rest",
    "that my dreams are actually alternate realities I'm visiting at",
    "walking past mirrors at night because something might look back",
    "that déjà vu means I died in another timeline and",
    "accidentally breaking a mirror and actually getting seven years of",
    "that my pet knows all my secrets and judges me",
    "opening my eyes underwater in the shower because something's there",
    "that parallel universe me is living my best life instead"
  ],
  "serious": [
    "not living up to my potential and wasting my talents",
    "failing to achieve my goals despite working hard for them",
    "disappointing the people who believe in me and my abilities",
    "not being successful enough to provide for my future family",
    "making the wrong decisions that negatively impact my future self",
    "not being financially stable and struggling later in my life",
    "failing at my career and not reaching the success I",
    "not being able to support myself or my loved ones",
    "making mistakes that I can't come back from or fix",
    "not achieving the life I've been working so hard toward",
    "letting my fears hold me back from reaching my goals",
    "not being good enough at what I do professionally or",
    "failing to build the secure future I want for myself",
    "making poor choices that derail my carefully planned life path",
    "not reaching my full potential because of self doubt or",
    "disappointing myself by not following through on my commitments and",
    "not being prepared for emergencies or unexpected life challenges ahead",
    "failing to build the life I've always envisioned for myself",
    "not being successful enough to make my sacrifices worth it",
    "making irreversible mistakes that impact my long term future negatively"
  ],
  "intellectual": [
    "being wrong about fundamental beliefs I've held my whole life 🧠",
    "not being as smart as I think I am honestly",
    "missing obvious things that everyone else seems to understand clearly",
    "being confidently incorrect about something important in front of people",
    "not understanding concepts that others find simple or easy to",
    "having my worldview completely shattered by new information or evidence",
    "being stuck in echo chambers and not realizing my bias",
    "not questioning my assumptions enough and being fundamentally wrong about",
    "missing nuance in complex issues and oversimplifying things that aren't",
    "being intellectually arrogant and not recognizing my own ignorance about",
    "not growing intellectually and staying stagnant in my thinking forever",
    "being wrong about things I've argued passionately about for years",
    "not recognizing my own cognitive biases and blind spots clearly",
    "missing connections and patterns that are obvious to everyone else",
    "being less knowledgeable than I present myself as being to",
    "not understanding the implications of ideas I claim to understand fully",
    "being intellectually lazy and not challenging my own beliefs enough",
    "missing the bigger picture while focusing on irrelevant details instead",
    "not being open minded enough and dismissing valid perspectives too",
    "being wrong about fundamental aspects of how the world works"
  ],
  "default": [
    "losing the people I love most in my life ✨",
    "not being good enough for the people who matter to",
    "failing at the things that are most important to me",
    "being alone and not having meaningful connections with anyone ever",
    "not living a life that feels meaningful or purposeful to",
    "disappointing myself and the people who believe in me always",
    "making mistakes that hurt the people I care about most",
    "not being loved or valued by the people around me",
    "losing myself and forgetting who I really am inside",
    "not making a positive impact on anyone's life at all",
    "being forgotten or not mattering to anyone in the",
    "not being strong enough to handle what life throws at",
    "losing my sense of purpose and direction in my life",
    "not being there for people when they need me most",
    "making choices I'll regret for the rest of my life",
    "not being able to overcome my fears and limitations ever",
    "losing the things that make me who I am today",
    "not being remembered or leaving any kind of lasting impact",
    "failing the people who depend on me when it matters",
    "not living authentically and true to who I really am"
  ]
};

module.exports = myMostIrrationalFear;
