const mySelfcareRoutineIs = {
  funny: [
    "eating snacks in bed while watching trash TV",
    "online shopping then abandoning my cart",
    "taking a nap and calling it meditation",
    "scrolling through memes until I forget my problems",
    "doing a face mask while eating junk food",
    "staying in bed all day without shame",
    "watching my comfort show for the hundredth time",
    "ordering takeout because cooking is too much effort",
    "ignoring all my responsibilities",
    "talking to my pet about all my problems",
    "making elaborate snacks at midnight",
    "canceling all my plans",
    "doing absolutely nothing productive",
    "retail therapy in my cart without buying anything",
    "binge watching reality TV and judging everyone",
    "eating ice cream straight from the container",
    "scrolling social media until my eyes hurt",
    "taking a bubble bath with snacks",
    "having a full spa day at home",
    "doing nothing and calling it rest",
  ],
  romantic: [
    "writing in my journal about things I am grateful for",
    "listening to love songs and daydreaming about my future",
    "taking long walks while thinking about someone special",
    "reading romance novels that make me believe in love",
    "calling someone who always makes me feel better",
    "looking at old photos and messages that make me smile",
    "doing things that make me feel beautiful and confident",
    "spending quality time with people I love",
    "writing letters to people I care about even if unsent",
    "watching romantic movies that make me cry happy tears",
    "lighting candles and creating a cozy peaceful atmosphere",
    "listening to our playlist and replaying favorite memories",
    "doing small acts of kindness for others and myself",
    "taking bubble baths with soft music",
    "planning future adventures with someone I care about",
    "practicing self love and treating myself with kindness",
    "spending time in nature feeling grateful",
    "doing things that nourish my soul",
    "reminding myself that I am worthy of love",
    "creating space for love and joy in my life",
  ],
  adventurous: [
    "going for a run or hike to clear my head",
    "trying a new workout class that challenges me",
    "planning my next trip and getting excited",
    "going for drives with no destination just music blasting",
    "exploring new parts of the city",
    "doing something that scares me a little",
    "going somewhere in nature to breathe and reset",
    "trying a new restaurant or cafe",
    "booking spontaneous weekend getaways to look forward to",
    "going on solo adventures to reconnect with myself",
    "doing activities that get my adrenaline going",
    "taking different routes and discovering new places",
    "going to random events I find online",
    "trying new hobbies and activities",
    "going to the beach or lake to reset",
    "doing outdoor activities that make me feel alive",
    "exploring farmers markets and trying samples",
    "going for bike rides",
    "doing something spontaneous that breaks my routine",
    "planning adventures to give myself something to look forward to",
  ],
  quirky: [
    "reorganizing my entire space at midnight",
    "making oddly specific playlists for every possible mood",
    "doing a full skincare routine with ten steps",
    "watching oddly satisfying videos until I feel calm",
    "color coding everything in my life",
    "doing craft projects I saw online",
    "making lists of literally everything",
    "watching people clean and organize on social media",
    "doing jigsaw puzzles while listening to podcasts",
    "researching random topics until I feel like an expert",
    "organizing my bookshelf then changing it back",
    "doing personality tests to confirm what I already know",
    "making mood boards for aesthetics",
    "learning random skills from YouTube",
    "doing those oddly repetitive tasks that calm my brain",
    "watching restoration videos of things being fixed",
    "organizing my closet by color and season",
    "doing weird rituals that only make sense to me",
    "making elaborate plans I probably will not follow through with",
    "learning about random topics through Wikipedia rabbit holes",
  ],
  serious: [
    "journaling and processing my thoughts and feelings",
    "meditating and practicing mindfulness to center myself",
    "going to therapy and doing the homework",
    "setting boundaries with my time and energy",
    "doing yoga or stretching to reconnect with my body",
    "reading self development books that challenge my perspective",
    "going for quiet walks alone to clear my head",
    "practicing gratitude even when it is hard",
    "disconnecting from social media and being present",
    "reflecting on my goals and progress",
    "having honest conversations with myself about what I need",
    "doing actual self care that nourishes me",
    "allowing myself to feel emotions without judging them",
    "working on hobbies that bring me genuine joy",
    "spending intentional quality time with people who matter",
    "processing emotions through writing or creative expression",
    "setting intentions for the next day and week",
    "creating space for rest without guilt",
    "reflecting on my values",
    "giving myself permission to not be okay",
  ],
  intellectual: [
    "reading books that challenge my current way of thinking",
    "listening to podcasts about psychology philosophy or science",
    "watching documentaries that teach me something new",
    "writing and exploring ideas I have been thinking about",
    "researching topics that sparked my curiosity",
    "doing puzzles or brain games that challenge me",
    "reading articles about current events",
    "listening to lectures or talks from experts",
    "learning a new skill through online courses",
    "having deep conversations with people who challenge my thinking",
    "reading poetry or literature that makes me think differently",
    "exploring new perspectives through books from different cultures",
    "watching TED talks about topics outside my usual interests",
    "writing essays or thoughts about concepts",
    "learning about history and connecting it to present day",
    "reading scientific studies about things I find fascinating",
    "listening to music and analyzing the lyrics",
    "exploring philosophical questions",
    "reading biographies of people who changed the world",
    "learning languages or studying linguistics for fun",
  ],
};

module.exports = mySelfcareRoutineIs;
