const mySelfcareRoutineIs = {
  funny: [
    "eating snacks in bed while watching trash tv honestly",
    "online shopping then abandoning my cart feeling no guilt",
    "taking a nap and calling it meditation for wellness",
    "scrolling through memes until i forget my problems completely",
    "doing a face mask while eating junk food simultaneously",
    "staying in bed all day without any shame whatsoever",
    "watching my comfort show for the hundredth time again",
    "ordering takeout because cooking is too much effort today",
    "ignoring all my responsibilities and calling it a day",
    "talking to my pet about all my life problems",
    "making elaborate snacks at midnight i dont need really",
    "canceling all my plans and feeling zero guilt about",
    "doing absolutely nothing productive and loving every minute of",
    "retail therapy in my cart without actually buying anything",
    "binge watching reality tv and judging everyone elses choices",
    "eating ice cream straight from the container unapologetically always",
    "scrolling social media until my eyes hurt from screen",
    "taking a bubble bath with snacks and my phone",
    "having a full spa day at home basically",
    "doing nothing and calling it rest and recovery time",
  ],
  romantic: [
    "writing in my journal about things im grateful for",
    "listening to love songs and daydreaming about my future",
    "taking long walks while thinking about someone special always",
    "reading romance novels that make me believe in love",
    "calling someone who always makes me feel better instantly",
    "looking at old photos and messages that make smile",
    "doing things that make me feel beautiful and confident",
    "spending quality time with people i love most dearly",
    "writing letters to people i care about even unsent",
    "watching romantic movies that make me cry happy tears",
    "lighting candles and creating a cozy peaceful atmosphere everywhere",
    "listening to our playlist and replaying favorite memories together",
    "doing small acts of kindness for others and myself",
    "taking bubble baths with soft music playing in background",
    "planning future adventures with someone i care about deeply",
    "practicing self love and treating myself with kindness always",
    "spending time in nature feeling grateful for life beauty",
    "doing things that nourish my soul and heart deeply",
    "reminding myself that im worthy of love and goodness",
    "creating space for love and joy in my life",
  ],
  adventurous: [
    "going for a run or hike to clear my",
    "trying a new workout class that challenges me physically",
    "planning my next trip and getting excited about it",
    "going for drives with no destination just music blasting",
    "exploring new parts of the city ive never been",
    "doing something that scares me a little bit honestly",
    "going somewhere in nature to breathe and reset myself",
    "trying a new restaurant or cafe ive never visited",
    "booking spontaneous weekend getaways to look forward to soon",
    "going on solo adventures to reconnect with myself fully",
    "doing activities that get my adrenaline going and pumping",
    "taking different routes and discovering new places around me",
    "going to random events i find online last minute",
    "trying new hobbies and activities ive been curious about",
    "going to the beach or lake to reset energy",
    "doing outdoor activities that make me feel alive again",
    "exploring farmers markets and trying all the new samples",
    "going for bike rides to nowhere in particular today",
    "doing something spontaneous that breaks my usual routine completely",
    "planning adventures to give myself something to look forward",
  ],
  quirky: [
    "reorganizing my entire space at midnight for no reason",
    "making oddly specific playlists for every possible mood ever",
    "doing a full skincare routine with like ten steps",
    "watching oddly satisfying videos until i feel calm again",
    "color coding everything in my life including my calendar",
    "doing craft projects i saw online probably wont finish",
    "making lists of literally everything to feel in control",
    "watching people clean and organize on social media satisfyingly",
    "doing jigsaw puzzles while listening to murder mystery podcasts",
    "researching random topics until i feel like an expert",
    "organizing my bookshelf then changing it back again later",
    "doing personality tests to confirm what i already know",
    "making mood boards for aesthetics ill never actually achieve",
    "learning random skills from youtube at odd hours nightly",
    "doing those oddly repetitive tasks that calm my brain",
    "watching restoration videos of things being fixed so satisfying",
    "organizing my closet by color and season and vibe",
    "doing weird rituals that only make sense to me",
    "making elaborate plans i probably wont follow through with",
    "learning about random topics through wikipedia rabbit holes for",
  ],
  serious: [
    "journaling and processing my thoughts and feelings from today",
    "meditating and practicing mindfulness to center myself again here",
    "going to therapy and doing the homework assigned to",
    "setting boundaries with my time and energy for tomorrow",
    "doing yoga or stretching to reconnect with my body",
    "reading self development books that challenge my perspective daily",
    "going for quiet walks alone to clear my head",
    "practicing gratitude even when its hard to find things",
    "disconnecting from social media and being present with myself",
    "reflecting on my goals and progress ive made recently",
    "having honest conversations with myself about what i need",
    "doing actual self care that nourishes me not just",
    "allowing myself to feel emotions without judging them harshly",
    "working on hobbies that bring me genuine joy and",
    "spending intentional quality time with people who matter most",
    "processing emotions through writing or creative expression honestly here",
    "setting intentions for the next day and week ahead",
    "creating space for rest without guilt or productivity pressure",
    "reflecting on my values and whether im living aligned",
    "giving myself permission to not be okay sometimes today",
  ],
  intellectual: [
    "reading books that challenge my current way of thinking",
    "listening to podcasts about psychology philosophy or science topics",
    "watching documentaries that teach me something completely new today",
    "writing and exploring ideas ive been thinking about lately",
    "researching topics that sparked my curiosity during the day",
    "doing puzzles or brain games that actually challenge me",
    "reading articles about current events and forming my opinions",
    "listening to lectures or talks from experts in various",
    "learning a new skill through online courses or tutorials",
    "having deep conversations with people who challenge my thinking",
    "reading poetry or literature that makes me think differently",
    "exploring new perspectives through books from different cultures always",
    "watching ted talks about topics outside my usual interests",
    "writing essays or thoughts about concepts im trying to",
    "learning about history and connecting it to present day",
    "reading scientific studies about things i find fascinating currently here",
    "listening to music and analyzing the lyrics and composition",
    "exploring philosophical questions that dont have easy answers at",
    "reading biographies of people who changed the world somehow",
    "learning languages or studying linguistics just for fun honestly",
  ],
};

module.exports = mySelfcareRoutineIs;
