const mySimplePleasures = {
  "funny": [
    "sleeping in on weekends and ignoring all my responsibilities completely 😂",
    "finding money in pockets I forgot about which feels like winning",
    "when plans get cancelled so I can stay home guilt", "perfectly timed naps that make me feel like a brand new",
    "free food because there's nothing better than food you didn't",
    "getting into bed with freshly washed sheets that smell amazing honestly",
    "when my food delivery arrives way faster than the app said",
    "finding the perfect meme that describes my exact current mood right",
    "coffee that hits different on a monday morning when I need",
    "when someone else does the dishes so I don't have to",
    "lazy sundays where I have zero plans and zero responsibilities at",
    "when my favorite song comes on shuffle at the perfect moment",
    "online shopping deals that make me feel like I'm winning at",
    "staying in my pajamas all day without any judgment from anyone",
    "when my package arrives early and I forgot I even ordered",
    "perfectly cooked food that I didn't have to make myself honestly",
    "finding a new show to binge that's actually good and", "when everything just works out without any stress or extra effort",
    "cozy rainy days where staying inside feels totally justified and perfect",
    "when someone brings me snacks without me even having to ask"
  ],
  "romantic": [
    "holding hands while walking and feeling completely connected to someone ❤️",
    "good morning texts that make me smile before I'm even",
    "random hugs from behind that make me feel safe and loved",
    "deep conversations late at night where we share everything with each",
    "when someone remembers my coffee order and surprises me with it",
    "forehead kisses that feel more intimate than anything else in world",
    "cuddling on the couch while watching movies together in comfortable silence",
    "when someone plays with my hair and it's the most",
    "meaningful eye contact that says everything without needing any words at",
    "cooking together and dancing in the kitchen to our favorite songs",
    "falling asleep next to someone I love and feeling completely safe",
    "when someone sends me songs that remind them of me",
    "lazy morning cuddles where we don't want to leave bed ever",
    "when someone looks at me like I'm the only person",
    "sharing comfortable silence where we don't need to fill every",
    "random I love yous throughout the day that feel so genuine",
    "when someone remembers small details I mentioned weeks ago to them",
    "goodnight kisses that make me feel loved before falling asleep peacefully",
    "being the little spoon and feeling protected and cared for",
    "when someone makes me feel beautiful without any makeup or effort"
  ],
  "adventurous": [
    "sunrise hikes that make waking up early actually worth it 🌟",
    "spontaneous road trips with no destination just good music and vibes",
    "trying new foods from cuisines I've never experienced before at",
    "exploring new neighborhoods and finding hidden gems nobody knows about yet",
    "weekend getaways to places I've never been to before in",
    "outdoor adventures that make me feel alive and connected to",
    "discovering new trails and paths I didn't know existed near me",
    "trying activities that scare me a little but excite me",
    "exploring new cities like a local not a tourist with",
    "spontaneous beach trips when the weather is perfect and calling out",
    "finding new coffee shops and rating them like I'm a",
    "taking different routes home and discovering new places along the way",
    "trying new hobbies and activities I've never done before at",
    "exploring nature and finding peaceful spots away from the city",
    "spontaneous adventures that turn into the best memories I have honestly",
    "discovering new music venues and seeing live performances from unknown artists",
    "trying extreme sports that push my limits and make me",
    "exploring farmers markets and trying all the samples they offer there",
    "taking photos of beautiful places I discover on my adventures always",
    "saying yes to random invitations that lead to unexpected fun"
  ],
  "quirky": [
    "organizing things in oddly specific ways that make sense to 🎨",
    "finding perfectly shaped rocks and adding them to my collection honestly",
    "making playlists for weirdly specific moods that only I understand completely",
    "rearranging my room at 2am because the energy suddenly feels",
    "collecting random things that have sentimental value only to me",
    "talking to my plants and genuinely believing it helps them",
    "making up songs about whatever I'm doing at the moment",
    "finding patterns and coincidences that nobody else seems to notice",
    "organizing my books by color because it looks pretty even",
    "having full conversations with my pet like they totally understand me",
    "making weird food combinations that sound gross but taste amazing",
    "collecting stickers and putting them on everything I own like",
    "finding vintage items at thrift stores that have interesting histories behind",
    "making art projects that make no sense but bring me",
    "having oddly specific routines that help me function throughout my",
    "collecting quotes and writing them in random places around my",
    "naming inanimate objects and getting attached to them like they're",
    "making friendship bracelets for myself because why should kids have",
    "having themed days where I dress according to random aesthetics",
    "finding beauty in strange things that most people would overlook"
  ],
  "serious": [
    "quiet mornings with coffee before the chaos of the day",
    "achieving small goals that contribute to my bigger life plans",
    "moments of peace and clarity when everything feels aligned and",
    "productive days where I accomplish everything on my to do",
    "financial stability and knowing my bills are paid on time",
    "personal growth moments when I realize how far I've come",
    "quality time invested in relationships that matter most to me",
    "progress towards my goals even when it's slow and steady",
    "moments of gratitude for the life I'm building for myself",
    "peaceful evenings reflecting on my day and planning for tomorrow",
    "achieving work life balance and feeling good about both areas",
    "investing in myself through education courses or personal development always",
    "building healthy habits that support my long term wellbeing and",
    "moments of clarity about my purpose and direction in life",
    "financial progress and seeing my savings grow over time consistently",
    "quality sleep that helps me show up as my",
    "accomplishing tasks that move me closer to my long term",
    "moments of self reflection that lead to personal growth and",
    "building a life that aligns with my values and priorities",
    "peaceful moments where I feel content with where I am"
  ],
  "intellectual": [
    "learning something new that changes my perspective on the world 🧠",
    "reading a book that makes me think differently about life",
    "having deep conversations that challenge my assumptions and beliefs about",
    "discovering new ideas and concepts that fascinate me and spark",
    "moments of clarity when complex concepts suddenly make perfect sense",
    "listening to podcasts that teach me something valuable and interesting always",
    "engaging in debates that help me refine my thinking on",
    "reading articles that provide new insights into topics I care",
    "learning from people who are experts in their fields and",
    "discovering connections between different ideas I've been learning about recently",
    "having aha moments when everything clicks into place and makes",
    "exploring new subjects that expand my understanding of the world",
    "thoughtful discussions that go beyond surface level small talk always honestly",
    "reading philosophy that makes me question fundamental assumptions about everything around",
    "learning about different cultures and perspectives that broaden my worldview",
    "discovering new authors or thinkers whose work resonates with me",
    "engaging with complex topics that require deep thought and analysis",
    "moments of intellectual growth when I realize my thinking has",
    "learning skills that challenge me mentally and help me grow",
    "having conversations that leave me thinking long after they've ended"
  ],
  "default": [
    "morning coffee that tastes perfect and starts my day right ✨",
    "sunshine on my face on a beautiful day outside honestly",
    "good conversations with people I care about and love deeply",
    "cozy evenings at home doing absolutely nothing but relaxing fully",
    "laughter with friends that makes my stomach hurt in best",
    "peaceful moments alone where I can just be with myself",
    "good music that matches my mood perfectly at the right",
    "warm hugs from people I love that make everything better",
    "beautiful sunsets that remind me to appreciate the little things",
    "quality time with loved ones without any distractions from phones",
    "comfortable silence with people I'm close to and trust",
    "fresh air and nature that helps me feel grounded and",
    "good food that satisfies my soul not just my stomach",
    "moments of gratitude for the life I have and people",
    "peaceful mornings before the world gets busy and chaotic outside",
    "genuine smiles from strangers that restore my faith in humanity",
    "cozy blankets and comfortable clothes that make me feel safe",
    "beautiful weather that makes me want to be outside all",
    "simple moments of joy that remind me life is beautiful",
    "feeling content and at peace with where I am right"
  ]
};

module.exports = mySimplePleasures;
