const myTherapistWouldSayI = {
  funny: [
    "need to stop overthinking literally everything in my life",
    "use humor as a defense mechanism way too much",
    "need to actually deal with my problems instead of",
    "should probably get more sleep and less screen time",
    "need to stop avoiding difficult conversations with people close",
    "use sarcasm to deflect when things get too real",
    "should stop comparing myself to everyone on social media",
    "need to set boundaries instead of people pleasing constantly",
    "overthink every text message i send to anyone ever",
    "need to stop catastrophizing every single little thing always",
    "should probably leave my comfort zone more often honestly",
    "use jokes to avoid talking about my actual feelings",
    "need to stop seeking validation from other people constantly",
    "should work on my communication skills in relationships definitely",
    "need to stop running away from my responsibilities daily",
    "have attachment issues i refuse to acknowledge or address",
    "should probably stop self sabotaging when things go well",
    "need to work on my impulse control and decision",
    "use avoidance as my primary coping mechanism for everything",
    "should stop making excuses and actually do the work",
  ],
  romantic: [
    "have a fearful avoidant attachment style in relationships clearly",
    "need to work on letting people in emotionally more",
    "put up walls when i start catching real feelings",
    "need to communicate my needs instead of expecting mind",
    "have abandonment issues from past relationships affecting me now",
    "need to stop looking for red flags in everyone",
    "should work on trusting people who show theyre trustworthy",
    "have a pattern of self sabotaging good relationships unfortunately",
    "need to believe im worthy of the love i",
    "should stop pushing people away when they get close",
    "have unrealistic expectations from watching too many romance movies",
    "need to work on being vulnerable without fear of",
    "should stop overthinking every little thing in my relationships",
    "have a tendency to love too hard too fast",
    "need to learn the difference between love and attachment",
    "should work on my communication in relationships more actively",
    "have a pattern of choosing emotionally unavailable people always",
    "need to stop settling for less than i deserve",
    "should work on loving myself before loving someone else",
    "have codependent tendencies i need to address in therapy",
  ],
  adventurous: [
    "use adventure as escapism instead of dealing with things",
    "need to find balance between adventure and stability finally",
    "run away from problems instead of facing them directly",
    "need to learn that staying still isnt giving up",
    "use constant movement to avoid sitting with my feelings",
    "need to work on being present instead of always",
    "have commitment issues disguised as a free spirit mentality",
    "need to stop running toward things and start running",
    "should learn that growth can happen without constant change",
    "use adventure to fill a void im not addressing",
    "need to find peace in the present moment sometimes",
    "have a fear of missing out that drives decisions",
    "need to work on building roots not just wings",
    "should stop equating stillness with stagnation in my life",
    "use spontaneity to avoid making real commitments to things",
    "need to learn that adventure is a mindset not",
    "have a pattern of leaving when things get hard",
    "need to work on staying instead of always going",
    "should find adventure in depth not just new experiences",
    "use change as a coping mechanism for discomfort always",
  ],
  quirky: [
    "need to accept that being different is actually okay",
    "use my quirks as a shield to keep people",
    "need to stop apologizing for being myself all the",
    "should embrace my weirdness instead of hiding it from",
    "need to find people who appreciate my quirks genuinely",
    "use humor to deflect when people dont get me",
    "need to stop dimming my light to make others",
    "should work on being unapologetically myself in all situations",
    "need to accept that not everyone will understand me",
    "use my uniqueness as both armor and weapon sometimes",
    "need to stop trying to fit into boxes that",
    "should celebrate what makes me different from everyone else",
    "need to work on confidence in my own weirdness",
    "use my quirks to test if people really accept",
    "need to stop seeking validation for being authentically myself",
    "should find community with people who get my vibe",
    "need to accept that weird is wonderful not wrong",
    "use my oddness to filter out people who dont",
    "need to work on owning my quirks with pride",
    "should stop explaining myself to people who dont care",
  ],
  serious: [
    "need to work on my attachment style and patterns",
    "have trust issues from past trauma affecting current relationships",
    "need to set better boundaries with people in life",
    "should work on communicating my needs more clearly always",
    "need to stop taking responsibility for other peoples emotions",
    "have codependent tendencies i need to address in therapy",
    "need to work on self compassion and being kinder to",
    "should process my trauma instead of just pushing through",
    "need to learn that healing isnt linear or perfect",
    "have people pleasing tendencies that hurt me in the",
    "need to work on sitting with uncomfortable emotions instead",
    "should stop seeking external validation for my self worth",
    "need to address my perfectionism and unrealistic standards for",
    "have avoidant coping mechanisms i use when things get",
    "need to work on vulnerability and letting people in",
    "should stop punishing myself for being human and imperfect",
    "need to learn that my worth isnt tied to",
    "have control issues stemming from past experiences and trauma",
    "need to work on accepting help from others sometimes",
    "should focus on progress not perfection in my healing",
  ],
  intellectual: [
    "overthink everything and need to get out of head",
    "use intellectualization as a defense mechanism to avoid feelings",
    "need to feel emotions instead of just analyzing them",
    "should work on being present instead of always thinking",
    "need to accept that not everything requires deep analysis",
    "use logic to avoid dealing with emotional issues honestly",
    "need to work on emotional intelligence not just intellectual",
    "should stop trying to think my way out of",
    "need to learn that feelings are valid even without",
    "use analysis paralysis to avoid making decisions or acting",
    "need to work on trusting my gut not just",
    "should accept that some things cant be understood logically",
    "need to stop living in my head all the",
    "use knowledge as a way to feel in control",
    "need to work on connecting emotionally not just intellectually",
    "should learn that being smart doesnt mean having all",
    "need to accept uncertainty instead of needing to understand",
    "use thinking as avoidance for actually doing the work",
    "need to work on balance between head and heart",
    "should stop using intelligence to distance myself from others",
  ],
};

module.exports = myTherapistWouldSayI;
