const somethingThatsNonNegotiableForMeIs = {
  funny: [
    "laughing at my jokes even when theyre really bad",
    "sharing food being mandatory not optional in this relationship",
    "loving dogs or at least pretending to for me",
    "not judging my screen time or netflix watching habits",
    "understanding that naps are sacred and non negotiable always",
    "being okay with me talking to my pet constantly",
    "not making fun of my comfort show choices ever",
    "accepting that im always cold and need extra blankets",
    "understanding my need for snacks at all times daily",
    "being fine with my chaotic energy and random thoughts",
    "not judging my spotify wrapped results every single year",
    "accepting that i will steal your hoodies unapologetically always",
    "understanding that breakfast for dinner is completely valid meal",
    "being okay with my obsession with reality tv shows",
    "not questioning my online shopping habits or cart abandonment",
    "accepting my need to rewatch the same shows repeatedly",
    "understanding that im not a morning person at all",
    "being fine with my collection of random things nobody",
    "not making me choose between you and my pet",
    "accepting that i need alone time to recharge daily",
  ],
  romantic: [
    "honest communication even when its hard to hear truth",
    "effort and consistency not just words and empty promises",
    "being emotionally available and willing to be vulnerable with",
    "making me feel chosen not just an option ever",
    "respecting my boundaries without making me feel guilty about",
    "showing love through actions not just saying the words",
    "being loyal and trustworthy in all situations always here",
    "making our relationship a priority not an afterthought constantly",
    "supporting my dreams and goals like theyre your own",
    "being my safe space where i can be vulnerable",
    "choosing me every day not just when its easy",
    "being honest about your feelings and intentions from start",
    "making me feel loved on my worst days too",
    "being present and engaged not just physically there with",
    "respecting me and treating me with kindness always consistently",
    "being someone i can trust completely without question ever",
    "making effort to understand me and my love language",
    "being my partner and best friend at same time",
    "showing up consistently through actions not just pretty words",
    "making me feel secure and safe in our relationship",
  ],
  adventurous: [
    "being open to spontaneous adventures and last minute plans",
    "saying yes to trying new things together without hesitation",
    "supporting my need for adventure and new experiences always",
    "being willing to step out of your comfort zone",
    "not holding me back from chasing my dreams boldly",
    "matching my energy for exploring and discovering new places",
    "being okay with change and not needing everything planned",
    "supporting my travel goals and wanting to join me",
    "not making me choose between you and my adventures",
    "being excited about life and living it to fullest",
    "not trying to keep me in a box or",
    "being willing to take risks and try scary things",
    "supporting my independence while still being there for me",
    "not needing a plan for everything we do together",
    "being open to new experiences and perspectives from travel",
    "matching my enthusiasm for making memories over making money",
    "not being threatened by my need for freedom and",
    "being willing to get lost and find our way",
    "supporting my bucket list dreams and helping me achieve",
    "being my adventure partner not my anchor holding back",
  ],
  quirky: [
    "accepting my weirdness and quirks without trying to change",
    "not judging my oddly specific routines and habits ever",
    "appreciating my niche interests even if you dont share",
    "understanding my need to do things my own way",
    "not making fun of my comfort items or rituals",
    "accepting that i have strong opinions about random things",
    "understanding my organizational system even if it seems chaotic",
    "not questioning my collections or hobbies that seem weird",
    "appreciating what makes me different from everyone else around",
    "understanding my need for specific routines and schedules always",
    "not trying to make me more normal or mainstream",
    "accepting my random knowledge about obscure topics nobody cares",
    "understanding that my quirks are part of who i",
    "not judging my comfort show that ive watched repeatedly",
    "accepting my weirdly specific preferences and pet peeves always",
    "understanding my need to research everything before deciding anything",
    "not making me feel bad for being authentically myself",
    "accepting that i do things differently than most people",
    "understanding my specific way of doing literally everything daily",
    "appreciating my uniqueness instead of trying to change it",
  ],
  serious: [
    "honesty and direct communication in all situations no exceptions",
    "respecting my boundaries without guilt tripping or pushing back",
    "emotional maturity and ability to handle difficult conversations well",
    "taking accountability for actions and words without making excuses",
    "being consistent and reliable through actions not just words",
    "respecting my time and energy as valuable resources always",
    "having integrity and living by your values consistently daily",
    "being emotionally available and willing to do the work",
    "treating me with respect and basic human decency always",
    "following through on commitments and promises you make to",
    "having self awareness and working on personal growth actively",
    "communicating clearly about intentions and expectations from the start",
    "being trustworthy and earning that trust through consistent actions",
    "respecting my need for independence and personal space sometimes",
    "handling conflict maturely without stonewalling or running away ever",
    "being loyal and committed when you say you are",
    "showing up consistently not just when its convenient for",
    "respecting my mental health and supporting my healing journey",
    "being honest about your feelings and where you stand",
    "treating our relationship with intention and care it deserves",
  ],
  intellectual: [
    "being able to have deep meaningful conversations regularly together",
    "respecting my intelligence and not talking down to me",
    "being open minded and willing to consider different perspectives",
    "valuing learning and personal growth as much as i",
    "being able to debate without getting defensive or emotional",
    "having intellectual curiosity about the world around us always",
    "being willing to admit when you dont know something",
    "valuing substance and depth over surface level interactions only",
    "being able to challenge my perspective respectfully and thoughtfully",
    "having opinions backed by actual thought and research always",
    "being interested in ideas and concepts not just things",
    "valuing education and self improvement as lifelong pursuits here",
    "being able to discuss complex topics without dumbing down",
    "having critical thinking skills and using them in life",
    "being willing to learn from me and teach me",
    "valuing knowledge but not being pretentious about it ever",
    "being able to hold conversations beyond small talk always",
    "having curiosity and asking thoughtful questions about everything around",
    "being intellectually stimulating and making me think differently about",
    "valuing depth and meaning in our conversations and connection",
  ],
};

module.exports = somethingThatsNonNegotiableForMeIs;
