const iKnowTheBestSpotInTownFor = {
  funny: [
    "how to adult because i clearly have no idea",
    "your most embarrassing moment so i feel better about",
    "how to cook something other than instant ramen please",
    "your go to karaoke song and why its perfect",
    "how to look like you have your life together",
    "your signature dance move i need to see it",
    "how to survive on a budget of basically nothing",
    "your worst date story i need to hear this",
    "how to make friends as an adult its hard",
    "your most irrational fear and the story behind it",
    "how to stop procrastinating on literally everything in life",
    "your favorite meme format and why it hits different",
    "how to cancel plans without feeling guilty about it",
    "your unpopular opinion that would get you cancelled probably",
    "how to pretend youre listening when youre really not",
    "your comfort show and why youve watched it repeatedly",
    "how to avoid small talk and skip to good",
    "your go to excuse for getting out of things",
    "how to make instant food taste like actual food",
    "your most useless talent that still impresses people somehow",
  ],
  romantic: [
    "your idea of the perfect date night in detail",
    "how you like to be loved and shown affection",
    "your favorite love song and why it means something",
    "how you knew you were ready for something real",
    "your love language and how you show you care",
    "how to make you smile on your worst days",
    "your idea of what real love should feel like",
    "how you show someone they matter to you deeply",
    "your favorite romantic gesture someone has done for you",
    "how you want your future relationship to look like",
    "your definition of a healthy loving relationship and partnership",
    "how to know when someones right for you truly",
    "your favorite memory with someone you cared about deeply",
    "how you knew you were falling for someone special",
    "your idea of the perfect cozy night in together",
    "how to make ordinary moments feel special and meaningful",
    "your thoughts on what makes relationships actually last long",
    "how you like to be comforted when youre upset",
    "your favorite thing about being in love with someone",
    "how to know if what you feel is real",
  ],
  adventurous: [
    "your favorite travel destination and why it changed you",
    "how to plan the perfect spontaneous road trip adventure",
    "your most adventurous experience and what you learned from",
    "how to travel on a budget without missing out",
    "your bucket list item youre most excited to check",
    "how to overcome fear and just do the thing",
    "your best travel tips for first time solo travelers",
    "how to pack light for any type of trip",
    "your favorite hidden gem destination nobody knows about yet",
    "how to find adventure in everyday life around you",
    "your craziest travel story that still makes you laugh",
    "how to stay safe while still having fun adventures",
    "your dream adventure and who youd want there with",
    "how to convince friends to take spontaneous trips together",
    "your favorite adrenaline activity and why its worth trying",
    "how to make the most of weekend getaways nearby",
    "your best advice for someone wanting to travel more",
    "how to find the best local spots tourists miss",
    "your favorite way to explore a new city fully",
    "how to turn any day into an adventure together",
  ],
  quirky: [
    "your weirdly specific interest that nobody else cares about",
    "how your brain works because it seems fascinating honestly",
    "your oddly specific pet peeve and why it bothers",
    "how you organize things because your system seems interesting",
    "your niche hobby that most people dont understand fully",
    "how you came up with your specific routines and",
    "your random talent that impresses absolutely nobody really here",
    "how you remember so many random facts about everything",
    "your comfort show and why its deeper than people",
    "how you make connections between completely random things always",
    "your collection and why you started collecting it originally",
    "how your mind works when solving problems or thinking",
    "your signature quirk and the story behind it honestly",
    "how you developed your unique perspective on things around",
    "your favorite random fact you know that nobody uses",
    "how you stay so unapologetically yourself all the time",
    "your weirdly specific preference and why it matters to",
    "how you find joy in the little things others",
    "your most niche reference that nobody ever gets unfortunately",
    "how you embrace being different from everyone else around",
  ],
  serious: [
    "how you set and maintain healthy boundaries with people",
    "your biggest lesson from therapy or personal growth work",
    "how you practice self care that actually nourishes you",
    "your communication style and what you need from others",
    "how you process difficult emotions in healthy ways effectively",
    "your perspective on what makes relationships work long term",
    "how you knew it was time to walk away",
    "your journey with mental health and what helped you",
    "how you built self worth and confidence over time",
    "your non negotiables in relationships and why they matter",
    "how you handle conflict in mature productive ways always",
    "your attachment style and how you work with it",
    "how you practice self compassion on your hard days",
    "your values and how you try to live them",
    "how you knew you needed to make a change",
    "your definition of emotional maturity and healthy relationships here",
    "how you balance independence with intimacy in relationships well",
    "your journey to self love and what it taught",
    "how you recognize your patterns and work to change",
    "your perspective on healing and what it means to",
  ],
  intellectual: [
    "your favorite book and how it changed your perspective",
    "how you form your opinions on complex issues thoughtfully",
    "your current philosophical question youre pondering deeply about life",
    "how you think critically about information you consume daily",
    "your favorite theory or concept that fascinates you completely",
    "how you connect seemingly unrelated ideas and concepts together",
    "your perspective on a topic you're passionate about deeply",
    "how you approach learning new complex topics or subjects",
    "your favorite documentary and what it taught you recently",
    "how you analyze situations from multiple different perspectives always",
    "your thoughts on human nature and what drives people",
    "how you developed your critical thinking skills over time",
    "your favorite debate topic and your stance on it",
    "how you stay informed without getting overwhelmed by information",
    "your perspective on the meaning of life and purpose",
    "how you challenge your own beliefs and assumptions regularly",
    "your favorite thought experiment and why it interests you",
    "how you articulate complex ideas in simple clear terms",
    "your current research rabbit hole and why its fascinating",
    "how you balance logic and emotion in decision making",
  ],
};

module.exports = iKnowTheBestSpotInTownFor;
