const theDorkiestThingAboutMeIs = {
  "funny": [
    "I laugh at my own jokes before I even finish telling 😂",
    "I do a little dance when my food arrives at restaurants",
    "I talk to my plants and genuinely believe they respond back",
    "I make sound effects for literally everything I do throughout day",
    "I have full conversations with my pet like they totally understand",
    "I get way too excited about office supplies and organization stuff",
    "I practice conversations in my head before having them with people",
    "I narrate my life like I'm in a documentary sometimes",
    "I make up songs about whatever I'm doing at moment",
    "I get genuinely excited about finding a good parking spot honestly",
    "I do victory dances when I accomplish even the smallest things",
    "I have names for all my plants and talk to them",
    "I get overly invested in tv show characters and their relationships",
    "I make weird noises when I'm concentrating on something hard",
    "I celebrate small wins like they're major life achievements honestly",
    "I have a specific playlist for every possible mood I experience",
    "I get excited about new kitchen gadgets like they're toys",
    "I do impressions of people when telling stories about them always",
    "I make up elaborate backstories for strangers I see in public",
    "I get way too competitive about board games and trivia nights"
  ],
  "romantic": [
    "I still believe in soulmates and love at first sight ❤️",
    "I get butterflies thinking about someone I really like still honestly",
    "I save cute texts and reread them when I'm missing",
    "I make playlists for people I have crushes on secretly always",
    "I daydream about future scenarios with someone I'm into constantly",
    "I get nervous and giggly around someone I really like",
    "I notice every little detail about someone I'm interested in",
    "I write poetry or journal entries about people I care about",
    "I plan out perfect dates in my head before they",
    "I get excited about the idea of meeting someone's family",
    "I save voice notes just to hear someone's voice later",
    "I screenshot sweet messages to look at when I'm sad",
    "I believe in grand romantic gestures and love languages and stuff",
    "I get genuinely excited about relationship milestones and anniversaries always honestly",
    "I make up cute couple names in my head for",
    "I plan future trips and adventures with someone I'm dating",
    "I get emotional watching romantic movies and thinking about my",
    "I keep little mementos from dates and special moments together",
    "I believe in the magic of first kisses and meaningful",
    "I get excited about the idea of growing old with"
  ],
  "adventurous": [
    "I research random places I want to visit for hours 🌟",
    "I have a bucket list that's way too long honestly",
    "I get overly excited about trying new foods and cuisines everywhere",
    "I plan imaginary trips to places I've never been to",
    "I collect maps and travel guides even for places I",
    "I watch travel vlogs and documentaries like it's my job",
    "I have detailed itineraries for trips I haven't even booked",
    "I get excited about airport security and the whole travel process",
    "I research hiking trails and outdoor activities in my free time",
    "I make lists of adventures I want to have someday",
    "I get genuinely excited about trying new activities even when scary",
    "I plan road trips with detailed stops and photo opportunities marked",
    "I collect souvenirs from every place I visit no matter how",
    "I research local customs and phrases before visiting new places always",
    "I get excited about packing and planning what to bring on",
    "I watch videos about extreme sports I'll probably never try honestly",
    "I have a world map where I mark places I",
    "I get overly excited about spontaneous adventure opportunities that come up",
    "I research the best local spots before visiting anywhere new always",
    "I plan future adventures constantly even when I can't afford"
  ],
  "quirky": [
    "I have very specific and weird routines that I follow 🎨",
    "I collect random things that have no real value to",
    "I organize things in oddly specific ways that make sense",
    "I have strong opinions about things that don't really matter",
    "I make up words and use them like they're real",
    "I have elaborate theories about random things nobody else cares",
    "I notice patterns and coincidences that nobody else seems to see",
    "I have niche interests that I could talk about for hours",
    "I make spreadsheets for things that don't need spreadsheets at",
    "I have a very specific way of doing everyday tasks",
    "I get attached to inanimate objects and give them personalities",
    "I have weird superstitions that I follow even though they're",
    "I make lists for literally everything in my life constantly",
    "I have strong feelings about fonts and design choices in",
    "I notice small details that most people completely overlook or miss",
    "I have elaborate systems for organizing my digital and physical",
    "I get excited about things most people find boring or mundane",
    "I have very specific preferences about random everyday things honestly",
    "I make connections between unrelated things that somehow make sense",
    "I have quirky habits that I don't even realize I'm"
  ],
  "serious": [
    "I take my goals and personal development very seriously always",
    "I have detailed plans for my future that I review",
    "I track my progress and habits with apps and journals",
    "I read self improvement books and actually implement what I",
    "I have a morning routine that I follow religiously every",
    "I set goals for every area of my life and",
    "I take notes during podcasts and lectures to remember key",
    "I have a five year plan that I update regularly",
    "I track my finances meticulously and budget for everything I spend",
    "I take my career development seriously and constantly work on",
    "I have systems in place for productivity and time management",
    "I read industry news and stay updated on my field",
    "I network intentionally and maintain professional relationships carefully and thoughtfully",
    "I invest in courses and education to improve my skills",
    "I have mentors and actively seek feedback on my performance",
    "I take my health seriously and track nutrition and exercise",
    "I plan my weeks in advance and schedule everything I",
    "I set quarterly reviews to assess my progress toward goals",
    "I take continuing education seriously and always work on learning",
    "I have backup plans for my backup plans just in"
  ],
  "intellectual": [
    "I read multiple books at once and remember details from 🧠",
    "I fact check things mid conversation and can't help myself",
    "I get excited about learning new words and using them correctly",
    "I listen to educational podcasts for fun in my free time",
    "I watch documentaries and take notes like I'm in school",
    "I correct grammar and pronunciation in my head constantly without",
    "I get into deep research rabbit holes about random topics",
    "I have strong opinions about proper citation formats and academic",
    "I get excited about visiting museums and reading every single plaque",
    "I debate ideas for fun and enjoy intellectual discourse with",
    "I read academic papers and journals in my spare time",
    "I get genuinely excited about learning new concepts and theories",
    "I have a reading list that's organized by topic and",
    "I take online courses just for fun not for credit",
    "I get excited about TED talks and intellectual discussions online always",
    "I remember random facts and bring them up in conversations",
    "I enjoy analyzing and discussing complex topics with anyone who'll",
    "I get excited about libraries and bookstores like they're theme",
    "I have opinions about different schools of thought and philosophical",
    "I get genuinely excited when I learn something new that"
  ],
  "default": [
    "I get really excited about things most people find boring ✨",
    "I have weird little habits that I don't even notice",
    "I get overly invested in things that don't really matter",
    "I make everything more complicated than it needs to be",
    "I have strong opinions about random everyday things that don't",
    "I get excited about small things that make me happy",
    "I do little dances when I'm happy or excited about",
    "I talk to myself more than I probably should honestly",
    "I have elaborate systems for organizing my life and stuff",
    "I get way too into hobbies and interests I pick",
    "I make lists for everything even when I don't need",
    "I have specific ways of doing things that seem weird",
    "I get genuinely excited about things other people find mundane",
    "I notice details that most people completely miss or overlook",
    "I have quirks that I'm not even aware of until",
    "I get overly enthusiastic about my interests and passions in",
    "I make everything into a bigger deal than it is",
    "I have weird preferences about everyday things that don't matter",
    "I get excited about organization and planning way too much",
    "I'm way more enthusiastic about life than most people are"
  ]
};

module.exports = theDorkiestThingAboutMeIs;
