const theHallmarkOfAGoodRelationshipIs = {
  funny: [
    "being able to fart in front of each other",
    "laughing at the same dumb things",
    "sharing food without asking",
    "having your own language nobody else understands",
    "being comfortable in complete silence together",
    "roasting each other but knowing its love",
    "sending each other memes only you two get",
    "being weird together in public",
    "having inside jokes that make no sense",
    "being able to be gross around each other",
    "laughing at each others terrible jokes",
    "knowing each others food orders",
    "being comfortable with no makeup",
    "matching energy for spontaneous adventures",
    "communicating with just looks across the room",
    "making boring errands fun together",
    "being each others favorite person to do nothing",
    "having the same sense of humor",
    "being able to annoy each other lovingly",
    "knowing when to be serious and when to joke",
  ],
  romantic: [
    "feeling safe enough to be vulnerable",
    "choosing each other every single day",
    "making each other feel loved on hard days",
    "being each others safe space",
    "growing together instead of apart",
    "showing love through consistent actions",
    "making effort every day",
    "being best friends and lovers",
    "feeling chosen not like an option",
    "supporting each others dreams",
    "communicating openly even when its hard",
    "making ordinary moments feel special",
    "being a team through everything",
    "keeping the spark alive",
    "making each other better people",
    "feeling like home with each other",
    "celebrating small moments",
    "weathering storms together",
    "making each other laugh every day",
    "building a future together",
  ],
  adventurous: [
    "saying yes to adventures together",
    "pushing each other out of comfort zones",
    "making memories together not just taking pictures",
    "being each others adventure partner",
    "supporting each others wild ideas",
    "trying new things together even when scary",
    "making every day feel like an adventure",
    "being willing to get lost",
    "exploring the world together",
    "encouraging each other to take risks",
    "finding beauty in the journey",
    "being spontaneous with plans",
    "making life one big adventure",
    "supporting each others need for growth",
    "being excited about living life fully",
    "collecting experiences together",
    "being open to change",
    "making the ordinary extraordinary",
    "encouraging each other to live without regrets",
    "taking the scenic route together",
  ],
  quirky: [
    "accepting each others weirdness without judgment",
    "having your own weird traditions",
    "appreciating what makes each other different",
    "being weird together and loving it",
    "understanding each others oddly specific preferences",
    "having inside jokes nobody else gets",
    "embracing your quirks instead of changing them",
    "making up your own words together",
    "appreciating each others niche interests",
    "being unapologetically yourselves",
    "finding someone who matches your weird",
    "matching energy for random deep dives",
    "celebrating differences instead of being the same",
    "understanding each others specific ways",
    "being completely authentic without fear",
    "having your own little world",
    "appreciating little quirks",
    "being weird in complementary ways",
    "making each other feel normal",
    "finding beauty in each others oddities",
  ],
  serious: [
    "honest communication even when its hard",
    "respecting each others boundaries",
    "being emotionally available and present",
    "taking accountability and working on yourselves",
    "handling conflict maturely without stonewalling",
    "showing up consistently through actions",
    "building trust through reliability",
    "supporting each others growth even when it changes things",
    "being a safe space for vulnerability",
    "making the relationship a priority",
    "respecting each others independence",
    "communicating needs clearly and listening",
    "being loyal and committed",
    "working through hard times together",
    "showing love in meaningful ways",
    "being partners who add value",
    "having difficult conversations instead of avoiding",
    "building something real and lasting",
    "being intentional about the relationship",
    "choosing growth over being right",
  ],
  intellectual: [
    "having deep meaningful conversations",
    "being intellectually stimulated by each other",
    "challenging each others perspectives respectfully",
    "valuing learning and growing together",
    "being able to discuss anything",
    "having intellectual compatibility",
    "debating ideas without it becoming personal",
    "appreciating each others intelligence",
    "asking thoughtful questions and seeking to understand",
    "valuing substance over surface level",
    "being curious about each other and the world",
    "learning from each other",
    "having conversations that make you think",
    "respecting each others opinions even when disagreeing",
    "being open minded and willing to change",
    "appreciating nuance and complexity",
    "making learning part of your relationship",
    "exploring ideas together without judgment",
    "valuing education and self improvement",
    "having mental chemistry as strong as physical",
  ],
};

module.exports = theHallmarkOfAGoodRelationshipIs;
