const theHallmarkOfAGoodRelationshipIs = {
  funny: [
    "being able to fart in front of each other",
    "laughing at the same dumb things together always constantly",
    "sharing food without asking or feeling weird about it",
    "having your own language nobody else understands at all",
    "being comfortable in complete silence together without awkwardness ever",
    "roasting each other but knowing its all love always",
    "sending each other memes that only you two get",
    "being weird together in public without caring what people",
    "having inside jokes that make no sense to anyone",
    "being able to be gross around each other comfortably",
    "laughing at each others jokes even the really bad",
    "knowing each others food orders without having to ask",
    "being comfortable with no makeup and messy hair around",
    "having matching energy for spontaneous bad ideas and adventures",
    "being able to communicate with just looks across room",
    "making everything fun even boring errands and daily tasks",
    "being each others favorite person to do nothing with",
    "having the same sense of humor about everything around",
    "being able to annoy each other lovingly every day",
    "knowing when to be serious and when to joke",
  ],
  romantic: [
    "feeling safe enough to be completely vulnerable and open",
    "choosing each other every single day not just once",
    "making each other feel loved on the hard days",
    "being each others safe space and biggest support system",
    "growing together instead of apart as you both change",
    "showing love through consistent actions not just words only",
    "making effort every day not just in the beginning",
    "being best friends and lovers at the same time",
    "feeling chosen not just an option or backup plan",
    "supporting each others dreams like theyre your own too",
    "communicating openly and honestly even when its hard to",
    "making ordinary moments feel special and meaningful together always",
    "being a team through everything life throws at you",
    "keeping the spark alive even after the honeymoon phase",
    "making each other better people just by being together",
    "feeling like home when youre with each other always",
    "celebrating the small moments not just the big ones",
    "being able to weather storms together and come out",
    "making each other laugh and smile every single day",
    "building a future together one day at a time",
  ],
  adventurous: [
    "saying yes to adventures and new experiences together always",
    "pushing each other out of comfort zones in good",
    "making memories together instead of just taking pictures only",
    "being each others adventure partner in life and everything",
    "supporting each others wild ideas and bucket list dreams",
    "trying new things together even when theyre scary honestly",
    "making every day feel like an adventure together somehow",
    "being willing to get lost and find your way",
    "exploring the world and life together with open minds",
    "encouraging each other to take risks and chase dreams",
    "finding beauty in the journey not just the destination",
    "being spontaneous and flexible with plans and life together",
    "making life one big adventure story you create together",
    "supporting each others need for growth and new experiences",
    "being excited about life and living it to fullest",
    "collecting experiences together not just material things only here",
    "being open to change and new possibilities always together",
    "making the ordinary extraordinary just by being together always",
    "encouraging each other to live without regrets or fear",
    "being willing to take the scenic route together always",
  ],
  quirky: [
    "accepting each others weirdness and quirks completely without judgment",
    "having your own weird traditions that make sense to",
    "appreciating what makes each other different and unique always",
    "being weird together and loving every minute of it",
    "understanding each others oddly specific preferences and routines completely",
    "having inside jokes and references nobody else gets ever",
    "embracing your quirks instead of trying to change them",
    "making up your own words and phrases together regularly",
    "appreciating each others niche interests even if not shared",
    "being unapologetically yourselves around each other every single day",
    "finding someone who matches your exact brand of weird",
    "having matching energy for random deep dives into topics",
    "celebrating your differences instead of trying to be same",
    "understanding each others specific way of doing things always",
    "being able to be completely authentic without fear of",
    "having your own little world that makes sense to",
    "appreciating the little quirks that make each other unique",
    "being weird in the same way or complementary ways",
    "making each other feel normal for being completely yourselves",
    "finding beauty in each others oddities and unique traits",
  ],
  serious: [
    "honest communication even when the truth is hard to",
    "respecting each others boundaries without guilt or pushing back",
    "being emotionally available and present for each other consistently",
    "taking accountability and working on yourselves individually and together",
    "handling conflict maturely without stonewalling or running away ever",
    "showing up consistently through actions not just pretty words",
    "building trust through reliability and following through on commitments",
    "supporting each others growth even when it means changing",
    "being a safe space for vulnerability and honest emotions",
    "making the relationship a priority through intentional consistent effort",
    "respecting each others independence while building something together here",
    "communicating needs clearly and listening to understand not",
    "being loyal and committed when you say you are",
    "working through hard times together instead of giving up",
    "showing love in ways that actually matter to each",
    "being partners who add value to each others lives",
    "having difficult conversations instead of avoiding them always courageously",
    "building something real and lasting not just something easy",
    "being intentional about the relationship and its future together",
    "choosing growth over being right in arguments and disagreements",
  ],
  intellectual: [
    "having deep meaningful conversations that challenge both of you",
    "being intellectually stimulated by each other regularly in conversations",
    "challenging each others perspectives respectfully and thoughtfully always here",
    "valuing learning and growing together as you go through",
    "being able to discuss anything from light to existential",
    "having intellectual compatibility thats just as important as physical",
    "debating ideas without it becoming personal or defensive ever",
    "appreciating each others intelligence and unique perspectives on life",
    "asking thoughtful questions and seeking to understand each other",
    "valuing substance and depth over surface level interactions only",
    "being curious about each other and the world together",
    "learning from each other and expanding your knowledge constantly",
    "having conversations that make you think differently about things",
    "respecting each others opinions even when you disagree strongly",
    "being open minded and willing to change your views",
    "appreciating nuance and complexity in discussions and life generally",
    "making learning and discovery part of your relationship always",
    "being able to explore ideas together without judgment ever",
    "valuing education and self improvement as shared lifelong pursuits",
    "having mental chemistry thats just as strong as physical",
  ],
};

module.exports = theHallmarkOfAGoodRelationshipIs;
