const theKeyToMyHeartIs = {
  "funny": [
    "food especially if you bring me snacks without me asking 😂",
    "making me laugh until my stomach hurts and I can't",
    "letting me nap whenever I want without any judgment at",
    "bringing me coffee in the morning because I'm not human",
    "laughing at my terrible jokes even when they're really not",
    "sharing your food with me which is basically true love",
    "not making me socialize when I'm in my introvert mode",
    "understanding that I need like twelve hours of sleep to",
    "appreciating my weird sense of humor and adding to it honestly",
    "bringing me random snacks because you thought of me while",
    "letting me be dramatic without making fun of me for",
    "making me laugh when I'm having the worst day ever",
    "not judging my comfort shows that I've watched a million",
    "understanding my need for alone time and personal space always",
    "appreciating my sarcasm and dishing it right back at me",
    "bringing me food when I'm hangry because that's when I",
    "letting me sleep in on weekends without making me feel",
    "making everything more fun just by being your chaotic self",
    "not taking life too seriously and laughing at everything with",
    "understanding that coffee is my love language in the morning"
  ],
  "romantic": [
    "genuine effort and showing up consistently not just when convenient ❤️",
    "making me feel safe enough to be vulnerable with you",
    "remembering small details I mention and bringing them up later randomly",
    "being emotionally available and communicating openly even when it's hard",
    "showing love through actions not just saying empty words to",
    "making me feel like a priority not an option in",
    "being affectionate without me having to ask for it constantly",
    "supporting my dreams and believing in me even when I",
    "making me laugh and smile even on my worst days",
    "being patient with me when I'm going through difficult times",
    "choosing me every single day not just in the beginning",
    "being vulnerable and open about your feelings with me always",
    "making me feel beautiful even when I'm in sweats",
    "listening when I talk and actually remembering what I said",
    "being thoughtful and doing little things that show you care",
    "making me feel heard and understood on a deep level",
    "being consistent with your words and actions so I can",
    "showing up for me when I need you most without",
    "making me feel cherished and appreciated for exactly who I",
    "being my best friend and my partner at the same"
  ],
  "adventurous": [
    "being spontaneous and saying yes to random adventures with me 🌟",
    "trying new things together even when they're scary or unknown",
    "being down for last minute road trips with no real",
    "matching my energy and enthusiasm for exploring new places together",
    "being willing to step outside your comfort zone with me",
    "saying yes to adventures and making memories we'll never forget",
    "being open to trying new foods and experiences without complaining",
    "having that wanderlust energy that matches mine perfectly and completely",
    "being spontaneous and not needing everything planned out in advance",
    "being excited about exploring and discovering new things together always",
    "being willing to get lost and find our way back",
    "having a sense of adventure and not being afraid to",
    "being down for outdoor activities and nature adventures with me",
    "being open to travel and experiencing different cultures together always",
    "being willing to take risks and see where they lead",
    "having that adventurous spirit that makes life so much more",
    "being excited about trying activities we've never done before together",
    "being spontaneous with plans and going with the flow always",
    "being willing to explore off the beaten path with me",
    "having that energy that makes every day feel like an"
  ],
  "quirky": [
    "appreciating my weirdness and adding your own to the mix 🎨",
    "being authentically yourself even when it's odd or different from",
    "getting my obscure references and making your own that I",
    "being weird with me and not caring what anyone thinks",
    "embracing your quirks and celebrating what makes you different and",
    "having niche interests that you're passionate about and want to",
    "being comfortable with being different and standing out from everyone",
    "appreciating the unconventional and finding beauty in strange things with",
    "being your authentic weird self without trying to be normal",
    "having your own unique perspective on things that fascinates me",
    "being okay with deep weird conversations at 3am about random",
    "celebrating our differences and the quirky things that make us",
    "being perfectly imperfect and owning every bit of your weirdness",
    "having obscure hobbies or interests that most people don't understand",
    "being unapologetically yourself even when it doesn't make sense to",
    "appreciating my odd habits and sharing your own with me",
    "being comfortable in your own skin even when you're different",
    "having that quirky energy that makes you interesting and memorable",
    "being weird in the best way possible and owning it",
    "celebrating what makes us unique instead of trying to fit"
  ],
  "serious": [
    "honesty and being genuine about your intentions from the very",
    "emotional maturity and being able to communicate like an adult",
    "respecting my boundaries without making me feel guilty for having",
    "being reliable and doing what you say you're going to",
    "taking accountability for your actions instead of making excuses all",
    "being emotionally available and present when we're together not distracted",
    "respecting my time and not wasting it playing games with",
    "being consistent with your words and actions so I can",
    "having your life somewhat together and working toward your goals",
    "being honest even when the truth is uncomfortable or difficult",
    "respecting me as an equal partner in everything we do",
    "being mature enough to handle difficult conversations without shutting down",
    "taking my feelings seriously and not dismissing them as dramatic",
    "being someone I can count on through good times and",
    "respecting my career and ambitions as much as your own",
    "being financially responsible and having a plan for your future",
    "taking our relationship seriously and putting in the effort it",
    "being honest about your past and what you've learned from",
    "respecting my standards because I set them for good reasons",
    "being ready for commitment not just casual dating or games"
  ],
  "intellectual": [
    "having deep meaningful conversations that go beyond surface level topics 🧠",
    "being intellectually curious and always wanting to learn new things",
    "challenging my thinking in respectful ways that help me grow",
    "being open to different perspectives and willing to change your",
    "having thoughtful discussions that make me see things differently than",
    "being well read and having interesting thoughts on various topics",
    "asking questions that make me think more deeply about things",
    "being open minded and willing to learn from anyone including",
    "engaging in debates without getting defensive or taking things too",
    "being curious about the world and wanting to understand it",
    "having opinions that are well thought out and based on",
    "being intellectually stimulating and making me think in new ways",
    "being interested in learning together and exploring ideas as a",
    "having meaningful discussions about topics that matter to both of",
    "being thoughtful and considering different angles before forming strong opinions",
    "being curious about my thoughts and perspectives on things that",
    "engaging with ideas seriously instead of dismissing them as overthinking",
    "being intellectually honest and admitting when you don't know something",
    "having that curiosity that makes conversations interesting and engaging always",
    "being open to having your views challenged in good ways"
  ],
  "default": [
    "kindness and treating everyone with respect not just me ✨",
    "being genuine and authentic in how you present yourself to",
    "making me feel comfortable being myself completely around you always",
    "being a good listener and actually hearing what I say",
    "showing up consistently and being someone I can count on",
    "being honest and communicating openly even when it's difficult or",
    "making me laugh and bringing joy into my life daily",
    "being supportive of my goals and dreams no matter what",
    "respecting my boundaries and understanding they exist for good reasons",
    "being patient and understanding with me through everything in life",
    "making me feel valued and appreciated for who I am",
    "being emotionally available and present when we're together not distant",
    "showing love through actions not just words that mean nothing",
    "being reliable and following through on what you say you'll",
    "making me feel safe and comfortable being vulnerable with you",
    "being thoughtful and doing little things that show you care",
    "respecting me and treating me well consistently not just sometimes",
    "being someone who makes me want to be better every",
    "making me feel like I matter and my feelings are",
    "being genuine about your intentions and what you want from"
  ]
};

module.exports = theKeyToMyHeartIs;
