const theKeyToMyHeartIs = {
  funny: [
    "food especially if you bring me snacks",
    "making me laugh until my stomach hurts",
    "letting me nap without judgment",
    "bringing me coffee in the morning",
    "laughing at my terrible jokes",
    "sharing your food with me",
    "not making me socialize when I need downtime",
    "appreciating my weird sense of humor",
    "bringing me random snacks because you thought of me",
    "letting me be dramatic",
    "making me laugh on my worst days",
    "not judging my comfort shows",
    "understanding my need for alone time",
    "appreciating my sarcasm",
    "bringing me food when Im hangry",
    "letting me sleep in on weekends",
    "making everything more fun",
    "not taking life too seriously",
    "coffee is my love language",
    "matching my chaotic energy",
  ],
  romantic: [
    "genuine effort and showing up consistently",
    "making me feel safe to be vulnerable",
    "remembering small details I mention",
    "being emotionally available and communicating openly",
    "showing love through actions",
    "making me feel like a priority",
    "being affectionate without me having to ask",
    "supporting my dreams and believing in me",
    "making me laugh on my worst days",
    "being patient with me during hard times",
    "choosing me every single day",
    "being vulnerable about your feelings",
    "making me feel beautiful even in sweats",
    "listening and remembering what I say",
    "being thoughtful with little things",
    "making me feel heard and understood",
    "being consistent with words and actions",
    "showing up when I need you",
    "making me feel cherished",
    "being my best friend and partner",
  ],
  adventurous: [
    "being spontaneous and saying yes to adventures",
    "trying new things together even when scary",
    "being down for last minute road trips",
    "matching my energy for exploring",
    "being willing to step outside your comfort zone",
    "saying yes to making memories",
    "being open to trying new foods",
    "having matching wanderlust energy",
    "not needing everything planned out",
    "being excited about discovering new things",
    "being willing to get lost",
    "having a sense of adventure",
    "being down for outdoor activities",
    "being open to travel and different cultures",
    "being willing to take risks",
    "having that adventurous spirit",
    "trying activities weve never done before",
    "being spontaneous with plans",
    "exploring off the beaten path",
    "making every day feel like an adventure",
  ],
  quirky: [
    "appreciating my weirdness and adding your own",
    "being authentically yourself even when odd",
    "getting my obscure references",
    "being weird with me without caring what anyone thinks",
    "embracing your quirks",
    "having niche interests you are passionate about",
    "being comfortable with being different",
    "appreciating the unconventional",
    "being your authentic weird self",
    "having your own unique perspective",
    "being okay with deep weird conversations",
    "celebrating our differences",
    "being perfectly imperfect",
    "having obscure hobbies",
    "being unapologetically yourself",
    "appreciating my odd habits",
    "being comfortable in your own skin",
    "having that quirky energy",
    "being weird in the best way",
    "celebrating what makes us unique",
  ],
  serious: [
    "honesty about your intentions",
    "emotional maturity and communication",
    "respecting my boundaries without guilt",
    "being reliable and doing what you say",
    "taking accountability for your actions",
    "being emotionally present when we are together",
    "respecting my time",
    "having your life somewhat together",
    "being honest even when uncomfortable",
    "respecting me as an equal",
    "being mature enough for difficult conversations",
    "taking my feelings seriously",
    "being someone I can count on",
    "respecting my career and ambitions",
    "being financially responsible",
    "taking our relationship seriously",
    "being honest about your past",
    "respecting my standards",
    "being ready for commitment",
    "being genuine about what you want",
  ],
  intellectual: [
    "having deep meaningful conversations",
    "being intellectually curious",
    "challenging my thinking in respectful ways",
    "being open to different perspectives",
    "having thoughtful discussions",
    "being well read",
    "asking questions that make me think",
    "being open minded to learn from anyone",
    "engaging in debates without getting defensive",
    "being curious about the world",
    "having well thought out opinions",
    "being intellectually stimulating",
    "being interested in learning together",
    "having meaningful discussions about things that matter",
    "being thoughtful about different angles",
    "being curious about my thoughts",
    "engaging with ideas seriously",
    "being intellectually honest",
    "having that curiosity",
    "being open to having your views challenged",
  ],
  default: [
    "kindness and treating everyone with respect",
    "being genuine and authentic",
    "making me feel comfortable being myself",
    "being a good listener",
    "showing up consistently",
    "being honest and communicating openly",
    "making me laugh and bringing joy",
    "being supportive of my goals",
    "respecting my boundaries",
    "being patient and understanding",
    "making me feel valued",
    "being emotionally available",
    "showing love through actions",
    "being reliable",
    "making me feel safe",
    "being thoughtful",
    "respecting me consistently",
    "making me want to be better",
    "making me feel like I matter",
    "being genuine about your intentions",
  ],
};

module.exports = theKeyToMyHeartIs;
