const theLastTimeICriedHappyTearsWas = {
  funny: [
    "watching a dog reunion video at 2am on tiktok",
    "when my food delivery arrived earlier than expected today",
    "seeing my bank account after payday felt so good",
    "when someone laughed at my joke i thought bombed",
    "watching the office finale for the hundredth time again",
    "when my favorite show got renewed for another season",
    "seeing a video of soldiers coming home to pets",
    "when i found money in my jacket pocket randomly",
    "watching pixar movies because they get me every time",
    "when my pet did something unreasonably cute and precious",
    "seeing a proposal video on social media that hit",
    "when someone complimented me and i actually believed them",
    "watching those videos of people getting surprised with puppies",
    "when my comfort show character finally got their happy",
    "seeing babies laugh at literally nothing on the internet",
    "when i successfully adulted and felt proud of myself",
    "watching any video of military homecoming surprises always works",
    "when someone remembered a small detail i mentioned once",
    "seeing elderly couples still in love after all those",
    "when my favorite artist dropped new music unexpectedly today",
  ],
  romantic: [
    "when someone told me they loved me and meant",
    "watching a couple get engaged in front of me",
    "when i realized i was falling in love again",
    "reading old messages that reminded me im loved deeply",
    "when someone showed up for me when i needed",
    "watching a wedding video that reminded me of love",
    "when someone looked at me like i was their",
    "seeing my parents still in love after all these",
    "when someone did something thoughtful without me asking them",
    "watching a love story that reminded me of us",
    "when i felt truly seen and understood by someone",
    "reading a love letter that was written for me",
    "when someone chose me over and over again consistently",
    "watching the notebook because it gets me every single",
    "when i realized someone loved me for who i",
    "seeing a couple reunite after being apart for long",
    "when someone made me believe in love again finally",
    "watching a proposal that was so pure and genuine",
    "when i felt safe enough to be vulnerable with",
    "seeing proof that real love actually exists out there",
  ],
  adventurous: [
    "reaching the summit after a challenging hike to top",
    "watching the sunrise from somewhere ive never been before",
    "when i finally booked the trip ive been dreaming",
    "seeing a view that took my breath away completely",
    "when i overcame a fear and did it anyway",
    "watching the sunset from a place ive always wanted",
    "when i realized how far ive come in life",
    "standing at the edge of something beautiful and vast",
    "when i checked off a bucket list item finally",
    "seeing the ocean for the first time in months",
    "when i took a risk and it paid off",
    "watching the stars from the middle of nowhere peaceful",
    "when i felt most alive and free in nature",
    "reaching a destination after a long journey to get",
    "when i realized i was living my dream life",
    "seeing a place id only dreamed about in person",
    "when i pushed past my limits and succeeded finally",
    "watching a documentary about someone living their dream life",
    "when i felt grateful for all the adventures ive",
    "standing somewhere i never thought id actually get to",
  ],
  quirky: [
    "watching a video essay about my niche interest finally",
    "when someone got my obscure reference nobody else understands",
    "finishing a puzzle that took me way too long",
    "when i found my people who get my weird",
    "organizing my bookshelf perfectly and stepping back to admire",
    "when someone appreciated my quirks instead of judging them",
    "watching a show finale that gave my favorite character",
    "when i completed my oddly specific collection finally today",
    "reading a book that understood me better than people",
    "when someone validated my weirdly specific opinion about something",
    "watching a documentary about something i find fascinating deeply",
    "when i found a community around my niche interest",
    "finishing a project that nobody else would care about",
    "when someone made me feel normal for being myself",
    "watching a character arc that hit way too close",
    "when i realized being different is actually my strength",
    "reading something that put my feelings into perfect words",
    "when someone celebrated my weirdness instead of tolerating it",
    "watching a movie that felt like it was made",
    "when i embraced my quirks and stopped apologizing for",
  ],
  serious: [
    "when i realized how much ive grown and healed",
    "seeing my therapist proud of my progress in therapy",
    "when someone validated my feelings without trying to fix",
    "realizing i finally love myself after years of work",
    "when i set a boundary and felt empowered not",
    "seeing how far ive come from my lowest point",
    "when someone told me they were proud of me",
    "realizing i survived something i didnt think i would",
    "when i forgave myself for something ive carried for",
    "seeing the progress ive made in my healing journey",
    "when i chose myself for the first time ever",
    "realizing im not the same person i was before",
    "when someone saw me for who i really am",
    "breaking a cycle i thought id never escape from",
    "when i realized my worth and stopped settling for",
    "seeing myself through someone elses loving eyes for once",
    "when i finally let go of something holding me",
    "realizing i made it through the hardest year yet",
    "when i felt proud of who im becoming finally",
    "seeing proof that healing is possible and happening now",
  ],
  intellectual: [
    "reading a book that completely changed my perspective on",
    "when i finally understood a concept ive been struggling",
    "watching a documentary that opened my eyes to something",
    "when someone challenged my perspective and i actually grew",
    "reading something that articulated thoughts i couldnt express before",
    "when i made a connection between two concepts finally",
    "watching a ted talk that shifted how i see",
    "when i learned something that changed everything i thought",
    "reading poetry that understood me better than i understand",
    "when i had a breakthrough in understanding myself or",
    "watching someone explain something ive always wondered about clearly",
    "when i finished a book that felt like it",
    "learning about something that gave me hope for humanity",
    "when i realized how much ive learned and grown",
    "reading about someone who overcame what i thought impossible",
    "when i understood something on a deeper level finally",
    "watching a lecture that answered questions ive had for",
    "when i connected dots i never saw before clearly",
    "reading something that validated my thoughts and perspective completely",
    "when i learned something that made the world make",
  ],
};

module.exports = theLastTimeICriedHappyTearsWas;
