const theLastTimeICriedHappyTearsWas = {
  funny: [
    "watching a dog reunion video at 2am on TikTok",
    "when my food delivery arrived earlier than expected",
    "seeing my bank account after payday felt so good",
    "when someone laughed at my joke I thought bombed",
    "watching The Office finale for the hundredth time",
    "when my favorite show got renewed for another season",
    "seeing a video of soldiers coming home to pets",
    "when I found money in my jacket pocket randomly",
    "watching Pixar movies because they get me every time",
    "when my pet did something unreasonably cute and precious",
    "seeing a proposal video on social media that hit different",
    "when someone complimented me and I actually believed them",
    "watching those videos of people getting surprised with puppies",
    "when my comfort show character finally got their happy ending",
    "seeing babies laugh at literally nothing on the internet",
    "when I successfully adulted and felt proud of myself",
    "watching any video of military homecoming surprises",
    "when someone remembered a small detail I mentioned once",
    "seeing elderly couples still in love after all these years",
    "when my favorite artist dropped new music unexpectedly",
  ],
  romantic: [
    "when someone told me they loved me and meant it",
    "watching a couple get engaged in front of me",
    "when I realized I was falling in love again",
    "reading old messages that reminded me I am loved",
    "when someone showed up for me when I needed them",
    "watching a wedding video that reminded me of love",
    "when someone looked at me like I was their whole world",
    "seeing my parents still in love after all these years",
    "when someone did something thoughtful without me asking",
    "watching a love story that reminded me of us",
    "when I felt truly seen and understood by someone",
    "reading a love letter that was written for me",
    "when someone chose me over and over again",
    "watching The Notebook because it gets me every time",
    "when I realized someone loved me for who I am",
    "seeing a couple reunite after being apart for long",
    "when someone made me believe in love again",
    "watching a proposal that was so pure and genuine",
    "when I felt safe enough to be vulnerable with someone",
    "seeing proof that real love actually exists out there",
  ],
  adventurous: [
    "reaching the summit after a challenging hike",
    "watching the sunrise from somewhere I have never been",
    "when I finally booked the trip I have been dreaming about",
    "seeing a view that took my breath away",
    "when I overcame a fear and did it anyway",
    "watching the sunset from a place I have always wanted to go",
    "when I realized how far I have come in life",
    "standing at the edge of something beautiful and vast",
    "when I checked off a bucket list item",
    "seeing the ocean for the first time in months",
    "when I took a risk and it paid off",
    "watching the stars from the middle of nowhere",
    "when I felt most alive and free in nature",
    "reaching a destination after a long journey",
    "when I realized I was living my dream life",
    "seeing a place I had only dreamed about in person",
    "when I pushed past my limits and succeeded",
    "watching a documentary about someone living their dream life",
    "when I felt grateful for all the adventures I have had",
    "standing somewhere I never thought I would actually get to",
  ],
  quirky: [
    "watching a video essay about my niche interest",
    "when someone got my obscure reference nobody else understands",
    "finishing a puzzle that took me way too long",
    "when I found my people who get my weird",
    "organizing my bookshelf perfectly and stepping back to admire",
    "when someone appreciated my quirks instead of judging them",
    "watching a show finale that gave my favorite character closure",
    "when I completed my oddly specific collection",
    "reading a book that understood me better than people",
    "when someone validated my weirdly specific opinion",
    "watching a documentary about something I find fascinating",
    "when I found a community around my niche interest",
    "finishing a project that nobody else would care about",
    "when someone made me feel normal for being myself",
    "watching a character arc that hit way too close to home",
    "when I realized being different is actually my strength",
    "reading something that put my feelings into perfect words",
    "when someone celebrated my weirdness instead of tolerating it",
    "watching a movie that felt like it was made for me",
    "when I embraced my quirks and stopped apologizing",
  ],
  serious: [
    "when I realized how much I have grown and healed",
    "seeing my therapist proud of my progress",
    "when someone validated my feelings without trying to fix them",
    "realizing I finally love myself after years of work",
    "when I set a boundary and felt empowered",
    "seeing how far I have come from my lowest point",
    "when someone told me they were proud of me",
    "realizing I survived something I did not think I would",
    "when I forgave myself for something I have carried",
    "seeing the progress I have made in my healing journey",
    "when I chose myself for the first time",
    "realizing I am not the same person I was before",
    "when someone saw me for who I really am",
    "breaking a cycle I thought I would never escape from",
    "when I realized my worth and stopped settling",
    "seeing myself through someone else is loving eyes",
    "when I finally let go of something holding me back",
    "realizing I made it through the hardest year",
    "when I felt proud of who I am becoming",
    "seeing proof that healing is possible and happening",
  ],
  intellectual: [
    "reading a book that completely changed my perspective",
    "when I finally understood a concept I have been struggling with",
    "watching a documentary that opened my eyes to something new",
    "when someone challenged my perspective and I actually grew",
    "reading something that articulated thoughts I could not express",
    "when I made a connection between two concepts",
    "watching a TED talk that shifted how I see things",
    "when I learned something that changed everything I thought I knew",
    "reading poetry that understood me better than I understand myself",
    "when I had a breakthrough in understanding myself",
    "watching someone explain something I have always wondered about",
    "when I finished a book that felt like it was written for me",
    "learning something that gave me hope for humanity",
    "when I realized how much I have learned and grown",
    "reading about someone who overcame what I thought was impossible",
    "when I understood something on a deeper level",
    "watching a lecture that answered questions I have had for years",
    "when I connected dots I never saw before",
    "reading something that validated my thoughts and perspective",
    "when I learned something that made the world make sense",
  ],
};

module.exports = theLastTimeICriedHappyTearsWas;
