const theOneThingIdLoveToKnowAboutYouIs = {
  funny: [
    "your most embarrassing moment that still haunts you today",
    "what youre weirdly competitive about for no reason at",
    "your go to karaoke song and how bad you",
    "the dumbest thing youve ever done for a crush",
    "what your search history says about you as person",
    "your most irrational fear that makes no sense logically",
    "the worst pickup line youve ever used or heard",
    "what you would do with a million dollars today",
    "your signature dance move i need to see it",
    "the weirdest compliment youve ever received from someone random",
    "what celebrity you think you could beat in fight",
    "your most unpopular opinion that gets you in trouble",
    "the last lie you told and why you told",
    "what your pet would say about you if they",
    "your guilty pleasure that youd defend to the death",
    "the most chaotic thing youve done on impulse recently",
    "what youre secretly judging people for all the time",
    "your comfort show and how many times youve watched",
    "the worst date youve ever been on story time",
    "what you do when you think nobodys watching you",
  ],
  romantic: [
    "what makes you feel most loved and appreciated always",
    "the moment you knew you wanted something real serious",
    "what your idea of a perfect relationship looks like",
    "the little things that make you fall for someone",
    "what love language speaks to you the most deeply",
    "the moment you felt most connected to someone special",
    "what you look for in a real genuine connection",
    "the sweetest thing someone has ever done for you",
    "what your future looks like in your dreams ideally",
    "the qualities you value most in a partner always",
    "what makes you believe in love and happy endings",
    "the moment you realized you were falling for someone",
    "what you need to feel safe in a relationship",
    "the small gestures that mean more than grand ones",
    "what you want your love story to look like",
    "the moment you knew someone was different from everyone",
    "what you think makes relationships actually last long term",
    "the way you show someone you care about them",
    "what your idea of perfect date night looks like",
    "the thing that makes your heart skip a beat",
  ],
  adventurous: [
    "the craziest thing on your bucket list right now",
    "where youd go if you could travel anywhere tomorrow",
    "the most spontaneous thing youve ever done in life",
    "what living life to the fullest means to you",
    "the adventure that changed your perspective on everything completely",
    "where you see yourself in five years from now",
    "the scariest thing youve done that was worth it",
    "what your dream adventure looks like in detail here",
    "the next place you want to explore and why",
    "what experience made you feel most alive and free",
    "the risk you took that paid off big time",
    "where you feel most at home in the world",
    "the trip that changed you as a person completely",
    "what youre running toward instead of away from now",
    "the next big goal or dream youre working toward",
    "what adventure means to you beyond just traveling places",
    "the moment you realized you were capable of more",
    "where your happy place is in the entire world",
    "the experience you want to have before you die",
    "what makes you feel most alive and present today",
  ],
  quirky: [
    "your weirdly specific ick that makes no sense to",
    "the random hill youd die on without any hesitation",
    "what niche interest youre currently obsessed with right now",
    "the oddly specific thing you find attractive in people",
    "your comfort show and why its deeper than people",
    "the weird habit you have that you dont notice",
    "what your organizational system says about you as person",
    "the random talent you have that impresses nobody really",
    "your go to fun fact about yourself thats interesting",
    "the thing you collect that makes no sense to",
    "what your oddly specific routine says about your personality",
    "the niche community youre part of that nobody knows",
    "your signature quirk and the story behind it honestly",
    "the random thing that brings you unreasonable joy daily",
    "what makes you different from everyone else you know",
    "the weirdly specific preference you have about literally everything",
    "your most niche reference that nobody ever gets unfortunately",
    "the random fact you know that youll never use",
    "what your comfort items say about you psychologically here",
    "the thing that makes you uniquely you and nobody",
  ],
  serious: [
    "what youve learned about yourself through therapy or growth",
    "the biggest lesson life has taught you so far",
    "what your non negotiables are in relationships and life",
    "the moment that changed your perspective on everything completely",
    "what youre working on improving about yourself right now",
    "the pattern youve noticed in your relationships and behaviors",
    "what makes you feel truly seen and understood deeply",
    "the boundary you had to set that changed everything",
    "what emotional intimacy means to you in relationships here",
    "the thing youre most proud of overcoming in life",
    "what you need to feel secure in a relationship",
    "the cycle youre trying to break in your life",
    "what self love actually looks like for you personally",
    "the fear youre currently working through right now actively",
    "what your values are and how you live them",
    "the thing you need to forgive yourself for finally",
    "what vulnerability means to you and why its hard",
    "the person youre becoming and whether you like them",
    "what your attachment style is and how it affects",
    "the thing that keeps you up at night thinking",
  ],
  intellectual: [
    "the book that completely changed your perspective on life",
    "what philosophical question youre currently pondering deeply about existence",
    "the topic you could talk about for hours without",
    "what your unpopular opinion is on a social issue",
    "the documentary that made you think differently about everything",
    "what theory or concept fascinates you the most right",
    "the idea that challenges conventional thinking you find interesting",
    "what you think the meaning of life actually is",
    "the pattern youve noticed that nobody else talks about",
    "what your favorite debate topic is and your stance",
    "the connection you made between two unrelated concepts recently",
    "what keeps you up at night thinking about deeply",
    "the question you wish more people would ask themselves",
    "what your thoughts are on human nature and behavior",
    "the concept youre trying to fully understand right now",
    "what your current research rabbit hole is and why",
    "the perspective that shifted after learning something new recently",
    "what you think makes life meaningful and worthwhile overall",
    "the idea youre developing about something youve been observing",
    "what you believe about the world that most people",
  ],
};

module.exports = theOneThingIdLoveToKnowAboutYouIs;
