const therapyRecentlyTaughtMe = {
  funny: [
    "that I use humor to avoid my actual feelings",
    "my coping mechanisms are just avoidance with extra steps",
    "that overthinking is not the same as problem solving",
    "I need to stop people pleasing and start disappointing",
    "that my comfort zone is actually a prison",
    "I cannot think my way out of every problem",
    "that rest is not a reward it is a necessity",
    "my inner critic needs to shut up sometimes",
    "that I deserve good things without earning them",
    "my anxiety lies to me literally all the time",
    "that feelings are temporary even when they feel permanent",
    "I need to stop apologizing for existing",
    "that self care is not selfish it is necessary",
    "my brain is mean to me for no reason",
    "that I cannot control everything and that is okay",
    "I need better boundaries with everyone in life",
    "that asking for help is not weakness it is strength",
    "my perfectionism is just fear wearing a fancy hat",
    "that I need to be kinder to myself",
    "my thoughts are not facts they are just thoughts",
  ],
  romantic: [
    "that I have a fearful avoidant attachment style",
    "love is not supposed to hurt or feel like anxiety",
    "that I deserve love without having to earn it",
    "my worth is not determined by whether someone chooses me",
    "that I need to love myself before loving someone",
    "healthy love feels calm not chaotic or anxious",
    "that I attract what I think I deserve",
    "I cannot fix people or save them from themselves",
    "that vulnerability is strength not weakness in relationships",
    "I need to stop settling for less than I deserve",
    "that being alone is better than being with the wrong person",
    "love should not require me to shrink or change myself",
    "that I have patterns I need to break",
    "the right person will not make me question my worth",
    "that I need to communicate my needs clearly",
    "love is a choice not just a feeling",
    "that I cannot pour from an empty cup",
    "I deserve someone who shows up consistently for me",
    "that red flags do not turn into green ones",
    "I need to trust my gut about people more",
  ],
  adventurous: [
    "that I use adventure to run from my problems",
    "staying still does not mean I am stuck",
    "that I need to find balance between movement and stillness",
    "adventure cannot fill the void I am trying to avoid",
    "that growth can happen without constant change",
    "I need to learn to be present where I am",
    "that running toward things is different from running away",
    "I cannot escape myself no matter where I go",
    "that commitment is not the opposite of freedom",
    "I need roots just as much as I need wings",
    "that fear of missing out drives too many decisions",
    "staying is sometimes braver than leaving",
    "that I need to sit with discomfort sometimes",
    "adventure is a mindset not just a location change",
    "that I use spontaneity to avoid making real commitments",
    "I need to stop equating stillness with stagnation",
    "that depth is just as important as breadth",
    "I can find peace in the present moment",
    "that change for change is sake is not always growth",
    "I need to learn when to stay and when to go",
  ],
  quirky: [
    "that being different is actually my superpower",
    "I do not need to explain myself to everyone",
    "that my quirks make me interesting not weird",
    "I need to stop apologizing for being authentically myself",
    "that not everyone will understand me and that is okay",
    "my weirdness is what makes me uniquely me",
    "that I should embrace what makes me different",
    "the right people will appreciate my quirks not tolerate them",
    "that I do not need to fit into boxes",
    "my uniqueness is a gift not something to hide",
    "that weird is wonderful and I should own it",
    "I need to find my people who get me",
    "that trying to be normal is exhausting and pointless",
    "my specific way of doing things is valid",
    "that I should celebrate my differences not hide them",
    "the world needs more people who are unapologetically themselves",
    "that my niche interests make me interesting and unique",
    "I do not need everyone is approval to exist",
    "that being authentic is more important than being liked",
    "my quirks are features not bugs",
  ],
  serious: [
    "that healing is not linear and that is okay",
    "I need to set boundaries without feeling guilty",
    "that my feelings are valid even when others disagree",
    "I cannot control other people only my own reactions",
    "that I deserve respect and basic human decency",
    "my past does not define who I am becoming",
    "that I need to prioritize my mental health",
    "self compassion is just as important as compassion for others",
    "that I cannot pour from an empty cup",
    "my worth is not tied to my productivity",
    "that asking for help is strength not weakness",
    "I need to stop taking responsibility for others emotions",
    "that progress is still progress even when it is slow",
    "I deserve to take up space without apologizing",
    "that I need to feel my emotions not avoid them",
    "my needs are just as important as everyone else is",
    "that I cannot heal in the same environment that hurt me",
    "I need to trust myself and my own judgment",
    "that letting go is sometimes the most loving thing",
    "I deserve peace and I do not need permission",
  ],
  intellectual: [
    "that I use intellectualization to avoid feeling my emotions",
    "thinking about feelings is not the same as feeling them",
    "that I need to get out of my head",
    "not everything needs to be analyzed or understood logically",
    "that I cannot think my way out of everything",
    "feelings are valid even without logical explanations",
    "that I need emotional intelligence not just intellectual intelligence",
    "overthinking is not the same as processing emotions healthily",
    "that I use logic to distance myself from others",
    "I need to trust my gut not just my head",
    "that some things are meant to be felt not understood",
    "analysis paralysis keeps me stuck",
    "that I need balance between my head and heart",
    "being smart does not mean I have all the answers",
    "that I need to accept uncertainty instead of understanding everything",
    "knowledge is power but so is emotional awareness",
    "that I use thinking as avoidance for actually doing",
    "I need to connect emotionally not just intellectually",
    "that understanding something does not mean I have processed it",
    "I need to feel more and think less sometimes",
  ],
};

module.exports = therapyRecentlyTaughtMe;
