const therapyRecentlyTaughtMe = {
  funny: [
    "that i use humor to avoid my actual feelings",
    "my coping mechanisms are just avoidance with extra steps",
    "that overthinking is not the same as problem solving",
    "i need to stop people pleasing and start disappointing",
    "that my comfort zone is actually a prison basically",
    "i cant think my way out of every problem",
    "that rest is not a reward its a necessity",
    "my inner critic needs to shut up sometimes honestly",
    "that i deserve good things without earning them constantly",
    "my anxiety lies to me literally all the time",
    "that feelings are temporary even when they feel permanent",
    "i need to stop apologizing for existing and taking",
    "that self care isnt selfish its actually necessary for",
    "my brain is mean to me for no reason",
    "that i cant control everything and thats okay actually",
    "i need better boundaries with literally everyone in life",
    "that asking for help isnt weakness its strength actually",
    "my perfectionism is just fear wearing a fancy hat",
    "that i need to be kinder to myself daily",
    "my thoughts arent facts theyre just thoughts passing through",
  ],
  romantic: [
    "that i have a fearful avoidant attachment style",
    "love isnt supposed to hurt or feel like anxiety",
    "that i deserve love without having to earn it",
    "my worth isnt determined by whether someone chooses me",
    "that i need to love myself before loving someone",
    "healthy love feels calm not chaotic or anxious constantly",
    "that i attract what i think i deserve unfortunately",
    "i cant fix people or save them from themselves",
    "that vulnerability is strength not weakness in relationships here",
    "i need to stop settling for less than i",
    "that being alone is better than being with wrong",
    "love shouldnt require me to shrink or change myself",
    "that i have patterns i need to break urgently",
    "the right person wont make me question my worth",
    "that i need to communicate my needs clearly always",
    "love is a choice not just a feeling daily",
    "that i cant pour from an empty cup ever",
    "i deserve someone who shows up consistently for me",
    "that red flags dont turn into green ones magically",
    "i need to trust my gut about people more",
  ],
  adventurous: [
    "that i use adventure to run from my problems",
    "staying still doesnt mean im stuck or giving up",
    "that i need to find balance between movement and",
    "adventure cant fill the void im trying to avoid",
    "that growth can happen without constant change or movement",
    "i need to learn to be present where i",
    "that running toward things is different from running away",
    "i cant escape myself no matter where i go",
    "that commitment isnt the opposite of freedom actually here",
    "i need roots just as much as i need",
    "that fear of missing out drives too many decisions",
    "staying is sometimes braver than leaving or running away",
    "that i need to sit with discomfort sometimes instead",
    "adventure is a mindset not just a location change",
    "that i use spontaneity to avoid making real commitments",
    "i need to stop equating stillness with stagnation always",
    "that depth is just as important as breadth in",
    "i can find peace in the present moment here",
    "that change for changes sake isnt always growth really",
    "i need to learn when to stay and",
  ],
  quirky: [
    "that being different is actually my superpower not weakness",
    "i dont need to explain myself to everyone always",
    "that my quirks make me interesting not weird or",
    "i need to stop apologizing for being authentically myself",
    "that not everyone will understand me and thats okay",
    "my weirdness is what makes me uniquely me honestly",
    "that i should embrace what makes me different always",
    "the right people will appreciate my quirks not tolerate",
    "that i dont need to fit into boxes that",
    "my uniqueness is a gift not something to hide",
    "that weird is wonderful and i should own it",
    "i need to find my people who get me",
    "that trying to be normal is exhausting and pointless",
    "my specific way of doing things is valid always",
    "that i should celebrate my differences not hide them",
    "the world needs more people who are unapologetically themselves",
    "that my niche interests make me interesting and unique",
    "i dont need everyones approval or understanding to exist",
    "that being authentic is more important than being liked",
    "my quirks are features not bugs in my personality",
  ],
  serious: [
    "that healing isnt linear and thats completely okay always",
    "i need to set boundaries without feeling guilty about",
    "that my feelings are valid even when others disagree",
    "i cant control other people only my own reactions",
    "that i deserve respect and basic human decency always",
    "my past doesnt define who i am becoming now",
    "that i need to prioritize my mental health over",
    "self compassion is just as important as compassion for",
    "that i cant pour from an empty cup ever",
    "my worth isnt tied to my productivity or achievements",
    "that asking for help is strength not weakness ever",
    "i need to stop taking responsibility for others emotions",
    "that progress is still progress even when its slow",
    "i deserve to take up space without apologizing for",
    "that i need to feel my emotions not avoid",
    "my needs are just as important as everyone elses",
    "that i cant heal in the same environment that",
    "i need to trust myself and my own judgment",
    "that letting go is sometimes the most loving thing",
    "i deserve peace and i dont need permission for",
  ],
  intellectual: [
    "that i use intellectualization to avoid feeling my emotions",
    "thinking about feelings isnt the same as feeling them",
    "that i need to get out of my head",
    "not everything needs to be analyzed or understood logically",
    "that i cant think my way out of everything",
    "feelings are valid even without logical explanations for them",
    "that i need emotional intelligence not just intellectual intelligence",
    "overthinking is not the same as processing emotions healthily",
    "that i use logic to distance myself from others",
    "i need to trust my gut not just my",
    "that some things are meant to be felt not",
    "analysis paralysis keeps me stuck and unable to act",
    "that i need balance between my head and heart",
    "being smart doesnt mean i have all the answers",
    "that i need to accept uncertainty instead of understanding",
    "knowledge is power but so is emotional awareness here",
    "that i use thinking as avoidance for actually doing",
    "i need to connect emotionally not just intellectually with",
    "that understanding something doesnt mean ive processed it emotionally",
    "i need to feel more and think less sometimes",
  ],
};

module.exports = therapyRecentlyTaughtMe;
