const theWayToWinMeOverIs = {
  "funny": [
    "make me laugh until I snort and can't breathe properly 😂",
    "bring me food especially when I didn't even ask for",
    "let me nap whenever I want without any judgment whatsoever",
    "appreciate my terrible jokes and laugh even when they're not",
    "bring me coffee in the morning because I'm basically a",
    "understand that I need alone time to recharge my social",
    "make everything fun even boring tasks like grocery shopping together",
    "don't take yourself too seriously and laugh at yourself with",
    "let me be dramatic without calling me out for it",
    "share your food with me which is basically a marriage",
    "match my chaotic energy and add to it not tone",
    "appreciate my sarcasm and dish it right back at me",
    "make me laugh when I'm having the absolute worst day",
    "understand my need for twelve hours of sleep to function",
    "don't judge my comfort shows that I've watched a million",
    "bring me random snacks because you thought of me while",
    "let me sleep in on weekends without making me feel",
    "be goofy and silly with me without worrying about looking",
    "appreciate my weird sense of humor and contribute your own",
    "make ordinary moments fun just by being your authentic self"
  ],
  "romantic": [
    "show genuine effort and be consistent not just in beginning ❤️",
    "make me feel safe enough to be completely vulnerable with",
    "remember small details I mention and bring them up later",
    "be emotionally available and communicate openly about your feelings always",
    "show love through actions not just empty words you say",
    "make me feel like a priority in your life not",
    "be affectionate without me having to ask for it constantly",
    "support my dreams and believe in me even when I",
    "make me laugh and smile even on my worst days",
    "be patient with me when I'm going through difficult times",
    "choose me every single day not just when it's easy",
    "be vulnerable and open about your feelings with me too",
    "make me feel beautiful even when I'm in sweats",
    "listen when I talk and actually remember what I said",
    "be thoughtful and do little things that show you care",
    "make me feel heard and understood on a deep level",
    "be consistent so I know I can trust you completely",
    "show up for me when I need you most without",
    "make me feel cherished and appreciated for exactly who I",
    "be my best friend and partner at the same time"
  ],
  "adventurous": [
    "be spontaneous and say yes to random adventures with me 🌟",
    "try new things together even when they're scary or unknown",
    "be down for last minute road trips with no plan",
    "match my energy and enthusiasm for exploring new places always",
    "be willing to step outside your comfort zone with me",
    "say yes to adventures and make memories we'll never forget",
    "be open to trying new foods and experiences without complaining",
    "have that wanderlust energy that matches mine perfectly and completely",
    "be spontaneous and not need everything planned out in advance",
    "be excited about exploring and discovering new things together always",
    "be willing to get lost and find our way back",
    "have a sense of adventure and not be afraid to",
    "be down for outdoor activities and nature adventures with me",
    "be open to travel and experiencing different cultures together always",
    "be willing to take risks and see where they lead",
    "have that adventurous spirit that makes life so much more",
    "be excited about trying activities we've never done before together",
    "be spontaneous with plans and go with the flow always",
    "be willing to explore off the beaten path with me",
    "have that energy that makes every day feel like an"
  ],
  "quirky": [
    "appreciate my weirdness and add your own to the mix 🎨",
    "be authentically yourself even when it's odd or different from",
    "get my obscure references and make your own that I",
    "be weird with me and not care what anyone thinks",
    "embrace your quirks and celebrate what makes you different and",
    "have niche interests that you're passionate about and share with",
    "be comfortable with being different and standing out from everyone",
    "appreciate the unconventional and find beauty in strange things with",
    "be your authentic weird self without trying to be normal",
    "have your own unique perspective on things that fascinates me",
    "be okay with deep weird conversations at 3am about random",
    "celebrate our differences and the quirky things that make us",
    "be perfectly imperfect and own every bit of your weirdness",
    "have obscure hobbies or interests that most people don't understand",
    "be unapologetically yourself even when it doesn't make sense to",
    "appreciate my odd habits and share your own with me",
    "be comfortable in your own skin even when you're different",
    "have that quirky energy that makes you interesting and memorable",
    "be weird in the best way possible and own it",
    "celebrate what makes us unique instead of trying to fit"
  ],
  "serious": [
    "be honest and genuine about your intentions from the start",
    "show emotional maturity and communicate like an actual adult always",
    "respect my boundaries without making me feel guilty for having",
    "be reliable and do what you say you're going to",
    "take accountability for your actions instead of making excuses constantly",
    "be emotionally available and present when we're together not distracted",
    "respect my time and don't waste it playing games with",
    "be consistent with your words and actions so I can",
    "have your life somewhat together and work toward your goals",
    "be honest even when the truth is uncomfortable or difficult",
    "respect me as an equal partner in everything we do",
    "be mature enough to handle difficult conversations without shutting down",
    "take my feelings seriously and not dismiss them as dramatic",
    "be someone I can count on through good times and",
    "respect my career and ambitions as much as your own",
    "be financially responsible and have a plan for your future",
    "take our relationship seriously and put in the effort it",
    "be honest about your past and what you've learned from",
    "respect my standards because I set them for good reasons",
    "be ready for commitment not just casual dating or games"
  ],
  "intellectual": [
    "have deep meaningful conversations that go beyond surface level topics 🧠",
    "be intellectually curious and always want to learn new things",
    "challenge my thinking in respectful ways that help me grow",
    "be open to different perspectives and willing to change your",
    "have thoughtful discussions that make me see things differently than",
    "be well read and have interesting thoughts on various topics",
    "ask questions that make me think more deeply about things",
    "be open minded and willing to learn from anyone including",
    "engage in debates without getting defensive or taking things too",
    "be curious about the world and want to understand it",
    "have opinions that are well thought out and based on",
    "be intellectually stimulating and make me think in new ways",
    "be interested in learning together and exploring ideas as a",
    "have meaningful discussions about topics that matter to both of",
    "be thoughtful and consider different angles before forming strong opinions",
    "be curious about my thoughts and perspectives on things that",
    "engage with ideas seriously instead of dismissing them as overthinking",
    "be intellectually honest and admit when you don't know something",
    "have that curiosity that makes conversations interesting and engaging always",
    "be open to having your views challenged in good ways"
  ],
  "default": [
    "be kind and treat everyone with respect not just me ✨",
    "be genuine and authentic in how you present yourself to",
    "make me feel comfortable being myself completely around you always",
    "be a good listener and actually hear what I say",
    "show up consistently and be someone I can count on",
    "be honest and communicate openly even when it's difficult or",
    "make me laugh and bring joy into my life daily",
    "be supportive of my goals and dreams no matter what",
    "respect my boundaries and understand they exist for good reasons",
    "be patient and understanding with me through everything in life",
    "make me feel valued and appreciated for who I am",
    "be emotionally available and present when we're together not distant",
    "show love through actions not just words that mean nothing",
    "be reliable and follow through on what you say you'll",
    "make me feel safe and comfortable being vulnerable with you",
    "be thoughtful and do little things that show you care",
    "respect me and treat me well consistently not just sometimes",
    "be someone who makes me want to be better every",
    "make me feel like I matter and my feelings are",
    "be genuine about your intentions and what you want from"
  ]
};

module.exports = theWayToWinMeOverIs;
