const thisYearIReallyWantTo = {
  "funny": [
    "finally become a morning person but that's probably never happening honestly 😂",
    "learn to cook without setting off the smoke alarm every time",
    "actually use my gym membership instead of just paying for it",
    "finish all the shows on my watch list before adding more",
    "become someone who meal preps instead of ordering takeout constantly every",
    "learn to keep plants alive for longer than two weeks",
    "master the art of adulting without googling everything I need honestly",
    "become the person who responds to texts immediately instead of days",
    "learn to pack light instead of bringing my entire closet everywhere",
    "figure out how to be on time instead of fashionably late",
    "actually finish books instead of starting ten at once and abandoning",
    "learn to take good selfies on the first try somehow",
    "become someone who has their life together at least a little",
    "master the skill of small talk without it being super awkward",
    "learn to save money instead of spending it all on random",
    "become someone who actually uses their planner instead of buying pretty",
    "figure out how to fold fitted sheets properly because that's impossible",
    "learn to wake up without hitting snooze seventeen times every morning",
    "become the kind of person who drinks water instead of coffee",
    "master the art of not procrastinating everything until the last minute"
  ],
  "romantic": [
    "find someone who truly gets me and loves me for me ❤️",
    "build a relationship that's based on trust and genuine connection always",
    "create meaningful memories with someone special who makes me feel alive",
    "fall in love with someone who makes me want to be",
    "build a partnership where we both feel supported and loved every",
    "find my person and start building a beautiful life together honestly",
    "create a relationship that feels like home no matter where we",
    "meet someone who makes ordinary moments feel special and magical somehow",
    "build something real with someone who's ready for commitment and growth",
    "find love that's patient kind and unconditional through everything in life",
    "create a relationship where we choose each other every single day",
    "meet someone who loves me on my bad days not just",
    "build a partnership based on friendship and genuine care for each",
    "find someone to share adventures and quiet moments with equally and",
    "create a love story that inspires others and stands the test",
    "meet my best friend and fall in love at the same",
    "build a relationship where vulnerability is safe and love is unconditional",
    "find someone who makes me laugh and supports my dreams always",
    "create a partnership where we grow together instead of growing apart",
    "meet someone who feels like coming home after a long day"
  ],
  "adventurous": [
    "travel to at least three new countries I've never been 🌟",
    "try something that scares me and push past my comfort zone",
    "go on a spontaneous road trip with no real plan at",
    "learn a new skill like surfing or rock climbing this year",
    "visit every national park on my bucket list if I can",
    "take a solo trip and prove to myself I can do",
    "try all the adventure activities I've been too scared to attempt",
    "explore my own city like a tourist and find hidden gems",
    "say yes to opportunities that come up even if they're scary",
    "hike to the top of a mountain I've been wanting",
    "try foods from cuisines I've never experienced before at all honestly",
    "take a weekend trip somewhere new at least once a month",
    "learn to scuba dive and explore underwater worlds I've never seen",
    "go camping under the stars in places I've never been before",
    "try extreme sports that push my limits and make me feel",
    "explore off the beaten path destinations that tourists don't usually visit",
    "take a cross country road trip and see where it leads",
    "learn a new language so I can travel more confidently everywhere",
    "go on adventures that become stories I'll tell for years",
    "live more spontaneously and say yes to things that excite me"
  ],
  "quirky": [
    "start a weird collection that nobody else would understand or appreciate 🎨",
    "learn an obscure skill that's totally random but fascinating to me",
    "create art that makes people say what the heck but I",
    "master a niche hobby that most people have never heard of",
    "start a quirky tradition that my future self will think is",
    "learn to play an unusual instrument that nobody expects me to",
    "create something totally unique that's never been done before in history",
    "embrace my weirdness so fully that it becomes my personal brand",
    "start a blog or podcast about my niche interests nobody shares",
    "collect something oddly specific that brings me joy even if strange",
    "learn a weird talent that I can show off at parties",
    "create my own aesthetic that's totally unique and authentically me honestly",
    "start doing something unconventional that makes me happy even if odd",
    "master the art of thrifting and finding the most unique pieces",
    "become known for my eccentricity and unique perspective on everything in",
    "learn about obscure topics that fascinate me even if nobody cares",
    "create weird art projects that only I understand and appreciate fully",
    "start a quirky club for people who share my niche interests",
    "embrace being different and stop trying to fit into normal molds",
    "become the person everyone knows for being authentically weird and unique"
  ],
  "serious": [
    "achieve financial independence and build security for my future and family",
    "advance in my career and reach the next level professionally this",
    "build better habits that support my long term goals and wellbeing",
    "invest in myself through education courses or skills that help grow",
    "create multiple income streams so I have financial security and freedom",
    "prioritize my mental health and establish a consistent therapy or wellness",
    "build generational wealth and set up my family for future success",
    "achieve work life balance while still reaching my professional goals and",
    "develop leadership skills that will help me advance in my career",
    "create a solid financial plan and stick to it throughout year",
    "invest in real estate or assets that will grow over time",
    "build my professional network and make meaningful connections in my field",
    "achieve my biggest career goal that I've been working toward for",
    "establish healthy boundaries in all areas of my life and relationships",
    "create a retirement plan and start investing for my future seriously",
    "develop emotional intelligence and work on becoming a better communicator always",
    "achieve financial literacy and learn to manage money wisely and effectively",
    "build a business or side hustle that aligns with my values",
    "invest in my education and gain certifications that advance my career",
    "create stability and security in all areas of my life"
  ],
  "intellectual": [
    "read at least fifty books and expand my knowledge on topics 🧠",
    "learn a new language and become conversational by the end of",
    "take courses on subjects I'm passionate about and deepen my understanding",
    "write more whether it's journaling essays or creative pieces that challenge",
    "attend lectures workshops or seminars from experts in fields I admire",
    "learn about philosophy and develop my own well reasoned perspectives on",
    "read classic literature and understand the context and significance of works",
    "study a complex subject deeply and become knowledgeable enough to discuss",
    "engage in more intellectual conversations that challenge my thinking and perspectives",
    "learn about different cultures through books documentaries and meaningful conversations with",
    "develop critical thinking skills and question my assumptions about everything around",
    "read research papers and stay updated on developments in fields I",
    "learn about history and understand how it shapes our world today",
    "study psychology and understand human behavior and motivation more deeply than",
    "engage with diverse perspectives and challenge my own beliefs through learning",
    "learn about science and understand the world through evidence and research",
    "read philosophy and develop my own framework for understanding life and",
    "study art history and understand the cultural significance of different movements",
    "learn about economics and understand how systems shape society and behavior",
    "become a lifelong learner who never stops being curious about world"
  ],
  "default": [
    "travel somewhere new and make memories that I'll cherish forever ✨",
    "focus on my personal growth and become the best version of",
    "build stronger relationships with the people who matter most to me",
    "try new things and step outside my comfort zone more often",
    "prioritize my health and wellness both physically and mentally this year",
    "save money and be more financially responsible with my spending habits",
    "learn a new skill that I've been wanting to try",
    "spend more quality time with family and friends I care about",
    "work on my career goals and make progress toward where I",
    "be more present and mindful instead of always rushing through life",
    "create better work life balance and not let work consume everything",
    "develop healthier habits that support my overall wellbeing and happiness daily",
    "make new friends and expand my social circle with good people",
    "be more adventurous and say yes to opportunities that come up",
    "focus on self care and make my mental health a priority",
    "achieve goals I've been putting off and finally make them happen",
    "spend less time on my phone and more time living life",
    "be kinder to myself and practice more self compassion every day",
    "create memories and experiences rather than just accumulating more stuff honestly",
    "live more intentionally and make choices that align with my values"
  ]
};

module.exports = thisYearIReallyWantTo;
