const thisYearIReallyWantTo = {
  funny: [
    "actually wake up without hitting snooze",
    "learn to cook without burning everything",
    "use my gym membership for real",
    "stop starting shows I never finish",
    "keep a plant alive for once",
    "figure out how to be on time",
    "finally learn to fold fitted sheets",
    "respond to texts within the same day",
    "pack light for once in my life",
    "meal prep instead of ordering takeout",
    "stop buying planners I never use",
    "take a decent selfie for once",
    "save money instead of spending it all",
    "drink water instead of just coffee",
    "actually finish a book this year",
    "become a morning person... probably not",
    "learn to adult without googling everything",
    "stop procrastinating everything until the last minute",
    "have my life together... slightly",
    "master the art of small talk",
  ],
  romantic: [
    "find someone to go on adventures with",
    "fall in love with my best friend",
    "build a genuine connection with someone real",
    "meet someone who makes me laugh daily",
    "find love that feels easy and natural",
    "create memories with someone special this year",
    "find someone who gets my weird sense of humor",
    "build a relationship based on trust and fun",
    "meet someone I can be completely myself with",
    "find someone who loves Disney movies as much as me",
    "create a love story worth talking about",
    "find someone to share lazy Sundays with",
    "meet someone who makes ordinary moments special",
    "build something real with someone ready for love",
    "find someone to explore new places with",
    "fall for someone who sees the real me",
    "meet someone who feels like home",
    "find someone to build random traditions with",
    "create lasting memories with my person",
    "find someone who makes me want better",
  ],
  adventurous: [
    "travel to at least three new countries",
    "go on a spontaneous road trip",
    "try something that actually scares me",
    "learn to surf or rock climb",
    "take a solo trip by myself",
    "hike to the top of a mountain",
    "explore hidden gems in my own city",
    "say yes to things that scare me",
    "try foods from cuisines I've never had",
    "go camping under the stars",
    "take a weekend trip somewhere new",
    "learn to scuba dive this year",
    "go on a cross-country road trip",
    "visit every national park on my list",
    "try extreme sports that push my limits",
    "explore off the beaten path places",
    "learn a new language for travel",
    "create adventures worth telling stories about",
    "live more spontaneously this year",
    "find new adventures close to home",
  ],
  quirky: [
    "start a weird collection nobody gets",
    "learn an obscure skill for fun",
    "embrace my weirdness fully this year",
    "master a niche hobby nobody knows",
    "start a quirky tradition for myself",
    "learn to play an unusual instrument",
    "create something totally unique",
    "start a blog about my weird interests",
    "collect something oddly specific",
    "learn a weird party trick",
    "create my own aesthetic",
    "do something unconventional that makes me happy",
    "master the art of thrifting",
    "become known for being authentically weird",
    "learn about obscure topics I love",
    "start a quirky club",
    "stop trying to fit into normal molds",
    "be unapologetically weird",
    "dress to my own beat",
    "embrace my eccentricities fully",
  ],
  serious: [
    "achieve financial independence this year",
    "advance in my career",
    "build better habits that actually stick",
    "invest in myself through learning",
    "create multiple income streams",
    "prioritize my mental health",
    "build generational wealth for my future",
    "achieve better work life balance",
    "develop leadership skills",
    "create a solid financial plan",
    "invest in assets that grow",
    "build my professional network",
    "achieve my biggest career goal",
    "establish healthy boundaries",
    "create a retirement plan",
    "develop emotional intelligence",
    "achieve financial literacy",
    "build a business on the side",
    "invest in my education",
    "create stability in my life",
  ],
  intellectual: [
    "read at least fifty books",
    "learn a new language",
    "take courses on things I love",
    "write more consistently",
    "attend lectures from experts I admire",
    "learn about philosophy",
    "read classic literature",
    "study a subject deeply",
    "have more intellectual conversations",
    "learn about different cultures",
    "develop critical thinking skills",
    "read research papers",
    "learn about history",
    "study psychology",
    "challenge my own beliefs",
    "learn about science",
    "read philosophy books",
    "study art history",
    "learn about economics",
    "become a lifelong learner",
  ],
  default: [
    "travel somewhere new and make memories",
    "focus on my personal growth this year",
    "build stronger relationships with good people",
    "step outside my comfort zone more",
    "prioritize my health and wellness",
    "save money and be more financially smart",
    "learn a new skill I've been wanting",
    "spend more quality time with loved ones",
    "work on my career goals",
    "be more present and mindful",
    "create better work life balance",
    "develop healthier habits that stick",
    "make new friends this year",
    "be more adventurous and say yes",
    "focus on self care more",
    "finally achieve goals I've been putting off",
    "spend less time on my phone",
    "be kinder to myself",
    "create memories over buying stuff",
    "live more intentionally",
  ],
};

module.exports = thisYearIReallyWantTo;
