const togetherWeCould = {
  "funny": [
    "binge watch entire series and pretend we're being productive somehow 😂",
    "order way too much food and regret nothing about it",
    "have dance parties in the kitchen while cooking dinner together",
    "make terrible jokes and laugh at ourselves for hours straight",
    "stay in bed all day and call it self care",
    "try every restaurant in town and become food critics honestly",
    "have movie marathons with all the snacks we can find",
    "make up songs about random things and perform them dramatically",
    "people watch at cafes and make up stories about everyone",
    "have game nights and get way too competitive about it",
    "try cooking new recipes and probably burn something every time",
    "have karaoke nights and sing terribly but with full confidence",
    "build pillow forts and watch movies like we're kids again",
    "try every coffee shop and rate them like professionals honestly",
    "have lazy sundays doing absolutely nothing and loving every minute",
    "make each other laugh until our stomachs hurt and we",
    "try weird food combinations and see what actually works surprisingly",
    "have spontaneous dance offs in the living room for no",
    "make fun of each other lovingly and laugh about everything",
    "stay up way too late talking about the most random"
  ],
  "romantic": [
    "build a life filled with love laughter and beautiful memories ❤️",
    "travel the world and make memories in every place we",
    "grow old together and still be in love after all",
    "create our own traditions and build a life that's uniquely",
    "support each other's dreams and celebrate every win together always",
    "have deep conversations late at night and share everything with",
    "make every day special just by being together in it",
    "build a home that feels safe and full of love",
    "dance in the kitchen and kiss in the rain together",
    "watch sunsets and sunrises from all over the world together",
    "create a love story that inspires others and lasts forever",
    "be each other's best friend and biggest supporter through everything",
    "make ordinary moments feel magical just by being together in",
    "build something real and lasting that stands the test of",
    "grow together instead of apart and choose each other daily",
    "create beautiful memories that we'll cherish for the rest of",
    "be partners in everything and face life's challenges together always",
    "make each other better and bring out the best in",
    "build a life full of love adventure and genuine connection",
    "be there for each other through every high and low"
  ],
  "adventurous": [
    "travel to every continent and experience different cultures together 🌟",
    "go on spontaneous road trips with no destination in mind",
    "try every adventure sport and activity we can find anywhere",
    "hike all the best trails and see the most beautiful",
    "explore new cities and find hidden gems nobody knows about",
    "take cooking classes in different countries and learn local cuisines",
    "go on weekend getaways to places we've never been before",
    "try all the local food and become adventurous eaters together",
    "go camping under the stars in the most remote places",
    "take a cross country road trip and stop at random",
    "learn to surf dive or any water sport together somewhere",
    "explore national parks and see nature's most beautiful places together",
    "take spontaneous trips whenever we feel like getting away from",
    "try activities that scare us and push our limits together",
    "go on food tours and try everything the locals recommend",
    "explore off the beaten path destinations that tourists don't visit",
    "take adventure vacations instead of just relaxing on beaches always",
    "try new experiences in every city we visit together always",
    "go on sunrise hikes and watch the world wake up",
    "make every trip an adventure and collect stories not things"
  ],
  "quirky": [
    "start weird traditions that don't make sense to anyone else 🎨",
    "make art projects that are strange but meaningful to us",
    "have deep philosophical conversations about the most random topics at",
    "collect odd things together and create our own little museum",
    "make up our own language that nobody else would understand",
    "have themed days where we dress according to random aesthetics",
    "create playlists for oddly specific moods and situations we experience",
    "make weird food combinations and see what actually tastes good",
    "have our own inside jokes that nobody else gets at",
    "create our own quirky rituals and stick to them religiously",
    "make everything more interesting by adding our own weird twist",
    "have parallel play dates where we do our own things",
    "collect random mementos from places that mean something to us",
    "make up stories and theories about random things we observe",
    "have our own weird way of doing everything in life",
    "create art or music that's unconventional but uniquely ours together",
    "embrace our weirdness and not care what anyone else thinks",
    "make our relationship uniquely ours with all our quirks and",
    "have deep conversations about topics nobody else finds interesting at",
    "celebrate our oddities and the things that make us different"
  ],
  "serious": [
    "build a stable secure future for ourselves and our family",
    "support each other's career goals and celebrate every achievement together",
    "invest in our future and make smart financial decisions together",
    "work towards our goals and hold each other accountable always honestly",
    "build generational wealth and set up our family for success",
    "create a life that aligns with our values and priorities",
    "support each other through challenges and celebrate wins together always",
    "build something meaningful that we're both proud of in life",
    "work on personal growth together and become better people daily",
    "achieve our goals faster by supporting and motivating each other",
    "build a strong foundation for our future together through effort",
    "create financial stability and security for ourselves and our family",
    "work towards our dreams and make them reality together always",
    "build a life we're both proud of through hard work",
    "support each other's ambitions and help each other succeed in",
    "create a partnership where we both thrive and grow constantly",
    "build wealth and financial freedom for our future together always",
    "work on becoming the best versions of ourselves every day",
    "achieve more together than we ever could apart from each",
    "build a legacy that we're proud to leave behind"
  ],
  "intellectual": [
    "have deep conversations that challenge how we think about everything 🧠",
    "learn new things together and expand our knowledge constantly always",
    "read books and discuss them over coffee for hours honestly",
    "take classes together and learn new skills as a team",
    "visit museums and galleries and discuss what we see there",
    "have philosophical debates that make us both think more deeply",
    "learn from each other and grow intellectually as a couple",
    "explore new ideas and concepts that fascinate us both deeply",
    "attend lectures and talks about topics we're interested in together",
    "challenge each other's thinking in respectful and productive ways always",
    "read the same books and have discussions about them later",
    "learn new languages together and practice with each other daily",
    "explore different perspectives and broaden our worldviews together constantly always",
    "have meaningful discussions about topics that matter to us both",
    "learn about each other's interests and teach each other new",
    "grow intellectually together and never stop being curious about world",
    "discuss ideas and theories that fascinate us for hours on",
    "learn from experts together and expand our understanding of things",
    "challenge our assumptions and grow through intellectual discourse together always",
    "build a relationship based on intellectual connection and mutual growth"
  ],
  "default": [
    "make each other laugh and bring joy into each other's ✨",
    "support each other through everything life throws at us together",
    "build a life we're both happy with and proud of",
    "create beautiful memories that we'll cherish for years to come",
    "be there for each other through good times and bad",
    "make every day a little better just by being together",
    "grow together and bring out the best in each other",
    "build something real and meaningful that lasts through everything in",
    "support each other's dreams and celebrate every win together always",
    "make ordinary moments special just by being together in them",
    "be partners in everything and face life as a team",
    "create a life filled with love laughter and genuine connection",
    "be each other's biggest supporters and best friends through everything",
    "make each other better people and help each other grow",
    "build a future together that we're both excited about honestly",
    "be there for each other no matter what life brings",
    "create happiness and bring out the best in each other",
    "make life more fun and meaningful just by being together",
    "support each other and work towards our goals as a",
    "build a relationship based on trust love and genuine partnership"
  ]
};

module.exports = togetherWeCould;
