const tryToGuessThisAboutMe = {
  funny: [
    "my most embarrassing moment that i still cringe about",
    "what im weirdly competitive about for absolutely no reason",
    "my go to karaoke song that i absolutely butcher",
    "the dumbest thing ive ever done for a crush",
    "what my screen time report says about me weekly",
    "my most irrational fear that makes zero sense logically",
    "the worst pickup line ive ever used or heard",
    "what i would buy first with a million dollars",
    "my signature dance move that should never be seen",
    "the weirdest compliment ive ever received from someone random",
    "what celebrity i think i could beat in fight",
    "my most unpopular opinion that gets me cancelled probably",
    "the last lie i told and why i said",
    "what my pet would say about me if they",
    "my guilty pleasure show i watch on repeat always",
    "the most chaotic decision ive made on pure impulse",
    "what im secretly judging everyone for all the time",
    "my comfort food that i eat way too often",
    "the worst date ive been on and the story",
    "what i do when i think nobodys watching me",
  ],
  romantic: [
    "my love language and how i show i care",
    "what makes me fall for someone every single time",
    "my idea of the perfect date night together ideally",
    "the moment i knew i wanted something real serious",
    "what little things make my heart skip a beat",
    "my favorite way to be shown love and affection",
    "the quality i value most in a partner always",
    "what my future relationship looks like in my dreams",
    "the sweetest thing someone has ever done for me",
    "what makes me believe in love and happy endings",
    "my favorite romantic gesture that melts my heart instantly",
    "the moment i realized i was falling for someone",
    "what i need to feel safe in a relationship",
    "my favorite love song and why it hits different",
    "the small gesture that means more than grand ones",
    "what i look for in a real connection with",
    "my idea of what true love should feel like",
    "the way i show someone they matter to me",
    "what makes me feel most loved and appreciated always",
    "my relationship goal and what i want to build",
  ],
  adventurous: [
    "the craziest thing on my bucket list right now",
    "where id go if i could travel anywhere tomorrow",
    "my most spontaneous decision that turned out amazing well",
    "what living life to the fullest means to me",
    "the adventure that changed my entire perspective on life",
    "where i see myself living in five years exactly",
    "the scariest thing ive done that was worth it",
    "my dream adventure and who id want there with",
    "the next place i want to explore and why",
    "what experience made me feel most alive and free",
    "the biggest risk i took that paid off well",
    "where i feel most at home in the world",
    "the trip that changed me as a person completely",
    "what im running toward instead of away from now",
    "my next big goal or dream im working toward",
    "what adventure means to me beyond just traveling places",
    "the moment i realized i was capable of more",
    "where my happy place is in the entire world",
    "the experience i want to have before i die",
    "what makes me feel most alive right this moment",
  ],
  quirky: [
    "my weirdly specific ick that nobody else understands fully",
    "the random hill id die on without any hesitation",
    "what niche interest im currently obsessed with researching now",
    "the oddly specific thing i find attractive in people",
    "my comfort show and how many times ive watched",
    "the weird habit i have that i dont notice",
    "what my organizational system says about my personality type",
    "the random talent i have that impresses nobody really",
    "my go to fun fact that i tell everyone",
    "the thing i collect that makes no sense to",
    "what my oddly specific routine reveals about me psychologically",
    "the niche community im part of that nobody knows",
    "my signature quirk and the weird story behind it",
    "the random thing that brings me unreasonable joy daily",
    "what makes me different from literally everyone else around",
    "my weirdly specific preference about literally everything in life",
    "the most niche reference i make that nobody gets",
    "the random fact i know that ill never use",
    "what my comfort items say about me as person",
    "the thing that makes me uniquely me and nobody",
  ],
  serious: [
    "what ive learned about myself through therapy or growth",
    "the biggest lesson life has taught me so far",
    "my non negotiables in relationships and life in general",
    "the moment that changed my perspective on everything completely",
    "what im currently working on improving about myself actively",
    "the pattern ive noticed in all my past relationships",
    "what makes me feel truly seen and understood deeply",
    "the boundary i set that changed everything for me",
    "what emotional intimacy means to me in relationships here",
    "the thing im most proud of overcoming in life",
    "what i need to feel secure in a relationship",
    "the cycle im actively trying to break right now",
    "what self love actually looks like for me personally",
    "the fear im currently working through in therapy now",
    "my core values and how i try to live",
    "the thing i need to forgive myself for finally",
    "what vulnerability means to me and why its hard",
    "the person im becoming and whether i like them",
    "my attachment style and how it affects my relationships",
    "the thing that keeps me up at night thinking",
  ],
  intellectual: [
    "the book that completely changed my perspective on life",
    "what philosophical question im currently pondering deeply about existence",
    "the topic i could talk about for hours endlessly",
    "my unpopular opinion on a major social or cultural",
    "the documentary that made me think differently about everything",
    "what theory or concept fascinates me the most currently",
    "the idea that challenges conventional thinking i find interesting",
    "my thoughts on the meaning of life and purpose",
    "the pattern ive noticed that nobody else talks about",
    "my favorite debate topic and my stance on it",
    "the connection i made between two unrelated concepts recently",
    "what keeps me up at night thinking about deeply",
    "the question i wish more people asked themselves daily",
    "my thoughts on human nature and what drives people",
    "the concept im trying to fully understand right now",
    "my current research rabbit hole and why its fascinating",
    "the perspective shift that happened after learning something new",
    "what i think makes life meaningful and worthwhile overall",
    "the idea im developing about something ive been observing",
    "what i believe about the world that most disagree",
  ],
};

module.exports = tryToGuessThisAboutMe;
