const typicalSunday = {
  "funny": [
    "sleeping in late then making brunch that's honestly kinda burnt 😂",
    "binge watching shows in bed and pretending I'll be productive later",
    "trying new recipes that turn into ordering takeout instead lol",
    "coffee runs and laughing at my own jokes all day long",
    "staying in pjs way too long and loving every second",
    "making plans to go out but ending up on the couch",
    "scrolling through memes and sending them to literally everyone I know",
    "attempting yoga but mostly just falling over and giggling about it",
    "farmers market vibes then napping like it was a full workout",
    "cooking breakfast at 2pm because mornings are honestly just a suggestion",
    "pretending I'll go to the gym but really just watching netflix",
    "making coffee and spilling it at least twice before noon hits",
    "trying to adult but mostly just eating snacks and being chaotic",
    "planning my week then forgetting everything by monday morning anyway",
    "brunch with friends where we laugh way too loud at everything",
    "attempting to be productive but getting distracted by literally anything shiny",
    "making tiktoks in my room and hoping my roommate doesn't judge",
    "coffee shop hopping and rating their vibes like I'm a professional",
    "staying in bed reading until I realize it's already dark outside",
    "trying new hobbies that I'll definitely quit by next sunday lol"
  ],
  "romantic": [
    "cuddling with someone special and making breakfast together in the morning ❤️",
    "long walks holding hands and talking about our dreams and future",
    "lazy mornings in bed with coffee and soft kisses that feel perfect",
    "cooking together while dancing in the kitchen to our favorite songs honestly",
    "farmers market dates then coming home to cook what we bought together",
    "staying in bed all day just talking and laughing with someone",
    "making pancakes together and stealing kisses between flipping them over the stove",
    "sunset walks and deep conversations that make me feel so connected",
    "cozy movie marathons with someone who makes my heart feel so full",
    "brunch dates where we share everything and just enjoy each other's company",
    "morning coffee on the balcony talking about life with someone I adore",
    "cooking dinner together and slow dancing while waiting for it to finish",
    "lazy afternoons reading next to someone who just gets me completely honestly",
    "exploring new cafes and holding hands like we're in our own world",
    "staying up late talking about everything and nothing with someone I love",
    "making breakfast in bed for someone who makes me smile every day",
    "long drives with good music and someone who feels like home honestly",
    "picnics in the park with someone who makes ordinary moments feel magical",
    "cooking together and tasting everything while laughing at our messy kitchen honestly",
    "cozy mornings with someone special where we don't need words to connect"
  ],
  "adventurous": [
    "hiking new trails and finding hidden spots that feel like secrets 🌟",
    "spontaneous road trips to places I've never been before just for fun",
    "trying that new restaurant or activity that everyone's been talking about lately",
    "exploring the city and discovering cute cafes and shops I didn't know",
    "saying yes to random plans and seeing where the day takes me",
    "outdoor adventures like kayaking or rock climbing to feel alive and free",
    "weekend getaways to new cities where I can explore and get lost",
    "trying new foods and cuisines that push me out of my comfort",
    "sunrise hikes that make waking up early actually worth it for once",
    "spontaneous beach trips where we just drive and see what happens next",
    "exploring farmers markets and trying all the samples like it's a mission",
    "bike rides through new neighborhoods to find hidden gems and cool spots",
    "trying new hobbies like pottery or painting just to see if I'm",
    "road trips with no real plan just good music and good vibes",
    "exploring nature trails and taking way too many photos of everything pretty",
    "spontaneous concerts or events that I decide to go to last minute",
    "trying adventure sports that scare me a little but make me feel",
    "exploring new coffee shops and rating them like I'm a professional critic",
    "weekend camping trips where we disconnect and just enjoy nature and stars",
    "saying yes to plans that sound crazy but end up being best"
  ],
  "quirky": [
    "thrifting for weird vintage finds and creating outfits nobody else would wear 🎨",
    "making playlists for oddly specific moods that probably only I understand honestly",
    "talking to my plants and genuinely believing they grow better with encouragement",
    "collecting random things like cool rocks or vintage postcards for no reason",
    "having full conversations with my pet about life like they totally get",
    "making up songs about whatever I'm doing and performing them dramatically",
    "organizing my books by color because it looks pretty even though impractical",
    "trying weird food combinations that sound gross but actually taste amazing trust",
    "naming inanimate objects and getting attached to them like they're my friends",
    "making art projects that make no sense but I love them anyway",
    "watching documentaries about the most random topics and becoming obsessed with them",
    "collecting stickers and putting them on everything I own like a child",
    "having dance parties alone in my room to songs from like 2008",
    "making friendship bracelets for myself because why should kids have all fun",
    "talking in accents randomly just because it makes everything more fun and",
    "keeping a journal where I draw badly but with so much enthusiasm",
    "collecting vintage mugs and using a different one every day for vibes",
    "making tiktoks of my weird thoughts that probably only I find funny",
    "rearranging my room at 2am because suddenly the energy just feels wrong",
    "having themed days where I dress and act according to random aesthetics"
  ],
  "serious": [
    "working on personal projects and goals that actually matter to my future",
    "meal prepping and planning my week so I can stay on track",
    "reading books that challenge me and help me grow as a person",
    "working out and taking care of my body because health is important",
    "journaling and reflecting on my goals and where I want to be",
    "learning new skills that will help me in my career and life",
    "organizing my space and life so I can be more productive overall",
    "working on side projects that align with my long term goals honestly",
    "planning my finances and making sure I'm being responsible with my money",
    "networking and building connections that will help me grow professionally and personally",
    "taking online courses to improve my skills and stay competitive in field",
    "working on my mental health through therapy or self reflection and growth",
    "setting boundaries and making sure I'm prioritizing what truly matters to",
    "building habits that will help me become the person I want to",
    "volunteering or giving back to causes that I genuinely care about deeply",
    "working towards certifications or qualifications that will advance my career path forward",
    "meal planning and cooking healthy meals to fuel my body and mind",
    "dedicating time to my passion projects that align with my core values",
    "building a morning routine that sets me up for success every day",
    "investing in relationships that are meaningful and help me grow as person"
  ],
  "intellectual": [
    "reading philosophy books and questioning everything I thought I knew about life 🧠",
    "listening to podcasts about science and history while doing literally anything else",
    "visiting museums and getting lost in art and history for hours honestly",
    "watching documentaries about random topics and falling down research rabbit holes after",
    "reading articles about psychology and trying to understand why people do things",
    "learning new languages on apps because I love how it changes perspective",
    "going to lectures or talks about topics I know nothing about yet",
    "reading multiple books at once because I can't commit to just one",
    "having deep conversations about existence and meaning over coffee for hours and",
    "researching random questions that pop into my head until I understand them",
    "visiting bookstores and leaving with way more books than I can read",
    "listening to audiobooks while cooking or cleaning to maximize my learning time always",
    "taking online courses about subjects that fascinate me just for fun honestly",
    "writing essays or thoughts about concepts I'm trying to understand better lately",
    "attending workshops or seminars to learn from experts in different fields always",
    "reading scientific journals and trying to understand complex studies and their implications",
    "exploring different philosophies and worldviews to expand how I see everything around",
    "watching ted talks and taking notes like I'm in class again",
    "joining book clubs or discussion groups to hear different perspectives on topics",
    "researching historical events and trying to understand their impact on today's world"
  ],
  "default": [
    "sleeping in then doing whatever feels right in the moment honestly ✨",
    "mixing lazy vibes with random bursts of productivity throughout the whole day",
    "coffee and chill mornings then maybe going out if I feel like",
    "balancing me time with seeing friends and just going with the flow",
    "doing a mix of everything from reading to exploring to just relaxing",
    "starting slow then seeing where the day takes me without any pressure",
    "brunch with friends then maybe a walk or just hanging at home",
    "catching up on shows then getting outside for a bit of fresh",
    "self care morning then spontaneous plans if something fun comes up later",
    "cooking a nice meal and enjoying it without rushing through anything today",
    "mix of productive tasks and fun activities depending on my mood honestly",
    "coffee shop vibes in the morning then exploring or relaxing in afternoon",
    "doing whatever makes me happy without overthinking it too much at all",
    "balancing rest with adventure and seeing what feels right in the moment",
    "starting with breakfast and letting the rest unfold naturally throughout the day",
    "mixing social time with alone time based on what I need that",
    "doing things that bring me joy without any specific plan or schedule",
    "coffee walks and good conversations mixed with peaceful moments alone too honestly",
    "going with the flow and doing whatever feels authentic to me today",
    "balancing productivity with relaxation and just enjoying the day as it comes"
  ]
};

module.exports = typicalSunday;
