const wellGetAlongIf = {
  "funny": [
    "you laugh at my terrible jokes even when they're bad 😂",
    "you're okay with me being chaotic and add to it",
    "you don't judge me for eating cereal at midnight honestly",
    "you appreciate my sarcasm and dish it right back at",
    "you're down for spontaneous food runs at 2am without question",
    "you let me nap whenever I want without any judgment",
    "you understand that I'm not a morning person ever",
    "you make everything fun even boring tasks like grocery shopping",
    "you don't take yourself too seriously and laugh at yourself",
    "you're okay with my random tangents and find them entertaining",
    "you can handle my mood swings and don't take personally",
    "you appreciate my weird sense of humor and contribute your",
    "you're down for movie marathons and binge watching shows together",
    "you don't mind that I talk to myself constantly throughout",
    "you're okay with me being dramatic because that's just",
    "you can keep up with my energy levels that",
    "you appreciate my memes and send me good ones back",
    "you're down to try weird food combinations with me",
    "you don't judge my comfort shows that I've watched",
    "you make me laugh and don't mind when I'm"
  ],
  "romantic": [
    "you're looking for something real not just casual or temporary ❤️",
    "you value communication and emotional availability in relationships with people always",
    "you believe actions speak louder than words when showing love",
    "you're ready to build something meaningful with the right person",
    "you value quality time and being present with each other",
    "you're emotionally available and ready for a real connection honestly",
    "you believe in showing love consistently not just in beginning",
    "you value honesty and open communication even when it's hard",
    "you're looking for a partner not just someone to pass",
    "you believe in making effort and not playing games with",
    "you value affection and aren't afraid to show your feelings",
    "you're ready for commitment and building something that lasts long",
    "you believe in supporting each other's dreams and goals always",
    "you value emotional intimacy and being vulnerable with your partner",
    "you're looking for your best friend and partner in one",
    "you believe relationships take work and you're willing to put",
    "you value consistency and being someone your partner can count",
    "you're ready to choose someone every day not just sometimes",
    "you believe in building something real through effort and intention",
    "you value genuine connection over superficial attraction or chemistry alone"
  ],
  "adventurous": [
    "you're down for spontaneous adventures and last minute plans always 🌟",
    "you love trying new things even when they're scary or",
    "you're open to exploring new places and experiences with me",
    "you have that adventurous energy and love to travel explore",
    "you're willing to step outside your comfort zone regularly with",
    "you love trying new foods and cuisines from different cultures",
    "you're spontaneous and don't need everything planned out in advance",
    "you're down for outdoor activities and nature adventures with me",
    "you love road trips and exploring new places we've never",
    "you're open to saying yes to random opportunities that come",
    "you have wanderlust and want to see the world with",
    "you're willing to take risks and see where they lead",
    "you love making memories through experiences not just buying things",
    "you're excited about trying activities we've never done before together",
    "you're spontaneous with weekend plans and go with the flow",
    "you love exploring and discovering hidden gems in new places",
    "you're down for adventure dates instead of just dinner and",
    "you're open to travel and experiencing different cultures together always",
    "you love being active and trying new outdoor activities with",
    "you're excited about making every day an adventure together"
  ],
  "quirky": [
    "you're unapologetically yourself even when it's weird or different 🎨",
    "you appreciate my quirks and add your own to the",
    "you're okay with being different and standing out from everyone",
    "you have niche interests that you're passionate about and share",
    "you're comfortable with your weirdness and don't try to hide",
    "you appreciate the unconventional and find beauty in strange things",
    "you're authentically odd and own every bit of your uniqueness",
    "you have your own unique perspective on things that fascinates",
    "you're okay with deep weird conversations at 3am about random",
    "you celebrate what makes you different instead of trying to",
    "you're perfectly imperfect and embrace all your quirks and oddities",
    "you have obscure references that only certain people would understand",
    "you're comfortable being yourself even when it doesn't make sense",
    "you appreciate my oddities and don't try to change me",
    "you're weird in the best way possible and own it",
    "you have quirky habits that make you interesting and memorable",
    "you're okay with being eccentric and not fitting into molds",
    "you celebrate our differences and the things that make us",
    "you're authentically yourself without worrying about what others think about",
    "you appreciate weird humor and have your own brand of"
  ],
  "serious": [
    "you're emotionally mature and can communicate like an actual adult",
    "you have your life somewhat together and work toward goals",
    "you're honest about your intentions and what you're looking for",
    "you respect boundaries and understand they exist for good reasons",
    "you're reliable and do what you say you're going to",
    "you take accountability for your actions instead of making excuses",
    "you're looking for something real and meaningful not just casual",
    "you respect my time and don't waste it playing games",
    "you're financially responsible and have a plan for your future",
    "you're consistent with your words and actions so I can",
    "you take relationships seriously and put in the effort they",
    "you're emotionally available and ready for a real connection honestly",
    "you respect my career and ambitions as much as your",
    "you're mature enough to handle difficult conversations without shutting down",
    "you take my feelings seriously and don't dismiss them as",
    "you're someone I can count on through good times and",
    "you respect my standards because I set them for reasons",
    "you're honest about your past and what you've learned from",
    "you're ready for commitment not just casual dating or temporary",
    "you respect me as an equal partner in everything we"
  ],
  "intellectual": [
    "you enjoy deep conversations that go beyond surface level topics 🧠",
    "you're intellectually curious and always want to learn new things",
    "you're open to different perspectives and willing to change your",
    "you enjoy thoughtful discussions that challenge how we think about",
    "you're well read and have interesting thoughts on various topics",
    "you ask questions and want to understand things more deeply",
    "you're open minded and willing to learn from anyone including",
    "you enjoy debates without getting defensive or taking things too",
    "you're curious about the world and want to understand it",
    "you have opinions that are well thought out and based",
    "you're intellectually stimulating and make me think in new ways",
    "you're interested in learning together and exploring ideas as a",
    "you enjoy meaningful discussions about topics that matter to us",
    "you're thoughtful and consider different angles before forming strong opinions",
    "you're curious about my thoughts and perspectives on things that",
    "you engage with ideas seriously instead of dismissing them as",
    "you're intellectually honest and admit when you don't know something",
    "you enjoy conversations that are interesting and engaging not just",
    "you're open to having your views challenged in good ways",
    "you value intellectual connection as much as emotional connection in"
  ],
  "default": [
    "you're kind and treat everyone with respect not just me ✨",
    "you're genuine and authentic in how you present yourself to",
    "you make me feel comfortable being myself completely around you",
    "you're a good listener and actually hear what I say",
    "you're consistent and someone I can count on through everything",
    "you're honest and communicate openly even when it's difficult or",
    "you make me laugh and bring joy into my life",
    "you're supportive of my goals and dreams no matter what",
    "you respect my boundaries and understand they exist for reasons",
    "you're patient and understanding with me through everything in life",
    "you make me feel valued and appreciated for who I",
    "you're emotionally available and present when we're together not distant",
    "you show love through actions not just words that mean",
    "you're reliable and follow through on what you say you'll",
    "you make me feel safe and comfortable being vulnerable with",
    "you're thoughtful and do little things that show you care",
    "you respect me and treat me well consistently not just",
    "you're someone who makes me want to be better",
    "you make me feel like I matter and my feelings",
    "you're genuine about your intentions and what you want from"
  ]
};

module.exports = wellGetAlongIf;
