const wereTheSameTypeOfWeirdIf = {
  "funny": [
    "you also talk to yourself and have full conversations alone 😂",
    "you make sound effects for everything you do throughout the",
    "you also do a little dance when your food arrives",
    "you talk to your plants and genuinely believe they respond",
    "you also practice conversations in your head before having them",
    "you make up songs about whatever you're doing at moment",
    "you also narrate your life like you're in a documentary",
    "you do victory dances for accomplishing even the smallest things",
    "you also get way too excited about finding good parking",
    "you make weird noises when you're concentrating on something hard",
    "you also celebrate small wins like they're major life achievements",
    "you have names for all your belongings and talk to",
    "you also get overly invested in tv show characters' lives",
    "you make up elaborate backstories for strangers you see in",
    "you also get way too competitive about board games honestly",
    "you do impressions of people when telling stories about them",
    "you also have a specific playlist for every possible mood",
    "you get excited about office supplies and organization stuff too",
    "you also laugh at your own jokes before finishing them",
    "you make everything more dramatic than it needs to be"
  ],
  "romantic": [
    "you also believe in soulmates and love at first sight ❤️",
    "you get butterflies thinking about someone you really like still",
    "you save cute texts and reread them when you're missing",
    "you also make playlists for people you have crushes on",
    "you daydream about future scenarios with someone you're into constantly",
    "you get nervous and giggly around someone you really like",
    "you notice every little detail about someone you're interested in",
    "you also write poetry or journal entries about people you",
    "you plan out perfect dates in your head before they",
    "you get excited about the idea of meeting someone's family",
    "you save voice notes just to hear someone's voice later",
    "you screenshot sweet messages to look at when you're sad",
    "you believe in grand romantic gestures and love languages too",
    "you get genuinely excited about relationship milestones and anniversaries always",
    "you make up cute couple names in your head for",
    "you plan future trips and adventures with someone you're dating",
    "you get emotional watching romantic movies and thinking about your",
    "you keep little mementos from dates and special moments together",
    "you believe in the magic of first kisses and meaningful",
    "you get excited about the idea of growing old with"
  ],
  "adventurous": [
    "you also research random places you want to visit for 🌟",
    "you have a bucket list that's way too long honestly",
    "you get overly excited about trying new foods and cuisines",
    "you plan imaginary trips to places you've never been to",
    "you collect maps and travel guides even for places you",
    "you watch travel vlogs and documentaries like it's your job",
    "you have detailed itineraries for trips you haven't even booked",
    "you get excited about airport security and the whole travel",
    "you research hiking trails and outdoor activities in your free",
    "you make lists of adventures you want to have someday",
    "you get genuinely excited about trying new activities even when",
    "you plan road trips with detailed stops and photo opportunities",
    "you collect souvenirs from every place you visit no matter",
    "you research local customs and phrases before visiting new places",
    "you get excited about packing and planning what to bring",
    "you watch videos about extreme sports you'll probably never try",
    "you have a world map where you mark places you",
    "you get overly excited about spontaneous adventure opportunities that come",
    "you research the best local spots before visiting anywhere new",
    "you plan future adventures constantly even when you can't afford"
  ],
  "quirky": [
    "you have very specific and weird routines that you follow 🎨",
    "you collect random things that have no real value to",
    "you organize things in oddly specific ways that make sense",
    "you have strong opinions about things that don't really matter",
    "you make up words and use them like they're real",
    "you have elaborate theories about random things nobody else cares",
    "you notice patterns and coincidences that nobody else seems to",
    "you have niche interests that you could talk about for",
    "you make spreadsheets for things that don't need spreadsheets at",
    "you have a very specific way of doing everyday tasks",
    "you get attached to inanimate objects and give them personalities",
    "you have weird superstitions that you follow even though they're",
    "you make lists for literally everything in your life constantly",
    "you have strong feelings about fonts and design choices in",
    "you notice small details that most people completely overlook or",
    "you have elaborate systems for organizing your digital and physical",
    "you get excited about things most people find boring or",
    "you have very specific preferences about random everyday things honestly",
    "you make connections between unrelated things that somehow make sense",
    "you have quirky habits that you don't even realize you're"
  ],
  "serious": [
    "you take your goals and personal development very seriously always",
    "you have detailed plans for your future that you review",
    "you track your progress and habits with apps and journals",
    "you read self improvement books and actually implement what you",
    "you have a morning routine that you follow religiously every",
    "you set goals for every area of your life and",
    "you take notes during podcasts and lectures to remember key",
    "you have a five year plan that you update regularly",
    "you track your finances meticulously and budget for everything you",
    "you take your career development seriously and constantly work on",
    "you have systems in place for productivity and time management",
    "you read industry news and stay updated on your field",
    "you network intentionally and maintain professional relationships carefully and thoughtfully",
    "you invest in courses and education to improve your skills",
    "you have mentors and actively seek feedback on your performance",
    "you take your health seriously and track nutrition and exercise",
    "you plan your weeks in advance and schedule everything you",
    "you set quarterly reviews to assess your progress toward goals",
    "you take continuing education seriously and always work on learning",
    "you have backup plans for your backup plans just in"
  ],
  "intellectual": [
    "you read multiple books at once and remember details from 🧠",
    "you fact check things mid conversation and can't help yourself",
    "you get excited about learning new words and using them",
    "you listen to educational podcasts for fun in your free",
    "you watch documentaries and take notes like you're in school",
    "you correct grammar and pronunciation in your head constantly without",
    "you get into deep research rabbit holes about random topics",
    "you have strong opinions about proper citation formats and academic",
    "you get excited about visiting museums and reading every single",
    "you debate ideas for fun and enjoy intellectual discourse with",
    "you read academic papers and journals in your spare time",
    "you get genuinely excited about learning new concepts and theories",
    "you have a reading list that's organized by topic and",
    "you take online courses just for fun not for credit",
    "you get excited about TED talks and intellectual discussions online",
    "you remember random facts and bring them up in conversations",
    "you enjoy analyzing and discussing complex topics with anyone who'll",
    "you get excited about libraries and bookstores like they're theme",
    "you have opinions about different schools of thought and philosophical",
    "you get genuinely excited when you learn something new that"
  ],
  "default": [
    "you also get really excited about things most people find ✨",
    "you have weird little habits that you don't even notice",
    "you get overly invested in things that don't really matter",
    "you make everything more complicated than it needs to be",
    "you have strong opinions about random everyday things that don't",
    "you get excited about small things that make you happy",
    "you do little dances when you're happy or excited about",
    "you talk to yourself more than you probably should honestly",
    "you have elaborate systems for organizing your life and stuff",
    "you get way too into hobbies and interests you pick",
    "you make lists for everything even when you don't need",
    "you have specific ways of doing things that seem weird",
    "you get genuinely excited about things other people find mundane",
    "you notice details that most people completely miss or overlook",
    "you have quirks that you're not even aware of until",
    "you get overly enthusiastic about your interests and passions in",
    "you make everything into a bigger deal than it is",
    "you have weird preferences about everyday things that don't matter",
    "you get excited about organization and planning way too much",
    "you're way more enthusiastic about life than most people are"
  ]
};

module.exports = wereTheSameTypeOfWeirdIf;
