const whatIOrderForTheTable = {
  funny: [
    "literally everything on the appetizer menu without shame honestly",
    "way too much food then pretend i can finish",
    "the weirdest thing on the menu just to try",
    "enough fries for the table but theyre actually mine",
    "something i cant pronounce and hope for the best",
    "the most expensive thing because we only live once",
    "whatever has cheese on it thats my only requirement",
    "too many appetizers and then no room for dinner",
    "the thing that sounds disgusting but might be amazing",
    "enough food to feed an army but just us",
    "something spicy then immediately regret my life choices after",
    "the sampler platter so i can try everything available",
    "whatever the waiter recommends because i trust them completely",
    "way more than we need but leftovers are great",
    "the thing everyone says no to then steals from",
    "something adventurous then order backup safe option too just",
    "all the sides because sides are better than entrees",
    "the thing with the most ingredients listed on menu",
    "enough drinks to make bad decisions seem like good",
    "whatever looks good on someone elses table walking by",
  ],
  romantic: [
    "something we can share and feed each other bites",
    "the wine pairing because tonight is special and romantic",
    "dessert to share even if were full from dinner",
    "the charcuterie board so we can graze and talk",
    "something fancy to make the night feel more special",
    "the chocolate lava cake we can split together sweetly",
    "whatever you want because i want you happy tonight",
    "the appetizer sampler so we can try everything together",
    "champagne because every moment with you deserves celebrating always",
    "the romantic dessert with two spoons for sharing intimately",
    "something we both love so we can enjoy together",
    "the specialty cocktails to make tonight feel more magical",
    "whatever pairs well with good conversation and your company",
    "the fondue so we have an excuse to stay",
    "something indulgent because you deserve to be spoiled tonight",
    "the dessert tasting menu to extend our time together",
    "whatever makes you smile because thats all i want",
    "the romantic entree we can share lady and tramp",
    "something special to match how special you make me",
    "the wine flight so we can sip and talk",
  ],
  adventurous: [
    "the weirdest thing on the menu without hesitation ever",
    "something ive never tried before just to experience it",
    "the spiciest option to see if i can handle",
    "whatever the locals eat not the tourist stuff here",
    "something that scares me a little bit food wise",
    "the mystery dish because wheres the fun in knowing",
    "whatever has the most exotic ingredients listed on menu",
    "the thing everyone warns me about but ill try",
    "something from a cuisine ive never experienced before today",
    "the chefs special because i trust their creative vision",
    "whatever challenges my palate and comfort zone most here",
    "the thing that makes people say are you sure",
    "something i cant get anywhere else in the world",
    "the adventurous option everyone else is too scared for",
    "whatever the chef recommends even if it sounds weird",
    "the thing i might regret but will make great",
    "something that pushes my boundaries and taste buds far",
    "the local delicacy tourists usually avoid eating here always",
    "whatever has the most interesting story behind it culturally",
    "the thing ill either love or hate no between",
  ],
  quirky: [
    "the thing with the weirdest name on the menu",
    "something oddly specific that only i would order probably",
    "the item everyone else thinks is weird but i",
    "whatever has the most random combination of ingredients listed",
    "the thing that doesnt quite fit any category here",
    "something i have a very specific way of eating",
    "the menu item that makes the waiter raise eyebrows",
    "whatever satisfies my oddly specific craving right this moment",
    "the thing i always order because im a creature",
    "something that reflects my unique and quirky taste preferences",
    "the item with modifications that make it unrecognizable basically",
    "whatever matches my very particular mood right now exactly",
    "the thing that comes with a side everyone hates",
    "something i order the same way every single time",
    "the menu item that needs explaining to everyone else",
    "whatever appeals to my weirdly specific food preferences today",
    "the thing that makes people question my taste completely",
    "something with a very particular preparation i always request",
    "the item i have strong opinions about how its",
    "whatever satisfies my niche craving nobody else understands fully",
  ],
  serious: [
    "something healthy because i actually care about my body",
    "the option that aligns with my dietary restrictions always",
    "whatever fits my nutritional goals for the day today",
    "something balanced with protein and vegetables not just carbs",
    "the meal that wont make me feel terrible later",
    "whatever i can actually pronounce and know whats in",
    "something that respects my boundaries and food preferences completely",
    "the option that works for everyones dietary needs here",
    "whatever is fresh and made with quality ingredients only",
    "something mindful that nourishes my body not just fills",
    "the meal that aligns with my values and ethics",
    "whatever doesnt compromise my health goals or dietary choices",
    "something sustainable and ethically sourced if possible here always",
    "the option that respects my relationship with food healthily",
    "whatever i can enjoy without guilt or regret later",
    "something that fits my lifestyle and wellness goals perfectly",
    "the meal that makes me feel good physically mentally",
    "whatever aligns with my intentional eating habits and choices",
    "something nourishing that actually serves my body well today",
    "the option that respects my boundaries around food always",
  ],
  intellectual: [
    "something with an interesting cultural history behind it always",
    "the dish that represents authentic regional cuisine best here",
    "whatever has the most complex flavor profile on menu",
    "something that tells a story about the local culture",
    "the option that showcases the chefs technical skill best",
    "whatever represents the intersection of tradition and innovation here",
    "something that reflects the regions culinary heritage and history",
    "the dish with the most interesting preparation method described",
    "whatever demonstrates the art and science of cooking well",
    "something that challenges conventional ideas about this cuisine type",
    "the option that best represents the chefs culinary philosophy",
    "whatever has the most thoughtful ingredient pairings and combinations",
    "something that reflects sustainable and ethical food practices here",
    "the dish that showcases seasonal local ingredients best available",
    "whatever represents the evolution of this particular cuisine historically",
    "something with layers of flavor that reveal themselves slowly",
    "the option that demonstrates mastery of technique and flavor",
    "whatever tells the most compelling story through its ingredients",
    "something that represents the cultural significance of this food",
    "the dish that best exemplifies the restaurants culinary vision",
  ],
};

module.exports = whatIOrderForTheTable;
