const youShouldLeaveACommentIf = {
  "funny": [
    "they laugh at my terrible jokes",
    "they're not afraid to be silly",
    "they can handle my chaotic energy",
    "they appreciate my weird sense of humor",
    "they're down for spontaneous food runs",
    "they don't take themselves too seriously ever",
    "they can laugh at themselves too",
    "they match my meme energy perfectly",
    "they're okay with my random tangents",
    "they find my awkwardness endearing somehow",
    "they can keep up with banter",
    "they appreciate my sarcasm and dish back",
    "they're down for late night adventures",
    "they laugh when things go wrong",
    "they don't judge my comfort shows",
    "they're okay with me being dramatic",
    "they can handle my mood swings",
    "they appreciate my random fun facts",
    "they're down to try weird food",
    "they make everything more fun naturally"
  ],
  "romantic": [
    "they remember small details I mention",
    "they make me feel safe and valued",
    "they're emotionally available and communicate openly always",
    "they show affection in little ways daily",
    "they're consistent with their words and actions",
    "they make time for me no matter",
    "they're genuinely interested in my life deeply",
    "they support my dreams and goals always",
    "they're affectionate without me having to ask",
    "they make me feel like a priority",
    "they're vulnerable and open with their feelings",
    "they show love through actions not words",
    "they're patient with me when I'm struggling",
    "they make me feel beautiful every day",
    "they're thoughtful and remember what matters to me",
    "they communicate instead of playing games with me",
    "they make me feel heard and understood",
    "they're intentional about building something real together",
    "they show up consistently not just sometimes",
    "they make me feel cherished and appreciated"
  ],
  "adventurous": [
    "they're down for spontaneous road trips",
    "they say yes to new experiences",
    "they're not afraid to try new things",
    "they're open to exploring new places together",
    "they have that adventurous energy I love",
    "they're willing to step outside comfort zones",
    "they're spontaneous and go with the flow",
    "they love trying new foods and cuisines",
    "they're up for outdoor adventures and activities",
    "they're not afraid of getting a little",
    "they're open to travel and exploring world",
    "they have interesting stories from their adventures",
    "they're willing to take risks with me",
    "they're excited about trying new activities together",
    "they're not stuck in boring routines always",
    "they're open to last minute plans and",
    "they have that wanderlust energy I vibe",
    "they're willing to get lost and explore",
    "they're down for adrenaline rush activities sometimes",
    "they're excited about making new memories together"
  ],
  "quirky": [
    "they embrace their own weirdness fully",
    "they appreciate my odd interests and quirks",
    "they're unapologetically themselves always and completely",
    "they have niche interests that fascinate them",
    "they're okay with being different from everyone",
    "they celebrate the unconventional and unique things",
    "they have their own weird hobbies too",
    "they're not trying to fit into molds",
    "they appreciate art and creativity in life",
    "they have unique perspectives on random things",
    "they're comfortable with their eccentricities completely",
    "they don't judge my weird collections or",
    "they have obscure references I actually get",
    "they're authentically odd in the best way",
    "they appreciate the beauty in strange things",
    "they're not afraid to stand out always",
    "they have quirky habits that make them",
    "they're okay with deep weird conversations late",
    "they celebrate what makes them different proudly",
    "they're perfectly imperfect and own it"
  ],
  "serious": [
    "they respect boundaries without being told twice",
    "they're emotionally mature and can communicate well",
    "they take accountability for their actions always",
    "they're honest even when it's uncomfortable honestly",
    "they have their life somewhat together at least",
    "they're reliable and do what they say",
    "they respect my time and don't waste",
    "they're looking for something real and meaningful",
    "they have goals and are working toward",
    "they're financially responsible and have plans for",
    "they treat everyone with respect not just",
    "they're consistent and don't play mind games",
    "they have emotional intelligence and self awareness clearly",
    "they're serious about their intentions with me",
    "they respect my career and take it",
    "they're mature enough to handle difficult conversations",
    "they have their priorities straight and know",
    "they're honest about their past and learned",
    "they respect women and treat me as",
    "they're ready for commitment not just casual"
  ],
  "intellectual": [
    "they can hold deep meaningful conversations always",
    "they're curious and always learning new things",
    "they ask thoughtful questions that make me think",
    "they're open to different perspectives and ideas",
    "they can debate respectfully without getting defensive ever",
    "they're well read and have interesting thoughts",
    "they're intellectually curious about the world around them",
    "they can discuss complex topics without dumbing down",
    "they're open minded and willing to learn",
    "they challenge my thinking in good ways",
    "they're knowledgeable about topics they're passionate about",
    "they ask questions instead of assuming they know",
    "they're interested in understanding not just being right",
    "they can appreciate nuance in complex issues",
    "they're thoughtful and consider different angles on things",
    "they're engaged and present in conversations always",
    "they have opinions that are well thought out",
    "they're curious about my thoughts and perspectives too",
    "they can discuss ideas without making it",
    "they're intellectually stimulating and make me think"
  ],
  "default": [
    "they're kind to everyone not just me",
    "they're genuine and authentic in how they",
    "they communicate openly and honestly with me always",
    "they're respectful of my boundaries and feelings consistently",
    "they make me feel comfortable being myself completely",
    "they're consistent with their words and actions",
    "they show up when they say they will",
    "they're interested in getting to know me",
    "they treat me with respect from the",
    "they're emotionally available and present with me",
    "they make effort and don't make me",
    "they're honest about their intentions from start",
    "they're supportive of my goals and dreams",
    "they listen when I talk and remember",
    "they're patient and understanding with me always",
    "they make me feel valued and appreciated",
    "they're reliable and I can count on",
    "they're respectful and treat me well consistently",
    "they make me feel safe and comfortable",
    "they're looking for something real and meaningful"
  ]
};

module.exports = youShouldLeaveACommentIf;
